SootopolisCity_House2_Text_18FA66:: @ 818FA66
	.string "송화산...\p"
	.string "정상에 두 개의 구슬이\n"
	.string "놓여져 있다는 걸 알고 계신지...?$"
	@ おくりびやま……ｐ
	@ ちょうじょうに ふたつのたまがｎ
	@ おかれて いるのは ごぞんじ ですか……?

SootopolisCity_House2_Text_18FAAE:: @ 818FAAE
	.string "그래요... 두 개의 구슬이\n"
	.string "이웃한 모습은\l"
	.string "왠지 마음이 편해지지요...$"
	@ そう…… ふたつのたまがｎ
	@ となりあわせに おかれている ようすはｌ
	@ なにか こころが やすらぎますよ……

SootopolisCity_House2_Text_18FB04:: @ 818FB04
	.string "그렇군요...\n"
	.string "한번 가보는 건 어떤가요...$"
	@ そうですか……ｎ
	@ いちど いかれては どうでしょう……
