MossdeepCity_House1_Text_18D465:: @ 818D465
	.string "으음!\n"
	.string "너의 {STR_VAR_1}...$"
	// ムムムッ!ｎ
	// きみの §い……

MossdeepCity_House1_Text_18D475:: @ 818D475
	.string "{STR_VAR_1}{K_EULREUL} 좋아하는군!\p"
	.string "아니 틀림없이 {STR_VAR_1}{K_EULREUL}\n"
	.string "좋아하는 걸 거다!$"
	// §い が すきだろう!ｐ
	// いや まちがいなくｎ
	// §い が すきだ!

MossdeepCity_House1_Text_18D4C0:: @ 818D4C0
	.string "포켓몬스넥에 대한 호불호는 없는 것 같군$"
	// ポロックの すききらいは ないみたいだな

MossdeepCity_House1_Text_18D4F1:: @ 818D4F1
	.string "우리 남편은 보는 것만으로도\n"
	.string "포켓몬이 좋아하는 포켓몬스넥을 알 수 있어$"
	// だんなったら みただけでｎ
	// ポケモンが すきな ポロック わかるのよ
