MossdeepCity_SpaceCenter_1F_Text_18E1F3:: @ 818E1F3
	.string "이제 곧 로켓 발사할 거야!$"
	@ もうすぐ ロケットが はっしゃ するぞ!

MossdeepCity_SpaceCenter_1F_Text_18E214:: @ 818E214
	.string "로켓이 발사됐어!\n"
	.string "이걸로 {STR_VAR_1}번째 발사 성공이야!$"
	@ ロケットが はっしゃ したよ!ｎ
	@ これで §いかい うちあげ せいこうだ!

MossdeepCity_SpaceCenter_1F_Text_18E251:: @ 818E251
	.string "로켓을 발사하는 데에는\n"
	.string "1퍼센트의 실수도 용납되지 않아\p"
	.string "99퍼센트 문제가 없다고 해도\n"
	.string "1퍼센트의 실수로\l"
	.string "모든 게 실패하게 되는 혹독한 세계지\p"
	.string "그럼에도 반드시 성공시키려는 건\n"
	.string "거기에 로망이 가득 차 있기 때문이야$"
	@ ロケットを はっしゃ するにはｎ
	@ 1パ-セントの ミスも ゆるされないｐ
	@ 99パ-セント だいじょうぶ でもｎ
	@ 1パ-セント ダメならｌ
	@ すべてが ダメになる きびしい ものだｐ
	@ それでも やりとげようと するのはｎ
	@ そこに ロマンが つまっている からだな

MossdeepCity_SpaceCenter_1F_Text_18E335:: @ 818E335
	.string "해안에서 산책하면서\n"
	.string "이걸 발견했는데\l"
	.string "난 필요 없으니까 너 줄게!$"
	@ かいがんを さんぽ していてｎ
	@ これを みつけたんだけどｌ
	@ ぼくは いらないから きみに あげる!

MossdeepCity_SpaceCenter_1F_Text_18E39B:: @ 818E39B
	.string "예로부터 호연지방은\n"
	.string "운석이 많은 곳으로\l"
	.string "유명하단 말이지$"
	@ むかしから ホウエンちほうはｎ
	@ いんせきの おおい ばしょ としてｌ
	@ ゆうめい なんだよね

MossdeepCity_SpaceCenter_1F_Text_18E3E5:: @ 818E3E5
	.string "사람에 따라선\n"
	.string "포켓몬은 우주에서 왔다!\l"
	.string "라고도 하던데 진짜일까-?$"
	@ ひとに よってはｎ
	@ ポケモンは うちゅうから やってきた!ｌ
	@ って いうよね! ほんとう かな-?

MossdeepCity_SpaceCenter_1F_Text_18E427:: @ 818E427
	.string "거대한 철 덩어리가\n"
	.string "창공을 뚫고\l"
	.string "우주까지 날아간다...\p"
	.string "정말 굉장한 일이지$"
	@ でっかい てつの かたまりがｎ
	@ おおぞらを つきぬけｌ
	@ うちゅうまで とんで いく……ｐ
	@ たまげた もん だわい
