RustboroCity_House1_Text_184EBA:: @ 8184EBA
	.string "포켓몬에게 별명 지어주고 있어?\n"
	.string "난 멋있는 별명 지어주고 있어!\p"
	.string "하지만 내가 포켓몬을 부르면\n"
	.string "다들 킥킥거리면서 웃어...\p"
	.string "그래도 괜찮다면 내 {STR_VAR_2}{K_WAGWA}\n"
	.string "네 {STR_VAR_1}{K_EULREUL} 교환하지 않을래?$"
	// ポケモンに ニックネ-ム つけてる?ｎ
	// ぼく かっこいいの つけてるよ!ｐ
	// でもね ぼくが そのポケモンを よぶとｎ
	// みんな くすくす わらうんだ……ｐ
	// それでも よかったら ぼくの §うとｎ
	// きみの §い こうかん しない?

RustboroCity_House1_Text_184F6B:: @ 8184F6B
	.string "에헤헤!!\n"
	.string "왠지 두근두근거린다$"
	// でへへ!!ｎ
	// なんだか わくわく するよ

RustboroCity_House1_Text_184F8F:: @ 8184F8F
	.string "걔 {STR_VAR_1} 아니잖아?\n"
	.string "쳇 실망이야$"
	// そいつ §い じゃないよね?ｎ
	// ちぇ がっかり だな

RustboroCity_House1_Text_184FC1:: @ 8184FC1
	.string "좋은 포켓몬이긴 하지만...$"
	// いい ポケモン なんだけどな

RustboroCity_House1_Text_184FDD:: @ 8184FDD
	.string "다른 사람의 포켓몬이 어떤\n"
	.string "별명으로 불리는지 궁금하지?$"
	// ひとの ポケモンって どんなｎ
	// ニックネ-ムか きに なるよね

RustboroCity_House1_Text_185020:: @ 8185020
	.string "다양한 장소에\n"
	.string "다양한 포켓몬이 있고\l"
	.string "다양한 사람들도 있어\p"
	.string "그게 좋아서 나도\n"
	.string "다양한 곳으로 가는 거야!$"
	// いろんな ばしょにｎ
	// いろんな ポケモンが いるｌ
	// いろんな ひとも いるｐ
	// それが たのしみで わしもｎ
	// いろんな ところに でかけるのさ!
