MtChimney_Text_195760:: @ 8195760
	.string "굴뚝산 명물\n"
	.string "용암전병이 하나에 200원!\l"
	.string "하나 사가렴$"
	@ えんとつやま めいぶつｎ
	@ フエンせんべい ひとつ 200えん!ｌ
	@ かって おいきよ

MtChimney_Text_1957A9:: @ 81957A9
	.string "고맙구나$"
	@ どうも ありがとね

MtChimney_Text_1957BA:: @ 81957BA
	.string "이런 돈이 없으면\n"
	.string "물건을 살 수 없단다$"
	@ おやまあ おかねが なくちゃｎ
	@ ものは かえないよ

MtChimney_Text_1957F7:: @ 81957F7
	.string "어머 그러니$"
	@ あら そうかい

MtChimney_Text_195806:: @ 8195806
	.string "수수께끼 장치에\n"
	.string "운석이 박혀 있다...\p"
	.string "뭔가의 에너지를\n"
	.string "모으고 있는 듯하다$"
	@ なぞの そうちにｎ
	@ いんせきが はめられている……ｐ
	@ なにかの エネルギ-をｎ
	@ ためている さいちゅうの ようだ

MtChimney_Text_195870:: @ 8195870
	.string "수수께끼 장치에\n"
	.string "운석이 박혀 있다...\p"
	.string "운석을 빼겠습니까?$"
	@ なぞの そうちにｎ
	@ いんせきが はめられている……ｐ
	@ いんせきを とりますか?

MtChimney_Text_1958C6:: @ 81958C6
	.string "{PLAYER}{K_EUNNEUN} 운석을\n"
	.string "장치에서 빼냈다!$"
	@ §あは いんせきをｎ
	@ そうちから とりはずした!

MtChimney_Text_1958FC:: @ 81958FC
	.string "{PLAYER}{K_EUNNEUN} 운석을\n"
	.string "그대로 두었다$"
	@ §あは いんせきをｎ
	@ そのままに しておいた

MtChimney_Text_195920:: @ 8195920
	.string "수수께끼 장치...\n"
	.string "전혀 반응하지 않는다...$"
	@ なぞの そうち……ｎ
	@ まったく はんのう しない……

MtChimney_Text_19595C:: @ 819595C
	.string "{0x7A} 울퉁불퉁 산길\n"
	.string "빠져나가면 용암마을$"
	@ ©し© デコボコさんどうｎ
	@ とおりぬけると フエンタウン

MtChimney_Text_19597F:: @ 819597F
	.string "온천욕으로\n"
	.string "리프레쉬하고 왔으니\l"
	.string "지금의 난 강하다네!$"
	@ おんせんに つかってｎ
	@ リフレッシュ してきたからねえｌ
	@ いまの あたしゃあ つよいよ!

MtChimney_Text_1959D8:: @ 81959D8
	.string "흐음 이런\n"
	.string "대단하구만$"
	@ おんや まぁｎ
	@ たいした もんだよ

MtChimney_Text_195A04:: @ 8195A04
	.string "져버렸으니 이제는\n"
	.string "달인이라고 못 하겠구먼$"
	@ まけて しもうたかｎ
	@ これじゃあ たつじん とは いえないねえ

MtChimney_Text_195A45:: @ 8195A45
	.string "포켓몬과 한마음이 된다면\n"
	.string "굉장한 일을 할 수 있을 것 같구먼$"
	@ ポケモンと こころを ひとつに できればｎ
	@ すばらしいことが できそうじゃの

MtChimney_Text_195AAD:: @ 8195AAD
	.string "흐음 이런\n"
	.string "대단하구만$"
	@ おんや まぁｎ
	@ たいした もんだよ

MtChimney_Text_195AD9:: @ 8195AD9
	.string "자네와 포켓몬은\n"
	.string "한마음인 것 같구먼$"
	@ おまえさんの こころとｎ
	@ ポケモンの こころは ひとつ なのかもな

MtChimney_Text_195B1C:: @ 8195B1C
	.string "왠지 불타올라서\n"
	.string "배틀하고 싶어 참을 수 없어!$"
	@ なんだか もえあがってきてｎ
	@ たたかいたくて たまらないのっ!

MtChimney_Text_195B5F:: @ 8195B5F
	.string "뜨거운 배틀이었어$"
	@ あつい たたかい だったわ

MtChimney_Text_195B84:: @ 8195B84
	.string "굴뚝산의 열기가\n"
	.string "여자를 불태우지$"
	@ えんとつやまの あつさがｎ
	@ おんなを もえあがらせるの

MtChimney_Text_195BB2:: @ 8195BB2
	.string "모처럼 굴뚝산에 왔으니\n"
	.string "여기서도 포켓몬을 단련시키고 싶어!$"
	@ せっかく えんとつやまに きたんだからｎ
	@ ここでも ポケモンを たたかわせたいの!

MtChimney_Text_195BF9:: @ 8195BF9
	.string "네가 배틀하는 모습은\n"
	.string "마치 분화하는 굴뚝산 같아!$"
	@ その たたかいかたｎ
	@ まさに えんとつやま だいふんか!

MtChimney_Text_195C31:: @ 8195C31
	.string "모처럼 굴뚝산에 왔는데\n"
	.string "관광만 하고 가기에는 아까워\p"
	.string "승부도 즐기고 싶고\n"
	.string "선물로 전병도 사야지!$"
	@ せっかく えんとつやまに きたんだからｎ
	@ かんこう だけじゃ もったいないわｐ
	@ しょうぶも たのしみたいしｎ
	@ おみやげに せんべい かわなきゃ!

MtChimney_Text_195CD8:: @ 8195CD8
	.string "온천에 들어갔더니\n"
	.string "상태가 완전 최고야!\l"
	.string "틀림없이 이길 수 있어!$"
	@ おんせんに はいったらｎ
	@ ちょうし バッチリ なのよね!ｌ
	@ ぜったい かてるわ!

MtChimney_Text_195D2F:: @ 8195D2F
	.string "으-음 벌써 몸이 식었네$"
	@ う-ん ゆざめ しちゃう

MtChimney_Text_195D5C:: @ 8195D5C
	.string "한 번 더 온천에 들어가야지!\n"
	.string "너도 같이 들어갈래?\p"
	.string "농담이야!$"
	@ もういちど おんせんに はいらなきゃ!ｎ
	@ あなたも いっしょに はいる?ｐ
	@ なんてねっ!
