RustboroCity_DevonCorp_2F_Text_182B81:: @ 8182B81
	.string "포켓몬과 대화할 수 있게 해주는 도구를\n"
	.string "개발하고 있는데...\p"
	.string "이게 좀처럼 쉽지가 않네요$"
	// ポケモンと はなせる どうぐをｎ
	// かいはつ しているのですが……ｐ
	// なかなか うまく いかないね

RustboroCity_DevonCorp_2F_Text_182BD8:: @ 8182BD8
	.string "지금 신형 몬스터볼을\n"
	.string "개발하고 있는데...\p"
	.string "이게 좀처럼 쉽지가 않네요$"
	// いま しんがたの モンスタ-ボ-ルをｎ
	// かいはつ しているのですが……ｐ
	// なかなか うまく いかないね

RustboroCity_DevonCorp_2F_Text_182C25:: @ 8182C25
	.string "드디어 신형 몬스터볼\n"
	.string "개발에 성공했어요!\p"
	.string "리피드볼을 쓰면\n"
	.string "이미 잡았던 포켓몬을\l"
	.string "더 쉽게 잡을 수 있어요!\p"
	.string "타이마볼은 포켓몬과의\n"
	.string "배틀 시간이 길면 길어질수록\l"
	.string "더 쉽게 잡을 수 있어요!\p"
	.string "둘 다 우리 회사의 야심작이니\n"
	.string "많이 사용해 주세요!$"
	// しんがたの モンスタ-ボ-ルがｎ
	// ついに かんせい したのです!ｐ
	// リピ-トボ-ルを つかうとｎ
	// いちど つかまえた ポケモンがｌ
	// つかまえやすく なります!ｐ
	// タイマ-ボ-ルは ポケモンとのｎ
	// たたかいが ながびけば ながびくほどｌ
	// つかまえやすく なります!ｐ
	// どちらも わがしゃの じしんさくｎ
	// ぜひ つかって ください!

RustboroCity_DevonCorp_2F_Text_182D2A:: @ 8182D2A
	.string "포켓내비를 만든 건 접니다!\p"
	.string "이야- 그런 엄청난 걸 만들게 되다니\n"
	.string "개발자로서 영광이라구요!$"
	// ポケナビを つくったのは わたし!ｐ
	// いや- あんな すごいモノを つくれるとｎ
	// かいはつしゃ みょうりに つきますね!

RustboroCity_DevonCorp_2F_Text_182D7E:: @ 8182D7E
	.string "오오! 그건 포켓내비!\p"
	.string "포켓몬의 기분을 알고 싶다는\n"
	.string "사장님의 아이디어를\l"
	.string "실현시킨 물건이에요!\p"
	.string "자세히 설명해 드릴까요?\p"
	.string "... 아니지\n"
	.string "쓰다 보면 알게 되실 거예요!\l"
	.string "포켓내비를 많이 사용해 주세요!$"
	// おお! それは ポケナビ!ｐ
	// ポケモンの きもちを しりたいｎ
	// という しゃちょうの アイデアをｌ
	// じつげん したのです!ｐ
	// くわしい せつめいを しましょうか?ｐ
	// …… いやいやｎ
	// そのうちに わかるでしょう!ｌ
	// どんどん ポケナビを つかってくださいね!

RustboroCity_DevonCorp_2F_Text_182E6B:: @ 8182E6B
	.string "지금 포켓몬이 꾸고 있는\n"
	.string "꿈을 볼 수 있게 해주는 도구를\l"
	.string "개발하고 있는데...\p"
	.string "이게 좀처럼 쉽지가 않네요$"
	// いま ポケモンが みているｎ
	// ゆめを うつしだす どうぐをｌ
	// かいはつ しているのですが……ｐ
	// なかなか うまく いかないね

RustboroCity_DevonCorp_2F_Text_182ED5:: @ 8182ED5
	.string "지금 포켓몬의 화석을\n"
	.string "재생하는 장치를\l"
	.string "개발하고 있는데...\p"
	.string "그럭저럭 잘 되고 있어요!$"
	// いま ポケモンの かせきをｎ
	// さいせい する そうちをｌ
	// かいはつ していたのですが……ｐ
	// なかなか うまく いきましたよ!

RustboroCity_DevonCorp_2F_Text_182F35:: @ 8182F35
	.string "당신이 갖고 있는 그건\n"
	.string "포켓몬의 화석!?\p"
	.string "괜찮으시면 제가 만든\n"
	.string "화석 재생 머신으로\l"
	.string "화석을 복원시켜도 될까요?$"
	// きみの もっている それはｎ
	// ポケモンの かせき!?ｐ
	// よければ わたしが つくったｎ
	// カセキ さいせい マシンでｌ
	// いきかえらせて みましょうか?

RustboroCity_DevonCorp_2F_Text_182FD7:: @ 8182FD7
	.string "아- 그렇군요\p"
	.string "데봉의 기술력은 대단한데 말이죠...$"
	// あ- そうですかｐ
	// デボンの ぎじゅつは すごいのにな……

RustboroCity_DevonCorp_2F_Text_183023:: @ 8183023
	.string "알겠습니다!\n"
	.string "그럼 바로...\p"
	.string "{PLAYER}{K_EUNNEUN} 데봉의 연구원에게\n"
	.string "{STR_VAR_1}{K_EULREUL} 맡겼다!$"
	// わかりました!ｎ
	// では さっそく……ｐ
	// §あは デボンの けんきゅういんにｎ
	// §いを あずけた!

RustboroCity_DevonCorp_2F_Text_183072:: @ 8183072
	.string "제가 만든\n"
	.string "화석 재생 머신은 굉장하지만\l"
	.string "시간이 조금 걸리는 게 단점이죠...\p"
	.string "잠깐 다른 곳을\n"
	.string "견학하시는 게 어떨까요?$"
	// わたしが つくったｎ
	// カセキ さいせい マシンは すごいのですがｌ
	// じかんが かかるのが けってん……ｐ
	// すこし そこらへんをｎ
	// けんがく なされては いかがですか?

RustboroCity_DevonCorp_2F_Text_183124:: @ 8183124
	.string "오래 기다리셨습니다!\n"
	.string "화석이 되살아났습니다!\p"
	.string "복원된 화석은 고대의 포켓몬\n"
	.string "{STR_VAR_2}입니다!$"
	// おまたせ しました!ｎ
	// カセキが いきかえり ましたよ!ｐ
	// カセキは おおむかしの ポケモンｎ
	// §う でしたよ!

RustboroCity_DevonCorp_2F_Text_18319E:: @ 818319E
	.string "{PLAYER}{K_EUNNEUN} 데봉의 연구원에게\n"
	.string "{STR_VAR_2}{K_EULREUL} 받았다!$"
	// §あは デボンの けんきゅういんからｎ
	// §うを うけとった!

RustboroCity_DevonCorp_2F_Text_1831C8:: @ 81831C8
	.string "아- 포켓몬이 가득해서\n"
	.string "드릴 수가 없군요$"
	// あ- ポケモン いっぱいでｎ
	// もてないですね
