SootopolisCity_House6_Text_18FEA1:: @ 818FEA1
	.string "와- 오랜만의 손님이네!\p"
	.string "너-무 기쁘니까\n"
	.string "커다란 고래왕자인형을 줄게!$"
	// わ- ひさしぶりの おきゃくさん!ｐ
	// なんだか うれしいからｎ
	// ホエルコの おおきい ぬいぐるみ あげる!

SootopolisCity_House6_Text_18FF12:: @ 818FF12
	.string "소중히 해줘!$"
	// だいじに してね!

SootopolisCity_House6_Text_18FF28:: @ 818FF28
	.string "갖고 싶지만 지금은 안 돼?\n"
	.string "그럼 맡아 두고 있을게$"
	// ほしいけど いまは ダメ?ｎ
	// じゃあ あずかっておいて あげるね

SootopolisCity_House6_Text_18FF6D:: @ 818FF6D
	.string "그래?\n"
	.string "인형 필요 없니?$"
	// そうなの?ｎ
	// ぬいぐるみ ほしくないの?

SootopolisCity_House6_Text_18FF95:: @ 818FF95
	.string "난 인형이 너무 좋아!$"
	// あたし ぬいぐるみ だいすき!
