SSTidalCorridor_Text_199007:: @ 8199007
SSTidalRooms_Text_199007:: @ 8199007
	.string "해류에 꿈쩍도 하지 않고 나아가는\n"
	.string "연락선을 봐 주세요$"
	// かいりゅうを ものともせず すすむｎ
	// れんらくせんを どうぞ ごらんください

SSTidalCorridor_Text_199088:: @ 8199088
	.string "그럼 연락선을 이용한\n"
	.string "즐거운 배 여행을 만끽해 주세요$"
	// それでは れんらくせんに よるｎ
	// ふなたびを おたのしみ ください

SSTidalCorridor_Text_1990B4:: @ 81990B4
SSTidalRooms_Text_1990B4:: @ 81990B4
	.string "수고하셨습니다 지금 막\n"
	.string "잿빛도시에 도착했습니다$"
	// おつかれさまです ただいまｎ
	// カイナシティに とうちゃく しました

SSTidalRooms_Text_1990F8:: @ 81990F8
	.string "수고하셨습니다 지금 막\n"
	.string "해안시티에 도착했습니다$"
	// おつかれさまです ただいまｎ
	// ミナモシティに とうちゃく しました

SSTidalCorridor_Text_19913B:: @ 819913B
	.string "도착하려면 아직 멀었어\p"
	.string "자기 방에 돌아가서 쉬고 있으라고\n"
	.string "분명 네 방은\l"
	.string "2호실이었지\p"
	.string "그 방 침대는\n"
	.string "푹신푹신해서 정말 편하단다!$"
	// とうちゃくまで まだまだ だなｐ
	// じぶんの へやに もどって やすんでいなよｎ
	// たしか きみの へやはｌ
	// 2ごうしつ だったなｐ
	// あの へやの ベッドはｎ
	// ふかふか していて きもちいいぞ!

SSTidalCorridor_Text_1991F4:: @ 81991F4
	.string "도착했어!$"
	// とうちゃく したぞ!

SSTidalCorridor_Text_199203:: @ 8199203
	.string "배 여행에 질려버려서\n"
	.string "객실에서 포켓몬 승부를\l"
	.string "하고 싶어 하는 트레이너도 있어!$"
	// ふなたびに あきちゃってｎ
	// きゃくしつで ポケモンで しょうぶをｌ
	// したがっている トレ-ナ-も いるぞ!

SSTidalCorridor_Text_199255:: @ 8199255
	.string "즐거운 배 여행을 만끽해 줘$"
	// まっ ふなたびを たのしんでくれよ

SSTidalCorridor_Text_199268:: @ 8199268
	.string "창문 저편에\n"
	.string "수평선이 펼쳐져 있다!$"
	// まどの むこうにｎ
	// すいへいせんが ひろがっている!

SSTidalCorridor_Text_199291:: @ 8199291
	.string "하기: 어서 오너라! {PLAYER}!\p"
	.string "내가 이 타이드립호의\n"
	.string "명예 선장인 하기다!\p"
	.string "이야 한 번은 은퇴한 몸이지만\n"
	.string "이런 엄청난 배를 봐 버리면\l"
	.string "선원의 피가 들끓어서 말이지!!$"
	// ハギ『ようこそ! §あ§お!ｐ
	// わしが この タイドリップごうのｎ
	// めいよ せんちょう ハギ じゃよ!ｐ
	// いやぁ いちどは いんたい したがｎ
	// こんな すごい ふねを みてしまうとｌ
	// ふなのりの ちが さわぐのう!!

SSTidalCorridor_Text_199388:: @ 8199388
	.string "피코: 피효 피효효...!$"
	// ピ-コ『ピひょ ピひょひょ……!

SSTidalCorridor_Text_1993A1:: @ 81993A1
	.string "1호실$"
	// 1ごうしつ

SSTidalCorridor_Text_1993A9:: @ 81993A9
	.string "2호실$"
	// 2ごうしつ

SSTidalCorridor_Text_1993B1:: @ 81993B1
	.string "3호실$"
	// 3ごうしつ

SSTidalCorridor_Text_1993B9:: @ 81993B9
	.string "4호실$"
	// 4ごうしつ
