SeafloorCavern_Room1_Text_1974BA:: @ 81974BA
	.string "꼬마에게 볼일은 없다\n"
	.string "자 얼른 돌아가!$"
	// こどもに ようは ね-んだｎ
	// ほら さっさと かえれよ!

SeafloorCavern_Room1_Text_1974EA:: @ 81974EA
	.string "내가 돌아가고 싶어-!$"
	// おれが かえりたいよ-!

SeafloorCavern_Room1_Text_1974FF:: @ 81974FF
	.string "빨리 간부가 돼서\n"
	.string "조무래기들을 괴롭혀주고 싶다...$"
	// はやく かんぶに なってｎ
	// したっぱを しごいて やりたい……

SeafloorCavern_Room1_Text_19753C:: @ 819753C
	.string "잠수정이 너무 좁아서-\n"
	.string "몸 여기저기가 아프단 말이지-!$"
	// せんすいてい ちっちゃいからよ-ｎ
	// からだの あちこちが いたい じゃね-か!

SeafloorCavern_Room1_Text_197573:: @ 8197573
	.string "지면\n"
	.string "마음이 아프단 말이지-!$"
	// まけたらｎ
	// いたい じゃね-か!

SeafloorCavern_Room1_Text_197589:: @ 8197589
	.string "빼앗은 잠수정의 승차감은\n"
	.string "완전 최악이야!\l"
	.string "일단 너무 좁단 말이지-!$"
	// うばった せんすいていの のりごこちｎ
	// ありゃ さいあく だな!ｌ
	// とにかく せますぎ じゃね-か!
