Route124_DivingTreasureHuntersHouse_Text_19F416:: @ 819F416
	.string "난 다이빙 트레져헌터!\p"
	.string "깊은 바닷속으로 잠수해서\n"
	.string "해저에 잠들어 있는 보물을 모으는\l"
	.string "대단한 녀석이야!$"
	@ オレは ダイビング トレジャ-ハンタ-!ｐ
	@ ふかい うみに もぐってはｎ
	@ かいていに ねむる おたからを あつめるｌ
	@ すげえ やろう なのさ!

Route124_DivingTreasureHuntersHouse_Text_19F48F:: @ 819F48F
	.string "머나먼 옛날에 만들어졌다고 하는\n"
	.string "다양한 조각 발견했어?$"
	@ おおむかしに つくられた というｎ
	@ いろいろな かけら みつかったかい?

Route124_DivingTreasureHuntersHouse_Text_19F4D1:: @ 819F4D1
	.string "너 보물 안 가지고 있구나...\p"
	.string "빨강조각이라든가\n"
	.string "다양한 조각 발견하면\l"
	.string "교환해 줘!$"
	@ きみ おたから もってないのか……ｐ
	@ あかいかけら とかｎ
	@ いろいろな かけらを みつけたらｌ
	@ こうかん してくれよな!

Route124_DivingTreasureHuntersHouse_Text_19F544:: @ 819F544
	.string "오오! 그건!\n"
	.string "내가 찾고 있던 조각!!\p"
	.string "저기 말이야!\n"
	.string "네가 가지고 있는 보물이랑\l"
	.string "내 보물이랑 교환해 줘!$"
	@ おおっ! それは!ｎ
	@ オレが さがしている かけら!!ｐ
	@ なっ なっ!ｎ
	@ きみの もってる おたからとｌ
	@ オレの おたから こうかん してくれよ!

Route124_DivingTreasureHuntersHouse_Text_19F5C5:: @ 819F5C5
	.string "어떤 거랑 교환해 줄 거야?$"
	@ どれを こうかん するんだい?

Route124_DivingTreasureHuntersHouse_Text_19F5E0:: @ 819F5E0
	.string "{STR_VAR_1}{K_EULREUL} {STR_VAR_2}{K_I}랑\n"
	.string "교환하는 거지?$"
	@ §い を §うにｎ
	@ こうかん するんだな?

Route124_DivingTreasureHuntersHouse_Text_19F606:: @ 819F606
	.string "교환 성립!\n"
	.string "소중하게 써 줘!$"
	@ とりひき せいりつ!ｎ
	@ だいじに つかって くれよな!

Route124_DivingTreasureHuntersHouse_Text_19F629:: @ 819F629
	.string "또 교환할래?$"
	@ まだ こうかん するかい?

Route124_DivingTreasureHuntersHouse_Text_19F64E:: @ 819F64E
	.string "어이쿠 가방이 가득하잖아\n"
	.string "도구를 줄이고 와$"
	@ おっと バッグが いっぱい だぜｎ
	@ どうぐを へらして きなよ

Route124_DivingTreasureHuntersHouse_Text_19F686:: @ 819F686
	.string "그거 실망인데\n"
	.string "마음이 바뀌면 다시 와 줘!$"
	@ そいつは がっかりだｎ
	@ きが むいたら また きてくれよな!

Route124_DivingTreasureHuntersHouse_Text_19F6C5:: @ 819F6C5
	.string "{CLEAR_TO 0x0e}원하는 것{CLEAR_TO 0x7d}교환할 것\n"
	.string "{CLEAR_TO 0x0f}빨강조각{CLEAR_TO 0x51}{0x7B}{0x7C}{CLEAR_TO 0x7e}불꽃의돌\p"
	.string "{CLEAR_TO 0x0e}원하는 것{CLEAR_TO 0x7d}교환할 것\n"
	.string "{CLEAR_TO 0x0f}노랑조각{CLEAR_TO 0x51}{0x7B}{0x7C}{CLEAR_TO 0x7e}천둥의돌\p"
	.string "{CLEAR_TO 0x0e}원하는 것{CLEAR_TO 0x7d}교환할 것\n"
	.string "{CLEAR_TO 0x0f}파랑조각{CLEAR_TO 0x51}{0x7B}{0x7C}{CLEAR_TO 0x82}물의돌\p"
	.string "{CLEAR_TO 0x0e}원하는 것{CLEAR_TO 0x7d}교환할 것\n"
	.string "{CLEAR_TO 0x0f}초록조각{CLEAR_TO 0x51}{0x7B}{0x7C}{CLEAR_TO 0x7e}리프의돌$"
	@ ほしいモノ       あげるモノｎ
	@  あかいかけら   ©し©©し ほのおのいしｐ
	@ ほしいモノ       あげるモノｎ
	@  きいろいかけら  ©し©©し かみなりのいしｐ
	@ ほしいモノ       あげるモノｎ
	@  あおいかけら   ©し©©し みずのいしｐ
	@ ほしいモノ       あげるモノｎ
	@  みどりのかけら  ©し©©し リ-フのいし
