UnknownString_81B4F03: @ 81B4F03
	.string "{PLAYER}'s BLUE ORB suddenly began\n"
	.string "glowing!$"
	// §あの あいいろのたまがｎ
	// とつぜん かがやき はじめた!

UnknownString_81B4F29: @ 81B4F29
	.string "KYOGRE appears to have settled\n"
	.string "into sleep again...$"
	// カイオ-ガは ふたたびｎ
	// ねむりに ついた ようだ……

UnknownString_81B4F5C: @ 81B4F5C
	.string "ARCHIE: This...$"
	// アオギリ『これを……

UnknownString_81B4F6C: @ 81B4F6C
	.string "ARCHIE: ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "This is good-bye.\n"
	.string "This is the last you've seen of me...$"
	// アオギリ『…… …… ……ｎ
	//  …… …… ……ｐ
	// サヨナラだｎ
	// もう あうことは ないだろう……
