UnknownString_81B50C3: @ 81B50C3
	.string "I'll show you exactly how scary\n"
	.string "TEAM AQUA can be!$"
	// アクアだんの ほんとうの おそろしさｎ
	// おまえに おしえてやるぜ!

UnknownString_81B50F5: @ 81B50F5
	.string "So you think you can stand up alone\n"
	.string "to TEAM AQUA's might...$"
	// なるほど ひとりで アクアだんにｎ
	// さからおうって わけか

UnknownString_81B5131: @ 81B5131
	.string "Yeah, so you are strong...\n"
	.string "But there're a lot of us!$"
	// たしかに おまえは つよいな……ｎ
	// だけど おれたちは たくさん いるんだぞ!

UnknownString_81B5166: @ 81B5166
	.string "What's up with you?\n"
	.string "What does a single kid expect to do?$"
	// なんだ おまえ?ｎ
	// こどもが ひとりで なにしよう ってんだ?

UnknownString_81B519F: @ 81B519F
	.string "Dang...\n"
	.string "Too strong...$"
	// くそう つよいな……

UnknownString_81B51B5: @ 81B51B5
	.string "You don't know anything.\n"
	.string "Quit messing around with us!$"
	// なにも しらないくせにｎ
	// おれたちの じゃまを するんじゃないぜ!

UnknownString_81B51EB: @ 81B51EB
	.string "Hey, I remember you from MT. CHIMNEY!\n"
	.string "It's payback time!$"
	// おまえ…… えんとつやまで あったな!ｎ
	// その しかえし させてもらうぜ!

UnknownString_81B5224: @ 81B5224
	.string "Urgggh...\n"
	.string "Beaten by some kid again!$"
	// ぐぐぐ……ｎ
	// ま-た こどもに まけちまったよ

UnknownString_81B5248: @ 81B5248
	.string "Heh, it doesn't matter!\n"
	.string "We bought ourselves some time!\p"
	.string "The BOSS should have snatched what\n"
	.string "he was after!$"
	// まあいいさ じかんは かせげた!ｐ
	// リ-ダ-の もくてきの ものｎ
	// うばえた はずだぜ!

UnknownString_81B52B0: @ 81B52B0
	.string "ARCHIE: Not you again...\p"
	.string "You've impeded our plans repeatedly,\n"
	.string "but this time you're too late.\p"
	.string "The RED ORB that rested atop\n"
	.string "MT. PYRE...\l"
	.string "I, ARCHIE, claim it as mine!\p"
	.string "Fufufu... Finally, I can realize my\n"
	.string "grand design...\p"
	.string "Come on, crew!\n"
	.string "It's SLATEPORT next!$"
	// アオギリ『また きみか……ｐ
	// きみには これまで なんどもｎ
	// じゃまを されたがｌ
	// こんど ばかりは おそかった ようだな!ｐ
	// この おくりびやまに まつられていたｎ
	// べにいろのたま……ｌ
	// たしかに この アオギリが いただいた!ｐ
	// フフフ…… これで わたしの もくてきもｎ
	// たっせい できる……ｐ
	// つぎは カイナ だ!ｎ
	// いそぐぞ!!

UnknownString_81B53AB: @ 81B53AB
	.string "Oh, no...\n"
	.string "This cannot happen...\p"
	.string "How could they take the RED ORB?\p"
	.string "The BLUE ORB and RED ORB must never\n"
	.string "be separated. They belong together.\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "Hmm...\p"
	.string "Fine!\n"
	.string "You take the remaining BLUE ORB.\p"
	.string "Please take after that foul man and\n"
	.string "get the other ORB back!$"
	// ああ なんという ことじゃ……!ｐ
	// べにいろのたま が……ｎ
	// うばわれて しまうとは……ｐ
	// べにいろのたま と あいいろのたま がｎ
	// はなればなれに なって しまうなどｌ
	// けっして あっては ならないこと……ｐ
	// ……… ……… ………ｎ
	// ううむ……ｐ
	// よし! おまえさんに のこされたｎ
	// あいいろのたまを あずけようｐ
	// さっきの おとこを おいかけてｎ
	// たまを とりかえして おくれ……!

UnknownString_81B54BE: @ 81B54BE
	.string "The BLUE ORB you have been entrusted\n"
	.string "with and the stolen RED ORB...\p"
	.string "They must never be apart...\n"
	.string "Something terrible will happen...$"
	// おまえさんに わたした あいいろのたまとｎ
	// うばわれた べにいろのたま……ｐ
	// はなればなれ ではｎ
	// きっと よくないことが おこる……

UnknownString_81B5540: @ 81B5540
	.string "So...\n"
	.string "KYOGRE has awoken...\p"
	.string "The wondrous ORB that is said to have\n"
	.string "becalmed the raging KYOGRE...\l"
	.string "It is the BLUE ORB you bear.\p"
	.string "That BLUE ORB was found buried inside\n"
	.string "the CAVE OF ORIGIN in SOOTOPOLIS...\p"
	.string "There is perhaps a link between\n"
	.string "KYOGRE and the CAVE OF ORIGIN...$"
	// そうか……ｎ
	// カイオ-ガが めざめたのか……ｐ
	// かつて カイオ-ガの いかりをｎ
	// しずめた ふしぎな たま というのがｌ
	// その あいいろのたま といわれておる……ｐ
	// そして その たまが ほりだされたのはｎ
	// ルネにある めざめのほこら……ｐ
	// カイオ-ガと めざめのほこら にはｎ
	// なにかしら かんけいが あるのかもな……

UnknownString_81B5647: @ 81B5647
	.string "That man, he returned the RED ORB.\p"
	.string "Are you going to return the BLUE ORB\n"
	.string "to its rightful place, too?$"
	// さっきの おとこｎ
	// べにいろのたまを かえしに きよったｐ
	// おまえさんもｎ
	// あいいろのたまを かえすのかい?

UnknownString_81B56AB: @ 81B56AB
	.string "What's that?!\p"
	.string "If the balance is not restored, there\n"
	.string "is no telling what could happen.\p"
	.string "You will return the BLUE ORB to its\n"
	.string "rightful place, yes?$"
	// なんと!?ｎ
	// このまま バランスが くずれた ままではｌ
	// なにが おきるか わからんぞよ?ｐ
	// おまえさんｎ
	// あいいろのたまを もどすじゃろう?

UnknownString_81B5739: @ 81B5739
	.string "{PLAYER} handed the BLUE ORB to the\n"
	.string "old woman.$"
	// §あは ろうばにｎ
	// あいいろのたまを わたした!

UnknownString_81B5762: @ 81B5762
	.string "Yes...\n"
	.string "The two ORBS should remain here.\p"
	.string "It is how it should be for the good\n"
	.string "of all HOENN...$"
	// うむ……ｎ
	// 2つの たまは ここに おいておこう……ｐ
	// それが このホウエンの ためにもｎ
	// いちばん よい すがた だろうて……

UnknownString_81B57BE: @ 81B57BE
	.string "The spirit of the sea...\p"
	.string "That is what KYOGRE is said to be in\n"
	.string "POKéMON form...\p"
	.string "In the same manner that we and POKéMON\n"
	.string "have life, the sea is alive...\p"
	.string "KYOGRE has taught us that...$"
	// うみの けしん……ｎ
	// それが カイオ-ガの しょうたい ともｌ
	// いわれておる……ｐ
	// わしら にんげんや ポケモンにｎ
	// いのちが あるようにｌ
	// この うみだって いきている……ｐ
	// カイオ-ガは わしたちに そのことをｎ
	// おしえて くれたのじゃろう……

UnknownString_81B586F: @ 81B586F
	.string "MT. PYRE is where we calm the spirits\n"
	.string "of POKéMON that have passed on...\p"
	.string "This is a high place where one can\n"
	.string "see all of HOENN...\p"
	.string "The disembodied spirits of POKéMON\n"
	.string "must find solace here...\p"
	.string "Is it coincidence that you are here...\p"
	.string "Will you hear out my tale? A tale long\n"
	.string "told in the HOENN region?$"
	// おくりびやまは ポケモンの たましいをｎ
	// なぐさめる ための ところ……ｐ
	// ここは たかい ばしょに あってｎ
	// ホウエンを みわたす ことが できるからｌ
	// ポケモンたちの たましいもｌ
	// やすらぎを おぼえるの じゃろう……ｐ
	// おまえさんが ここに きたのもｎ
	// なにかの えん……ｐ
	// ホウエンちほうに つたわる はなしをｎ
	// きいて いきなされ……

UnknownString_81B5992: @ 81B5992
	.string "It happened long, long ago...\p"
	.string "The world was wracked by a ferocious\n"
	.string "clash between the POKéMON of the sea\l"
	.string "and the POKéMON of the land...\p"
	.string "The POKéMON of the sea raised huge\n"
	.string "waves and carved out oceans...\p"
	.string "The POKéMON of the land raised\n"
	.string "mountains and created continents...\p"
	.string "Their fierce duel raged without end.\p"
	.string "The world was engulfed in massive\n"
	.string "infernos and vicious storms.\p"
	.string "The BLUE ORB and the RED ORB brought\n"
	.string "an end to the calamity.\p"
	.string "Light poured from the two ORBS and\n"
	.string "becalmed the enraged adversaries.\p"
	.string "The pair, made docile, dove deep into\n"
	.string "the sea where eventually they\l"
	.string "disappeared...$"
	// とおい とおい おおむかしの こと……ｐ
	// せかいでは うみと りくの ポケモンがｎ
	// はげしい たたかいを くりひろげていたｐ
	// うみの ポケモンはｎ
	// あらなみを おこして うみを ひろげｐ
	// りくの ポケモンはｎ
	// だいちを もりあげ じめんを ひろげたｐ
	// 2ひきの たたかいは おわることなくｎ
	// この せかいは もえさかる ほのおとｌ
	// ふきあれる あらしで うめつくされたｐ
	// それを しずめたのがｎ
	// あいいろのたま と べにいろのたま……ｐ
	// ふたつの たまから ひろがる ひかりがｎ
	// 2ひきの いかりを しずめたｐ
	// そして おとなしくなった 2ひきはｎ
	// かいてい ふかく もぐっていきｌ
	// やがて そのすがたを けしたのじゃ……

UnknownString_81B5BD7: @ 81B5BD7
	.string "I see...\n"
	.string "Well, that, too, is fine...$"
	// そうかね……ｎ
	// まあ それも よいじゃろう……

UnknownString_81B5BFC: @ 81B5BFC
	.string "ARCHIE: You...\n"
	.string "So you stopped KYOGRE...\p"
	.string "I shouldn't be surprised...\p"
	.string "I understand now that humans cannot\n"
	.string "freely control the balance between\l"
	.string "the land and the sea...\p"
	.string "So I have come to return the\n"
	.string "RED ORB...\p"
	.string "I doubt that we will cross paths again...\n"
	.string "Farewell...$"
	// アオギリ『きみが……ｎ
	// カイオ-ガを……ｐ
	// さすが だな……ｐ
	// しょせん にんげん にはｎ
	// うみと だいちの バランスをｌ
	// じゆうに あやつる なんて できない……ｐ
	// だから ここにｎ
	// べにいろのたまを かえしに きた……ｐ
	// もう きみと あうことは ないだろう……ｎ
	// さらば だ……
