UnknownString_81B4F03: @ 81B4F03
	.string "{PLAYER}의 쪽빛구슬이\n"
	.string "갑자기 빛나기 시작했다!$"
	// §あの あいいろのたまがｎ
	// とつぜん かがやき はじめた!

UnknownString_81B4F29: @ 81B4F29
	.string "가이오가는 다시\n"
	.string "잠에 든 모양이다...$"
	// カイオ-ガは ふたたびｎ
	// ねむりに ついた ようだ……

UnknownString_81B4F5C: @ 81B4F5C
	.string "아강: 받아라...$"
	// アオギリ『これを……

UnknownString_81B4F6C: @ 81B4F6C
	.string "아강: ...... ...... ......\n"
	.string "{CLEAR_TO 0x16}...... ...... ......\p"
	.string "작별이다\n"
	.string "이제 만날 일은 없겠지...$"
	// アオギリ『…… …… ……ｎ
	//  …… …… ……ｐ
	// サヨナラだｎ
	// もう あうことは ないだろう……
