UnknownString_81C426C: @ 81C426C
	.string "나는 커다란 {STR_VAR_1}에\n"
	.string "무척 흥미가 있어!\p"
	.string "응? 너 {STR_VAR_1} 가지고 있어?\n"
	.string "자 자 잠깐...\l"
	.string "아저씨한테 좀 보여 줘!$"
	// わしは おおきな §いにｎ
	// とても きょうみが ある!ｐ
	// ん? きみ §い もってるの?ｎ
	// ちょ ちょ ちょっと®®®ｌ
	// おじさんに みせて おくれ!

UnknownString_81C42CE: @ 81C42CE
	.string "오오! 이 녀석 커!\n"
	.string "무척 아름다운 {STR_VAR_1}{K_I}야!\p"
	.string "보여 줘서 고마워\n"
	.string "답례로 이걸 가지고 가렴!$"
	// おお! こいつは でかい!ｎ
	// とても すばらしい §いだ!ｐ
	// みせて くれて ありがとうｎ
	// おれいに これを もって いきなさい

UnknownString_81C432C: @ 81C432C
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "{STR_VAR_2}{K_EULREUL} 받았다!$"
	// §あはｎ
	// §うを もらった!

UnknownString_81C4340: @ 81C4340
	.string "어라?\n"
	.string "너 지닌물건이 가득 찼네$"
	// ありゃ?ｎ
	// きみ もちもの いっぱいだね

UnknownString_81C4360: @ 81C4360
	.string "으음 난 이것보다 큰\n"
	.string "{STR_VAR_1}{K_EULREUL} 본 적이 있어...$"
	// ううむ わしは これより おおきいｎ
	// §いを みたこと あるな®®®

UnknownString_81C438C: @ 81C438C
	.string "오오 이 녀석 꽤...아니\n"
	.string "이거 {STR_VAR_1}{K_IGA} 아니잖아!$"
	// おお こいつは なかなか®®®ってｎ
	// これ §いじゃ ないよ!

UnknownString_81C43C2: @ 81C43C2
	.string "커다란 {STR_VAR_1} 없어?\n"
	.string "그거 안타깝네...\p"
	.string "다음에 커다란 {STR_VAR_1} 보여 줘$"
	// おおきい §い もってないの?ｌ
	// それは ざんねん®®®ｎ
	// こんど おおきい §い みせてね

UnknownString_81C4417: @ 81C4417
	.string "사상 최대의 {STR_VAR_1}!\n"
	.string "{STR_VAR_2}의 {STR_VAR_3}cm인 녀석!$"
	// しじょう さいだいの §い!ｎ
	// §うの §えcmのやつ!
