gTextBard_BardTesting: @ 81B0A83
	.string "아저씨는 테스트 중!$"
	// おやじテストちゅうです!

gTextBard_HiImTheBard:: @ 81B0A91
	.string "난 싱어송아저씨\n"
	.string "내 노래 들어볼래?$"
	// わし シンガ-ソングおやじｎ
	// わしの うた きいてくれる?

gTextBard_OhYouveLeftMe:: @ 81B0AC3
	.string "그렇구나...\n"
	.string "아저씨 아쉽다...$"
	// そう……ｎ
	// わし ざんねん……

gTextBard_OhWhatAMovingSong:: @ 81B0AED
	.string "아아 좋은 노래구나...\n"
	.string "다른 사람에게도 들려주고 싶다$"
	// あぁ いい うた だなぁｎ
	// ほかの ひとにも きかせて みたいなあ

gTextBard_SoHowDoYouLikeMySong:: @ 81B0B2C
	.string "내 노래 어때?\p"
	.string "근데 가사가 좀 마음에 안 들어\p"
	.string "그러니까 네가 좀 써줄래?$"
	// どう? わしの うた?ｐ
	// でも ちょっと かしが きにいらないｐ
	// だから きみ ちょっと かえてくれる?

gTextBard_OhYouveLeftMe2:: @ 81B0BA6
	.string "그렇구나...\n"
	.string "아저씨 아쉽다...$"
	// そう……ｎ
	// わし ざんねん……

gTextBard_ThankYouKindly:: @ 81B0BD0
	.string "고마워!\n"
	.string "그럼 불러본다!$"
	// ありがとう!ｎ
	// じゃあ うたって みるぞ!

gTextBard_WasThatHowYouWanted:: @ 81B0BFA
	.string "이런 느낌이면 되니?$"
	// こんな かんじで いいの?

gTextBard_OkayThatsIt:: @ 81B0C23
	.string "좋아 알았어!\n"
	.string "당분간 이 노래를 불러볼게!$"
	// よし わかった!ｎ
	// しばらく このうたを うたって みるよ!
