Underwater_SealedChamber_Braille_1C533D:: @ 81C533D
	.byte 3
	.byte 6
	.byte 26
	.byte 13
	.byte 5
	.byte 9
	.braille "⠱⠈⠕⠠⠎⠀⠍⠗⠐⠥$"
	@ 여기서 위로(작업 완료)

SealedChamber_OuterRoom_Braille_1C534F:: @ 81C534F
	.byte 1
	.byte 6
	.byte 29
	.byte 13
	.byte 3
	.byte 9
	.braille "⠈⠉⠊⠐⠑⠘⠠⠨⠰⠋⠓⠙⠚$"
	@ ᄀᄂᄃᄅᄆᄇᄉᄌᄎᄏᄐᄑᄒ(작업 완료)

SealedChamber_OuterRoom_Braille_1C5359:: @ 81C5359
	.byte 10
	.byte 6
	.byte 18
	.byte 13
	.byte 14
	.byte 9
	.braille "⠠$"
	@ 쌍자음 표시(작업 완료)

SealedChamber_OuterRoom_Braille_1C5363:: @ 81C5363
	.byte 0
	.byte 6
	.byte 29
	.byte 13
	.byte 1
	.byte 9
	.braille "⠁⠒⠔⠂⠢⠃⠄⠶⠅⠆⠖⠦⠲⠴$"
	@ ᆨᆫᆮᆯᆷᆸᆺᆼᆽᆾᆿᇀᇁᇂ(작업 완료)

SealedChamber_OuterRoom_Braille_1C536D:: @ 81C536D
	.byte 3
	.byte 6
	.byte 27
	.byte 13
	.byte 5
	.byte 9
	.braille "⠣⠜⠎⠱⠥⠬⠍⠩⠪⠕⠗$"
	@ ᅡᅣᅥᅧᅩᅭᅮᅲᅳᅵᅢ(작업 완료)

SealedChamber_OuterRoom_Braille_1C5377:: @ 81C5377
	.byte 0
	.byte 6
	.byte 29
	.byte 13
	.byte 1
	.byte 9
	.braille "⠜⠗⠝⠌⠧⠧⠗⠽⠏⠏⠗⠍⠗⠺$"
	@ ᅤᅦᅨᅪᅫᅬᅯᅰᅱᅴ(작업 완료)

SealedChamber_OuterRoom_Braille_1C5381:: @ 81C5381
	.byte 3
	.byte 6
	.byte 27
	.byte 13
	.byte 5
	.byte 9
	.braille "⠫⠉⠊⠑⠘⠇⠨⠋⠓⠙⠚$"
	@ 가나다마바사자카타파하(작업 완료)

SealedChamber_OuterRoom_Braille_1C538B:: @ 81C538B
	.byte 3
	.byte 6
	.byte 27
	.byte 13
	.byte 5
	.byte 9
	.braille "⠹⠾⠞⠡⠳⠻⠭⠷⠿⠛⠯$"
	@ 억언얼연열영옥온옹운울(작업 완료)

SealedChamber_OuterRoom_Braille_1C5396:: @ 81C5396
	.byte 8
	.byte 6
	.byte 22
	.byte 13
	.byte 10
	.byte 9
	.braille "⠵⠮⠟⠸⠎⠌$"
	@ 은을인것ㅆ(작업 완료)

SealedChamber_OuterRoom_Braille_1C539E:: @ 81C539E
	.byte 3
	.byte 6
	.byte 27
	.byte 13
	.byte 5
	.byte 9
	.braille "⠁⠎ ⠁⠉⠀⠁⠒⠀⠁⠢$"
	@ 그래서 그러나 그러면 그러므로(작업 완료)

SealedChamber_OuterRoom_Braille_1C53A9:: @ 81C53A9
	.byte 5
	.byte 6
	.byte 24
	.byte 13
	.byte 7
	.byte 9
	.braille "⠁⠝⠀⠁⠥⠀⠁⠱$"
	@ 그런데 그리고 그리하여(작업 완료)

SealedChamber_OuterRoom_Braille_1C53B1:: @ 81C53B1
	.byte 5
	.byte 4
	.byte 25
	.byte 15
	.byte 7
	.byte 7
	.braille "⠱⠈⠕⠠⠎\n"
	.braille "⠈⠍⠑⠎⠶⠙⠈⠕$"
	@ 여기서\n구멍파기(작업 완료)

SealedChamber_InnerRoom_Braille_1C53C1:: @ 81C53C1
	.byte 2
	.byte 0
	.byte 28
	.byte 19
	.byte 4
	.byte 3
	.braille "⠰⠎⠪⠢⠝⠀⠠⠕⠐⠣⠋⠒\n"
	.braille "⠠⠈⠪⠦⠝⠀⠈⠥⠐⠗⠧⠶\n"
	.braille "⠁⠒⠀⠑⠥⠊⠵⠀⠸⠎⠕\n"
	.braille "⠳⠐⠟⠊$"
	@ 처음에 시라칸\n끝에 고래왕\n그러면 모든 것이\n열린다(작업 완료)

SealedChamber_InnerRoom_Braille_1C53F2:: @ 81C53F2
	.byte 4
	.byte 0
	.byte 24
	.byte 19
	.byte 6
	.byte 3
	.braille "⠍⠐⠕⠊⠮⠵\n"
	.braille "⠕⠀⠊⠿⠈⠯⠝⠠⠎\n"
	.braille "⠠⠗⠶⠚⠧⠂⠚⠈⠥\n"
	.braille "⠇⠂⠣⠧⠌⠊$"
	@ 우리들은\n이 동굴에서\n생활하고\n살아왔다(작업 완료)

SealedChamber_InnerRoom_Braille_1C5414:: @ 81C5414
	.byte 4
	.byte 2
	.byte 22
	.byte 17
	.byte 6
	.byte 5
	.braille "⠑⠥⠊⠵⠀⠸⠎⠵\n"
	.braille "⠙⠥⠋⠝⠄⠑⠷\n"
	.braille "⠊⠹⠘⠛⠕⠊$"
	@ 모든 것은\n포켓몬\n덕분이다(작업 완료)

SealedChamber_InnerRoom_Braille_1C5435:: @ 81C5435
	.byte 3
	.byte 0
	.byte 27
	.byte 19
	.byte 5
	.byte 3
	.braille "⠁⠉\n"
	.braille "⠍⠐⠕⠊⠮⠵\n"
	.braille "⠈⠪⠀⠙⠥⠋⠝⠄⠑⠷⠮\n"
	.braille "⠫⠊⠍⠎⠌⠊$"
	@ 그러나\n우리들은\n그 포켓몬을\n가두었다(작업 완료)

SealedChamber_InnerRoom_Braille_1C545C:: @ 81C545C
	.byte 7
	.byte 6
	.byte 23
	.byte 13
	.byte 9
	.byte 9
	.braille "⠑⠍⠠⠎⠏⠌⠊$"
	@ 무서웠다(작업 완료)

SealedChamber_InnerRoom_Braille_1C5470:: @ 81C5470
	.byte 4
	.byte 0
	.byte 24
	.byte 19
	.byte 6
	.byte 3
	.braille "⠬⠶⠈⠕⠀⠕⠌⠉⠵\n"
	.braille "⠨⠣⠱\n"
	.braille "⠚⠺⠑⠶⠝⠀⠰⠣⠒\n"
	.braille "⠨⠣⠱$"
	@ 용기 있는\n자여\n희망에 찬\n자여(작업 완료)

SealedChamber_InnerRoom_Braille_1C549B:: @ 81C549B
	.byte 2
	.byte 2
	.byte 28
	.byte 17
	.byte 4
	.byte 5
	.braille "⠑⠛⠮⠀⠳⠎⠐⠣\n"
	.braille "⠈⠪⠈⠥⠄⠝⠀⠻⠏⠒⠺\n"
	.braille "⠙⠥⠋⠝⠄⠑⠷⠕⠀⠕⠌⠊$"
	@ 문을 열어라\n그곳에 영원의\n포켓몬이 있다(작업 완료)

DesertRuins_Braille_1C54C8:: @ 81C54C8
	.byte 1
	.byte 0
	.byte 27
	.byte 19
	.byte 3
	.byte 3
	.braille "⠍⠀⠍\n"
	.braille "⠚⠀⠚\n"
	.braille "⠈⠎⠈⠕⠠⠎\n"
	.braille "⠈⠽⠐⠱⠁⠮⠀⠠⠠⠎⠐⠣$"
	@ 우 우\n하 하\n거기서\n괴력을 써라(작업 완료)

IslandCave_Braille_1C54FC:: @ 81C54FC
	.byte 1
	.byte 0
	.byte 29
	.byte 19
	.byte 3
	.byte 3
	.braille "⠕⠊⠗⠐⠥\n"
	.braille "⠍⠢⠨⠕⠁⠕⠨⠕⠀⠑⠂⠈⠥\n"
	.braille "⠊⠍⠀⠈⠗⠺\n"
	.braille "⠠⠊⠗⠐⠮⠀⠈⠕⠊⠐⠱⠐⠣$"
	@ 이대로\n움직이지 말고\n두 개의\n때를 기다려라(작업 완료)

AncientTomb_Braille_1C552E:: @ 81C552E
	.byte 0
	.byte 0
	.byte 29
	.byte 19
	.byte 1
	.byte 3
	.braille "⠠⠗⠐⠥⠛⠀⠠⠊⠗⠐⠮\n"
	.braille "⠚⠺⠑⠶⠈⠧⠀⠇⠐⠣⠶⠮\n"
	.braille "⠫⠅⠈⠥⠀⠨⠍⠶⠠⠕⠢⠝⠠⠎\n"
	.braille "⠚⠉⠮⠮⠀⠉⠥⠐⠱⠐⠣$"
	@ 새로운 때를\n희망과 사랑을\n갖고 중심에서\n하늘을 노려라(작업 완료)
