OldaleTown_PokemonCenter_2F_Text_1A4510:: @ 81A4510
	.string "포켓몬 통신 클럽\n"
	.string "콜로세움에 잘 오셨습니다\p"
	.string "여기에서는 친구와\n"
	.string "포켓몬 대전을 즐길 수 있습니다\p"
	.string "대전을 하겠습니까?$"
	// ポケモン つうしん クラブｎ
	// コロシアム に ようこそｐ
	// こちらでは ともだちとｎ
	// ポケモンの たいせんが たのしめますｐ
	// たいせんを しますか?

OldaleTown_PokemonCenter_2F_Text_1A457E:: @ 81A457E
	.string "포켓몬 통신 클럽\n"
	.string "트레이드센터에 잘 오셨습니다\p"
	.string "여기에서는 친구와\n"
	.string "포켓몬 교환을 할 수 있습니다\p"
	.string "교환을 하겠습니까?$"
	// ポケモン つうしん クラブｎ
	// トレ-ドセンタ- に ようこそｐ
	// こちらでは ともだちとｎ
	// ポケモンの こうかんが たのしめますｐ
	// こうかんを しますか?

OldaleTown_PokemonCenter_2F_Text_1A45FE:: @ 81A45FE
	.string "포켓몬 통신 클럽\n"
	.string "레코드코너에 잘 오셨습니다\p"
	.string "여기에서는 트레이너로서의 레코드를\n"
	.string "친구의 것과 섞을 수 있습니다\p"
	.string "친구와 레코드를 섞겠습니까?$"
	// ポケモン つうしん クラブｎ
	// レコ-ド コ-ナ- へ ようこそｐ
	// こちらでは トレ-ナ-としての レコ-ドをｎ
	// ともだちと まぜる ことが できますｐ
	// ともだちと レコ-ドを まぜますか?

OldaleTown_PokemonCenter_2F_Text_1A4696:: @ 81A4696
	.string "통신 대전에는\n"
	.string "3개의 대전 모드가 있습니다\p"
	.string "싱글배틀은 배틀에 포켓몬이\n"
	.string "1마리씩 나오는 2인 대전\p"
	.string "더블배틀은 배틀에 포켓몬이\n"
	.string "2마리씩 나오는 2인 대전\p"
	.string "멀티배틀은 배틀에 포켓몬이\n"
	.string "2마리씩 나오는 4인 대전입니다$"
	// つうしん たいせんには ｎ
	// たいせんの モ-ドが 3つありますｐ
	// シングルバトルは せんとうに ポケモンがｎ
	// 1ひきずつでて ふたりで たいせんｐ
	// ダブルバトルは せんとうに ポケモンがｎ
	// 2ひきずつでて ふたりで たいせんｐ
	// マルチバトルは せんとうに ポケモンがｎ
	// 2ひきずつでて 4にんで たいせんします

OldaleTown_PokemonCenter_2F_Text_1A4826:: @ 81A4826
	.string "대전을 하겠습니까?$"
	// たいせんを しますか?

OldaleTown_PokemonCenter_2F_Text_1A4840:: @ 81A4840
	.string "어느 대전을 하겠습니까?$"
	// どちらの たいせんをしますか?

OldaleTown_PokemonCenter_2F_Text_1A486A:: @ 81A486A
	.string "더블배틀에서는 2마리 이상의\n"
	.string "포켓몬이 필요합니다$"
	// ダブルバトルでは 2ひき いじょうのｎ
	// ポケモンが ひつようです

OldaleTown_PokemonCenter_2F_Text_1A48A3:: @ 81A48A3
	.string "교환에서는 2마리 이상의\n"
	.string "지닌 포켓몬이 필요합니다$"
	// こうかんでは 2ひき いじょうのｎ
	// てもちが ひつようです

OldaleTown_PokemonCenter_2F_Text_1A48DD:: @ 81A48DD
	.string "{STR_VAR_1}열매를 지니고 있는 포켓몬은\n"
	.string "교환할 수 없습니다!$"
	// §いのみをもっている ポケモンはｎ
	// こうかんは できません!

gUnknown_081A490C:: @ 81A490C
OldaleTown_PokemonCenter_2F_Text_1A490C:: @ 81A490C
	.string "잠시 기다려 주십시오\n"
	.string "......B 버튼으로 취소$"
	// しょうしょう おまち くださいｎ
	// ……Bボタンで キャンセル

gUnknown_081A4932:: @ 81A4932
UnknownString_81A4932: @ 81A4932
	.string "인원수가 모이면 A 버튼으로 진행한다\n"
	.string "......B 버튼으로 취소$"
	// にんずうが そろったら Aボタンで すすむｎ
	// ……Bボタンで キャンセル

gUnknown_081A4975:: @ 81A4975
UnknownString_81A4975: @ 81A4975
	.string "{STR_VAR_1}명이서 통신을 시작합니다\n"
	.string "A 버튼으로 결정 B 버튼으로 취소$"
	// §いにんで つうしんを はじめますｎ
	// Aボタンで けってい Bボタンで もどる

gUnknown_081A49B6:: @ 81A49B6
UnknownString_81A49B6: @ 81A49B6
	.string "통신 시작을 기다리고 있습니다\n"
	.string "......B 버튼으로 취소$"
	// つうしんかいしを まっていますｎ
	// ……Bボタンで キャンセル

UnknownString_81A49E2: @ 81A49E2
	.string "통신을 시작하기 전에\n"
	.string "리포트를 작성합니다만 괜찮습니까?$"
	// つうしんを はじめるまえにｎ
	// レポ-トを かきますが よろしいですか?

OldaleTown_PokemonCenter_2F_Text_1A4A22:: @ 81A4A22
	.string "그럼 방으로 들어가십시오$"
	// それでは へやへ どうぞ

FallarborTown_ContestLobby_Text_1A4A30:: @ 81A4A30
OldaleTown_PokemonCenter_2F_Text_1A4A30:: @ 81A4A30
	.string "친구의 준비가\n"
	.string "되지 않은 것 같습니다\p"
	.string "준비를 마치면\n"
	.string "다시 와주십시오$"
	// おともだちの じゅんびがｎ
	// できて いない ようですｐ
	// じゅんびが できましたらｎ
	// また おこしください

FallarborTown_ContestLobby_Text_1A4A85:: @ 81A4A85
OldaleTown_PokemonCenter_2F_Text_1A4A85:: @ 81A4A85
	.string "통신 에러입니다\n"
	.string "리셋한 후 다시 해주십시오$"
	// つうしんエラ- ですｎ
	// リセットして やりなおして ください

OldaleTown_PokemonCenter_2F_Text_1A4AC8:: @ 81A4AC8
	.string "통신 에러입니다\n"
	.string "다른 나라의 언어와는\l"
	.string "레코드를 섞을 수 없습니다$"

FallarborTown_ContestLobby_Text_1A4B1D:: @ 81A4B1D
OldaleTown_PokemonCenter_2F_Text_1A4B1D:: @ 81A4B1D
	.string "서로의 선택이 다른 것 같습니다$"
	// おたがいの せんたくが ちがっているようです

OldaleTown_PokemonCenter_2F_Text_1A4B59:: @ 81A4B59
	.string "그럼 또 방문해 주십시오$"
	// それでは また おこしください

OldaleTown_PokemonCenter_2F_Text_1A4B6C:: @ 81A4B6C
	.string "참가한 인원수가\n"
	.string "맞지 않습니다$"
	// さんかしている にんずうがｎ
	// ただしく ありません

OldaleTown_PokemonCenter_2F_Text_1A4B95:: @ 81A4B95
	.string "싱글배틀은 {STR_VAR_1}명이서\n"
	.string "즐길 수 없습니다!$"
	// シングルバトルは §いにんでｎ
	// あそぶことは できません!

OldaleTown_PokemonCenter_2F_Text_1A4BCC:: @ 81A4BCC
	.string "더블배틀은 {STR_VAR_1}명이서\n"
	.string "즐길 수 없습니다!$"
	// ダブルバトルは §いにんではｎ
	// あそぶことは できません!

OldaleTown_PokemonCenter_2F_Text_1A4C03:: @ 81A4C03
	.string "참가 인원수가 4명이 아니면\n"
	.string "대전할 수 없습니다!$"
	// さんか にんずうが 4にん いないとｎ
	// たいせん することが できません!

OldaleTown_PokemonCenter_2F_Text_1A4C38:: @ 81A4C38
	.string "다시 한 번 인원수를 확인하고\n"
	.string "처음부터 다시 해주십시오$"
	// もういちど にんずうを たしかめてｎ
	// さいしょから やりなおして ください

TradeRoom_WillLinkBeTerminated: @ 81A4C6E
	.string "방에서 나가면 통신이\n"
	.string "종료됩니다만 괜찮겠습니까?$"
	// へやからでると つうしんを しゅうりょうｎ
	// しますが よろしいですか?

TradeRoom_TerminatingLink: @ 81A4CAF
	.string "통신 종료 후 방 밖으로\n"
	.string "안내하겠습니다! 잠시 기다려 주십시오$"
	// つうしんを しゅうりょうして へやの そとへｎ
	// ごあんないします! しばらく おまちください

CableClub_TooBusyToNotice: @ 81A4CF6
	.string "바쁜 것 같다...$"
	// とりこみちゅうの ようだ…

CableClub_LookAtTrainerCard1: @ 81A4D1C
	.string "{STR_VAR_1}의 트레이너카드를\n"
	.string "봤다!$"
	// §いの トレ-ナ-カ-ドをｎ
	// みせてもらった!

CableClub_LookAtTrainerCard2: @ 81A4D45
	.string "{STR_VAR_1}의 트레이너카드를\n"
	.string "봤다! ...{STR_VAR_2}카드다!$"
	// §いの トレ-ナ-カ-ドをｎ
	// みせてもらった! …§うカ-ドだ!

SingleBattleColosseum_Text_1A4D7E:: @ 81A4D7E
	.string "정해진 자리에 서서\n"
	.string "대전을 시작해 주십시오$"
	// しょていの いちに ついてｎ
	// たいせんを はじめて ください

TradeCenter_Text_1A4DAB:: @ 81A4DAB
	.string "정해진 자리에 서서\n"
	.string "교환을 시작해 주십시오$"
	// しょていの いちに ついてｎ
	// こうかんを はじめて ください

RecordCorner_Text_1A4DD7:: @ 81A4DD7
	.string "정해진 자리에 서서\n"
	.string "기다려 주십시오$"
	// しょていの いちに ついてｎ
	// おまち ください

RecordCorner_Text_1A4DF7:: @ 81A4DF7
	.string "이용해 주셔서 감사합니다$"
	// ごりよう ありがとう ございました

UnknownString_81A4E0A: @ 81A4E0A
	.string "그럼 멀티배틀에 내보낼\n"
	.string "포켓몬을 선택해 주십시오$"
	// では マルチバトルに だす ｎ
	// ポケモンを えらんでください

RecordCorner_Text_1A4E3B:: @ 81A4E3B
	.string "{STR_VAR_1}{K_EU}로부터\n"
	.string "{STR_VAR_2}{K_IGA} 전송됐다!$"
	// §いさんからｎ
	// §うが おくられてきた!

OldaleTown_PokemonCenter_2F_Text_1A4E50:: @ 81A4E50
	.string "트레이너카드의\n"
	.string "기록을 다시 씁니다!$"
	// トレ-ナ-カ-ドのｎ
	// きろくを かきかえます!

OldaleTown_PokemonCenter_2F_Text_1A4E79:: @ 81A4E79
	.string "또 이용해 주세요!$"
	// では また どうぞ!
