Text_PictureBookshelf: @ 81C6A69
	.string "포켓몬 그림책이 모여 있다!$"
	@ ポケモンえほんが そろってる!

Text_Bookshelf: @ 81C6A91
	.string "다양한 책이 가득 있다!$"
	@ いろんな ほんが いっぱいだ!

Text_PokemonCenterBookshelf: @ 81C6AB6
	.string "포켓몬 잡지가 진열되어 있다!\p"
	.string "...“포켓몬의 친구”\n"
	.string "...“포켓몬수첩”\l"
	.string "...“귀여운 포켓몬”$"
	@ ポケモンざっしが ならんでる!ｐ
	@ ……「ポケモンのとも」ｎ
	@ ……「ポケモン てちょう」ｌ
	@ ……「かわいい ポケモン」

Text_Vase: @ 81C6B00
	.string "비싸 보이는 항아리가 있다!\n"
	.string "들여다보니...\p"
	.string "안은 텅 비었다!$"
	@ たかそうな つぼが ある!ｎ
	@ のぞきこむと……ｐ
	@ なかは からっぽ だ!

Text_EmptyTrashCan: @ 81C6B41
	.string "안은 텅 비었다!$"
	@ なかは からっぽ だ!

Text_ShopShelf: @ 81C6B4D
	.string "가지각색의 포켓몬 상품이\n"
	.string "빽빽하게 진열되어 있다!$"
	@ たくさんの ポケモン グッズがｎ
	@ ところせましと ならべられてる!

Text_Blueprint: @ 81C6B85
	.string "무언가의 설계도...?\n"
	.string "봐도 뭐가 뭔지 모르겠다!$"
	@ なにかの せっけいず……?ｎ
	@ みても チンプンカンプン!
