FallarborTown_ContestLobby_Text_1A5DFC:: @ 81A5DFC
	.string "안녕하세요!\n"
	.string "여기에서는 포켓몬 콘테스트\l"
	.string "{STR_VAR_1}랭크의\l"
	.string "접수를 받고 있습니다!$"
	// こんにちは!ｎ
	// こちらでは ポケモンコンテストｌ
	// §い ランクのｌ
	// うけつけを おこなって います!

FallarborTown_ContestLobby_Text_1A5E46:: @ 81A5E46
	.string "당신의 포켓몬도 콘테스트에\n"
	.string "참가시켜 보겠습니까?$"
	// あなたの ポケモンも コンテストにｎ
	// さんか させて みませんか?

FallarborTown_ContestLobby_Text_1A5E7C:: @ 81A5E7C
	.string "어느 설명을 듣겠습니까?$"
	// どの せつめいを ききますか?

FallarborTown_ContestLobby_Text_1A5E98:: @ 81A5E98
	.string "포켓몬 콘테스트는 4명의 트레이너가\n"
	.string "1마리씩 포켓몬을 데리고 와서\l"
	.string "총 4마리로 진행됩니다!\p"
	.string "콘테스트에는 1차 심사와\n"
	.string "2차 심사가 있습니다!\p"
	.string "1차 심사에서는 회장의\n"
	.string "관객이 맘에 드는 포켓몬에게\l"
	.string "투표를 합니다!\p"
	.string "2차 심사에서는 포켓몬이 순서대로\n"
	.string "특기인 기술로 어필을 합니다!\l"
	.string "심사위원의 주목을 받거나\l"
	.string "관객을 기술로 열광시키거나...\l"
	.string "어쨌든 마구 눈에 띄면 됩니다!\p"
	.string "1차 심사와 2차 심사의 결과로\n"
	.string "종합 포인트를 합산하여\l"
	.string "가장 평가가 높은 포켓몬이\l"
	.string "우승하게 됩니다!$"
	// ポケモンコンテストは 4にんの トレ-ナ-がｎ
	// 1ぴきずつ ポケモンを もちよってｌ
	// 4ひきで おこなわれます!ｐ
	// コンテスト には 1じ しんさとｎ
	// 2じ しんさが あります!ｐ
	// 1じ しんさでは かいじょうのｎ
	// おきゃくさまが きにいった ポケモンをｌ
	// とうひょう します!ｐ
	// 2じ しんさでは ポケモンが じゅんばんにｎ
	// とくいな わざで アピ-ルを します!ｌ
	// しんさいんに ちゅうもくされたりｌ
	// おきゃくさまに わざを きにいられたり……ｌ
	// とにかく たくさん めだって ください!ｐ
	// 1じしんさと 2じしんさの けっかからｎ
	// そうごうポイントを だしてｌ
	// いちばん たかかった ポケモンがｌ
	// ゆうしょう できます!

FallarborTown_ContestLobby_Text_1A609B:: @ 81A609B
	.string "콘테스트는 총 5종류!\n"
	.string "근사함 아름다움 귀여움\l"
	.string "슬기로움 그리고 강인함입니다!\p"
	.string "참가할 포켓몬에게\n"
	.string "어울리는 콘테스트를\l"
	.string "선택해 주세요!$"
	// コンテストには 5しゅるい あります!ｐ
	// かっこよさ うつくしさ かわいさｎ
	// かしこさ そして たくましさｌ
	// いじょうの 5しゅるい です!ｐ
	// エントリ- する ポケモンにｎ
	// ピッタリの コンテストをｌ
	// えらんで あげて くださいね!

FallarborTown_ContestLobby_Text_1A613F:: @ 81A613F
	.string "포켓몬 콘테스트에는\n"
	.string "노말랭크 슈퍼랭크\l"
	.string "하이퍼랭크 마스터랭크라고 하는\l"
	.string "4개의 랭크가 있습니다\p"
	.string "노말랭크에는 모든\n"
	.string "포켓몬이 나갈 수 있습니다\p"
	.string "노말랭크에서 우승한\n"
	.string "포켓몬은 같은 종류의\l"
	.string "슈퍼랭크 콘테스트에 나갈 수 있게 됩니다\p"
	.string "마찬가지로 슈퍼에서 우승하면\n"
	.string "하이퍼에 하이퍼에서 우승하면\l"
	.string "마스터랭크에 나갈 수 있습니다\p"
	.string "마스터랭크에서 우승한\n"
	.string "포켓몬은 몇 번이고 마스터랭크의\l"
	.string "콘테스트에 나갈 수 있습니다$"
	// ポケモンコンテスト にはｎ
	// ノ-マルランク ス-パ-ランクｌ
	// ハイパ-ランク そしてマスタ-ランクｌ
	// という 4つの ランクが ありますｐ
	// ノ-マルランク には すべてのｎ
	// ポケモンが でることが できますｐ
	// ノ-マルランクで ゆうしょう できたｎ
	// ポケモンは おなじ しゅるいのｌ
	// ス-パ-ランクの コンテストに でられますｐ
	// おなじように ス-パ-で ゆうしょう すればｎ
	// ハイパ-に ハイパ-で ゆうしょう すればｌ
	// マスタ-ランクに でられるのですｐ
	// マスタ-ランクで ゆうしょう したｎ
	// ポケモンは なんどでも マスタ-ランクのｌ
	// コンテストに でる ことが できます

FallarborTown_ContestLobby_Text_1A6319:: @ 81A6319
	.string "어느 포켓몬을 참가시키겠습니까?$"
	// どのポケモンを さんか させますか?

FallarborTown_ContestLobby_Text_1A6340:: @ 81A6340
	.string "콘테스트패스를 갖고 계신 분은\n"
	.string "누구든지 참가하실 수 있습니다!\p"
	.string "콘테스트패스는 잔디마을에 있는\n"
	.string "노말랭크 콘테스트 회장에서\l"
	.string "조건 없이 받으실 수 있답니다!\p"
	.string "패스를 받고 나서 다시 와주세요!$"
	// コンテストパスを おもちの かたはｎ
	// どなたでも さんか できます!ｐ
	// コンテストパスは シダケタウンに あるｎ
	// ノ-マルランクの コンテスト かいじょうでｌ
	// どなたでも もらえますよ!ｐ
	// パスをもって また いらして くださいね!

LilycoveCity_ContestLobby_Text_1A63F4:: @ 81A63F4
	.string "여기에서는 포켓몬 콘테스트\n"
	.string "4인 전용 접수를 받고 있습니다!\p"
	.string "콘테스트패스를 갖고 계신 분은\n"
	.string "누구든지 참가하실 수 있습니다!\p"
	.string "콘테스트패스는 잔디마을에 있는\n"
	.string "노말랭크 콘테스트 회장에서\l"
	.string "조건 없이 받으실 수 있답니다!\p"
	.string "패스를 받고 나서 다시 와주세요!$"
	// こちらは ポケモンコンテストのｎ
	// 4めいさま せんようの うけつけです!ｐ
	// コンテストパスを おもちの かたはｎ
	// どなたでも さんか できます!ｐ
	// コンテストパスは シダケタウンに あるｎ
	// ノ-マルランクの コンテスト かいじょうでｌ
	// どなたでも もらえますよ!ｐ
	// パスをもって また いらして くださいね!

FallarborTown_ContestLobby_Text_1A64F4:: @ 81A64F4
	.string "콘테스트패스를 갖고 계신 분은\n"
	.string "누구든지 참가하실 수 있습니다!\p"
	.string "갖고 계시지 않은 분께는\n"
	.string "이쪽에서 발행해 드립니다!\p"
	.string "콘테스트패스를\n"
	.string "발행하시겠습니까?$"
	// コンテストパスを おもちの かたはｎ
	// どなたでも さんか できます!ｐ
	// おもちで ない かたはｎ
	// こちらで はっこう いたします!ｐ
	// コンテストパスをｎ
	// はっこう しますか?

FallarborTown_ContestLobby_Text_1A6583:: @ 81A6583
	.string "그럼 여기 받으세요!$"
	// それでは こちらを どうぞ!

FallarborTown_ContestLobby_Text_1A6590:: @ 81A6590
	.string "어라?\p"
	.string "{PLAYER}님의 패스는\n"
	.string "이미 발행되었습니다!\p"
	.string "콘테스트패스를 가지고\n"
	.string "다시 와주십시오!$"
	// あら?ｐ
	// §あさんの パスはｎ
	// すでに はっこう されてますね!ｐ
	// コンテストパスを おもちに なってｎ
	// また いらして くださいね!

FallarborTown_ContestLobby_Text_1A65EA:: @ 81A65EA
	.string "참가하고 싶을 때는\n"
	.string "언제든지 다시 와주십시오!$"
	// さんか したい ときはｎ
	// いつでも いらして くださいね!

FallarborTown_ContestLobby_Text_1A6623:: @ 81A6623
	.string "어느 콘테스트에 참가하겠습니까?$"
	// どの コンテストに さんか しますか?

FallarborTown_ContestLobby_Text_1A664A:: @ 81A664A
LilycoveCity_ContestLobby_Text_1A664A:: @ 81A664A
	.string "죄송합니다만\n"
	.string "손님의 포켓몬으로는\l"
	.string "이 랭크에는 아직\l"
	.string "참가할 수 없는 듯합니다...$"
	// もうしわけ ないのですがｎ
	// おきゃくさまの ポケモンですとｌ
	// このランクには まだ しゅつじょうｌ
	// できないようです…

FallarborTown_ContestLobby_Text_1A669F:: @ 81A669F
LilycoveCity_ContestLobby_Text_1A669F:: @ 81A669F
	.string "죄송합니다!\n"
	.string "알은 참가할 수 없습니다...$"
	// ごめんなさい!ｎ
	// タマゴは しゅつじょう できないんです……

FallarborTown_ContestLobby_Text_1A66DC:: @ 81A66DC
LilycoveCity_ContestLobby_Text_1A66DC:: @ 81A66DC
	.string "그 포켓몬은 건강하지 않은 것\n"
	.string "같으니 참가할 수 없습니다...$"
	// そちらの ポケモンは げんきがないｎ
	// ようなので しゅつじょう できないです……

FallarborTown_ContestLobby_Text_1A6724:: @ 81A6724
	.string "어라 그 리본은...\p"
	.string "손님의 포켓몬은 이미\n"
	.string "이 콘테스트에서 우승한 적이\l"
	.string "있습니다... 그래도 괜찮겠습니까?$"
	// あら そちらの リボンは……ｐ
	// おきゃくさまの ポケモンは もうｎ
	// この コンテストで ゆうしょう したことがｌ
	// あるのですね… それでも いいですか?

FallarborTown_ContestLobby_Text_1A67A3:: @ 81A67A3
LilycoveCity_ContestLobby_Text_1A67A3:: @ 81A67A3
	.string "그 포켓몬으로 하시겠습니까?$"
	// そちらの ポケモンで よろしいですか?

FallarborTown_ContestLobby_Text_1A67C1:: @ 81A67C1
	.string "그럼 손님의 포켓몬을\n"
	.string "참가시킵니다!\l"
	.string "손님의 참가 번호는\l"
	.string "4번입니다!\l"
	.string "콘테스트가 곧 시작됩니다!$"
	// それでは おきゃくさまの ポケモンをｎ
	// エントリ- します!ｌ
	// おきゃくさまの エントリ-ナンバ-はｌ
	// 4ばん に なります!ｌ
	// コンテストは すぐに はじまります!

FallarborTown_ContestLobby_Text_1A6832:: @ 81A6832
LilycoveCity_ContestLobby_Text_1A6832:: @ 81A6832
SlateportCity_ContestLobby_Text_1A6832:: @ 81A6832
VerdanturfTown_ContestLobby_Text_1A6832:: @ 81A6832
	.string "그럼 이쪽으로 오세요!\n"
	.string "힘내세요!$"
	// それでは こちらへ どうぞ!ｎ
	// がんばって くださいね!

FallarborTown_ContestLobby_Text_1A685A:: @ 81A685A
	.string "콘테스트 우승\n"
	.string "축하합니다!\p"
	.string "상품은 이쪽에\n"
	.string "있습니다! 자 받으세요!$"
	// コンテストでの ゆうしょうｎ
	// おめでとう ございます!ｐ
	// しょうひんは こちらで おあずかりｎ
	// して ありますよ! さあ どうぞ!

FallarborTown_ContestLobby_Text_1A68C6:: @ 81A68C6
	.string "그럼 다음에\n"
	.string "가지러 와주세요!$"
	// それでは また あとでｎ
	// とりに きて くださいね!

LinkContestRoom1_Text_1A68F0:: @ 81A68F0
	.string "사회자: 네! 이제부터\n"
	.string "{STR_VAR_3}랭크\l"
	.string "포켓몬 {STR_VAR_2}콘테스트를\l"
	.string "시작하겠습니다!\p"
	.string "참가한 트레이너와\n"
	.string "포켓몬들은 모두 이쪽!$"
	// しかい『はい! これよりｎ
	// §え ランクのｌ
	// ポケモン §うコンテストがｌ
	// はじまります!ｐ
	// しゅつじょう される トレ-ナ-とｎ
	// ポケモンの みなさんは こちら!

LinkContestRoom1_Text_1A6976:: @ 81A6976
	.string "사회자: 네! 이제부터\n"
	.string "친구 4인 통신\l"
	.string "포켓몬 {STR_VAR_2}콘테스트를\l"
	.string "시작하겠습니다!\p"
	.string "참가한 트레이너와\n"
	.string "포켓몬들은 모두 이쪽!$"
	// しかい『はい! これよりｎ
	// おともだち 4にん つうしんのｌ
	// ポケモン §うコンテストがｌ
	// はじまります!ｐ
	// しゅつじょう される トレ-ナ-とｎ
	// ポケモンの みなさんは こちら!

LinkContestRoom1_Text_1A6A04:: @ 81A6A04
	.string "사회자: 참가 번호 {STR_VAR_2}번!\n"
	.string "{STR_VAR_1}님의 {STR_VAR_3}입니다!$"
	// しかい『エントリ-ナンバ- §うばん!ｎ
	// §いさんの §え です!

LinkContestRoom1_Text_1A6A1F:: @ 81A6A1F
	.string "사회자: 자\n"
	.string "포켓몬의 소개가 끝났습니다\l"
	.string "1차 심사를 시작합니다!\p"
	.string "회장의 관객은\n"
	.string "포켓몬의 인기투표를 해주십시오!\p"
	.string "그럼 바로 시작합시다!\n"
	.string "투표 부탁드립니다!$"
	// しかい『さあｎ
	// ポケモンの しょうかいが おわりましたｌ
	// 1じ しんさに はいりましょう!ｐ
	// かいじょうの おきゃくさまに よるｎ
	// ポケモンの にんき とうひょうです!ｐ
	// では さっそく はじめましょう!ｎ
	// とうひょう おねがいします!

LinkContestRoom1_Text_1A6AE1:: @ 81A6AE1
	.string "                      투표 중...$"
	//     とうひょう ちゅう…

LinkContestRoom1_Text_1A6AF5:: @ 81A6AF5
	.string "자!\n"
	.string "투표가 끝났습니다!\l"
	.string "집계하는 동안에\l"
	.string "2차 심사를 시작하겠습니다!\p"
	.string "2차 심사는 드디어\n"
	.string "기다리시던 어필타임!\l"
	.string "기술로 마구 어필합시다-!\p"
	.string "그럼 힘내서 갑시다!\n"
	.string "렛츠! 어필!$"
	// さあ!ｎ
	// いま とうひょうが おわりました!ｌ
	// しゅうけいを している あいだにｌ
	// 2じ しんさに うつりましょう!ｐ
	// 2じ しんさは いよいよｎ
	// おまちかねの アピ-ルタイム!ｌ
	// わざで アピ-ル しまくりましょう-!ｐ
	// では はりきって どうぞ!ｎ
	// レッツ! アピ-ル!

LinkContestRoom1_Text_1A6C06:: @ 81A6C06
	.string "사회자: 네에 거기까지--!$"
	// しかい『はあい そこまでえ--!

LinkContestRoom1_Text_1A6C21:: @ 81A6C21
	.string "여러분들 대단한 어필이었습니다!\n"
	.string "이것으로 모두 종료입니다!\l"
	.string "수고하셨습니다!$"
	// みなさん すばらしい アピ-ルでした!ｎ
	// これで すべて しゅうりょう です!ｌ
	// おつかれさまでした!

LinkContestRoom1_Text_1A6C9D:: @ 81A6C9D
	.string "자 그럼 남은 것은\n"
	.string "두근거리는 결과 발표군요!\l"
	.string "발표는 심사위원 쪽에서\l"
	.string "이루어집니다!$"
	// さて のこるはｎ
	// ドキドキの けっかはっぴょう ですね!ｌ
	// はっぴょうは しんさいんの ほうからｌ
	// おこなわれます!

LinkContestRoom1_Text_1A6D16:: @ 81A6D16
	.string "심사위원: 그럼... 발표하겠습니다!$"
	// しんさいん『では… はっぴょう します!

LinkContestRoom1_Text_1A6D3C:: @ 81A6D3C
	.string "사회자: 참가 번호 {STR_VAR_2}번\n"
	.string "{STR_VAR_3}님! 그리고 {STR_VAR_1}!\l"
	.string "축하합니다!$"
	// しかい『エントリ-ナンバ- §うばんｎ
	// §えさん! そして §い!ｌ
	// おめでとう ございます!

LinkContestRoom1_Text_1A6D6A:: @ 81A6D6A
	.string "상품으로\n"
	.string "이 리본을 받아 주세요!$"
	// しょうひんと してｎ
	// この リボンを おうけとり ください!

LinkContestRoom1_Text_1A6D96:: @ 81A6D96
	.string "{PLAYER}{K_EUNNEUN} 리본을 받았다!$"
	// §あは リボンを もらった!

LinkContestRoom1_Text_1A6DAC:: @ 81A6DAC
	.string "{PLAYER}{K_EUNNEUN} 리본을\n"
	.string "{STR_VAR_1}에게 달아 줬다!$"
	// §あは リボンをｎ
	// §いに つけて あげた!

LinkContestRoom1_Text_1A6DC5:: @ 81A6DC5
	.string "사회자: 자!\n"
	.string "상품을 받아 주세요!$"
	// しかい『さあ!ｎ
	// しょうひんを おうけとり ください!

LinkContestRoom1_Text_1A6DF1:: @ 81A6DF1
	.string "사회자: 축하합니다!\n"
	.string "또 참가해 주세요!$"
	// しかい『おめでとう ございます!ｎ
	// また さんか してくださいね!

LinkContestRoom1_Text_1A6E1F:: @ 81A6E1F
	.string "그럼 상품은 나중에\n"
	.string "접수처에서 받아 주세요!\l"
	.string "다음번 참가를 기다리고 있겠습니다!$"
	// それでは しょうひんは あとでｎ
	// うけつけで おうけとり ください!ｌ
	// またの さんかを おまち してます!
