Route117_Text_1B25CB:: @ 81B25CB
	.string "나는 키우미집 할아버지라네\p"
	.string "여기서 모두의 소중한 포켓몬을\n"
	.string "돌보고 있지\p"
	.string "뭔가 키우고 싶다면\n"
	.string "할머니에게 부탁하게나$"
	@ わしは そだてや じいさんじゃｐ
	@ ここで みんなの だいじな ポケモンのｎ
	@ めんどうを みて おるのじゃよｐ
	@ なにか そだてて ほしければｎ
	@ ばあさんに たのんで おくれ

Route117_Text_1B2659:: @ 81B2659
	.string "오오! 자네구먼\p"
	.string "맡고 있던 포켓몬을\n"
	.string "키우고 있었더니... 글쎄!\p"
	.string "포켓몬이 알을\n"
	.string "가지고 있었다네!\p"
	.string "어디서 가져왔는지 모르겠지만\n"
	.string "자네의 포켓몬이 가지고 있었으니\p"
	.string "역시 갖고 싶겠지?$"
	@ おお! あんたかｐ
	@ あずかっていた ポケモンをｎ
	@ そだてていたら……なんと!ｐ
	@ ポケモンが タマゴをｎ
	@ もっておったんじゃ!ｐ
	@ どこから もってきたか わからんがｎ
	@ あんたの ポケモンが もってたんじゃｐ
	@ やっぱり ほしいじゃろ?

Route117_Text_1B2710:: @ 81B2710
	.string "오오 자네구먼! 잘 왔네\n"
	.string "{STR_VAR_1}{K_EUNNEUN} 잘 있구먼$"
	@ おお あんたか! よくきたなｎ
	@ §いは げんきじゃぞ

Route117_Text_1B2745:: @ 81B2745
	.string "그럼 내가 갖겠네\n"
	.string "고맙구먼$"
	@ それじゃ わしが もらおうｎ
	@ ありがとよ

Route117_Text_1B2766:: @ 81B2766
	.string "포켓몬이 가득한 것 같구먼...\n"
	.string "지닌 포켓몬을 정리하고 다시 오게나$"
	@ てもちが いっぱいの ようじゃな…ｎ
	@ てもちを せいりしてから またきなさい

Route117_Text_1B27A2:: @ 81B27A2
	.string "{PLAYER}{K_EUNNEUN} 키우미집 할아버지에게서\n"
	.string "알을 받았다!$"
	@ §あは そだてや じいさんからｎ
	@ タマゴを もらった!

Route117_Text_1B27CD:: @ 81B27CD
	.string "소중히 키우게!$"
	@ だいじにそだてなさいよ!

Route117_Text_1B27E3:: @ 81B27E3
	.string "그런데 자네의 {STR_VAR_1} 말인데\p"
	.string "왠지 {STR_VAR_2}의 {STR_VAR_3}{K_WAGWA}\n"
	.string "사이좋게 놀고 있었다네\p"
	.string "게다가 아무래도 메일을\n"
	.string "받은 모양이구먼$"
	@ ところで あんたの §いじゃがｐ
	@ なんか §うとこの §えとｎ
	@ なかよく あそんで おったぞｐ
	@ しかも なにやら メ-ルをｎ
	@ もらっておった ようじゃ

UnknownString_81B2858: @ 81B2858
	.string "포켓몬을 데려가고 싶을 때는\n"
	.string "할머니에게 말해주게$"
	@ ポケモンを ひきとりたい ときはｎ
	@ ばさんに いって おくれ

Route117_Text_1B2897:: @ 81B2897
	.string "오오 자네구먼! 잘 왔네\n"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2}{K_EUNNEUN} 잘 있구먼$"
	@ おお あんたか! よくきたなｎ
	@ §いと §うは げんきじゃぞ

Route117_Text_1B28C4:: @ 81B28C4
	.string "내가 가져갈지도 모른다네\n"
	.string "사실은 갖고 싶지?$"
	@ わしが もらってしまうぞｎ
	@ ほんとうは ほしいんじゃろ?

Route117_PokemonDayCare_Text_1B28F2:: @ 81B28F2
	.string "나는 키우미집 할머니라네\p"
	.string "자네를 대신해서 포켓몬을\n"
	.string "키워줄 수 있지\p"
	.string "뭔가 맡기고 싶은가?$"
	@ わしは そだてや ばあさんじゃｐ
	@ おまえさんの かわりに ポケモンをｎ
	@ そだてて あげるよｐ
	@ なにか そだてて ほしいのかい?

Route117_PokemonDayCare_Text_1B2947:: @ 81B2947
	.string "어느 아이를 키우게 할 텐가?$"
	@ どのこを そだてて みるかね?

Route117_PokemonDayCare_Text_1B296E:: @ 81B296E
	.string "그럼 {STR_VAR_1}{K_EULREUL}\n"
	.string "당분간 맡아주겠네\p"
	.string "적당히 시간이\n"
	.string "지나면 다시 오게나$"
	@ それでは §いをｎ
	@ しばらく あずかるぞｐ
	@ てきとうに じかんがｎ
	@ たったら またきなさい

Route117_PokemonDayCare_Text_1B29AD:: @ 81B29AD
	.string "2마리까지 맡을 수 있는데\n"
	.string "다른 1마리도 키우게 할 텐가?$"
	@ 2ひき までなら あずかれるけどｎ
	@ もう 1ぴき そだててみるかい?

Route117_PokemonDayCare_Text_1B29F4:: @ 81B29F4
	.string "할아버지가 자네를 찾고 있다네$"
	@ じいさんが あんたを さがして おったぞ

Route117_PokemonDayCare_Text_1B2A14:: @ 81B2A14
	.string "그래 그럼 또 오게나$"
	@ そうかい それじゃ また きておくれ

Route117_PokemonDayCare_Text_1B2A30:: @ 81B2A30
	.string "돈이 부족한 것 같은데...$"
	@ おかねが たりない ようじゃのう…

Route117_PokemonDayCare_Text_1B2A4F:: @ 81B2A4F
	.string "다른 1마리도 데리고 갈 텐가?$"
	@ もう 1ぴきも ひきとるかい?

Route117_PokemonDayCare_Text_1B2A76:: @ 81B2A76
	.string "그럼 또 오게나$"
	@ それじゃ また きておくれ

Route117_PokemonDayCare_Text_1B2A88:: @ 81B2A88
	.string "오오 자넨가! 잘 왔구먼\n"
	.string "자네의 포켓몬은 잘 있다네$"
	@ おお あんたか! よくきたなｎ
	@ おまえさんの ポケモンは ゲンキじゃぞ

Route117_PokemonDayCare_Text_1B2ACC:: @ 81B2ACC
	.string "{STR_VAR_1}{K_EUNNEUN} 레벨로 말하면\n"
	.string "{STR_VAR_2} 정도 자랐구먼$"
	@ §いは レベルで いうとｎ
	@ §うくらい そだって おるぞ

Route117_PokemonDayCare_Text_1B2AEF:: @ 81B2AEF
	.string "지닌 포켓몬이 가득하구먼!\n"
	.string "포켓몬을 정리하고 나서 와주게나$"
	@ てもちの ポケモンがいっぱいじゃよ!ｎ
	@ ポケモンを せいりしてから きなさい

UnknownString_81B2B27: @ 81B2B27
	.string "어느 포켓몬을 데리고 갈 텐가?$"
	@ どっちの ポケモンを ひきとるかい?

Route117_PokemonDayCare_Text_1B2B49:: @ 81B2B49
	.string "{STR_VAR_1}{K_EULREUL} 데리고 갈 거면\n"
	.string "요금은 {STR_VAR_2}원이구먼$"
	@ §いを ひきとるならｎ
	@ りょうきんは §う￥ だよ

Route117_PokemonDayCare_Text_1B2B75:: @ 81B2B75
	.string "잘 받았네!\n"
	.string "그럼 데리고 가게나!$"
	@ はいよ たしかに!ｎ
	@ じゃあ ポケモンを つれていきなさい!

Route117_PokemonDayCare_Text_1B2B93:: @ 81B2B93
	.string "{PLAYER}{K_EUNNEUN} 키우미집 할머니한테서\n"
	.string "{STR_VAR_1}{K_EULREUL} 데리고 왔다!$"
	@ §あは そだてや ばあさんからｎ
	@ §いを ひきとった!

Route117_PokemonDayCare_Text_1B2BBB:: @ 81B2BBB
	.string "어라? 포켓몬이\n"
	.string "1마리밖에 없구먼\p"
	.string "또 오게나$"
	@ おや? ポケモンがｎ
	@ 1ぴき しか いないようだなｐ
	@ また きなさいよ

Route117_PokemonDayCare_Text_1B2BF6:: @ 81B2BF6
	.string "포켓몬을 찾아갈 텐가?$"
	@ ポケモンを ひきとるかい?

Route117_PokemonDayCare_Text_1B2C17:: @ 81B2C17
	.string "그 포켓몬을 맡기면\n"
	.string "싸울 수 없게 된다네\p"
	.string "또 오게나$"
	@ その ポケモンを あずけるとｎ
	@ たたかえなく なるぞｐ
	@ また きなさいよ

UnknownString_81B2C68: @ 81B2C68
	.string "어라...?$"
	@ おや…?

@ XXX JP
	.string "\p"
	.string "たまごの　ようすが‥\p"
	.string "‥‥‥‥\p"
	.string "おめでとう！\n"
	.string "たまごから　{STR_VAR_1}が　うまれた！$"
	@ ｐ
	@ たまごの ようすが…ｐ
	@ …………ｐ
	@ おめでとう!ｎ
	@ たまごから §いが うまれた!
