UnknownString_81C5033: @ 81C5033
	.string "DAD: {PLAYER}! Good to see you!\n"
	.string "There's a letter here for you, {PLAYER}.$"
	// パパ『§あ! よく きたな!ｎ
	// §ああての てがみが とどけられたぞ

UnknownString_81C5070: @ 81C5070
	.string "DAD: I guess this is a PASS for a ship.\n"
	.string "But I've never seen this ship before.\p"
	.string "You should find out what this is about\n"
	.string "in LILYCOVE.$"
	// パパ『わたしも みたことのないｎ
	// ふねの チケット だな……ｌ
	// ミナモに いってみると いいだろう

LilycoveCity_Harbor_Text_1C50F2:: @ 81C50F2
	.string "The ferry to SLATEPORT is...\p"
	.string "Oh?\n"
	.string "That PASS...$"
	// カイナいき れんらくせん……ｐ
	// あら?ｎ
	// その チケットは……!

LilycoveCity_Harbor_Text_1C5120:: @ 81C5120
	.string "Aye, mate, are you the one who brought\n"
	.string "that mighty odd PASS?\p"
	.string "I'll tell you, you're trying to reach a\n"
	.string "tiny spit of an island far in the south.\p"
	.string "There's no telling what we'll encounter\n"
	.string "once we reach there, aye.\l"
	.string "That shivers my timbers!\p"
	.string "All aboard!$"
	// ヘンテコな チケットをｎ
	// もってきたのは おまえさんか?ｐ
	// おまえが いこうと しているのはｎ
	// みなみの はての ちっぽけな しま……ｐ
	// そこでは なにが おこるのかｎ
	// だれも わからねえ……ｌ
	// ううむ ふなのりの ちが さわぐぜ!ｐ
	// さあ のりな!

SouthernIsland_Exterior_Text_1C5215:: @ 81C5215
	.string "Aye, mate, there's nothing here to\n"
	.string "see or do on this forgettable island.\p"
	.string "What say we sail back to LILYCOVE?$"
	// なにもねえ ちんけな しま だな……ｎ
	// ミナモへ かえるか?

SouthernIsland_Exterior_Text_1C5281:: @ 81C5281
	.string "Aye, right, then!\n"
	.string "Sail home we will!$"
	// よし! かえると するか!

SouthernIsland_Exterior_Text_1C52A6:: @ 81C52A6
	.string "Aye, right, as you like, then.$"
	// そうかいｎ
	// まあ すきにするが いいさ

SouthernIsland_Interior_Text_1C52C5:: @ 81C52C5
	.string "“All dreams are but another reality.\n"
	.string "Never forget...”$"
	// すべての ゆめは もうひとつの げんじつｎ
	// それを わすれるべからず……

SouthernIsland_Exterior_Text_1C52FB:: @ 81C52FB
	.string "“Those whose memories fade seek to\n"
	.string "carve them in their hearts...”$"
	// きおく かすみし ものはｎ
	// こころに きざみつける ことを のぞむ……
