UnknownString_81C5033: @ 81C5033
	.string "아빠: {PLAYER}{K_AYA}! 잘 왔구나!\n"
	.string "네 앞으로 편지가 왔단다$"
	// パパ『§あ! よく きたな!ｎ
	// §ああての てがみが とどけられたぞ

UnknownString_81C5070: @ 81C5070
	.string "아빠: 나도 본 적이 없는\n"
	.string "배의 티켓인걸...\l"
	.string "해안시티로 가보도록 하렴$"
	// パパ『わたしも みたことのないｎ
	// ふねの チケット だな……ｌ
	// ミナモに いってみると いいだろう

LilycoveCity_Harbor_Text_1C50F2:: @ 81C50F2
	.string "잿빛도시행 연락선...\p"
	.string "어라?\n"
	.string "그 티켓은...!$"
	// カイナいき れんらくせん……ｐ
	// あら?ｎ
	// その チケットは……!

LilycoveCity_Harbor_Text_1C5120:: @ 81C5120
	.string "이상한 티켓을\n"
	.string "가지고 온 게 너야?\p"
	.string "네가 가려고 하는 곳은\n"
	.string "남쪽 제일 끝에 있는 조그만 섬...\p"
	.string "그곳은 뭐가 일어날지\n"
	.string "아무도 모르는 곳...\l"
	.string "으음 선원의 피가 들끓는구만!\p"
	.string "자 어서 타!$"
	// ヘンテコな チケットをｎ
	// もってきたのは おまえさんか?ｐ
	// おまえが いこうと しているのはｎ
	// みなみの はての ちっぽけな しま……ｐ
	// そこでは なにが おこるのかｎ
	// だれも わからねえ……ｌ
	// ううむ ふなのりの ちが さわぐぜ!ｐ
	// さあ のりな!

SouthernIsland_Exterior_Text_1C5215:: @ 81C5215
	.string "아무것도 없는 시시한 섬이구만...\n"
	.string "해안시티로 돌아갈래?$"
	// なにもねえ ちんけな しま だな……ｎ
	// ミナモへ かえるか?

SouthernIsland_Exterior_Text_1C5281:: @ 81C5281
	.string "좋아! 그럼 돌아가자고!$"
	// よし! かえると するか!

SouthernIsland_Exterior_Text_1C52A6:: @ 81C52A6
	.string "그러냐\n"
	.string "뭐 마음대로 해$"
	// そうかいｎ
	// まあ すきにするが いいさ

SouthernIsland_Interior_Text_1C52C5:: @ 81C52C5
	.string "모든 꿈은 또 하나의 현실\n"
	.string "그걸 잊지 마...$"
	// すべての ゆめは もうひとつの げんじつｎ
	// それを わすれるべからず……

SouthernIsland_Exterior_Text_1C52FB:: @ 81C52FB
	.string "기억이 흐려지는 자는\n"
	.string "마음에 새기는 것을 희망한다...$"
	// きおく かすみし ものはｎ
	// こころに きざみつける ことを のぞむ……
