gTextGiddy_Introduction:: @ 81B092A
	.string "난 메르헨아저씨\n"
	.string "엄청 재밌는 이야기를 하곤 해\p"
	.string "내 얘기 들어볼래?$"
	// わし メルヘンおやじｎ
	// とても いい はなし するよｐ
	// わしの ハナシ ききたい?

gTextGiddy_YouveDeflatedMe:: @ 81B097C
	.string "그렇구나...\n"
	.string "아저씨 아쉽다...$"
	// そう…ｎ
	// わし ざんねん…

gTextGiddy_AlsoIWasThinking:: @ 81B0998
	.string "그리고 생각해 봤는데...$"
	// あと おもったんだけどさ…

gTextGiddy_ByeBye:: @ 81B09B0
	.string "이 정도려나...\p"
	.string "들어줘서 고마워!\n"
	.string "바이바이!$"
	// そのぐらい かな®®®ｐ
	// また はなし しようね!ｎ
	// ばいばい!
