gTextHipster_TheyCallMeTheHipster:: @ 81B0C5B
	.string "난 지금유행아저씨\n"
	.string "요즘 유행하는 유행어를 알려줄게$"
	@ わし ナウイおやじｎ
	@ いまどきの ナウイことば おしえるよ

gTextHipster_TaughtYouAlready:: @ 81B0CA7
	.string "하지만 네게는 지난번에 알려줬었지\p"
	.string "이번에는 다른 사람에게도 알려주고 싶어$"
	@ でも きみには このまえ おしえたよねｐ
	@ こんどは ほかの ひとに おしえたいなぁ

gTextHipster_YouAlreadyKnowALot:: @ 81B0D11
	.string "근데 너 유행어 많이 알고 있잖아\n"
	.string "알려줄 건 이제 전혀 없어$"
	@ でも きみ ことば たくさん しってるねｎ
	@ おしえること ぜんぜん ないよ

gTextHipster_HaveYouHeardAbout:: @ 81B0D75
	.string "너 “{STR_VAR_1}”라는\n"
	.string "말 알고 있어?\p"
	.string "의미? 그건 말이지...\n"
	.string "아빠나 엄마한테 한번 물어봐$"
	@ きみ §いってｎ
	@ ことば しってる?ｐ
	@ いみ? それはね……ｎ
	@ おとうさんか おかあさんに きいてみて
