LilycoveCity_DepartmentStore_1F_Text_1C4B5E:: @ 81C4B5E
	.string "This is the POKéMON LOTTERY CORNER.\p"
	.string "All shoppers visiting our DEPARTMENT\n"
	.string "STORE get to draw a POKéMON LOTO\l"
	.string "TICKET.\p"
	.string "If the LOTO TICKET's number matches\n"
	.string "the ID number of any of your POKéMON,\l"
	.string "you will receive a fabulous gift.\p"
	.string "Would you like to draw a POKéMON\n"
	.string "LOTO TICKET?$"
	// こちらは ポケモンくじｎ
	// ちゅうせん コ-ナ-ですｐ
	// とうデパ-トに おこし いただいた かたにｎ
	// もれなく ポケモンくじをｌ
	// ひいて いただいて います!ｐ
	// ひいた くじの ナンバ-とｎ
	// おきゃくさまの ポケモンの IDがｌ
	// あっていましたら すてきな しょうひんをｌ
	// プレゼント いたします!ｐ
	// ポケモンくじを ひかれますか?

LilycoveCity_DepartmentStore_1F_Text_1C4C6A:: @ 81C4C6A
	.string "Please come back tomorrow.$"
	// また あした いこうｎ
	// おこし ください

LilycoveCity_DepartmentStore_1F_Text_1C4C85:: @ 81C4C85
	.string "Please do visit us again.$"
	// それでは また おこし ください

UnknownString_81C4C9F: @ 81C4C9F
	.string "Please pick a LOTO TICKET.\n"
	.string "... ... ...$"
	// では くじを ひいて くださいｎ………

LilycoveCity_DepartmentStore_1F_Text_1C4CC6:: @ 81C4CC6
	.string "Please pick a LOTO TICKET.\n"
	.string "...{PAUSE}{0x39} ...{PAUSE}{0x39} ...{PAUSE}{0x39}$"
	// では くじを ひいて くださいｎ
	// …©くぐ…©くぐ…©くぐ

LilycoveCity_DepartmentStore_1F_Text_1C4CF6:: @ 81C4CF6
	.string "The LOTO TICKET number is {STR_VAR_1}.\p"
	.string "I need to run a check on this number\n"
	.string "to see if it matches any of your\l"
	.string "POKéMON's ID numbers. Please wait.$"
	// くじの ナンバ-は §いです!ｐ
	// ナンバ-が あなたの ポケモンの IDとｎ
	// いっちしているか おしらべ いたしますのでｌ
	// しょうしょう おまちください

LilycoveCity_DepartmentStore_1F_Text_1C4D7D:: @ 81C4D7D
	.string "Congratulations!\p"
	.string "The ID number of your team's\n"
	.string "{STR_VAR_1} matches your LOTO TICKET's\l"
	.string "number!$"
	// おめでとう ございます!ｐ
	// あなたが つれているｎ
	// §いちゃんの IDが みごとにｌ
	// くじの ナンバ-と いっち しました!

LilycoveCity_DepartmentStore_1F_Text_1C4DD1:: @ 81C4DD1
	.string "Congratulations!\p"
	.string "The ID number of your PC-boxed\n"
	.string "{STR_VAR_1} matches your LOTO TICKET's\l"
	.string "number!$"
	// おめでとう ございます!ｐ
	// パソコンに あずけているｎ
	// §いちゃんの IDが みごとにｌ
	// くじの ナンバ-と いっち しました!

LilycoveCity_DepartmentStore_1F_Text_1C4E27:: @ 81C4E27
	.string "I'm sorry.\n"
	.string "None of the numbers matched.$"
	// ざんねんでしたｎ
	// すべて はずれの ようです

LilycoveCity_DepartmentStore_1F_Text_1C4E4F:: @ 81C4E4F
	.string "Two digits matched, so you win the\n"
	.string "third prize!\l"
	.string "You've won the {STR_VAR_1}!$"
	// 2ケタ あって いましたのでｎ
	// 3とう です!ｌ
	// §いを さしあげます!!

LilycoveCity_DepartmentStore_1F_Text_1C4E92:: @ 81C4E92
	.string "Three digits matched, so you win the\n"
	.string "second prize!\l"
	.string "You've won the {STR_VAR_1}!$"
	// 3ケタ あって いましたのでｎ
	// 2とう です!ｌ
	// §いを さしあげます!!

LilycoveCity_DepartmentStore_1F_Text_1C4ED8:: @ 81C4ED8
	.string "Four digits matched, so you win the\n"
	.string "first prize!\l"
	.string "You've won the {STR_VAR_1}!$"
	// 4ケタ あって いましたのでｎ
	// 1とう です!ｌ
	// §いを さしあげます!!

LilycoveCity_DepartmentStore_1F_Text_1C4F1C:: @ 81C4F1C
	.string "Oh, my goodness, all five digits matched!\p"
	.string "You've won the jackpot prize!\n"
	.string "You've won the {STR_VAR_1}!$"
	// なんと 5ケタ すべてｎ
	// あって いました!!ｐ
	// とくとうです!!ｎ
	// §いを さしあげます!!

LilycoveCity_DepartmentStore_1F_Text_1C4F77:: @ 81C4F77
	.string "Oh?\n"
	.string "You seem to have no room for this.\p"
	.string "Please make room in your BAG and\n"
	.string "let me know.$"
	// ………あら?ｎ
	// どうぐが いっぱいの ようですねｐ
	// どうぐを せいりしてから もういちどｎ
	// おこし ください

LilycoveCity_DepartmentStore_1F_Text_1C4FCC:: @ 81C4FCC
	.string "{PLAYER}?\n"
	.string "Yes, I've been expecting you.\p"
	.string "This is the prize we've been holding\n"
	.string "for you.$"
	// §あさん ですねｎ
	// おまちして おりました!ｐ
	// では しょうひんをｎ
	// おわたし いたします

LilycoveCity_DepartmentStore_1F_Text_1C501C:: @ 81C501C
	.string "Please do visit again.$"
	// それでは また おこし ください
