CaveOfOrigin_B4F_Text_1B4FE4:: @ 81B4FE4
	.string "{PLAYER}의 주홍구슬이\n"
	.string "갑자기 빛나기 시작했다!$"
	// §あの べにいろのたまがｎ
	// とつぜん かがやき はじめた!

CaveOfOrigin_B4F_Text_1B5009:: @ 81B5009
	.string "그란돈은 다시\n"
	.string "잠에 든 모양이다...$"
	// グラ-ドンは ふたたびｎ
	// ねむりに ついた ようだ……

UnknownString_81B503D: @ 81B503D
	.string "마적: 받아라...$"
	// マツブサ『これを……

UnknownString_81B504C: @ 81B504C
	.string "마적: ...... ...... ......\n"
	.string "{CLEAR_TO 0x16}...... ...... ......\p"
	.string "작별이다\n"
	.string "이제 만날 일은 없겠지...$"
	// マツブサ『…… …… ……ｎ
	//  …… …… ……ｐ
	// サヨナラだｎ
	// もう あうことは ないだろう……
