MtChimney_Text_1B37BB:: @ 81B37BB
	.string "The power contained in the METEORITE...\p"
	.string "By amplifying its power with this\n"
	.string "machine, MT. CHIMNEY's volcanic activity\l"
	.string "will instantly intensify...\p"
	.string "Fufufu... The volcano will erupt, spewing\n"
	.string "lava that will cool and harden.\l"
	.string "It will expand the landmass...$"
	// いんせきに ひめられた ちからｐ
	// この そうちで ぞうふく すればｎ
	// たちまちの うちに えんとつやまのｌ
	// かざん かつどうは かっぱつになる……ｐ
	// フフフ…… かざんは ふんかしてｎ
	// やがて ようがんが ひえて かたまりｌ
	// だいちが ふえるだろう……

MtChimney_Text_1B38B3:: @ 81B38B3
	.string "MAXIE: You again...\p"
	.string "Now listen.\n"
	.string "We humans have grown on dry land.\p"
	.string "The land is everything!\n"
	.string "Its importance is paramount!\p"
	.string "That is why we of TEAM MAGMA are\n"
	.string "committed to expanding the landmass.\p"
	.string "It will create space for new species\n"
	.string "of POKéMON to evolve.\p"
	.string "It will give us humans more space to\n"
	.string "advance.\p"
	.string "That is TEAM MAGMA's vision!\p"
	.string "I can't allow an ignorant child like\n"
	.string "you to get in our way.\p"
	.string "I, MAXIE, will show you the\n"
	.string "consequences of meddling!$"
	// マツブサ『また きみか……ｐ
	// …… いいか われわれｎ
	// にんげんは だいちで しんか してきた!ｐ
	// そう だいちこそが すべて!ｐ
	// だから われわれ マグマだんはｎ
	// だいちを ふやすことでｌ
	// あらたな ポケモンを しんか させる!ｐ
	// にんげんが はってん するためのｎ
	// ばしょも ふやす!ｐ
	// これこそが マグマだんの りそう!ｎ
	// なにも しらない きみのような こどもにｌ
	// じゃま させる わけには いかないｐ
	// じゃまを するなら どうなるかｎ
	// この マツブサが わからせて あげよう!

MtChimney_Text_1B3A68:: @ 81B3A68
	.string "What?!\p"
	.string "I, MAXIE, was caught off guard?!$"
	// なに!?ｐ
	// この マツブサとも あろう ものがｎ
	// ゆだん したか!?

MtChimney_Text_1B3A90:: @ 81B3A90
	.string "MAXIE: Ah, whatever.\n"
	.string "I will give up our plans for MT. CHIMNEY\l"
	.string "for the time being...\p"
	.string "But no one can ever stop us!\n"
	.string "TEAM MAGMA will prevail!\p"
	.string "Don't you ever forget that!$"
	// マツブサ『まあ いいｎ
	// この えんとつやまは ひとまずｌ
	// あきらめよう……ｐ
	// だが われわれ マグマだんの かつどうをｎ
	// とめることなど だれにも できない!ｐ
	// それだけは わすれないで もらおう!

MtChimney_Text_1B3B36:: @ 81B3B36
	.string "Hehehe!\p"
	.string "So you've come all the way here!\p"
	.string "But you're too late!\n"
	.string "I've already delivered the METEORITE\l"
	.string "from METEOR FALLS to the BOSS!$"
	// ウヒョヒョ!ｐ
	// おまえ ここまで きたのか!ｐ
	// だけど おそかったぜｎ
	// りゅうせいのたきで みつけたｌ
	// いんせきは リ-ダ-に わたしたからな!

MtChimney_Text_1B3BB8:: @ 81B3BB8
	.string "Hehehe...\n"
	.string "So I lost...\p"
	.string "I'm sure glad I never took you on back\n"
	.string "at METEOR FALLS.$"
	// ウヒョヒョ……ｎ
	// まけて しまったかｐ
	// あのとき りゅうせいのたきでｎ
	// たたかわなくて よかったぜ

MtChimney_Text_1B3C07:: @ 81B3C07
	.string "Hehehe!\p"
	.string "You might have beaten me, but you don't\n"
	.string "stand a chance against the BOSS!\p"
	.string "If you get lost now, you won't have to\n"
	.string "face a sound whipping!$"
	// ウヒョヒョ……!ｐ
	// おれに かててもｎ
	// リ-ダ-には かてないぜ!ｐ
	// さっさと かえったほうがｎ
	// いたい おもい しなくて すむぜ

MtChimney_Text_1B3C96:: @ 81B3C96
	.string "We of TEAM MAGMA are working hard for\n"
	.string "everyone's sake.\p"
	.string "Like, if there's more land, there'd be\n"
	.string "more places to live.\l"
	.string "Everyone'd be happy!$"
	// おれら マグマだんはｎ
	// みんなの ために がんばってるんだ!ｐ
	// だって だいちが ふえればｎ
	// すむところが ふえるからｌ
	// みんな うれしいだろ!

MtChimney_Text_1B3D1E:: @ 81B3D1E
	.string "Hunh?\n"
	.string "What do you mean I lost?$"
	// あれ-?ｎ
	// おれ まけたの-!?

MtChimney_Text_1B3D3D:: @ 81B3D3D
	.string "Our BOSS says, “It will make everyone\n"
	.string "happy.”\p"
	.string "But why does everyone keep getting\n"
	.string "in our way?$"
	// おれらの リ-ダ-はｎ
	// 「みんなが よろこぶ ことだ」ってｌ
	// いってるんだ!ｐ
	// なのに なんで みんな ジャマするんだ?

MtChimney_Text_1B3D9A:: @ 81B3D9A
	.string "That annoying TEAM AQUA...\n"
	.string "They always mess with our plans!$"
	// アクアだんの やつらめ……ｎ
	// いちいち おれたちの じゃまを しやがって!

MtChimney_Text_1B3DD6: @ 81B3DD6
	.string "METEORITES pack amazing power!$"
	// いんせきには すごい パワ-が あるのだ!

MtChimney_Text_1B3DF5:: @ 81B3DF5
	.string "Go! Stomp TEAM AQUA!\n"
	.string "And expand the land!$"
	// いけ-! アクアだんを ぶっつぶせ!ｎ
	// そして だいちを ふやすのだ!

MtChimney_Text_1B3E1F:: @ 81B3E1F
	.string "Stay out of our way, okay?\p"
	.string "We're trying to enlarge the landmass\n"
	.string "for the good of everybody!$"
	// いいか おれたちの じゃまを するな!ｐ
	// おれたちは みんなの ためにｎ
	// だいちを ふやそうと してるんだからな!

MtChimney_Text_1B3E7A:: @ 81B3E7A
	.string "Yeah!\n"
	.string "Douse them in fire!$"
	// よ-し!ｎ
	// ほのおを ぶっかけてやれ-!!

UnknownString_81B3E94: @ 81B3E94
	.string "We're going to keep making more land!$"
	// もっと もっと だいちを ふやすぜ!!

MtChimney_Text_1B3EBA:: @ 81B3EBA
	.string "Bufoh!$"
	// ぶふぉ-!!

MtChimney_Text_1B3EC1:: @ 81B3EC1
	.string "ARCHIE: Oh, {PLAYER}{KUN}!\p"
	.string "Please, you must stop TEAM MAGMA\n"
	.string "for me!\p"
	.string "They're trying to make this volcano\n"
	.string "erupt by using the stolen METEORITE's\l"
	.string "power!\p"
	.string "It's all a part of their plans to\n"
	.string "expand the world's landmass!$"
	// アオギリ『おお! §あ§お!ｎ
	// いいところに きてくれたな!ｐ
	// わたしに かわってｎ
	// マグマだんを とめてくれ!ｐ
	// あいつら うばった いんせきの パワ-でｎ
	// この かざんを ふんか させてｌ
	// りくを ふやそうと しているんだ!

MtChimney_Text_1B3F8C:: @ 81B3F8C
	.string "ARCHIE: {PLAYER}{KUN}!\p"
	.string "Please, you've got to stop TEAM MAGMA\n"
	.string "for me!\p"
	.string "Dealing with these three thugs is\n"
	.string "a lot, even for me!$"
	// アオギリ『§あ§お!ｐ
	// わたしに かわってｎ
	// マグマだんを とめてくれ!ｐ
	// こいつら したっぱ 3にんの あいてはｎ
	// さすがの わたしでも たいへんだ!

MtChimney_Text_1B3FFE:: @ 81B3FFE
	.string "ARCHIE: {PLAYER}{KUN}! Thank you!\p"
	.string "With your help, we thwarted TEAM\n"
	.string "MAGMA's destructive plan!\p"
	.string "But... This victory doesn't mean the\n"
	.string "end of their evil plans.\p"
	.string "We will remain vigilant and keep up\n"
	.string "our pursuit of TEAM MAGMA.\p"
	.string "{PLAYER}{KUN}, we shall meet again!$"
	// アオギリ『§あ§お! ありがとうｎ
	// きみの おかけで マグマだんのｌ
	// はかいかつどうを ふせぐことが できたｐ
	// だが…… まだ あいつらの やぼうはｎ
	// これで おわった わけじゃない!ｐ
	// われわれは ひきつづき マグマだんをｎ
	// おいかけると しよう!ｐ
	// §あ§おｎ
	// では また あおう!

MtChimney_Text_1B40EA:: @ 81B40EA
	.string "Darn... TEAM MAGMA outnumbers us!\n"
	.string "We can't keep up with them!$"
	// くそう マグマだんが おおすぎる……ｎ
	// このままでは まずいぞ!

MtChimney_Text_1B4128:: @ 81B4128
	.string "If they expand the land, there'll be\n"
	.string "less habitats for WATER POKéMON!$"
	// だいちを ふやしたらｎ
	// みずポケモンが すむ ばしょがｌ
	// へってしまう じゃね-か!

MtChimney_Text_1B416E:: @ 81B416E
	.string "TEAM MAGMA wants to expand the\n"
	.string "landmass... How's that for insane?$"
	// マグマだんめｎ
	// りくを ふやそう なんて ばかげてるぜ!

MtChimney_Text_1B41B0:: @ 81B41B0
	.string "Bushaa!$"
	// ぷしゃ-!!
