MtPyre_Summit_Text_1B5CFD:: @ 81B5CFD
	.string "I'll show you exactly how scary\n"
	.string "TEAM MAGMA can be!$"
	// マグマだんの ほんとうの おそろしさｎ
	// おまえに おしえてやるぜ!

MtPyre_Summit_Text_1B5D30:: @ 81B5D30
	.string "So you think you can stand up alone\n"
	.string "to TEAM MAGMA's might...$"
	// なるほど ひとりで マグマだんにｎ
	// さからおうって わけか

MtPyre_Summit_Text_1B5D6D:: @ 81B5D6D
	.string "Yeah, so you are strong...\n"
	.string "But there're a lot of us!$"
	// たしかに おまえは つよいな……ｎ
	// だけど おれたちは たくさん いるんだぞ!

MtPyre_Summit_Text_1B5DA2:: @ 81B5DA2
	.string "What's up with you?\n"
	.string "What does a single kid expect to do?$"
	// なんだ おまえ?ｎ
	// こどもが ひとりで なにしよう ってんだ?

MtPyre_Summit_Text_1B5DDB:: @ 81B5DDB
	.string "Dang...\n"
	.string "Too strong...$"
	// くそう つよいな……

MtPyre_Summit_Text_1B5DF1:: @ 81B5DF1
	.string "You don't know anything.\n"
	.string "Quit messing around with us!$"
	// なにも しらないくせにｎ
	// おれたちの じゃまを するんじゃないぜ!

MtPyre_Summit_Text_1B5E27:: @ 81B5E27
	.string "Hey, I remember you from MT. CHIMNEY!\n"
	.string "It's payback time!$"
	// おまえ…… えんとつやまで あったな!ｎ
	// その しかえし させてもらうぜ!

MtPyre_Summit_Text_1B5E60:: @ 81B5E60
	.string "Urgggh...\n"
	.string "Beaten by some kid again!$"
	// ぐぐぐ……ｎ
	// ま-た こどもに まけちまったよ

MtPyre_Summit_Text_1B5E84:: @ 81B5E84
	.string "Heh, it doesn't matter!\n"
	.string "We bought ourselves some time!\p"
	.string "The BOSS should have snatched what\n"
	.string "he was after!$"
	// まあいいさ じかんは かせげた!ｐ
	// リ-ダ-の もくてきの ものｎ
	// うばえた はずだぜ!

MtPyre_Summit_Text_1B5EEC:: @ 81B5EEC
	.string "MAXIE: Not you again...\p"
	.string "You've impeded our plans repeatedly,\n"
	.string "but this time you're too late.\p"
	.string "The BLUE ORB that rested atop\n"
	.string "MT. PYRE...\l"
	.string "I, MAXIE, claim it as mine!\p"
	.string "Fufufu... Finally, I can realize my\n"
	.string "grand design...\p"
	.string "Come on, crew!\n"
	.string "It's SLATEPORT next!$"
	// マツブサ『また きみか……ｐ
	// きみには これまで なんどもｎ
	// じゃまを されたがｌ
	// こんど ばかりは おそかった ようだな!ｐ
	// この おくりびやまに まつられていたｎ
	// あいいろのたま……ｌ
	// たしかに この マツブサが いただいた!ｐ
	// フフフ…… これで わたしの もくてきもｎ
	// たっせい できる……ｐ
	// つぎは カイナ だ!ｎいそぐぞ!!

MtPyre_Summit_Text_1B5FE6:: @ 81B5FE6
	.string "Oh, no...\n"
	.string "This cannot happen...\p"
	.string "How could they take the BLUE ORB?\p"
	.string "The BLUE ORB and RED ORB must never\n"
	.string "be separated. They belong together.\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "Hmm...\p"
	.string "Fine!\n"
	.string "You take the remaining RED ORB.\p"
	.string "Please take after that foul man and\n"
	.string "get the other ORB back!$"
	// ああ なんという ことじゃ……!ｐ
	// あいいろのたま がｎ
	// うばわれて しまうとは……ｐ
	// あいいろのたま と べにいろのたま がｎ
	// はなればなれに なって しまうなどｌ
	// けっして あっては ならないこと……ｐ
	// ……… ……… ………ｎ
	// ううむ……ｐ
	// よし! おまえさんに のこされたｎ
	// べにいろのたまを あずけようｐ
	// さっきの おとこを おいかけてｎ
	// たまを とりかえして おくれ……!

MtPyre_Summit_Text_1B60F9:: @ 81B60F9
	.string "The RED ORB you have been entrusted\n"
	.string "with and the stolen BLUE ORB...\p"
	.string "They must never be apart...\n"
	.string "Something terrible will happen...$"
	// おまえさんに わたした べにいろのたまとｎ
	// うばわれた あいいろのたま……ｐ
	// はなればなれ ではｎ
	// きっと よくないことが おこる……

MtPyre_Summit_Text_1B617B:: @ 81B617B
	.string "So...\n"
	.string "GROUDON has awoken...\p"
	.string "The wondrous ORB that is said to have\n"
	.string "becalmed the raging GROUDON...\l"
	.string "It is the RED ORB you bear.\p"
	.string "That RED ORB was found buried inside\n"
	.string "the CAVE OF ORIGIN in SOOTOPOLIS...\p"
	.string "There is perhaps a link between\n"
	.string "GROUDON and the CAVE OF ORIGIN...$"
	// そうか……ｎ
	// グラ-ドンが めざめたのか……ｐ
	// かつて グラ-ドンの いかりをｎ
	// しずめた ふしぎな たま というのがｌ
	// その べにいろのたま なんじゃ……ｐ
	// そして その たまが ほりだされたのはｎ
	// ルネにある めざめのほこら……ｐ
	// グラ-ドンと めざめのほこら にはｎ
	// なにかしら かんけいが あるのかもな……

MtPyre_Summit_Text_1B6283:: @ 81B6283
	.string "That man, he returned the BLUE ORB.\p"
	.string "Are you going to return the RED ORB\n"
	.string "to its rightful place, too?$"
	// さっきの おとこｎ
	// あいいろのたまを かえしに きよったｐ
	// おまえさんもｎ
	// べにいろのたまを かえすのかい?

MtPyre_Summit_Text_1B62E7:: @ 81B62E7
	.string "What's that?!\p"
	.string "If the balance is not restored, there\n"
	.string "is no telling what could happen.\p"
	.string "You will return the RED ORB to its\n"
	.string "rightful place, yes?$"
	// なんと!?ｎ
	// このまま バランスが くずれた ままではｌ
	// なにが おきるか わからんぞよ?ｐ
	// おまえさんｎ
	// べにいろのたまを もどすじゃろう?

UnknownString_81B6374: @ 81B6374
	.string "{PLAYER} handed the RED ORB to the\n"
	.string "old woman.$"
	// §あは ろうばにｎ
	// べにいろのたまを わたした!

MtPyre_Summit_Text_1B639C:: @ 81B639C
	.string "Yes...\n"
	.string "The two ORBS should remain here.\p"
	.string "It is how it should be for the good\n"
	.string "of all HOENN...$"
	// うむ……ｎ
	// 2つの たまは ここに おいておこう……ｐ
	// それが このホウエンの ためにもｎ
	// いちばん よい すがた だろうて……

MtPyre_Summit_Text_1B63F8:: @ 81B63F8
	.string "The spirit of the land...\p"
	.string "That is what GROUDON is said to be in\n"
	.string "POKéMON form...\p"
	.string "In the same manner that we and POKéMON\n"
	.string "have life, this very land is alive...\p"
	.string "GROUDON has taught us that...$"
	// だいちの けしん……ｎ
	// それが グラ-ドンの しょうたい ともｌ
	// いわれておる……ｐ
	// わしら にんげんや ポケモンにｎ
	// いのちが あるようにｌ
	// この だいちだって いきている……ｐ
	// グラ-ドンは わしたちに そのことをｎ
	// おしえて くれたのじゃろう……

MtPyre_Summit_Text_1B64B3:: @ 81B64B3
	.string "MT. PYRE is where we calm the spirits\n"
	.string "of POKéMON that have passed on...\p"
	.string "This is a high place where one can\n"
	.string "see all of HOENN...\p"
	.string "The disembodied spirits of POKéMON\n"
	.string "must find solace here...\p"
	.string "Is it coincidence that you are here...\p"
	.string "Will you hear out my tale? A tale long\n"
	.string "told in the HOENN region?$"
	// おくりびやまは ポケモンの たましいをｎ
	// なぐさめる ための ところ……ｐ
	// ここは たかい ばしょに あってｎ
	// ホウエンを みわたす ことが できるからｌ
	// ポケモンたちの たましいもｌ
	// やすらぎを おぼえるの じゃろう……ｐ
	// おまえさんが ここに きたのもｎ
	// なにかの えん……ｐ
	// ホウエンちほうに つたわる はなしをｎ
	// きいて いきなされ……

MtPyre_Summit_Text_1B65D6:: @ 81B65D6
	.string "It happened long, long ago...\p"
	.string "The world was wracked by a ferocious\n"
	.string "clash between the POKéMON of the land\l"
	.string "and the POKéMON of the sea...\p"
	.string "The POKéMON of the land raised\n"
	.string "mountains and created continents...\p"
	.string "The POKéMON of the sea raised huge\n"
	.string "waves and carved out oceans...\p"
	.string "Their fierce duel raged without end.\p"
	.string "The world was engulfed in vicious\n"
	.string "storms and massive infernos.\p"
	.string "The RED ORB and the BLUE ORB brought\n"
	.string "an end to the calamity.\p"
	.string "Light poured from the two ORBS and\n"
	.string "becalmed the enraged adversaries.\p"
	.string "The pair, made docile, burrowed deep\n"
	.string "under the ground where eventually\l"
	.string "they disappeared...$"
	// とおい とおい おおむかしの こと……ｐ
	// せかいでは りくと うみの ポケモンがｎ
	// はげしい たたかいを くりひろげていたｐ
	// りくの ポケモンはｎ
	// だいちを もりあげ じめんを ひろげｐ
	// うみの ポケモンはｎ
	// あらなみを おこして うみを ひろげたｐ
	// 2ひきの たたかいは おわることなくｎ
	// この せかいは ふきあれる あらしとｌ
	// もえさかる ほのおで うめつくされたｐ
	// それを しずめたのがｎ
	// べにいろのたま と あいいろのたま……ｐ
	// ふたつの たまから ひろがる ひかりがｎ
	// 2ひきの いかりを しずめたｐ
	// そして おとなしくなった 2ひきはｎ
	// ちちゅう ふかく もぐっていきｌ
	// やがて そのすがたを けしたのじゃ……

MtPyre_Summit_Text_1B6823:: @ 81B6823
	.string "I see...\n"
	.string "Well, that, too, is fine...$"
	// そうかね……ｎ
	// まあ それも よいじゃろう……

MtPyre_Summit_Text_1B6848:: @ 81B6848
	.string "MAXIE: You...\n"
	.string "So you stopped GROUDON...\p"
	.string "I shouldn't be surprised...\p"
	.string "I understand now that humans cannot\n"
	.string "freely control the balance between\l"
	.string "the land and the sea...\p"
	.string "So I have come to return the\n"
	.string "BLUE ORB...\p"
	.string "I doubt that we will cross paths again...\n"
	.string "Farewell...$"
	// マツブサ『きみが……ｎ
	// グラ-ドンを……ｐ
	// さすが だな……ｐ
	// しょせん にんげん にはｎ
	// だいちと うみの バランスをｌ
	// じゆうに あやつる なんて できない……ｐ
	// だから ここにｎ
	// あいいろのたまを かえしに きた……ｐ
	// もう きみと あうことは ないだろう……ｎ
	// さらば だ……
