PetalburgCity_PokemonCenter_1F_Text_1B1C97:: @ 81B1C97
	.string "안녕하세요\n"
	.string "미소가 멋진 트레이너님!\p"
	.string "저는 포켓몬 트레이너들의\n"
	.string "프로필을 모으는 게\l"
	.string "취미인데요...$"
	@ こんにちはｎ
	@ えがおの すてきな トレ-ナ-さん!ｐ
	@ ぼくは ポケモントレ-ナ-さん たちのｎ
	@ プロフィ-ルを あつめるのがｌ
	@ しゅみ なんだけど……

PetalburgCity_PokemonCenter_1F_Text_1B1D10:: @ 81B1D10
	.string "어때요? 당신의 프로필을\n"
	.string "제게 알려 주실 수 있나요?$"
	@ どうかな? きみの プロフィ-ルｎ
	@ ぼくに おしえて もらえないかな?

PetalburgCity_PokemonCenter_1F_Text_1B1D3A:: @ 81B1D3A
	.string "프로필은 좋아하는 말을\n"
	.string "4개 조합해서 만들면 돼요!\p"
	.string "지금부터 제가\n"
	.string "적당한 4개의 말로 만든\l"
	.string "프로필을 보여드릴 테니\p"
	.string "당신은 그 말을\n"
	.string "원하는 대로 바꿔서\l"
	.string "자신만의 프로필을 만들면 됩니다!\p"
	.string "쓸 수 있는 말들은\n"
	.string "굉장히 많이 있어요\l"
	.string "그룹별로 나뉘어 있답니다\l"
	.string "포켓몬 생활 취미...\l"
	.string "같은 식으로 말이죠!\p"
	.string "그러니 우선\n"
	.string "그룹을 선택하고...\l"
	.string "그 뒤에 선택한 그룹 안에 있는\l"
	.string "수많은 말들 중에서\l"
	.string "마음에 드는 것을\l"
	.string "고르시면 됩니다!$"
	@ プロフィ-ルは すきな ことばをｎ
	@ 4つ くみあわせて つくるんだよ!ｐ
	@ これから ぼくがｎ
	@ てきとうな 4つの ことばで つくったｌ
	@ プロフィ-ルを みせるからｐ
	@ きみは その ことばをｎ
	@ すきなものに いれかえてｌ
	@ きみだけの プロフィ-ルに してね!ｐ
	@ えらべる ことばはｎ
	@ すごく たくさん あるからｌ
	@ グル-プに わかれて いるんだｌ
	@ ポケモン とか せいかつ とか しゅみ…ｌ
	@ という ぐあいにね!ｐ
	@ だから まずはｎ
	@ グル-プを えらんで……ｌ
	@ そのあとに えらんだ グル-プのｌ
	@ ことばが いくつも でてくるからｌ
	@ そこから すきな ことばをｌ
	@ みつけてね!

UnknownString_81B1F7A: @ 81B1F7A
	.string "$"

PetalburgCity_PokemonCenter_1F_Text_1B1F7B:: @ 81B1F7B
	.string "앗싸! 감사합니다!\n"
	.string "그럼 바로 알려 주세요!$"
	@ やった! ありがとう!ｎ
	@ じゃ さっそく きかせてよ!

PetalburgCity_PokemonCenter_1F_Text_1B1FA3:: @ 81B1FA3
	.string "그럴 수가...\p"
	.string "당신의 프로필은 무척\n"
	.string "멋질 것 같았는데...$"
	@ そんなあ……ｐ
	@ きみの プロフィ-ルは さぞかしｎ
	@ すてきだと おもうんだけど なぁ……

PetalburgCity_PokemonCenter_1F_Text_1B1FF0:: @ 81B1FF0
	.string "어라? 지금은 내키지 않으신가요?\p"
	.string "뭐 언제든 괜찮습니다!$"
	@ あれ? いまは きが のらないんだね?ｐ
	@ だったら いつでも いいよ!

PetalburgCity_PokemonCenter_1F_Text_1B202F:: @ 81B202F
	.string "안녕하세요\n"
	.string "미소가 멋진 트레이너님!$"
	@ こんにちはｎ
	@ えがおの すてきな トレ-ナ-さん!

PetalburgCity_PokemonCenter_1F_Text_1B2063:: @ 81B2063
	.string "당신의 새로운 프로필을\n"
	.string "알려 주실 수 있나요?$"
	@ きみの あたらしい プロフィ-ルをｎ
	@ おしえて くれるのかな?

PetalburgCity_PokemonCenter_1F_Text_1B207F:: @ 81B207F
	.string "앗싸! 감사합니다!\p"
	.string "그럼 전보다 더\n"
	.string "멋진 프로필을 기대할게요!$"
	@ やった! ありがとう!ｐ
	@ じゃあ まえにも ましてｎ
	@ すてきな やつを きたい してるよ!

PetalburgCity_PokemonCenter_1F_Text_1B20CE:: @ 81B20CE
	.string "지금 그대로도 괜찮으신가요?\p"
	.string "그렇겠죠 무척이나 멋진\n"
	.string "프로필이니까요!$"
	@ いまの ままが いいんだね?ｐ
	@ そうだよね とても すてきなｎ
	@ プロフィ-ル だもの!

PetalburgCity_PokemonCenter_1F_Text_1B2137:: @ 81B2137
	.string "후 훌륭합니다!\p"
	.string "정말 당신 그 자체의 느낌이 담긴\n"
	.string "멋진 프로필이에요!\p"
	.string "이걸 들은 사람은\n"
	.string "누구든지 당신에게 푹 빠져버리겠죠!\p"
	.string "알려 주셔서 감사합니다!$"
	@ すっ すばらしい!ｐ
	@ まさに きみ そのもの って かんじのｎ
	@ すてきな プロフィ-ル!ｐ
	@ これを きいた ひとはｎ
	@ だれもが きみの とりこに なるだろうね!ｐ
	@ どうも ありがとう!

PetalburgCity_PokemonCenter_1F_Text_1B21CC:: @ 81B21CC
	.string "이럴 수가!\n"
	.string "그 말을 알고 있을 줄이야...\p"
	.string "그렇다는 건 당신도\n"
	.string "이상한 사건 클럽의 동료란 거군요!$"
	@ ややっ!ｎ
	@ その ことばを しっている とは……ｐ
	@ という ことは きみもｎ
	@ ふしぎな できごと クラブの なかま だね!
