Text_ObtainedTheItem: @ 81A0C68
	.string "{STR_VAR_2}{K_EULREUL} 손에 넣었다!$"

Text_TheBagIsFull:: @ 81A0C79
	.string "가방이 가득 찼다...$"

Text_PutItemInPocket: @ 81A0C8C
	.string "{PLAYER}{K_EUNNEUN} {STR_VAR_2}{K_EULREUL}\n"
	.string "{STR_VAR_3} 포켓에 넣었다$"

Text_FoundOneItem: @ 81A0CB1
	.string "{PLAYER}{K_EUNNEUN}\n"
    .string "{STR_VAR_2}{K_EULREUL} 발견했다!$"

Text_TooBadBagIsFull:
	.string "아쉽다!\n"
	.string "가방이 가득 찼다...$"

Text_ObtainedTheDecor: @ 81A0CDE
	.string "{STR_VAR_2}{K_EULREUL} 손에 넣었다!$"

Text_NoRoomLeftForAnother:: @ 81A0CEF
	.string "아쉽다! {STR_VAR_2}{K_EULREUL}\n"
	.string "넣을 공간이 없다...$"

Text_TheDecorWasTransferredToThePC: @ 81A0D1F
	.string "{STR_VAR_2}{K_EUNNEUN}\n"
	.string "PC로 전송되었다!$"
