Text_BootUpPC: @ 81A09EC
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "PC 전원을 켰다!$"

Text_WhichPCShouldBeAccessed:: @ 81A0A01
	.string "어느 PC에 접속해서\n"
	.string "통신할까요?$"

Text_AccessedSomeonesPC: @ 81A0A1E
	.string "누군가의\n"
	.string "PC에 접속했다!$"

Text_StorageSystemOpened: @ 81A0A35
	.string "포켓몬 보관 시스템을\n"
	.string "불러왔습니다!$"

Text_AccessedPlayersPC: @ 81A0A54
	.string "{PLAYER}의\n"
	.string "PC에 접속했다!$"

Text_AccessedLanettesPC: @ 81A0A66
	.string "유미의\n"
	.string "PC에 접속했다!$"
