gText_NurseJoy_Welcome:: @ 81A0A7D
	.string "안녕하세요!\n"
	.string "포켓몬센터입니다\p"
	.string "여기에서는 포켓몬의\n"
	.string "HP를 회복시켜 드립니다\p"
	.string "당신의 포켓몬을\n"
	.string "쉬게 하겠습니까?$"
	// おつかれさまです!ｎ
	// ポケモン センタ- ですｐ
	// ここでは ポケモンのｎ
	// たいりょく かいふくを しますｐ
	// あなたの ポケモンをｎ
	// やすませて あげますか?

gText_NurseJoy_WeHopeToSeeYouAgain:: @ 81A0AFA
	.string "또 이용해 주세요!$"
	// またのｎ
	// ごりようを おまち してます!

gText_NurseJoy_ThankYouForWaiting:: @ 81A0B14
	.string "오래 기다리셨습니다!\p"
	.string "맡겨 두신 포켓몬이\n"
	.string "모두 건강해졌습니다!$"
	// おまちどおさま!ｐ
	// おあずかり した ポケモンはｎ
	// みんな げんきに なりましたよ!

UnknownString_81A0B57: @ 81A0B57
	.string "포켓몬 통신 클럽\p"
	.string "트레이드센터에 잘 오셨습니다!$"
	// ポケモン つうしん クラブｐ
	// トレ-ドセンタ-に ようこそ!

UnknownString_81A0B87: @ 81A0B87
	.string "포켓몬 통신 클럽\p"
	.string "콜로세움에 잘 오셨습니다!$"
	// ポケモン つうしん クラブｐ
	// コロシアムに ようこそ!

UnknownString_81A0BB4: @ 81A0BB4
	.string "포켓몬 통신 클럽\p"
	.string "타입캡슐에 잘 오셨습니다!$"
	// ポケモン つうしん クラブｐ
	// タイムカプセルに ようこそ!
