gBirchDexRatingText_ComeToShowMePokedex:: @ 81C4449
	.string "PROF. BIRCH: Ah, {PLAYER}{KUN}!\p"
	.string "Have you come to show me how your\n"
	.string "POKéDEX is coming along?$"
	// オダマキ『おお §あ§お!ｐ
	// ポケモンずかんの ようすをｎ
	// みせて くれるのかい?

gBirchDexRatingText_Cancel:: @ 81C449B
	.string "Hm? Oh, you haven't caught enough\n"
	.string "POKéMON to make it worthwhile.$"
	// うん? みせるほどｎ
	// ポケモンを つかまえて いないのか

gBirchDexRatingText_SoYouveSeenAndCaught:: @ 81C44DC
	.string "Hmhm...\p"
	.string "So, you've seen {STR_VAR_1} POKéMON,\n"
	.string "and you've caught {STR_VAR_2} POKéMON...$"
	// ふむふむ……ｐ
	// みつけた ポケモン §いｎ
	// つかまえた ポケモン §う か……

gBirchDexRatingText_LessThan10:: @ 81C4520
	.string "You should go into grassy areas more\n"
	.string "and look for POKéMON more carefully.$"
	// もっと くさむらに はいってｎ
	// ポケモンを さがしてみると いいな!

gBirchDexRatingText_LessThan20:: @ 81C456A
	.string "I guess you're getting the hang of it.\n"
	.string "But, it gets harder from here.$"
	// ちょうしが でてきた みたいだねｎ
	// でも これからが たいへん なんだぞ!

gBirchDexRatingText_LessThan30:: @ 81C45B0
	.string "Some POKéMON only appear in certain\n"
	.string "areas. You'll need to be persistent.$"
	// きまった ばしょでしか みつからないｎ
	// ポケモンは しつこく さがすしか ないぞ!

gBirchDexRatingText_LessThan40:: @ 81C45F9
	.string "Well, it could use more quantity, but\n"
	.string "this is looking more like a POKéDEX now.$"
	// ボリュ-ムは まだまだ だけどｎ
	// すこしは ポケモンずかん らしく なったぞ

gBirchDexRatingText_LessThan50:: @ 81C4648
	.string "This is coming along pretty good.\n"
	.string "Keep up the effort.$"
	// なかなか いい かんじ だな!ｎ
	// この ちょうしで がんばって くれよ

gBirchDexRatingText_LessThan60:: @ 81C467E
	.string "Are you using any RODS?\n"
	.string "There are many POKéMON in the sea.$"
	// つりざおは つかって いるかな?ｎ
	// うみにも ポケモンは たくさん いるからな

gBirchDexRatingText_LessThan70:: @ 81C46B9
	.string "Instead of just catching POKéMON,\n"
	.string "how about making them evolve, too?$"
	// ポケモンを つかまえる だけでなくｎ
	// しんか させるのは どうだい?

gBirchDexRatingText_LessThan80:: @ 81C46FE
	.string "This is going to be a fantastic POKéDEX.\n"
	.string "That's the feeling I'm getting.$"
	// すばらしい ポケモンずかんに なりそうだｎ
	// そんな よかんが して たまらないね!

gBirchDexRatingText_LessThan90:: @ 81C4747
	.string "You've collected this many...\n"
	.string "Your talent is remarkable!$"
	// ここまで あつめるとは……ｎ
	// きみの さいのうは たいした ものだよ!

gBirchDexRatingText_LessThan100:: @ 81C4780
	.string "Have you visited the SAFARI ZONE?\p"
	.string "I hear there are some POKéMON that\n"
	.string "can only be caught there.$"
	// サファリゾ-ンには いったかい?ｎ
	// あそこでしか つかまえられないｌ
	// ポケモンも いるって はなし だぞ!

gBirchDexRatingText_LessThan110:: @ 81C47DF
	.string "You've finally reached the 100-kind\n"
	.string "mark. This is an impressive POKéDEX!$"
	// とうとう 100しゅるい こえたのか!ｎ
	// ポケモンずかん として みごとな もんだね!

gBirchDexRatingText_LessThan120:: @ 81C4828
	.string "There might be POKéMON that can be\n"
	.string "found using ROCK SMASH.$"
	// ……そういえば いわくだきを つかうことでｎ
	// みつかる ポケモンも いたっけ

gBirchDexRatingText_LessThan130:: @ 81C4863
	.string "You should get some more POKéMON by\n"
	.string "trading with others.$"
	// ポケモンこうかん すればｎ
	// もっと あつまるかも しれないな

gBirchDexRatingText_LessThan140:: @ 81C489C
	.string "I've heard of POKéMON that evolve when\n"
	.string "they come to fully love their TRAINERS.$"
	// なんでも なついているとｎ
	// しんか する ポケモンも いるそうだよ!

gBirchDexRatingText_LessThan150:: @ 81C48EB
	.string "I had no idea that there were so many\n"
	.string "POKéMON species in the HOENN region.$"
	// ホウエンちほう には こんなにもｎ
	// おおくの ポケモンが いたのか……

gBirchDexRatingText_LessThan160:: @ 81C4936
	.string "On occasion, some POKéMON appear in\n"
	.string "large numbers like wild outbreaks.\l"
	.string "Don't miss opportunities like those.$"
	// ときどき たいりょうはっせい するｎ
	// ポケモンが いるらしいｌ
	// その チャンスを のがさないようにな!

gBirchDexRatingText_LessThan170:: @ 81C49A2
	.string "One can get a very good idea about the\n"
	.string "POKéMON of the HOENN region by looking\l"
	.string "through your POKéDEX.$"
	// きみの ずかんを みればｎ
	// ホウエンちほうの ポケモンのｌ
	// すべてが わかるようだ!

gBirchDexRatingText_LessThan180:: @ 81C4A06
	.string "I'd say you already qualify as a POKéMON\n"
	.string "PROFESSOR, and a good one, too!$"
	// きみは ポケモンはかせ としてもｎ
	// ゆうしゅう なんだな

gBirchDexRatingText_LessThan190:: @ 81C4A4F
	.string "With a POKéDEX this complete, you're\n"
	.string "a real professional at this!$"
	// ここまで ずかんが できたらｎ
	// もはや プロフェッショナル だぞ!

gBirchDexRatingText_LessThan200:: @ 81C4A91
	.string "You're very close to completing this\n"
	.string "POKéDEX. I can feel it in my bones!$"
	// いよいよ かんせいに ちかづいた!ｎ
	// そんな よかんが してきたよ!

gBirchDexRatingText_DexCompleted:: @ 81C4ADA
	.string "Congratulations!\n"
	.string "Your POKéDEX is complete!$"
	// おめでとう!!ｎ
	// ポケモンずかんの かんせい だよ!!

gBirchDexRatingText_OnANationwideBasis:: @ 81C4B05
	.string "Hmhm...\n"
	.string "On a nationwide basis...\p"
	.string "You've seen {STR_VAR_1} POKéMON,\n"
	.string "and you've caught {STR_VAR_2} POKéMON...$"
	// ふむふむ ぜんこくてき には……ｐ
	// みつけた ポケモン §いｎ
	// つかまえた ポケモン §う だね
