gUnknown_081C40DF:: @ 81C40DF
UnknownString_81C40DF: @ 81C40DF
	.string "여기는 레이트 {STR_VAR_1}의 룰렛입니다\n"
	.string "룰렛을 즐기겠습니까?$"
	// ここは レ-ト§いの ル-レットだい ですｎ
	// ル-レットで あそびますか?

gUnknown_081C411C:: @ 81C411C
UnknownString_81C411C: @ 81C411C
	.string "동전이 부족합니다$"
	// コインが たりません

gUnknown_081C4139:: @ 81C4139
UnknownString_81C4139: @ 81C4139
	.string "오늘 이 테이블은\n"
	.string "레이트 업!$"
	// ほんじつ このだいではｎ
	// レ-ト アップ じっしちゅう!

gUnknown_081C4157:: @ 81C4157
	.string "베팅할 곳을 십자 버튼으로 선택하고\n"
	.string "A 버튼으로 결정합니다$"
	// ベットする わくを じゅうじボタンで えらんでｎ
	// Aボタンで けってい します

gUnknown_081C4199:: @ 81C4199
UnknownString_81C4199: @ 81C4199
	.string "당첨-!$"
	// あたり-!

gUnknown_081C41A5:: @ 81C41A5
UnknownString_81C41A5: @ 81C41A5
	.string "대당첨!!$"
	// おおあたり!!

gUnknown_081C41AE:: @ 81C41AE
UnknownString_81C41AE: @ 81C41AE
	.string "꽝-$"
	// はずれ- 

gUnknown_081C41BD:: @ 81C41BD
UnknownString_81C41BD: @ 81C41BD
	.string "축하합니다!\n"
	.string "동전 {STR_VAR_1}개를 얻습니다!$"
	// おめでとう ございます!ｎ
	// コイン §いまい はいります!

gUnknown_081C41D2:: @ 81C41D2
UnknownString_81C41D2: @ 81C41D2
	.string "동전이 다 떨어졌습니다$"
	// コインが なくなりました

gUnknown_081C41E3:: @ 81C41E3
UnknownString_81C41E3: @ 81C41E3
	.string "계속해서 즐기겠습니까?$"
	// つづけて あそびますか?

gUnknown_081C41F1:: @ 81C41F1
UnknownString_81C41F1: @ 81C41F1
	.string "테이블 위의 구슬을\n"
	.string "리셋합니다$"
	// だいの うえの たまをｎ
	// クリア します

UnknownString_81C4215: @ 81C4215
	.string "동전케이스를 가지고 있지 않습니다!$"
	// コインケ-スを もっていません!

gUnknown_081C4231:: @ 81C4231
UnknownString_81C4231: @ 81C4231
	.string "동전이 가득 찼습니다!\n"
	.string "경품과 교환해 주십시오$"
	// コインが いっぱいです!ｎ
	// けいひんと こうかん して ください
