Text_SampleMessage1:: @ 81A089A
	.string "샘플 메시지 1입니다\p"
	.string "포켓몬 AGB의 세계에\n"
	.string "어서 오세요!\l"
	.string "그럼 즐겁게 플레이해 주십시오$"
	@ サンプル メッセ-ジ1 ですｐ
	@ ポケモンAGBの せかいへｎ
	@ ようこそ!ｌ
	@ それでは たのしんでね

Text_SampleMessage2:: @ 81A08F1
	.string "샘플 메시지 2입니다\p"
	.string "포켓몬 AGB의 세계에\n"
	.string "어서 오세요!\l"
	.string "그럼 즐겁게 플레이해 주십시오$"
	@ サンプル メッセ-ジ2 ですｐ
	@ ポケモンAGBの せかいへｎ
	@ ようこそ!ｌ
	@ それでは たのしんでね

Text_SampleMessage3:: @ 81A0948
	.string "샘플 메시지 3입니다\p"
	.string "포켓몬 AGB의 세계에\n"
	.string "어서 오세요!\l"
	.string "그럼 즐겁게 플레이해 주십시오$"
	@ サンプル メッセ-ジ3 ですｐ
	@ ポケモンAGBの せかいへｎ
	@ ようこそ!ｌ
	@ それでは たのしんでね
