UnknownString_81A1948: @ 81A1948
	.string "If some vines drop down, this tree can\n"
	.string "be climbed.$"
	// ツルを おとせば うえに のぼれそう

UnknownString_81A197B: @ 81A197B
	.string "If some vines drop down, this tree can\n"
	.string "be climbed.\p"
	.string "Use the SECRET POWER?$"
	// ツルを おとせば うえに のぼれそうｐ
	// ひみつのちからを つかいますか?

UnknownString_81A19C4: @ 81A19C4
	.string "A thick vine dropped down!$"
	// ふといツルが おちてきた!

UnknownString_81A19DF: @ 81A19DF
	.string "Want to make your SECRET BASE here?$"
	// ここに ひみつきちを つくりますか?

UnknownString_81A1A03: @ 81A1A03
	.string "If this clump of grass can be moved,\n"
	.string "it might be possible to go inside.$"
	// くさのかたまりを どければｎ
	// なかへ はいれそう

UnknownString_81A1A4B: @ 81A1A4B
	.string "If this clump of grass can be moved,\n"
	.string "it might be possible to go inside.\p"
	.string "Use the SECRET POWER?$"
	// くさのかたまりを どければｎ
	// なかへ はいれそうｐ
	// ひみつのちからを つかいますか?

UnknownString_81A1AA9: @ 81A1AA9
	.string "Discovered a small entrance!$"
	// ちいさな いりぐちを はっけん!

UnknownString_81A1AC6: @ 81A1AC6
	.string "Want to make your SECRET BASE here?$"
	// ここに ひみつきちを つくりますか?

SecretBase_RedCave1_Text_1A1AEA:: @ 81A1AEA
	.string "Have you made a SECRET BASE already?\p"
	.string "I went here, there, everywhere before\n"
	.string "choosing this place.\p"
	.string "Since you're already here, how would\n"
	.string "you like to battle?$"
	// きみは もう ひみつきちを つくったかい?ｐ
	// ぼくは あっち こっち まわってｎ
	// やっと この ばしょに きめたんだ!ｐ
	// せっかく きたんだからｎ
	// ポケモン しょうぶ しない?

SecretBase_RedCave1_Text_1A1B83:: @ 81A1B83
	.string "Okay!\n"
	.string "Here we come!$"
	// それじゃ いくよ!

SecretBase_RedCave1_Text_1A1B97:: @ 81A1B97
	.string "Hunh?\n"
	.string "Oh, you can't now...$"
	// えっ いまは むりなんだ…

UnknownString_81A1BB2:: @ 81A1BB2
	.string "Waaargh! You're too strong!\n"
	.string "About me losing... Please keep it secret!$"
	// うわっ きみって つよいな-ｎ
	// ぼくが まけたこと ひみつに してね!

SecretBase_RedCave1_Text_1A1BF8:: @ 81A1BF8
	.string "What do you think of my SECRET BASE?\n"
	.string "Come visit me again tomorrow.$"
	// ぼくの ひみつきち どうかな-ｎ
	// また あしたも あそびに きてね!

SecretBase_RedCave1_Text_1A1C3B:: @ 81A1C3B
	.string "Have you made a SECRET BASE already?\p"
	.string "I went here, there, everywhere before\n"
	.string "choosing this place.\p"
	.string "Feel free to hang out!$"
	// きみは もう ひみつきちを つくったかい?ｐ
	// ぼくは あっち こっち まわってｎ
	// やっと この ばしょに きめたんだ!ｐ
	// ゆっくり して いってね!

SecretBase_RedCave1_Text_1A1CB2:: @ 81A1CB2
	.string "There're a lot of places where you can\n"
	.string "make a SECRET BASE.\p"
	.string "But I like this spot best.\n"
	.string "Don't you think it's nice?\p"
	.string "Oh, would you like to have a battle?$"
	// ひみつきちを つくれる ばしょはｎ
	// ほかにも たくさん あるけどｌ
	// ここが いちばん きにいったの!ｐ
	// ねっ! すてきでしょ!ｐ
	// あっ もし よかったらｎ
	// ポケモン しょうぶ しない?

SecretBase_RedCave1_Text_1A1D48:: @ 81A1D48
	.string "Okay, here goes!$"
	// それじゃ いくわよ!

SecretBase_RedCave1_Text_1A1D59:: @ 81A1D59
	.string "Oh...\n"
	.string "You can't now, okay.$"
	// そう いまは むりなのね…

UnknownString_81A1D74:: @ 81A1D74
	.string "Hmmm... It's our loss...\n"
	.string "But don't tell anyone!\l"
	.string "It's a confidential secret!$"
	// う-ん わたしの まけね…ｎ
	// わたしが まけたのは ないしょの ひみつね!

SecretBase_RedCave1_Text_1A1DC0:: @ 81A1DC0
	.string "If you're in this area again, I hope\n"
	.string "you'll visit me.$"
	// このちかくに くることが あったらｎ
	// また あそびに よってね!

SecretBase_RedCave1_Text_1A1DF6:: @ 81A1DF6
	.string "There're a lot of places where you can\n"
	.string "make a SECRET BASE.\p"
	.string "But I like this spot best.\n"
	.string "Don't you think it's nice?$"
	// ひみつきちを つくれる ばしょはｎ
	// ほかにも たくさん あるけどｌ
	// ここが いちばん きにいったの!ｐ
	// ねっ! すてきでしょ!

SecretBase_RedCave1_Text_1A1E67:: @ 81A1E67
	.string "This is a popular spot.\n"
	.string "It's always taken.\p"
	.string "Oh! Were you thinking about taking this\n"
	.string "spot, too?\p"
	.string "I'll tell you what, you can have this\n"
	.string "spot if you can beat me.$"
	// この ばしょは にんきが あるからｎ
	// いつも うまって いるんだ-ｐ
	// あっ もしかしてｎ
	// きみも ここを つかいたい?ｐ
	// う-ん ぼくに かてたらｎ
	// このばしょ あげても いいよ!

SecretBase_RedCave1_Text_1A1F04:: @ 81A1F04
	.string "Okay!\n"
	.string "I'm going to defend my SECRET BASE!$"
	// よしっ! ぼくの きちを まもるぞ-!

SecretBase_RedCave1_Text_1A1F2E:: @ 81A1F2E
	.string "Hunh? Is that right?\n"
	.string "You're not interested in this spot?$"
	// えっ この ばしょに きょうみが ないの?ｎ
	// そっか-

UnknownString_81A1F67:: @ 81A1F67
	.string "I can't keep going!\n"
	.string "I surrender!$"
	// もう ダメだ!ｎ
	// こうさ-ん!

SecretBase_RedCave1_Text_1A1F88:: @ 81A1F88
	.string "Okay, when I move one day, this place\n"
	.string "will be yours!$"
	// よしっ ぼくが いつか ひっこしたらｎ
	// この ばしょは きみの ものさ!

SecretBase_RedCave1_Text_1A1FBD:: @ 81A1FBD
	.string "This is a popular spot.\n"
	.string "It's always taken.\p"
	.string "I waited a long time for it to open.\n"
	.string "I finally got to use it!$"
	// この ばしょは にんきが あるからｎ
	// いつも うまって いるんだよ-ｐ
	// ぼくは ずっと まっていてｎ
	// やっと つかえる ように なったんだ!

SecretBase_RedCave1_Text_1A2026:: @ 81A2026
	.string "Welcome to my POKéMON LAB.\p"
	.string "I carry out research on battling in\n"
	.string "secrecy.\p"
	.string "Would you like to see how strong I am?$"
	// わたしの ポケモン けんきゅうじょへｎ
	// ようこそ!ｐ
	// ここで ポケモン しょうぶに ついてｎ
	// こっそり べんきょう してるのよｐ
	// どう わたしの じつりょく みてみる?

SecretBase_RedCave1_Text_1A2095:: @ 81A2095
	.string "I'm going to go all out!$"
	// ほんきで いくわよ!

SecretBase_RedCave1_Text_1A20AE:: @ 81A20AE
	.string "Oh.\n"
	.string "Some other time, then!$"
	// それじゃ また こんどね!

UnknownString_81A20C9:: @ 81A20C9
	.string "Hmm... I've still got lots to learn.\n"
	.string "I have to study some more.$"
	// う-ん わたしも まだまだね-ｎ
	// もっと  べんきょう しないと!

SecretBase_RedCave1_Text_1A2109:: @ 81A2109
	.string "Thanks for battling with me.\n"
	.string "Please come back again tomorrow.$"
	// しょうぶ してくれて どうも ありがとう!ｎ
	// また あしたも きてね-

SecretBase_RedCave1_Text_1A2147:: @ 81A2147
	.string "Welcome to my POKéMON LAB.\p"
	.string "I carry out research on battling in\n"
	.string "secrecy.$"
	// わたしの ポケモン けんきゅうじょへｎ
	// ようこそ!ｐ
	// ここで ポケモン しょうぶに ついてｎ
	// こっそり べんきょう してるのよ

SecretBase_RedCave1_Text_1A218F:: @ 81A218F
	.string "A big mansion is nice, but I like this\n"
	.string "sort of place more.\p"
	.string "I like it because all kinds of people\n"
	.string "come visit me.\p"
	.string "So, how would you like a battle?$"
	// おおきな いえも いいけどｎ
	// ぼくは こういう ばしょが すきなんだｐ
	// だって いろいろな ひとがｎ
	// あそびに きてくれる からね-!ｐ
	// どう ポケモン しょうぶでも するかい?

SecretBase_RedCave1_Text_1A2220:: @ 81A2220
	.string "That's the way!$"
	// そう こなくっちゃ!

SecretBase_RedCave1_Text_1A2230:: @ 81A2230
	.string "When you're ready, give me a shout!$"
	// よういが できたらｎ
	// いつでも こえを かけてね!

UnknownString_81A2254:: @ 81A2254
	.string "Aww! Done in!\n"
	.string "But it's still fun to battle!$"
	// やられた-!ｎ
	// だけど ポケモン しょうぶは たのしい-!

SecretBase_RedCave1_Text_1A2280:: @ 81A2280
	.string "Well, anyway, I should go buy some\n"
	.string "decorations and furniture.\p"
	.string "I want my SECRET BASE to be a place\n"
	.string "other people can enjoy.$"
	// さてと グッズでも かいに いこうかなｐ
	// ぼくの ひみつきちをｎ
	// みんなに たのしんで ほしい からね!

SecretBase_RedCave1_Text_1A22FA:: @ 81A22FA
	.string "A big mansion is nice, but I like this\n"
	.string "sort of place more.\p"
	.string "I like it because all kinds of people\n"
	.string "come visit me.$"
	// おおきな いえも いいけどｎ
	// ぼくは こういう ばしょが すきなんだｐ
	// だって いろいろな ひとがｎ
	// あそびに きてくれる からね-!

SecretBase_RedCave1_Text_1A236A:: @ 81A236A
	.string "I simply adore shopping for decorations\n"
	.string "and furniture.\p"
	.string "I also love raising POKéMON just\n"
	.string "as much.\p"
	.string "If you would be so kind, will you battle\n"
	.string "with my POKéMON?$"
	// わたし グッズの おかいものがｎ
	// だいすき です!ｐ
	// それと おなじくらい ポケモンを そだてるのｎ
	// だいすき です!ｐ
	// もし よかったら わたしの ポケモンちゃんとｎ
	// しょうぶして くれますか?

SecretBase_RedCave1_Text_1A2405:: @ 81A2405
	.string "Thank you.\n"
	.string "Shall we begin?$"
	// それでは おねがいします

SecretBase_RedCave1_Text_1A2420:: @ 81A2420
	.string "Oh.\n"
	.string "How disappointing...$"
	// そう それは ざんねん です…

UnknownString_81A2439:: @ 81A2439
	.string "I concede...$"
	// まいりました……

SecretBase_RedCave1_Text_1A2446:: @ 81A2446
	.string "That was all in good fun!\n"
	.string "I should go enjoy shopping now.$"
	// ああ たのしかった!ｎ
	// つぎは おかいものを たのしもう かしら

SecretBase_RedCave1_Text_1A2480:: @ 81A2480
	.string "I simply adore shopping for decorations\n"
	.string "and furniture.\p"
	.string "I also love raising POKéMON just\n"
	.string "as much.$"
	// わたし グッズの おかいものがｎ
	// だいすき ですｐ
	// それと おなじくらい ポケモンを そだてるのｎ
	// だいすき です

SecretBase_RedCave1_Text_1A24E1:: @ 81A24E1
	.string "Some people make their SECRET BASES in\n"
	.string "hard-to-find places.\l"
	.string "Do they want to just lie low?\p"
	.string "But since you found me, how about we\n"
	.string "have a battle?$"
	// みつかり にくい ばしょにｎ
	// ひみつきちを つくる ひとが いるけどｌ
	// こっそりと かくれて いたいのかなぁ……ｐ
	// うん せっかく みつけて くれたんだからｎ
	// ポケモン しょうぶ しようか?

SecretBase_RedCave1_Text_1A256F:: @ 81A256F
	.string "I'm not going down easily!$"
	// かんたんには おわらせ ないよ!

SecretBase_RedCave1_Text_1A258A:: @ 81A258A
	.string "Oh... Are you maybe tired from searching\n"
	.string "for this place?$"
	// もしかして さがすのに つかれちゃった?

UnknownString_81A25C3:: @ 81A25C3
	.string "I went down...$"
	// おわっちゃった……

SecretBase_RedCave1_Text_1A25D2:: @ 81A25D2
	.string "Where's your SECRET BASE?\n"
	.string "I should go visit you there.$"
	// きみの ひみつきちは どこなんだい!ｎ
	// こんど あそびに いこうかな-

SecretBase_RedCave1_Text_1A2609:: @ 81A2609
	.string "Some people make their SECRET BASES in\n"
	.string "hard-to-find places.\l"
	.string "Do they want to just lie low?$"
	// みつかり にくい ばしょにｎ
	// ひみつきちを つくる ひとが いるけどｌ
	// こっそりと かくれて いたいのかなぁ

SecretBase_RedCave1_Text_1A2663:: @ 81A2663
	.string "People have told me that you can get\n"
	.string "decorations in several ways.\p"
	.string "We should have a race to see who can\n"
	.string "get nicer decorations and furniture!\p"
	.string "In the meantime, want to battle?$"
	// グッズを てにいれる ほうほうはｎ
	// いろいろ あるって はなしよｐ
	// どっちが すてきな グッズをｎ
	// てにいれるか きょうそうね!ｐ
	// ついでに ポケモン しょうぶも しない? 

SecretBase_RedCave1_Text_1A2710:: @ 81A2710
	.string "This is my SECRET BASE.\n"
	.string "I can't lose!$"
	// じぶんの ひみつきちで まけられないわ!

SecretBase_RedCave1_Text_1A2736:: @ 81A2736
	.string "I'll battle with you anytime.$"
	// いつでも しょうぶ まってるわ!

UnknownString_81A2754:: @ 81A2754
	.string "Huh?\n"
	.string "Did I just lose?$"
	// えっ もしかして わたしの まけ?

SecretBase_RedCave1_Text_1A276A:: @ 81A276A
	.string "I won't lose at collecting decorations.\n"
	.string "Come visit again!$"
	// グッズあつめ まけないわよ!ｎ
	// また あそびに きてね!

SecretBase_RedCave1_Text_1A27A4:: @ 81A27A4
	.string "People have told me that you can get\n"
	.string "decorations in several ways.\p"
	.string "We should have a race to see who can\n"
	.string "get nicer decorations and furniture!$"
	// グッズを てにいれる ほうほうはｎ
	// いろいろ あるって はなしよｐ
	// どっちが すてきな グッズをｎ
	// てにいれるか きょうそうね!

SecretBase_RedCave1_Text_1A2830:: @ 81A2830
	.string "I found a spot I liked, and I did it up\n"
	.string "with my favorite decorations.\p"
	.string "I raise my favorite POKéMON and grow\n"
	.string "stronger with it.\p"
	.string "That's what I do.\n"
	.string "Want to battle with me?$"
	// すきな ばしょを さがしてｎ
	// すきな グッズを おく!ｐ
	// すきな ポケモンを そだててｎ
	// ぼくも いっしょに つよくなるｐ
	// そんな ぼくと しょうぶ しよう!

SecretBase_RedCave1_Text_1A28D7:: @ 81A28D7
	.string "Show me what you're made of!$"
	// きみの じつりょくを みせてくれ!

SecretBase_RedCave1_Text_1A28F4:: @ 81A28F4
	.string "I guess there are times when you're not\n"
	.string "into it.$"
	// まぁ そんな ときも あるよね!

UnknownString_81A2925:: @ 81A2925
	.string "I know exactly what you're made of now.$"
	// きみの じつりょくは じゅうぶん わかった!

SecretBase_RedCave1_Text_1A294D:: @ 81A294D
	.string "We can both become stronger.\n"
	.string "Let's keep at it!$"
	// きみも ぼくも もっと つよく なれる!ｎ
	// おたがいに がんばろうね!

SecretBase_RedCave1_Text_1A297C:: @ 81A297C
	.string "I found a spot I liked, and I did it up\n"
	.string "with my favorite decorations.\p"
	.string "I raise my favorite POKéMON and grow\n"
	.string "stronger with it.\p"
	.string "Every day is a great day.$"
	// すきな ばしょを さがしてｎ
	// すきな ものを おく!ｐ
	// すきな ポケモンを そだててｎ
	// ぼくも いっしょに つよくなるｐ
	// まいにち たのしいね-

SecretBase_RedCave1_Text_1A2A13:: @ 81A2A13
	.string "You can learn a lot about the taste\n"
	.string "and sense of people by the kinds of\l"
	.string "decorations they have, and how they\l"
	.string "display them.\p"
	.string "What do you think of my taste?\n"
	.string "Are you speechless?\p"
	.string "Want to see my taste in battling?$"
	// グッズの しゅるいや おきかたを みればｎ
	// そのひとが どんな センスの もちぬしかｌ
	// よ-く わかるわね!ｐ
	// わたしの センスは どうかしら?ｎ
	// うふふっ なにも いえないって かんじね!ｐ
	// しょうぶの センスも ためして みる?

SecretBase_RedCave1_Text_1A2AE2:: @ 81A2AE2
	.string "There's no holding back!$"
	// おもいっきり いくわよ!

SecretBase_RedCave1_Text_1A2AFB:: @ 81A2AFB
	.string "I'll be happy to demonstrate my style\n"
	.string "anytime.$"
	// いつでも わたしの センスを みせるわよ!

UnknownString_81A2B2A:: @ 81A2B2A
	.string "You're supremely talented!\n"
	.string "Your power seems to be limitless...$"
	// すごい さいのうね!ｎ
	// そこしれぬ つよさを かんじたわ……

SecretBase_RedCave1_Text_1A2B69:: @ 81A2B69
	.string "What did you think of my style?\n"
	.string "I'll keep on polishing it!$"
	// わたしの センス どうだった?ｎ
	// もっと センスを みがくわよ-

SecretBase_RedCave1_Text_1A2BA4:: @ 81A2BA4
	.string "You can learn a lot about the taste\n"
	.string "and sense of people by the kinds of\l"
	.string "decorations they have, and how they\l"
	.string "display them.\p"
	.string "What do you think of my taste?\n"
	.string "Are you speechless?$"
	// グッズの しゅるいや おきかたを みればｎ
	// そのひとが どんな センスの もちぬしかｌ
	// よ-く わかるわね!ｐ
	// わたしの センスは どうかしら?ｎ
	// うふふっ なにも いえないって かんじね!
