UnknownString_81A1948: @ 81A1948
	.string "덩굴이 떨어진다면 위로\n"
	.string "올라갈 수 있을 것 같다$"
	@ ツルを おとせば うえに のぼれそう

UnknownString_81A197B: @ 81A197B
	.string "덩굴이 떨어진다면 위로\n"
	.string "올라갈 수 있을 것 같다\p"
	.string "비밀의힘을 사용하겠습니까?$"
	@ ツルを おとせば うえに のぼれそうｐ
	@ ひみつのちからを つかいますか?

UnknownString_81A19C4: @ 81A19C4
	.string "굵은 덩굴이 내려왔다!$"
	@ ふといツルが おちてきた!

UnknownString_81A19DF: @ 81A19DF
	.string "여기에 비밀기지를 만들겠습니까?$"
	@ ここに ひみつきちを つくりますか?

UnknownString_81A1A03: @ 81A1A03
	.string "풀 덩어리를 치운다면\n"
	.string "안으로 들어갈 수 있을 것 같다$"
	@ くさのかたまりを どければｎ
	@ なかへ はいれそう

UnknownString_81A1A4B: @ 81A1A4B
	.string "풀 덩어리를 치운다면\n"
	.string "안으로 들어갈 수 있을 것 같다\p"
	.string "비밀의힘을 사용하겠습니까?$"
	@ くさのかたまりを どければｎ
	@ なかへ はいれそうｐ
	@ ひみつのちからを つかいますか?

UnknownString_81A1AA9: @ 81A1AA9
	.string "작은 입구를 발견!$"
	@ ちいさな いりぐちを はっけん!

UnknownString_81A1AC6: @ 81A1AC6
	.string "여기에 비밀기지를 만들겠습니까?$"
	@ ここに ひみつきちを つくりますか?

SecretBase_RedCave1_Text_1A1AEA:: @ 81A1AEA
	.string "넌 이미 비밀기지를 만들었니?\p"
	.string "난 이곳저곳 돌아다니다가\n"
	.string "드디어 이곳으로 정했어!\p"
	.string "모처럼 왔으니까\n"
	.string "포켓몬 승부하지 않을래?$"
	@ きみは もう ひみつきちを つくったかい?ｐ
	@ ぼくは あっち こっち まわってｎ
	@ やっと この ばしょに きめたんだ!ｐ
	@ せっかく きたんだからｎ
	@ ポケモン しょうぶ しない?

SecretBase_RedCave1_Text_1A1B83:: @ 81A1B83
	.string "그럼 간다!$"
	@ それじゃ いくよ!

SecretBase_RedCave1_Text_1A1B97:: @ 81A1B97
	.string "엇 지금은 안 되는구나...$"
	@ えっ いまは むりなんだ…

UnknownString_81A1BB2:: @ 81A1BB2
	.string "우왓 너 정말로 강하구나-\n"
	.string "내가 진 건 비밀로 해 줘!$"
	@ うわっ きみって つよいな-ｎ
	@ ぼくが まけたこと ひみつに してね!

SecretBase_RedCave1_Text_1A1BF8:: @ 81A1BF8
	.string "내 비밀기지는 어때-\n"
	.string "내일 또 놀러 와!$"
	@ ぼくの ひみつきち どうかな-ｎ
	@ また あしたも あそびに きてね!

SecretBase_RedCave1_Text_1A1C3B:: @ 81A1C3B
	.string "넌 이미 비밀기지를 만들었니?\p"
	.string "난 이곳저곳 돌아다니다가\n"
	.string "드디어 이곳으로 정했어!\p"
	.string "천천히 있다 가!$"
	@ きみは もう ひみつきちを つくったかい?ｐ
	@ ぼくは あっち こっち まわってｎ
	@ やっと この ばしょに きめたんだ!ｐ
	@ ゆっくり して いってね!

SecretBase_RedCave1_Text_1A1CB2:: @ 81A1CB2
	.string "비밀기지를 만들 수 있는 곳은\n"
	.string "다른 곳도 많이 있지만\l"
	.string "여기가 제일 마음에 들어!\p"
	.string "봐! 근사하지!\p"
	.string "앗 혹시 괜찮다면\n"
	.string "포켓몬 승부하지 않을래?$"
	@ ひみつきちを つくれる ばしょはｎ
	@ ほかにも たくさん あるけどｌ
	@ ここが いちばん きにいったの!ｐ
	@ ねっ! すてきでしょ!ｐ
	@ あっ もし よかったらｎ
	@ ポケモン しょうぶ しない?

SecretBase_RedCave1_Text_1A1D48:: @ 81A1D48
	.string "그럼 간다!$"
	@ それじゃ いくわよ!

SecretBase_RedCave1_Text_1A1D59:: @ 81A1D59
	.string "그래 지금은 안 되는구나...$"
	@ そう いまは むりなのね…

UnknownString_81A1D74:: @ 81A1D74
	.string "으-음 내 패배네...\n"
	.string "내가 진 건 비밀이야!$"
	@ う-ん わたしの まけね…ｎ
	@ わたしが まけたのは ないしょの ひみつね!

SecretBase_RedCave1_Text_1A1DC0:: @ 81A1DC0
	.string "이 근처에 오게 된다면\n"
	.string "또 놀러 와줘!$"
	@ このちかくに くることが あったらｎ
	@ また あそびに よってね!

SecretBase_RedCave1_Text_1A1DF6:: @ 81A1DF6
	.string "비밀기지를 만들 수 있는 곳은\n"
	.string "다른 곳도 많이 있지만\l"
	.string "여기가 제일 마음에 들어!\p"
	.string "봐! 근사하지!$"
	@ ひみつきちを つくれる ばしょはｎ
	@ ほかにも たくさん あるけどｌ
	@ ここが いちばん きにいったの!ｐ
	@ ねっ! すてきでしょ!

SecretBase_RedCave1_Text_1A1E67:: @ 81A1E67
	.string "이곳은 인기가 많아서\n"
	.string "항상 차 있어-\p"
	.string "앗 혹시\n"
	.string "너도 여기를 쓰고 싶어?\p"
	.string "으-음 나한테 이긴다면\n"
	.string "이곳을 가져도 좋아!$"
	@ この ばしょは にんきが あるからｎ
	@ いつも うまって いるんだ-ｐ
	@ あっ もしかしてｎ
	@ きみも ここを つかいたい?ｐ
	@ う-ん ぼくに かてたらｎ
	@ このばしょ あげても いいよ!

SecretBase_RedCave1_Text_1A1F04:: @ 81A1F04
	.string "좋아!\n"
	.string "내 기지를 지킬 거야-!$"
	@ よしっ! ぼくの きちを まもるぞ-!

SecretBase_RedCave1_Text_1A1F2E:: @ 81A1F2E
	.string "엇 이곳에 관심없어?\n"
	.string "그렇구나-$"
	@ えっ この ばしょに きょうみが ないの?ｎ
	@ そっか-

UnknownString_81A1F67:: @ 81A1F67
	.string "더는 안 되겠다!\n"
	.string "항-복!$"
	@ もう ダメだ!ｎ
	@ こうさ-ん!

SecretBase_RedCave1_Text_1A1F88:: @ 81A1F88
	.string "알았어 내가 언젠가 이사하게 된다면\n"
	.string "이곳은 네 거야!$"
	@ よしっ ぼくが いつか ひっこしたらｎ
	@ この ばしょは きみの ものさ!

SecretBase_RedCave1_Text_1A1FBD:: @ 81A1FBD
	.string "이곳은 인기가 많아서\n"
	.string "항상 차 있어-\p"
	.string "나도 계속 기다리다가\n"
	.string "드디어 쓸 수 있게 되었지!$"
	@ この ばしょは にんきが あるからｎ
	@ いつも うまって いるんだよ-ｐ
	@ ぼくは ずっと まっていてｎ
	@ やっと つかえる ように なったんだ!

SecretBase_RedCave1_Text_1A2026:: @ 81A2026
	.string "내 포켓몬 연구소에\n"
	.string "잘 왔어!\p"
	.string "여기서 포켓몬 승부에 대해\n"
	.string "몰래 공부를 하고 있지\p"
	.string "어때 내 실력을 보여줄까?$"
	@ わたしの ポケモン けんきゅうじょへｎ
	@ ようこそ!ｐ
	@ ここで ポケモン しょうぶに ついてｎ
	@ こっそり べんきょう してるのよｐ
	@ どう わたしの じつりょく みてみる?

SecretBase_RedCave1_Text_1A2095:: @ 81A2095
	.string "진심으로 간다!$"
	@ ほんきで いくわよ!

SecretBase_RedCave1_Text_1A20AE:: @ 81A20AE
	.string "그럼 다음에 하자!$"
	@ それじゃ また こんどね!

UnknownString_81A20C9:: @ 81A20C9
	.string "으-음 나도 멀었네-\n"
	.string "더 공부해야겠다!$"
	@ う-ん わたしも まだまだね-ｎ
	@ もっと  べんきょう しないと!

SecretBase_RedCave1_Text_1A2109:: @ 81A2109
	.string "승부해 줘서 고마워!\n"
	.string "내일 또 놀러 와-$"
	@ しょうぶ してくれて どうも ありがとう!ｎ
	@ また あしたも きてね-

SecretBase_RedCave1_Text_1A2147:: @ 81A2147
	.string "내 포켓몬 연구소에\n"
	.string "잘 왔어!\p"
	.string "여기서 포켓몬 승부에 대해\n"
	.string "몰래 공부를 하고 있지$"
	@ わたしの ポケモン けんきゅうじょへｎ
	@ ようこそ!ｐ
	@ ここで ポケモン しょうぶに ついてｎ
	@ こっそり べんきょう してるのよ

SecretBase_RedCave1_Text_1A218F:: @ 81A218F
	.string "커다란 집도 좋지만\n"
	.string "나는 이런 곳이 좋아\p"
	.string "왜냐면 다양한 사람이\n"
	.string "놀러 와주니까-!\p"
	.string "어때 포켓몬 승부할래?$"
	@ おおきな いえも いいけどｎ
	@ ぼくは こういう ばしょが すきなんだｐ
	@ だって いろいろな ひとがｎ
	@ あそびに きてくれる からね-!ｐ
	@ どう ポケモン しょうぶでも するかい?

SecretBase_RedCave1_Text_1A2220:: @ 81A2220
	.string "그렇게 나와야지!$"
	@ そう こなくっちゃ!

SecretBase_RedCave1_Text_1A2230:: @ 81A2230
	.string "준비가 됐으면\n"
	.string "언제든 말을 걸어 줘!$"
	@ よういが できたらｎ
	@ いつでも こえを かけてね!

UnknownString_81A2254:: @ 81A2254
	.string "당했다-!\n"
	.string "하지만 포켓몬 승부는 즐거워-!$"
	@ やられた-!ｎ
	@ だけど ポケモン しょうぶは たのしい-!

SecretBase_RedCave1_Text_1A2280:: @ 81A2280
	.string "자 굿즈라도 사러 가볼까?\p"
    .string "내 비밀기지에서\n"
    .string "모두가 재밌게 놀 수 있도록 말이야!$"
	@ さてと グッズでも かいに いこうかなｐ
	@ ぼくの ひみつきちをｎ
	@ みんなに たのしんで ほしい からね!

SecretBase_RedCave1_Text_1A22FA:: @ 81A22FA
	.string "커다란 집도 좋지만\n"
	.string "나는 이런 곳이 좋아\p"
	.string "왜냐면 다양한 사람이\n"
	.string "놀러 와주니까-!$"
	@ おおきな いえも いいけどｎ
	@ ぼくは こういう ばしょが すきなんだｐ
	@ だって いろいろな ひとがｎ
	@ あそびに きてくれる からね-!

SecretBase_RedCave1_Text_1A236A:: @ 81A236A
	.string "저는 굿즈 쇼핑을\n"
	.string "엄청 좋아해요!\p"
	.string "그리고 그만큼 포켓몬 키우기도\n"
	.string "엄청 좋아해요!\p"
	.string "혹시 괜찮다면 제 포켓몬과\n"
	.string "승부해 주실래요?$"
	@ わたし グッズの おかいものがｎ
	@ だいすき です!ｐ
	@ それと おなじくらい ポケモンを そだてるのｎ
	@ だいすき です!ｐ
	@ もし よかったら わたしの ポケモンちゃんとｎ
	@ しょうぶして くれますか?

SecretBase_RedCave1_Text_1A2405:: @ 81A2405
	.string "그럼 잘 부탁드립니다$"
	@ それでは おねがいします

SecretBase_RedCave1_Text_1A2420:: @ 81A2420
	.string "그렇군요 아쉽네요...$"
	@ そう それは ざんねん です…

UnknownString_81A2439:: @ 81A2439
	.string "졌습니다...$"
	@ まいりました……

SecretBase_RedCave1_Text_1A2446:: @ 81A2446
	.string "아아 즐거웠어요!\n"
	.string "다음은 쇼핑이나 할까$"
	@ ああ たのしかった!ｎ
	@ つぎは おかいものを たのしもう かしら

SecretBase_RedCave1_Text_1A2480:: @ 81A2480
	.string "저는 굿즈 쇼핑을\n"
	.string "엄청 좋아해요\p"
	.string "그리고 그만큼 포켓몬 키우기도\n"
	.string "엄청 좋아해요$"
	@ わたし グッズの おかいものがｎ
	@ だいすき ですｐ
	@ それと おなじくらい ポケモンを そだてるのｎ
	@ だいすき です

SecretBase_RedCave1_Text_1A24E1:: @ 81A24E1
	.string "찾기 힘든 곳에\n"
	.string "비밀기지를 만드는 사람이 있는데\l"
	.string "몰래 숨어 있고 싶은 걸까...\p"
	.string "음 모처럼 찾아와 주었으니까\n"
	.string "포켓몬 승부하지 않을래?$"
	@ みつかり にくい ばしょにｎ
	@ ひみつきちを つくる ひとが いるけどｌ
	@ こっそりと かくれて いたいのかなぁ……ｐ
	@ うん せっかく みつけて くれたんだからｎ
	@ ポケモン しょうぶ しようか?

SecretBase_RedCave1_Text_1A256F:: @ 81A256F
	.string "간단히 끝나진 않겠어!$"
	@ かんたんには おわらせ ないよ!

SecretBase_RedCave1_Text_1A258A:: @ 81A258A
	.string "혹시 찾는 데 지쳐버린 거야?$"
	@ もしかして さがすのに つかれちゃった?

UnknownString_81A25C3:: @ 81A25C3
	.string "끝나버렸다...$"
	@ おわっちゃった……

SecretBase_RedCave1_Text_1A25D2:: @ 81A25D2
	.string "네 비밀기지는 어디야!\n"
	.string "다음에 놀러 가야지-$"
	@ きみの ひみつきちは どこなんだい!ｎ
	@ こんど あそびに いこうかな-

SecretBase_RedCave1_Text_1A2609:: @ 81A2609
	.string "찾기 힘든 곳에\n"
	.string "비밀기지를 만드는 사람이 있는데\l"
	.string "몰래 숨어 있고 싶은 걸까$"
	@ みつかり にくい ばしょにｎ
	@ ひみつきちを つくる ひとが いるけどｌ
	@ こっそりと かくれて いたいのかなぁ

SecretBase_RedCave1_Text_1A2663:: @ 81A2663
	.string "굿즈를 손에 넣는 방법은\n"
	.string "여러 가지 있다고들 이야기해\p"
	.string "어느 쪽이 근사한 굿즈를\n"
	.string "손에 넣는지 경쟁하자!\p"
	.string "그리고 포켓몬 승부도 하지 않을래?$"
	@ グッズを てにいれる ほうほうはｎ
	@ いろいろ あるって はなしよｐ
	@ どっちが すてきな グッズをｎ
	@ てにいれるか きょうそうね!ｐ
	@ ついでに ポケモン しょうぶも しない? 

SecretBase_RedCave1_Text_1A2710:: @ 81A2710
	.string "내 비밀기지에서 질 수는 없지!$"
	@ じぶんの ひみつきちで まけられないわ!

SecretBase_RedCave1_Text_1A2736:: @ 81A2736
	.string "언제라도 승부 기다릴게!$"
	@ いつでも しょうぶ まってるわ!

UnknownString_81A2754:: @ 81A2754
	.string "엇 설마 내 패배?$"
	@ えっ もしかして わたしの まけ?

SecretBase_RedCave1_Text_1A276A:: @ 81A276A
	.string "굿즈 모으기는 지지 않을 거야!\n"
	.string "또 놀러 와!$"
	@ グッズあつめ まけないわよ!ｎ
	@ また あそびに きてね!

SecretBase_RedCave1_Text_1A27A4:: @ 81A27A4
	.string "굿즈를 손에 넣는 방법은\n"
	.string "여러 가지 있다고들 이야기해\p"
	.string "어느 쪽이 근사한 굿즈를\n"
	.string "손에 넣는지 경쟁하자!$"
	@ グッズを てにいれる ほうほうはｎ
	@ いろいろ あるって はなしよｐ
	@ どっちが すてきな グッズをｎ
	@ てにいれるか きょうそうね!

SecretBase_RedCave1_Text_1A2830:: @ 81A2830
	.string "멋진 곳을 찾아서\n"
	.string "좋아하는 굿즈를 놓는다!\p"
	.string "좋아하는 포켓몬을 키워서\n"
	.string "나도 함께 강해진다\p"
	.string "그런 나와 승부하자!$"
	@ すきな ばしょを さがしてｎ
	@ すきな グッズを おく!ｐ
	@ すきな ポケモンを そだててｎ
	@ ぼくも いっしょに つよくなるｐ
	@ そんな ぼくと しょうぶ しよう!

SecretBase_RedCave1_Text_1A28D7:: @ 81A28D7
	.string "네 실력을 보여 줘!$"
	@ きみの じつりょくを みせてくれ!

SecretBase_RedCave1_Text_1A28F4:: @ 81A28F4
	.string "뭐 그럴 때도 있지!$"
	@ まぁ そんな ときも あるよね!

UnknownString_81A2925:: @ 81A2925
	.string "네 실력은 충분히 알았어!$"
	@ きみの じつりょくは じゅうぶん わかった!

SecretBase_RedCave1_Text_1A294D:: @ 81A294D
	.string "너도 나도 더 강해질 수 있어!\n"
	.string "서로 힘내자!$"
	@ きみも ぼくも もっと つよく なれる!ｎ
	@ おたがいに がんばろうね!

SecretBase_RedCave1_Text_1A297C:: @ 81A297C
	.string "멋진 곳을 찾아서\n"
	.string "좋아하는 굿즈를 놓는다!\p"
	.string "좋아하는 포켓몬을 키워서\n"
	.string "나도 함께 강해진다\p"
	.string "매일이 즐거워-$"
	@ すきな ばしょを さがしてｎ
	@ すきな ものを おく!ｐ
	@ すきな ポケモンを そだててｎ
	@ ぼくも いっしょに つよくなるｐ
	@ まいにち たのしいね-

SecretBase_RedCave1_Text_1A2A13:: @ 81A2A13
	.string "굿즈의 종류나 놓는 방법을 보면\n"
	.string "그 사람이 어떤 센스가 있는지\l"
	.string "자-알 알 수 있어!\p"
	.string "내 센스는 어떤 것 같아?\n"
	.string "우후후 아무 말도 안 하는구나!\p"
	.string "승부 센스도 시험해 볼래?$"
	@ グッズの しゅるいや おきかたを みればｎ
	@ そのひとが どんな センスの もちぬしかｌ
	@ よ-く わかるわね!ｐ
	@ わたしの センスは どうかしら?ｎ
	@ うふふっ なにも いえないって かんじね!ｐ
	@ しょうぶの センスも ためして みる?

SecretBase_RedCave1_Text_1A2AE2:: @ 81A2AE2
	.string "있는 힘껏 간다!$"
	@ おもいっきり いくわよ!

SecretBase_RedCave1_Text_1A2AFB:: @ 81A2AFB
	.string "언제라도 내 센스를 보여줄게!$"
	@ いつでも わたしの センスを みせるわよ!

UnknownString_81A2B2A:: @ 81A2B2A
	.string "굉장한 재능이네!\n"
	.string "끝없는 강함을 느꼈어...$"
	@ すごい さいのうね!ｎ
	@ そこしれぬ つよさを かんじたわ……

SecretBase_RedCave1_Text_1A2B69:: @ 81A2B69
	.string "내 센스 어땠어?\n"
	.string "더 센스를 갈고닦을 거야-$"
	@ わたしの センス どうだった?ｎ
	@ もっと センスを みがくわよ-

SecretBase_RedCave1_Text_1A2BA4:: @ 81A2BA4
	.string "굿즈의 종류나 놓는 방법을 보면\n"
	.string "그 사람이 어떤 센스가 있는지\l"
	.string "자-알 알 수 있어!\p"
	.string "내 센스는 어떤 것 같아?\n"
	.string "우후후 아무 말도 안 하는구나!$"
	@ グッズの しゅるいや おきかたを みればｎ
	@ そのひとが どんな センスの もちぬしかｌ
	@ よ-く わかるわね!ｐ
	@ わたしの センスは どうかしら?ｎ
	@ うふふっ なにも いえないって かんじね!
