SecretBase_Text_AllDecorationsWillBeReturned: @ 81A38FB
	.string "비밀기지의 굿즈는 모두\n"
	.string "PC로 돌아갑니다\p"
	.string "그래도 괜찮겠습니까?$"
	@ ひみつきちの グッズは すべてｎ
	@ パソコンに もどりますｐ
	@ それでも よろしいですか?

SecretBase_Text_WantToRegisterSecretBase: @ 81A3958
	.string "{STR_VAR_1}의 비밀기지를\n"
	.string "등록하겠습니까?$"
	@ §いの ひみつきちをｎ
	@ とうろく しますか?

SecretBase_Text_AlreadyRegisteredDelete: @ 81A3982
	.string "이미 등록되어 있습니다\n"
	.string "등록을 해제하겠습니까?$"
	@ すでに とうろくされていますｎ
	@ とうろくを かいじょ しますか?

SecretBase_Text_TooManyBasesDeleteSome: @ 81A39C0
	.string "등록할 수 있는 수는\n"
	.string "10곳까지입니다\p"
	.string "어느 장소가 해제되면\n"
	.string "등록할 수 있습니다$"
	@ とうろく できる かずはｎ
	@ 10かしょ まで ですｐ
	@ どれか かいじょ すればｎ
	@ とうろく できます

SecretBase_Text_RegistrationCompleted: @ 81A3A22
	.string "등록했습니다!$"
	@ とうろく しました!

SecretBase_Text_DataUnregistered: @ 81A3A3A
	.string "등록을 해제했습니다!$"
	@ とうろくを かいじょ しました!

UnknownString_81A3A56: @ 81A3A56
	.string "모양 바꾸기 굿즈가 없습니다...$"
	@ もようがえグッズが ありません…

SecretBase_Text_BootUpPC: @ 81A3A72
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string	"PC 전원을 켰다!$"
	@ §あはｎ
	@ パソコンの スイッチを いれた!

SecretBase_Text_WhatWouldYouLikeToDo: @ 81A3A87
	.string "무엇을 하겠습니까?$"
	@ なにを しますか?

SecretBase_Text_RegistryInfo: @ 81A3AA2
	.string "등록한 비밀기지는\n"
	.string "상대가 이사를 하지 않는 한\l"
	.string "사라지는 일은 없습니다\p"
	.string "등록 리스트에서 삭제하면\n"
	.string "다른 비밀기지로\l"
	.string "바뀌는 일도 있습니다\p"
	.string "등록은 10곳까지 할 수 있습니다{PAUSE_UNTIL_PRESS}$"
	@ とうろくした ひみつきちはｎ
	@ あいてが ひっこしを しないかぎりｌ
	@ なくなる ことは ありませんｐ
	@ とうろく リストから さくじょするとｎ
	@ ほかの ひみつきちにｌ
	@ かわることが ありますｐ
	@ とうろくは 10かしょ まで できます©け

SecretBase_Text_BattleTowerShield: @ 81A3B5B
	.string "배틀타워에서 {STR_VAR_1}명 연승한\n"
	.string "기념의 {STR_VAR_2} 상패$"
	@ バトルタワ-で §いにん かちぬいたｎ
	@ きねんの §うの たて

SecretBase_Text_ToyTV: @ 81A3BA4
	.string "진짜와 꼭 닮게 만들어진 장난감 TV\n"
	.string "모르는 사람이 보면 착각할지도!?$"
	@ ほんもの そっくりの オモチャのテレビｎ
	@ しらない ひとが みたら まちがうかも!?

SecretBase_Text_SeedotTV: @ 81A3BE8
	.string "도토링을 닮은 장난감 TV\n"
	.string "왠지 굴러다닐 것 같다!?$"
	@ タネボ- みたいな オモチャのテレビｎ
	@ なんだか ころがりだしそう!?

SecretBase_Text_SkittyTV: @ 81A3C31
	.string "에나비를 닮은 장난감 TV\n"
	.string "왠지 걸어다닐 것 같다!?$"
	@ エネコ みたいな オモチャのテレビｎ
	@ なんだか あるきだしそう!?

UnknownString_81A3C71: @ 81A3C71
	.string "비밀기지는 하나밖에 만들 수 없습니다!\p"
	.string "{STR_VAR_1}에 있는\n"
	.string "비밀기지를 이사하겠습니까?$"
	@ ひみつきちは ひとつしか つくれません!ｐ
	@ §い にあるｎ
	@ ひみつきちを ひっこし しますか?

UnknownString_81A3CC9: @ 81A3CC9
	.string "이사 완료!\p"
	.string "비밀의힘을 사용하겠습니까?$"
	@ ひっこし かんりょう!ｐ
	@ ひみつのちからを つかいますか?
