ShoalCave_LowTideEntranceRoom_Text_1C6668:: @ 81C6668
	.string "이 앞으로 갈 겐가?\p"
	.string "혹시 괜찮으면\n"
	.string "여울소금과 여울조개껍질을\l"
	.string "모아주지 않겠나?\p"
	.string "재료가 모이면\n"
	.string "내가 좋은 걸 만들어 줄 테니$"
	@ このさきに すすむのかね?ｐ
	@ もしで よかったらｎ
	@ あさせのしおと あさせのかいがらをｌ
	@ あつめてきて くれないかｐ
	@ ざいりょうが あつまったらｎ
	@ わたしが いいもの つくるんだがね

ShoalCave_LowTideEntranceRoom_Text_1C670D:: @ 81C670D
	.string "여울소금과 여울조개껍질이\n"
	.string "각각 4개씩 있으면\l"
	.string "조개껍질방울을 만들 수 있네...\p"
	.string "조개껍질방울의 재료라면\n"
	.string "매일 캘 수 있지$"
	@ あさせのしおと あさせのかいがらｎ
	@ それぞれ 4つ あればｌ
	@ かいがらのすずが つくれるんだが……ｐ
	@ かいがらのすずの ざいりょう ならｎ
	@ まいにち とれるよ

ShoalCave_LowTideEntranceRoom_Text_1C6793:: @ 81C6793
	.string "오! 여울소금과 여울조개껍질!\n"
	.string "양도 충분하구먼!\p"
	.string "이걸로 조개껍질방울을\n"
	.string "만들어도 되겠나?$"
	@ お! あさせのしおと あさせのかいがら!ｎ
	@ りょうも じゅうぶんだ!ｐ
	@ これで かいがらのすずｎ
	@ つくっても いいかね?

ShoalCave_LowTideEntranceRoom_Text_1C6808:: @ 81C6808
	.string "그럼 바로\n"
	.string "조개껍질방울을 만들겠네\p"
	.string "...... ...... ...... ......\n"
	.string "...... ...... ...... ......\p"
	.string "자 됐다!$"
	@ かいがらのすずｎ
	@ さっそく つくらせて もらうよｐ
	@ …… …… …… ……ｎ
	@ …… …… …… ……ｐ
	@ よし できたっ!

ShoalCave_LowTideEntranceRoom_Text_1C688E:: @ 81C688E
	.string "포켓몬에게 지니게 하면 기뻐할 걸세\p"
	.string "누가 뭐라 해도 조개껍질방울의 소리는\n"
	.string "천하일품이거든\p"
	.string "조개껍질방울의 재료라면\n"
	.string "매일 캘 수 있으니\l"
	.string "모이면 다시 만들어 주겠네$"
	@ ポケモンに もたせてあげると よろこぶよｐ
	@ なんたって かいがらのすずの ねいろはｎ
	@ てんか いっぴん だからねｐ
	@ かいがらのすずの ざいりょう ならｎ
	@ まいにち とれるからｌ
	@ そろえば また つくらせて もらうよ

ShoalCave_LowTideEntranceRoom_Text_1C6944:: @ 81C6944
	.string "그렇구먼...\n"
	.string "조개껍질방울 만들고 싶었는데...$"
	@ そうかね……ｎ
	@ かいがらのすず つくりたかった……

ShoalCave_LowTideInnerRoom_Text_1C6979:: @ 81C6979
ShoalCave_LowTideLowerRoom_Text_1C6979:: @ 81C6979
ShoalCave_LowTideStairsRoom_Text_1C6979:: @ 81C6979
	.string "여울소금을 모은 다음...\n"
	.string "지금은 아무것도 없네...$"
	@ あさせのしおを とった あと……ｎ
	@ いまは なにも ない……

ShoalCave_LowTideInnerRoom_Text_1C69B8:: @ 81C69B8
	.string "여울조개껍질을 찾은 다음...\n"
	.string "지금은 아무것도 없네...$"
	@ あさせのかいがらを みつけた あと……ｎ
	@ いまは なにも ない……

ShoalCave_LowTideEntranceRoom_Text_1C69F5:: @ 81C69F5
	.string "만들어도 가방이 가득 차서\n"
	.string "지닐 수 없을 것 같구먼...\p"
	.string "정리하고 다시 오게$"
	@ つくっても バッグが いっぱいでｎ
	@ もてない ようだね……ｐ
	@ せいりして また くると いいよ
