gTextStoryteller_Introduction:: @ 81AECC6
	.string "난 전설아저씨\n"
	.string "전설의 트레이너의 이야기를 하곤 해\p"
	.string "내 얘기 들어볼래?$"
	@ わし でんせつおやじｎ
	@ でんせつの トレ-ナ-の はなし するよｐ
	@ わしの ハナシ ききたい?

gTextStoryteller_OhIFeelStifled:: @ 81AED1D
	.string "그렇구나...\n"
	.string "아저씨 아쉽다...$"
	@ そう……ｎ
	@ わし ざんねん……

gTextStoryteller_WhichTale:: @ 81AED35
	.string "난 이런 전설들을 알고 있어\n"
	.string "어느 전설을 듣고 싶어?$"
	@ わしが しってる でんせつは これだけｎ
	@ どの でんせつが ききたい?

gTextStoryteller_ButIKnowOfNoLegendaryTrainers:: @ 81AED70
	.string "그렇지만 난...\n"
	.string "전설의 트레이너에 대한 이야기를\l"
	.string "하나도 알고 있지 않아\p"
	.string "어딘가에 전설로 남을 만한\n"
	.string "트레이너는 없는 걸까$"
	@ でも わし……ｎ
	@ でんせつの トレ-ナ-の はなしｌ
	@ なにも しらないｐ
	@ どこかに でんせつに のこるｎ
	@ トレ-ナ-は いないかなあ

gTextStoryteller_BirthOfANewLegend:: @ 81AEDE8
	.string "...뭐라고!!!\p"
	.string "너 {STR_VAR_1}번이나\n"
	.string "{STR_VAR_2}고!?\p"
	.string "...으음 그거 대단한데!\n"
	.string "새로운 전설의 시작이야!$"
	@ ……え!!!ｐ
	@ きみ §いかい もｎ
	@ §う の!?ｐ
	@ ……ううむ それは すごい!ｎ
	@ あたらしい でんせつの はじまりだ!

gTextStoryteller_CouldThereBeOtherTrainers:: @ 81AEE50
	.string "이것보다 좀 더 대단한\n"
	.string "전설을 가진 트레이너는\l"
	.string "어디 없으려나...$"
	@ これより もっとすごいｎ
	@ でんせつを もってる トレ-ナ-ｌ
	@ どこかに いない かなあ…

gTextStoryteller_HaveYouAnyTales:: @ 81AEEB4
	.string "...너 트레이너야?\p"
	.string "그럼 뭔가 전설 같은 이야기\n"
	.string "좀 들려줘!$"
	@ ……きみ トレ-ナ-?ｐ
	@ だったら なにか でんせつっぽい はなしｎ
	@ きかせてよ

gTextStoryteller_HearAnotherLegendaryTale:: @ 81AEF0A
	.string "그런데...\n"
	.string "또 다른 전설 듣고 싶어?$"
	@ ところで…ｎ
	@ まだ でんせつ ききたい?

gTextStoryteller_ImNotSatisfied:: @ 81AEF49
	.string "...으-음 어딘가 부족한걸\p"
	.string "좀 더 굉장한 이야기를\n"
	.string "들려줬으면 좋겠는데$"
	@ ……う-ん ものたりない なあｐ
	@ もっと すごい はなしをｎ
	@ きかせて ほしいなあ

gTextStoryteller_WishMorePeopleWould:: @ 81AEFA5
	.string "좀 더 많은 사람들이\n"
	.string "전설의 트레이너의 이야기를\l"
	.string "들어주면 좋을 텐데$"
	@ もっと たくさんの ひとにｎ
	@ でんせつの トレ-ナ-の はなしｌ
	@ きいて ほしいなあ

gTextStoryteller_Story1Title:: @ 81AEFFC
	.string "리포트를 많이 작성한 트레이너$"
	@ レポ-トを かきまくった トレ-ナ-

gTextStoryteller_Story1Action:: @ 81AF013
	.string "리포트를 작성했다$"
	@ レポ-トを かいた

gTextStoryteller_Story1Text:: @ 81AF022
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "{STR_VAR_1}번이나\n"
	.string "리포트를 작성했나 봐!\p"
	.string "{STR_VAR_3}{K_I}만큼 조심성 있는\n"
	.string "트레이너는 없을 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ §いかいもｎ
	@ レポ-トを かいた らしい!ｐ
	@ §えほど ようじん ぶかいｎ
	@ トレ-ナ-は いない だろう!

gTextStoryteller_Story2Title:: @ 81AF0A3
	.string "유행 발신 트레이너$"
	@ りゅうこう はっしん トレ-ナ-

gTextStoryteller_Story2Action:: @ 81AF0BB
	.string "유행을 만들었다$"
	@ りゅうこうを つくった

gTextStoryteller_Story2Text:: @ 81AF0CA
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "{STR_VAR_1}번이나\n"
	.string "유행을 새로 만들었나 봐!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 계속\n"
	.string "호연의 유행을 만들고 있어!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ §いかいもｎ
	@ りゅうこうを うみだした らしい!ｐ
	@ §えこそが つぎつぎとｎ
	@ ホウエンの りゅうこうを うみだしている!

gTextStoryteller_Story3Title:: @ 81AF149
	.string "나무열매를 많이 심은 트레이너$"
	@ きのみを うえまくった トレ-ナ-

gTextStoryteller_Story3Action:: @ 81AF164
	.string "나무열매를 심었다$"
	@ きのみを うえた

gTextStoryteller_Story3Text:: @ 81AF174
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "{STR_VAR_1}번이나\n"
	.string "나무열매를 심었나 봐!\p"
	.string "{STR_VAR_3}만큼 열렬히\n"
	.string "나무열매를 좋아하는 사람은 없을 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ §いかいもｎ
	@ きのみを うめた そうだ!ｐ
	@ §えは でんせつのｎ
	@ きのみ ずき だな!

gTextStoryteller_Story4Title:: @ 81AF1E5
	.string "자전거 애호가 트레이너$"
	@ じてんしゃ だいすき トレ-ナ-

gTextStoryteller_Story4Action:: @ 81AF1FD
	.string "자전거를 교환했다$"
	@ じてんしゃを こうかんした

gTextStoryteller_Story4Text:: @ 81AF20A
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "자전거를 교환했나 봐!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 어지간히도\n"
	.string "자전거를 좋아하는 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ じてんしゃを こうかんした そうだ!ｐ
	@ §えは よほどのｎ
	@ じてんしゃ だいすき トレ-ナ- だな!

gTextStoryteller_Story5Title:: @ 81AF281
	.string "인터뷰에 많이 응한 트레이너$"
	@ インタビュ-に こたえまくった トレ-ナ-

gTextStoryteller_Story5Action:: @ 81AF299
	.string "인터뷰에 응했다$"
	@ インタビュ-に こたえた

gTextStoryteller_Story5Text:: @ 81AF2A9
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "인터뷰에 응했나 봐!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 정말\n"
	.string "주목받는 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ インタビュ-を うけた そうだ!ｐ
	@ §えは とてもｎ
	@ ちゅうもく される トレ-ナ- だろう!

gTextStoryteller_Story6Title:: @ 81AF32C
	.string "승부 애호가 트레이너$"
	@ しょうぶ だいすき トレ-ナ-

gTextStoryteller_Story6Action:: @ 81AF345
	.string "승부했다$"
	@ しょうぶ した

gTextStoryteller_Story6Text:: @ 81AF34D
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "포켓몬 승부를 했나 봐!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 트레이너를 보면\n"
	.string "승부를 해야 직성이 풀리는 거겠지!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ ポケモン しょうぶを した そうだ!ｐ
	@ §えは トレ-ナ-を みるとｎ
	@ しょうぶ せずに おれない トレ-ナ-だ!

gTextStoryteller_Story7Title:: @ 81AF3D0
	.string "많이 잡은 트레이너$"
	@ つかまえまくった トレ-ナ-

gTextStoryteller_Story7Action:: @ 81AF3ED
	.string "포켓몬을 잡았다$"
	@ ポケモンを つかまえた

gTextStoryteller_Story7Text:: @ 81AF3FC
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}마리씩이나\n"
	.string "포켓몬을 잡았나 봐!\p"
	.string "{STR_VAR_3}{K_I}야말로 전설의\n"
	.string "포켓몬 잡기 달인일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いひき ものｎ
	@ ポケモンを つかまえた そうだ!ｐ
	@ §えこそ でんせつのｎ
	@ ポケモン つかまえ じょうず だ!

gTextStoryteller_Story8Title:: @ 81AF46D
	.string "많이 낚은 트레이너$"
	@ つりまくった トレ-ナ-

gTextStoryteller_Story8Action:: @ 81AF481
	.string "포켓몬을 낚았다$"
	@ ポケモンを つった

gTextStoryteller_Story8Text:: @ 81AF49B
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "포켓몬을 낚았나 봐!\p"
	.string "{STR_VAR_3}{K_I}야말로 전설의\n"
	.string "낚시 명인일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いひき ものｎ
	@ ポケモンを つった そうだ!ｐ
	@ §えこそ でんせつのｎ
	@ つり めいじん だ!

gTextStoryteller_Story9Title:: @ 81AF511
	.string "알을 많이 품은 트레이너$"
	@ タマゴを あたため つづけた トレ-ナ-

gTextStoryteller_Story9Action:: @ 81AF529
	.string "알을 부화시켰다$"
	@ タマゴを かえした

gTextStoryteller_Story9Text:: @ 81AF536
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "{STR_VAR_1}개나 되는 알을\n"
	.string "부화시켰나 봐!\p"
	.string "{STR_VAR_3}{K_I}야말로 전설의\n"
	.string "알품기 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ §いこ もの タマゴをｎ
	@ かえした そうだ!ｐ
	@ §えこそ でんせつのｎ
	@ タマゴ あたため トレ-ナ-だ!

gTextStoryteller_Story10Title:: @ 81AF5A9
	.string "진화를 많이 시킨 트레이너$"
	@ しんか させまくった トレ-ナ-

gTextStoryteller_Story10Action:: @ 81AF5BD
	.string "포켓몬을 진화시켰다$"
	@ ポケモンを しんか させた

gTextStoryteller_Story10Text:: @ 81AF5CD
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}마리씩이나\n"
	.string "포켓몬을 진화시켰나 봐!\p"
	.string "{STR_VAR_3}{K_I}야말로 최고의\n"
	.string "포켓몬 진화 마스터일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いひきものｎ
	@ ポケモンを しんか させたそうだ!ｐ
	@ §えこそ さいこうのｎ
	@ ポケモン しんか マスタ-だ!

gTextStoryteller_Story11Title:: @ 81AF63F
	.string "포켓몬센터 애호가 트레이너$"
	@ ポケモンセンタ- だいすき トレ-ナ-

gTextStoryteller_Story11Action:: @ 81AF661
	.string "포켓몬센터에서 회복했다$"
	@ ポケモンセンタ-で かいふくした

gTextStoryteller_Story11Text:: @ 81AF676
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "포켓몬센터에서 회복했나 봐!\p"
	.string "{STR_VAR_3}만큼 포켓몬센터를\n"
	.string "좋아하는 트레이너는 없겠지!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ ポケモンセンタ-で かいふく したのだ!ｐ
	@ §えほど ポケモンセンタ-がｎ
	@ すきな トレ-ナ-も いない だろう!

gTextStoryteller_Story12Title:: @ 81AF711
	.string "집 애호가 트레이너$"
	@ さとがえり だいすき トレ-ナ-

gTextStoryteller_Story12Action:: @ 81AF726
	.string "자신의 집에서 회복했다$"
	@ じぶんの いえで かいふくした

gTextStoryteller_Story12Text:: @ 81AF73D
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "자신의 집에서 회복했대!\p"
	.string "{STR_VAR_3}만큼 집을\n"
	.string "좋아하는 트레이너는 없을 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ じぶんの いえで かいふく したのだ!ｐ
	@ §えほど さとがえりがｎ
	@ すきな トレ-ナ-も いないだろう!

gTextStoryteller_Story13Title:: @ 81AF7BF
	.string "사파리존에 자주 가는 트레이너$"
	@ サファリゾ-ンに いりびたった トレ-ナ-

gTextStoryteller_Story13Action:: @ 81AF7D9
	.string "사파리존에 들어갔다$"
	@ サファリゾ-ンに はいった

gTextStoryteller_Story13Text:: @ 81AF7F1
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "사파리존에 들어갔나 봐!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 사파리존에서라면\n"
	.string "야생의 피가 끓는 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ サファリゾ-ンに はいった そうだ!ｐ
	@ §えは サファリゾ-ンではｎ
	@ やせいの ちが さわぐ トレ-ナ-だ!

gTextStoryteller_Story14Title:: @ 81AF88A
	.string "풀베기를 많이 쓴 트레이너$"
	@ いあいぎりを しまくった トレ-ナ-

gTextStoryteller_Story14Action:: @ 81AF8A1
	.string "풀베기를 썼다$"
	@ いあいぎり した

gTextStoryteller_Story14Text:: @ 81AF8AA
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "풀베기를 썼나 봐!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 풀베기가\n"
	.string "좋아서 참을 수 없는 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ いあいぎりを つかった そうだ!ｐ
	@ §えは いあいぎりがｎ
	@ すきで しょうがない トレ-ナ- なのだ!

gTextStoryteller_Story15Title:: @ 81AF91B
	.string "바위를 많이 깬 트레이너$"
	@ いわを くだかずに おれない トレ-ナ-

gTextStoryteller_Story15Action:: @ 81AF935
	.string "바위깨기를 썼다$"
	@ いわくだき した

gTextStoryteller_Story15Text:: @ 81AF943
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "바위깨기를 썼나 봐!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 바위를 봐도\n"
	.string "꺾이지 않는 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ いわくだきを つかった そうだ!ｐ
	@ §えは いわを みたらｎ
	@ くだかずに おれない トレ-ナ- なのだ!

gTextStoryteller_Story16Title:: @ 81AF9C8
	.string "이사를 좋아하는 트레이너$"
	@ ひっこし だいすき トレ-ナ-

gTextStoryteller_Story16Action:: @ 81AF9E0
	.string "이사를 했다$"
	@ ひっこし した

gTextStoryteller_Story16Text:: @ 81AF9F6
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "비밀기지를 이사했나 봐!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 이사를\n"
	.string "무척 좋아하는 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ ひみつきちを ひっこし したそうだ!ｐ
	@ §えは ひっこしがｎ
	@ とっても すきな トレ-ナ- なのだ!

gTextStoryteller_Story17Title:: @ 81AFA79
	.string "많이 튀게 한 트레이너$"
	@ はねまくり トレ-ナ-

gTextStoryteller_Story17Action:: @ 81AFA92
	.string "튀어오르기를 썼다$"
	@ はねるを つかった

gTextStoryteller_Story17Text:: @ 81AFA9E
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "튀어오르기를 썼나 봐!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 튀어오르기가\n"
	.string "무척 즐거운 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ はねるを つかった らしい!ｐ
	@ §えは はねる のがｎ
	@ とっても すきな トレ-ナ- なのだ!

gTextStoryteller_Story18Title:: @ 81AFB17
	.string "포기하지 않는 트레이너$"
	@ あきらめない トレ-ナ-

gTextStoryteller_Story18Action:: @ 81AFB2D
	.string "발버둥을 썼다$"
	@ わるあがき した

gTextStoryteller_Story18Text:: @ 81AFB48
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "발버둥을 썼나 봐!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 어떤 상황에서도\n"
	.string "결코 포기하지 않는 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ わるあがきを した らしい!ｐ
	@ §えは どんな じょうきょう でもｎ
	@ けっして あきらめない トレ-ナ-だ!

gTextStoryteller_Story19Title:: @ 81AFBD8
	.string "슬롯의 명인$"
	@ スロットの めいじん

gTextStoryteller_Story19Action:: @ 81AFBE7
	.string "슬롯에서 대당첨되었다$"
	@ スロットで おおあたり した

gTextStoryteller_Story19Text:: @ 81AFC04
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "슬롯에서 대당첨됐다지 뭐야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 슬롯머신을\n"
	.string "꿰고 있는 트레이너겠지!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ スロットで おおあたり した らしい!ｐ
	@ §えは スロットマシンをｎ
	@ しりつくして いる トレ-ナ-だ!

gTextStoryteller_Story20Title:: @ 81AFC8A
	.string "룰렛의 명인$"
	@ ル-レットの めいじん

gTextStoryteller_Story20Action:: @ 81AFC9D
	.string "룰렛을 연속으로 맞혔다$"
	@ ル-レットを れんぞくで あてた

gTextStoryteller_Story20Text:: @ 81AFCBE
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "룰렛을 연속으로 맞혔다지 뭐야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 확실하게\n"
	.string "룰렛을 지켜보는 트레이너겠지!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ ル-レットを れんぞくで あてた らしい!ｐ
	@ §えは はっきり いってｎ
	@ ル-レットを みきっている トレ-ナ-だ!

gTextStoryteller_Story21Title:: @ 81AFD44
	.string "배틀타워의 도전자$"
	@ バトルタワ-の ちょうせんしゃ

gTextStoryteller_Story21Action:: @ 81AFD60
	.string "배틀타워에 도전했다$"
	@ バトルタワ-に ちょうせん した

gTextStoryteller_Story21Text:: @ 81AFD80
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "배틀타워에 도전했나 봐!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 배틀타워에\n"
	.string "집착을 지닌 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ バトルタワ-に いどんだ そうだ!ｐ
	@ §えは バトルタワ-にｎ
	@ こだわりを もっている トレ-ナ-だ!

gTextStoryteller_Story22Title:: @ 81AFE1D
	.string "블렌드 애호가 트레이너$"
	@ ブレンド だいすき トレ-ナ-

gTextStoryteller_Story22Action:: @ 81AFE36
	.string "포켓몬스넥을 만들었다$"
	@ ポロックを つくった

gTextStoryteller_Story22Text:: @ 81AFE42
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "포켓몬스넥을 만들었나 봐!\p"
	.string "{STR_VAR_3}만큼 나무열매블렌더를\n"
	.string "잘 쓰는 사람은 없을 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ §いかいもｎ
	@ ポロックを つくった そうだ!ｐ
	@ §えに きのみブレンダ-をｎ
	@ つかわせたら みぎに でるものは ないな!

gTextStoryteller_Story23Title:: @ 81AFEC2
	.string "콘테스트 애호가 트레이너$"
	@ コンテスト だいすき トレ-ナ-

gTextStoryteller_Story23Action:: @ 81AFEDD
	.string "콘테스트에 참가했다$"
	@ コンテストに さんか した

gTextStoryteller_Story23Text:: @ 81AFEEE
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "{STR_VAR_1}번이나\n"
	.string "콘테스트에 참가했나 봐!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 자신의 포켓몬을\n"
	.string "남들에게 보여주고 싶어하는 트레이너겠지!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ §いかいもｎ
	@ コンテストに さんか した そうだ!ｐ
	@ §えは じぶんの ポケモンをｎ
	@ ひとに みせるのが だいすき なんだろう!

gTextStoryteller_Story24Title:: @ 81AFF68
	.string "콘테스트의 달인$"
	@ コンテストの たつじん

gTextStoryteller_Story24Action:: @ 81AFF7B
	.string "콘테스트에서 우승했다$"
	@ コンテストで ゆうしょう した

gTextStoryteller_Story24Text:: @ 81AFF88
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "콘테스트에서 우승했나 봐!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 엄청난\n"
	.string "콘테스트 마스터일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ コンテストで ゆうしょう した そうだ!ｐ
	@ §えは とてつも ないｎ
	@ コンテスト マスタ- だろう!

gTextStoryteller_Story25Title:: @ 81AFFFB
	.string "쇼핑 애호가 트레이너$"
	@ かいもの だいすき トレ-ナ-

gTextStoryteller_Story25Action:: @ 81B000D
	.string "쇼핑을 했다$"
	@ かいものを した

gTextStoryteller_Story25Text:: @ 81B0015
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "가게에서 쇼핑을 했대!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 가게에 들어가면\n"
	.string "어느새 사버리는 트레이너겠지!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ おみせで かいものを した らしい!ｐ
	@ §えは おみせに はいるとｎ
	@ ついつい かいもの する トレ-ナ-だな!

gTextStoryteller_Story26Title:: @ 81B009D
	.string "다우징 애호가 트레이너$"
	@ ダウジング だいすき トレ-ナ-

gTextStoryteller_Story26Action:: @ 81B00B6
	.string "다우징머신을 썼다$"
	@ ダウジングマシンを つかった

gTextStoryteller_Story26Text:: @ 81B00C9
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "다우징머신을 썼대!\p"
	.string "{STR_VAR_3}{K_EUNNEUN}\n"
	.string "정말 물건 찾기를 좋아하는 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ ダウジングマシンを つかった らしい!ｐ
	@ §えは ｎ
	@ さがしものが だいすきな トレ-ナ-だな!

gTextStoryteller_Story27Title:: @ 81B014D
	.string "비에 젖은 트레이너$"
	@ あめに ふられた トレ-ナ-

gTextStoryteller_Story27Action:: @ 81B0165
	.string "비에 젖었다$"
	@ あめに ふられた

gTextStoryteller_Story27Text:: @ 81B0173
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "비에 흠뻑 젖었대!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 비도 끌리게 하는\n"
	.string "매력적인 트레이너일 거 같아!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ あめで ずぶぬれに なった らしい!ｐ
	@ §えは みずも したたるｎ
	@ いい トレ-ナ-っていう かんじ だな!

gTextStoryteller_Story28Title:: @ 81B01E9
	.string "도감을 많이 본 트레이너$"
	@ ずかんで しらべまくった トレ-ナ-

gTextStoryteller_Story28Action:: @ 81B0201
	.string "도감을 봤다$"
	@ ずかんを みた

gTextStoryteller_Story28Text:: @ 81B0213
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "도감을 봤나 봐!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 도감으로 포켓몬을\n"
	.string "조사하는 것을 좋아하는 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ ずかんを みた そうだ!ｐ
	@ §えは ずかんで ポケモンをｎ
	@ しらべるのが だいすきな トレ-ナ-だな!

gTextStoryteller_Story29Title:: @ 81B0290
	.string "리본을 잔뜩 모은 트레이너$"
	@ リボンを たくさん あつめた トレ-ナ-

gTextStoryteller_Story29Action:: @ 81B02A5
	.string "리본을 받았다$"
	@ リボンを もらった

gTextStoryteller_Story29Text:: @ 81B02B6
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "리본을 받았나 봐!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 리본을 모으는 걸\n"
	.string "무척 좋아하는 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ リボンを もらった らしい!ｐ
	@ §えは リボンを あつめるのがｎ
	@ とても だいすきな トレ-ナ-だな!

gTextStoryteller_Story30Title:: @ 81B0337
	.string "언덕을 많이 뛰어넘은 트레이너$"
	@ だんさを とびおりまくった トレ-ナ-

gTextStoryteller_Story30Action:: @ 81B0351
	.string "언덕을 뛰어넘었다$"
	@ だんさを とびおりた

gTextStoryteller_Story30Text:: @ 81B0364
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "언덕을 뛰어넘었나 봐!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 언덕을 보면\n"
	.string "뛰어넘지 않곤 못 배기는 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ だんさを とびおりた らしい!ｐ
	@ §えは だんさを みるとｎ
	@ とびおりずに おれない トレ-ナ-だな!

gTextStoryteller_Story31Title:: @ 81B03E9
	.string "전설의 TV 시청자$"
	@ でんせつの テレビ ウォッチャ-

gTextStoryteller_Story31Action:: @ 81B0401
	.string "TV를 봤다$"
	@ テレビを みた

gTextStoryteller_Story31Text:: @ 81B040C
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "TV를 봤다는 거야!\p"
	.string "{STR_VAR_3}{K_EUNNEUN}\n"
	.string "TV가 정말 좋은 트레이너겠지!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ テレビを みた らしい!ｐ
	@ §えは ｎ
	@ テレビ だいすき トレ-ナ-だな!

gTextStoryteller_Story32Title:: @ 81B046E
	.string "시간을 신경 쓰는 트레이너$"
	@ じかんを きに する トレ-ナ-

gTextStoryteller_Story32Action:: @ 81B0489
	.string "시계를 봤다$"
	@ とけいを みた

gTextStoryteller_Story32Text:: @ 81B049A
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "시계를 봤대!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 시간을 신경 쓰는\n"
	.string "꼼꼼한 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ とけいを みた らしい!ｐ
	@ §えは じかんを きに するｎ
	@ きちょうめんな トレ-ナ-だな!

gTextStoryteller_Story33Title:: @ 81B0523
	.string "ID 추첨에 당첨된 트레이너$"
	@ ポケモンくじに あたりまくった トレ-ナ-

gTextStoryteller_Story33Action:: @ 81B053E
	.string "ID 추첨에 당첨됐다$"
	@ ポケモンくじで あたった

gTextStoryteller_Story33Text:: @ 81B0554
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "ID 추첨에서 당첨됐대!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 포켓몬을 교환할\n"
	.string "친구가 엄청 많은 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ ポケモンくじで あたった らしい!ｐ
	@ §えは ポケモンを こうかん するｎ
	@ ともだちが とても おおい トレ-ナ-だ!

gTextStoryteller_Story34Title:: @ 81B05D8
	.string "키우미집 단골 트레이너$"
	@ そだてやを つかいこなす トレ-ナ-

gTextStoryteller_Story34Action:: @ 81B05F3
	.string "키우미집에 포켓몬을 맡겼다$"
	@ そだてやに ポケモンを あずけた

gTextStoryteller_Story34Text:: @ 81B0610
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "키우미집에 포켓몬을 맡겼대!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 어쨌든 키우고 보는\n"
	.string "맹렬한 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ そだてやに あずけた らしい!ｐ
	@ §えは とにかく そだてまくるｎ
	@ モ-レツな トレ-ナ-に ちがいない!

gTextStoryteller_Story35Title:: @ 81B06A9
	.string "케이블카 애호가 트레이너$"
	@ ロ-プウェイ だいすき トレ-ナ-

gTextStoryteller_Story35Action:: @ 81B06C6
	.string "케이블카에 탔다$"
	@ ロ-プウェイに のった

gTextStoryteller_Story35Text:: @ 81B06D9
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "케이블카를 탔대!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 위아래로 왔다 갔다 하는\n"
	.string "매우 바쁜 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ ロ-プウェイに のった らしい!ｐ
	@ §えは うえに したにとｎ
	@ おおいそがしの トレ-ナ-だな!

gTextStoryteller_Story36Title:: @ 81B0763
	.string "온천에 자주 다니는 트레이너$"
	@ おんせんに かよいづめの トレ-ナ-

gTextStoryteller_Story36Action:: @ 81B0781
	.string "온천에 들어갔다$"
	@ おんせんに はいった

gTextStoryteller_Story36Text:: @ 81B0797
	.string "{STR_VAR_3}{K_I}라고 하는\n"
	.string "트레이너의 이야기인데...\p"
	.string "놀랍게도 {STR_VAR_1}번이나\n"
	.string "온천에 들어갔대!\p"
	.string "{STR_VAR_3}{K_EUNNEUN} 분명\n"
	.string "피부가 매끈매끈한 트레이너일 거야!$"
	@ §えというｎ
	@ トレ-ナ-の はなし だが……ｐ
	@ なんと §いかいもｎ
	@ おんせんに はいった らしい!ｐ
	@ §えは きっとｎ
	@ おはだが ツルツルの トレ-ナ- だろう!
