gTextTrader_Introduction:: @ 81AE88F
	.string "난 굿즈교환아저씨\n"
	.string "나랑 굿즈 교환하지 않을래?$"
	@ わし グッズこうかんオヤジｎ
	@ わしと グッズの こうかん する?

gTextTrader_FeelUnwanted1:: @ 81AE8C6
	.string "그렇구나...\n"
	.string "아저씨 아쉽다...$"
	@ そう……ｎ
	@ わし ざんねん……

gTextTrader_TradedAlready:: @ 81AE8DF
	.string "하지만 너하고는 지난번에\n"
	.string "굿즈를 교환했는걸$"
	@ でも きみとは このまえｎ
	@ グッズの こうかん したよね

gTextTrader_MenuPrompt:: @ 81AE910
	.string "이게 내가 가지고 있는 굿즈야\n"
	.string "가지고 싶은 거 있으면 말해$"
	@ これ わしが もってる グッズｎ
	@ なにか ほしいの あったら いってね

gTextTrader_DontWantAnything:: @ 81AE950
	.string "갖고 싶은 굿즈 없어?\n"
	.string "아저씨 아쉽다...$"
	@ ほしい グッズ ないの?ｎ
	@ わし ざんねん……

gTextTrader_ItemOnceBelongedTo:: @ 81AE97C
	.string "그건 {STR_VAR_1}{K_IGA}\n"
	.string "썼었던 굿즈야\p"
	.string "이걸로 할래?$"
	@ それは §いさんがｎ
	@ つかってた グッズ だよｐ
	@ これに するかい?

gTextTrader_YouDontHaveDecorations:: @ 81AE9B6
	.string "...엣 너 굿즈\n"
	.string "하나도 안 가지고 있잖아!$"
	@ ……って きみ グッズｎ
	@ ひとつも もってない じゃん!

gTextTrader_PickDecorationYoullTrade:: @ 81AE9F8
	.string "그럼 교환에 내놓을\n"
	.string "굿즈를 선택해 줘!$"
	@ じゃあ こうかんに だしてくれるｎ
	@ グッズを えらんで!

gTextTrader_FeelUnwanted2:: @ 81AEA2B
	.string "교환 안 할 거야?\n"
	.string "아저씨 아쉽다...$"
	@ こうかん して くれないの?ｎ
	@ わし ざんねん……

gTextTrader_NoRoomForThis:: @ 81AEA57
	.string "너 {STR_VAR_2}{K_IGA} 가득해서\n"
	.string "더 이상 지닐 수 없어$"
	@ きみ §うが いっぱいでｎ
	@ もう もてないよ

gTextTrader_SoWellTrade:: @ 81AEA9B
	.string "그럼 내 {STR_VAR_3}{K_WAGWA}\n"
	.string "너의 {STR_VAR_2}{K_EULREUL} 교환할게?$"
	@ じゃあ わしの §えとｎ
	@ きみの §うを こうかん するよ?

gTextTrader_InUseYouCantTradeIt:: @ 81AEAC3
	.string "그 굿즈는 지금 장식되어 있네\n"
	.string "장식한 굿즈는 교환할 수 없어$"
	@ きみ いま そのグッズ かざってるねｎ
	@ かざってる グッズは こうかん できないよ

gTextTrader_ThenWellTrade:: @ 81AEAFB
	.string "자 그럼 교환!\p"
	.string "네 PC에\n"
	.string "굿즈를 전송해둘게$"
	@ じゃあ こうかん!ｌ
	@ きみの パソコンにｎ
	@ グッズを おくっておくよ

gTextTrader_ICantTradeThatOneAway:: @ 81AEB31
	.string "아앗! 미안!\n"
	.string "그거 굉장히 희귀한 굿즈라서\l"
	.string "교환할 수 없어!\p"
	.string "그 밖에 원하는 굿즈 있어?$"
	@ ああ! ごめん!ｎ
	@ それ とっても レアな グッズ だからｌ
	@ こうかん できないんだ!ｐ
	@ ほかに ほしい グッズ ある?
