FallarborTown_ContestLobby_Text_1A6F7C:: @ 81A6F7C
	.string "으음? 당신 포켓몬 콘테스트에\n"
	.string "참가했었군요!\l"
	.string "그 포켓몬을 보면 안다구요!\p"
	.string "전 포켓몬 콘테스트에 대해\n"
	.string "기사를 쓰고 있는데\p"
	.string "괜찮다면 잠깐 감상을\n"
	.string "들려주실 수 있을까요?$"
	@ おや? あなた ポケモンコンテストにｎ
	@ さんかして いましたね!ｌ
	@ その ポケモンを みれば わかりますよ!ｐ
	@ わたくし ポケモンコンテストに ついてｎ
	@ きじを かいて いるのですがｐ
	@ できれば すこし かんそうをｎ
	@ きかせて くれませんかね?

FallarborTown_ContestLobby_Text_1A704E:: @ 81A704E
	.string "정말요!?\n"
	.string "감사합니다\p"
	.string "그럼 지금 했던 콘테스트에 대한 감상을\n"
	.string "한마디로 부탁할게요!$"
	@ ほんとう ですか!ｎ
	@ ありがとう ございますｐ
	@ それでは いまの コンテストの かんそうをｎ
	@ ひとことで おねがいします!

FallarborTown_ContestLobby_Text_1A70A5:: @ 81A70A5
	.string "으-음 그렇군요!\p"
	.string "어떤 콘테스트였는지\n"
	.string "잘 알 수 있는 한마디였습니다!\p"
	.string "...마지막으로\n"
	.string "살짝 물어보고 싶습니다만\p"
	.string "당신이 상상하는 {STR_VAR_2}{K_I}란\n"
	.string "대체 어떤 것인가요?$"
	@ う-ん なるほど!ｐ
	@ どんな コンテストだったかｎ
	@ よくわかる ひとこと ですね!ｐ
	@ ……さいごにｎ
	@ ちょっと おききしたいの ですがｐ
	@ あなたが イメ-ジする §うってｎ
	@ いったい どんなもの ですかね?

FallarborTown_ContestLobby_Text_1A7153:: @ 81A7153
	.string "그렇군요!\p"
	.string "그게 당신이 상상하는\n"
	.string "{STR_VAR_2}인 거군요!\p"
	.string "여러모로 참고가 됐습니다!\p"
	.string "콘테스트에 대한\n"
	.string "좋은 기사를 쓸 수 있을 것 같네요\p"
	.string "어쩌면 TV에서 이 내용을\n"
	.string "방송할지도 모르니까\l"
	.string "기대하고 있어주세요!$"
	@ なるほど!ｐ
	@ それが あなたの イメ-ジするｎ
	@ §う なんですね!ｐ
	@ いろいろ さんこうに なりました!ｐ
	@ コンテストに ついてｎ
	@ いい きじが かけそう ですよｐ
	@ もしかしたら テレビで このことがｎ
	@ ながれるかも しれないのでｌ
	@ たのしみに してくださいね!

FallarborTown_ContestLobby_Text_1A7256:: @ 81A7256
	.string "그렇습니까...\p"
	.string "다음에 재미있는 일이 생기면\n"
	.string "들려주세요$"
	@ そうですか……ｐ
	@ こんど おもしろいことが あればｎ
	@ きかせて くださいね

FallarborTown_ContestLobby_Text_1A72A8:: @ 81A72A8
	.string "다음 포켓몬 콘테스트도\n"
	.string "기대하고 있겠습니다!$"
	@ こんどの ポケモンコンテストもｎ
	@ たのしみに してますよ!

gTVBravoTrainerText1:: @ 81A72DE
	.string "이야-!\n"
	.string "“브라보 파트너”의 시간이야!\p"
	.string "오늘은 {STR_VAR_3} 클래스의\n"
	.string "{STR_VAR_2}{K_EULREUL} 자랑하는\l"
	.string "{STR_VAR_1}씨의 포켓몬!$"
	@ イヤ-!ｎ
	@ 『ブラボ- トレ-ナ-』の じかんだ!ｐ
	@ きょうは §えクラスのｎ
	@ §うを ほこるｌ
	@ §いさんの ポケモン!

gTVBravoTrainerText2:: @ 81A736B
	.string "{STR_VAR_1} “{STR_VAR_2}”의\n"
	.string "소개 시간이야-!\p"
	.string "“{STR_VAR_2}”인가...\p"
	.string "이미 닉네임부터\n"
	.string "{STR_VAR_3}{K_IGA} 드러나는걸!$"
	@ §い の 「§う」のｎ
	@ しょうかいだ-!ｐ
	@ 「§う」か……ｐ
	@ もう ニックネ-ム からしてｎ
	@ §えが にじみ でているぜ!

gTVBravoTrainerText3:: @ 81A73CA
	.string "그런데 그 {STR_VAR_1}씨가\n"
	.string "포켓몬 콘테스트에 참가했을 때\p"
	.string "자신의 포켓몬에 대해서\n"
	.string "열정적으로 얘기해 줬어!$"
	@ さ-て この §いさんがｎ
	@ ポケモンコンテストに さんか したときｐ
	@ じぶんの ポケモンに ついてｎ
	@ あつく はなして くれたぞ!

gTVBravoTrainerText4:: @ 81A744D
	.string "콘테스트를 한 뒤의\n"
	.string "감상을 물어보니\l"
	.string "엄청 기쁜 듯이\p"
	.string "“{STR_VAR_2}”{K_I}라고\n"
	.string "대답해 주었지!\p"
	.string "뭐 콘테스트에서는\n" 
	.string "{STR_VAR_3}번이었으니까 말이지-!\p"
	.string "지금의 {STR_VAR_1}씨에게\n"
	.string "정말 딱 맞는 대사였다고 생각해!$"
	@ コンテストを したあとのｎ
	@ かんそうを きくとｌ
	@ すごく うれしそうにｐ
	@ 「§う」ってｎ
	@ こたえて くれたぞ!ｐ
	@ まあ コンテストではｎ
	@ §えばん でした からね-!ｐ
	@ いまの §いさんにはｎ
	@ ぴったりの セリフだよ まったく!

gTVBravoTrainerText5:: @ 81A7508
	.string "콘테스트를 한 뒤의\n"
	.string "감상을 물어보니\l"
	.string "미묘하게 분해하면서\p"
	.string "“{STR_VAR_2}”{K_I}라고\n"
	.string "대답해 주었지!\p"
	.string "뭐 콘테스트에선\n"
	.string "{STR_VAR_3}번이었으니까 말이지-!\p"
	.string "이 대사에 {STR_VAR_1}씨의\n"
	.string "분함이 보일 듯 말 듯하네-$"
	@ コンテストを したあとのｎ
	@ かんそうを きくとｌ
	@ びみょうに くやしがり ながらｐ
	@ 「§う」ってｎ
	@ こたえて くれたぞ!ｐ
	@ まあ コンテストではｎ
	@ §えばん でした からね-!ｐ
	@ この ことばに §いさんのｎ
	@ くやしさが みえかくれ するね-

gTVBravoTrainerText6:: @ 81A75CE
	.string "그런데 {STR_VAR_1}씨가 목표로 하는\n"
	.string "{STR_VAR_2}{K_EUNNEUN} 대체 뭘까?\l"
	.string "들어보고 싶은걸-!\p"
	.string "물론 물어봤다고!\p"
	.string "이 한마디에 그\n"
	.string "모든 것이 담겨있지!\p"
	.string "바로 “{STR_VAR_3}!”\p"
	.string "그것이야말로 {STR_VAR_1}씨의\n"
	.string "{STR_VAR_2}의 모든 것인 거야!$"
	@ ところで §いさんの めざしてるｎ
	@ §うって いったい なんだろう?ｌ
	@ きいて みたいね-!ｐ
	@ もちろん きいて きました!ｐ
	@ それは つぎの ひとことにｎ
	@ すべてが つまって います!ｐ
	@ それは 「§え!」ｐ
	@ それこそ §いさんのｎ
	@ §うの すべて なんです!

gTVBravoTrainerText7:: @ 81A768D
	.string "마지막으로 {STR_VAR_1}{K_IGA}\n"
	.string "썼던 {STR_VAR_2}도\l"
	.string "모두 “{STR_VAR_3}”인 거래!$"
	@ さいごに §いがｎ
	@ つかった §うもｌ
	@ すべて 「§え」 なんです!

gTVBravoTrainerText8:: @ 81A76C5
	.string "브라보! {STR_VAR_1}!\n"
	.string "브라보!! {STR_VAR_2}!\p"
	.string "다음번 {STR_VAR_1}씨의 활약에\n"
	.string "기대가 되는걸-!\p"
	.string "그럼 또 다음\n"
	.string "방송에서 만나자구-!$"
	@ ブラボ-! §いｎ
	@ ブラボ-!! §うｐ
	@ こんごの §いさんの かつやくにｎ
	@ きたい したいね-!ｐ
	@ それじゃあ また じかいのｎ
	@ ほうそうで あいましょ-!

gTVBravoTrainerText9:: @ 81A774F
	.string "{STR_VAR_1}{K_EULREUL} 소개할 시간이야-!$"
	@ §い の しょうかいだ-!

BattleTower_Lobby_Text_1A776D:: @ 81A776D
	.string "아! 지금 막 배틀이 끝난\n"
	.string "트레이너분이시군요!\p"
	.string "저는 지금 여러 트레이너의\n"
	.string "이야기를 들으면서 돌아다니고 있는데\p"
	.string "배틀이 끝난 감상을\n"
	.string "조금만 들려주실 수 있을까요?$"
	@ あ! いま たたかっていたｎ
	@ トレ-ナ-の かたですね!ｐ
	@ わたし いま いろんな トレ-ナ-のｎ
	@ はなしを きいて まわってるんだけどｐ
	@ たたかいおわった かんそうをｎ
	@ すこしだけ きかせて もらえませんか?

BattleTower_Lobby_Text_1A7823:: @ 81A7823
	.string "정말인가요!?\n"
	.string "감사합니다!\l"
	.string "으음 그럼...\p"
	.string "이번 배틀타워의\n"
	.string "대전은 어땠나요?\p"
	.string "만족하셨습니까!?\n"
	.string "아니면 불만이신가요!?$"
	@ ほんと!?ｎ
	@ ありがとう!ｌ
	@ えっと それじゃあねぇ……ｐ
	@ こんかいの バトルタワ-のｎ
	@ たいせんは どうでしたかｐ
	@ まんぞく でしたか!ｎ
	@ それとも ふまん ですか!?

BattleTower_Lobby_Text_1A78B7:: @ 81A78B7
	.string "아아!\n"
	.string "죄송합니다\p"
	.string "그럼 다음에 또 배틀타워에 온다면\n"
	.string "들려주세요$"
	@ あぁ!ｎ
	@ ごめんなさいｐ
	@ じゃあ またこんど バトルタワ-に きたらｎ
	@ きかせて くださいね

BattleTower_Lobby_Text_1A791B:: @ 81A791B
	.string "역시나!\p"
	.string "그 만족한 얼굴을 보면\n"
	.string "얼마나 좋은 시합이었는지가\l"
	.string "보인단 말이죠!$"
	@ さっすが!ｐ
	@ その まんぞくした かおを みればｎ
	@ どんなに いいしあいだったかｌ
	@ わかりますよ!

BattleTower_Lobby_Text_1A7990:: @ 81A7990
	.string "으-음 그렇습니까...\p"
	.string "생각한 것처럼 승부하는 건\n"
	.string "꽤나 어려운 일이니 말이죠...$"
	@ う-ん そうですか……ｐ
	@ おもいどおりに しょうぶを するのってｎ
	@ なかなか むずかしい ですからね……

BattleTower_Lobby_Text_1A79EB:: @ 81A79EB
	.string "아앗 그리고\n"
	.string "하나만 더 괜찮을까요?\p"
	.string "이번 배틀의 감상을\n"
	.string "한마디로 딱 들려주세요!$"
	@ あぁっ あとｎ
	@ もう ひとつだけ いいですか?ｐ
	@ この たたかいの かんそうをｎ
	@ ひとことで ビシッと きかせてください!

BattleTower_Lobby_Text_1A7A6E:: @ 81A7A6E
	.string "멋있어요-!!\p"
	.string "좋은 마무리 대사네요\n"
	.string "다음 배틀도 기대하고 있겠습니다\p"
	.string "그럼 다음에 또 봐요!$"
	@ かっこい-!!ｐ
	@ いい きめゼリフ ですねｎ
	@ つぎの たたかいも きたい してますよｐ
	@ それでは また!

BattleTower_Lobby_Text_1A7AE0:: @ 81A7AE0
	.string "그렇습니까...\p"
	.string "하지만 아무 할 말이 없는 것\n"
	.string "또한 멋있네요!\p"
	.string "그럼 다음 기회에\n"
	.string "감상을 들려주세요!$"
	@ そうですか……ｐ
	@ でも なにも いわないのもｎ
	@ また かっこいいですね!ｐ
	@ それじゃあ またの きかいにｎ
	@ かんそうを きかせて ください!

BattleTower_Lobby_Text_1A7B66:: @ 81A7B66
	.string "다음 배틀도\n"
	.string "기대하고 있다구요$"
	@ つぎの たたかいもｎ
	@ きたい してますよ

gTVBravoTrainerBattleTowerText1:: @ 81A7B93
	.string "이야-!\n"
	.string "“브라보 파트너”의 시간이야!\p"
	.string "오늘은 배틀타워에 도전했던\n"
	.string "{STR_VAR_1}씨를 소개할게-!\p"
	.string "{STR_VAR_1}씨는 {STR_VAR_2}{K_EULREUL}\n"
	.string "사용한 배틀을 해서$"
	@ イヤ-!ｎ
	@ 『ブラボ- トレ-ナ-』の じかんだ!ｐ
	@ きょうは バトルタワ-に ちょうせんしたｎ
	@ §いさんの しょうかいだ-!ｐ
	@ §いさんは §うをｎ
	@ つかった たたかいをして

gTVBravoTrainerBattleTowerText2:: @ 81A7C26
	.string "무려 레벨{STR_VAR_1}의 방에서\n"
	.string "{STR_VAR_2}연승이라는\l"
	.string "기록을 세웠다고!$"
	@ なんと レベル§いの へやでｎ
	@ §うれんしょう というｌ
	@ きろくを うちたてたぞ!

gTVBravoTrainerBattleTowerText3:: @ 81A7C7D
	.string "아깝게도 {STR_VAR_2}번째로 싸웠던\n"
	.string "{STR_VAR_1}씨에게 져버렸지만 말야\l"
	.string "으-음! 안타까워\p"
	.string "이렇게 빨리 {STR_VAR_1}씨와\n"
	.string "마주친 건 운이 없었다고밖에 할 수 없지\p"
	.string "자 그럼 그 {STR_VAR_1}씨와\n"
	.string "승부한 감상을 물어봤는데$"
	@ おしくも §うにんめで たたかったｎ
	@ §いさんに まけて しまいましたｌ
	@ う-ん! ざんねんだねぇｐ
	@ でも こんなはじめに §いさんにｎ
	@ あたるとは うんがないとしか いえないよｐ
	@ さて その §いさんとのｎ
	@ しょうぶの かんそうを きいたところ

gTVBravoTrainerBattleTowerText4:: @ 81A7D4A
	.string "마지막에는 {STR_VAR_1}씨의\n"
	.string "{STR_VAR_2}{K_EULREUL} 훌륭히 쓰러뜨려서\l"
	.string "승리했다고\p"
	.string "이야 {STR_VAR_1}씨를 이기다니\n"
	.string "굉장하다는 말밖에 안 나와 참\p"
	.string "자 그럼 그 승리를 붙잡은\n"
	.string "순간의 감상을 물어봤는데$"
	@ さいごには §いさんのｎ
	@ §うを みごとに たおしてｌ
	@ しょうり したんですねぇｐ
	@ いや §いさんに かつなんてｎ
	@ すごいとしか いいようがないよ まったくｐ
	@ さて そのしょうりを つかんだｎ
	@ しゅんかんの かんそうを きいたところ

gTVBravoTrainerBattleTowerText5:: @ 81A7E0C
	.string "하지만 마지막으로 등장한\n"
	.string "{STR_VAR_1}씨의 {STR_VAR_2}에게\l"
	.string "결국 져버리고 말았지\p"
	.string "뭐 “{STR_VAR_1}의 {STR_VAR_2}” 하면\n"
	.string "유명한 콤비니까\p"
	.string "...자 그럼 그 유명인과\n"
	.string "승부한 감상을 물어봤는데$"
	@ しかし さいごに とうじょうしたｎ
	@ §いさんの §うにｌ
	@ ついに まけて しまったんですねぇｐ
	@ まあ 「§いの §う」ｎ
	@ といえば ゆうめいな コンビ ですからねｐ
	@ ……さて その ゆうめいじんとのｎ
	@ しょうぶの かんそうを きいたところ

gTVBravoTrainerBattleTowerText6:: @ 81A7F0E
	.string "“만족했다!!”\p"
	.string "라고 시원하게 답해줬어\n"
	.string "역시!\p"
	.string "만족스러운 배틀이 가능하다니\n"
	.string "정말로 굉장하지 참!\p"
	.string "그 만족감은 이 한마디를\n"
	.string "들었을 때 전부 이해했어$"
	@ まんぞく した!!ｐ
	@ と すがすがしく こたえてくれたよｎ
	@ さすがだぜ!ｐ
	@ まんぞくいく たたかいが できるなんてｎ
	@ ほんと すごいよねぇ まったく!ｐ
	@ その まんぞくかんは つぎの ひとことをｎ
	@ きいたとき すべて わかったよ

gTVBravoTrainerBattleTowerText7:: @ 81A8004
	.string "불만이었다...\p"
	.string "라고 미묘하게 우울해하면서\n"
	.string "대답해줬어\p"
	.string "...뭐 만족스러운 배틀은\n"
	.string "자주 겪을 수 있는 게 아니니까-\p"
	.string "그때의 분함은\n"
	.string "이 한마디가 잘 드러내고 있어$"
	@ ふまんだった……ｐ
	@ と びみょうに おちこみながらｎ
	@ こたえて くれたよｐ
	@ ……まあ まんぞくいく たたかいってｎ
	@ なかなかできる もんじゃないからね-ｐ
	@ そのときの くやしさはｎ
	@ つぎの ひとことが よくあらわしてるよ

gTVBravoTrainerBattleTowerText8:: @ 81A8119
	.string "없음$"
	@ なし

gTVBravoTrainerBattleTowerText9:: @ 81A811E
	.string "없음$"
	@ なし

gTVBravoTrainerBattleTowerText10:: @ 81A8123
	.string "없음$"
	@ なし

gTVBravoTrainerBattleTowerText11:: @ 81A8128
	.string "없음$"
	@ なし

gTVBravoTrainerBattleTowerText12:: @ 81A812D
	.string "그 말은\n"
	.string "“{STR_VAR_1}!”$"
	@ その ことばはｎ
	@ 「§い!」

gTVBravoTrainerBattleTowerText13:: @ 81A8133
	.string "“{STR_VAR_1}!”\n"
	.string "으-음 좋은 말인걸!!\p"
	.string "{STR_VAR_2}씨의 기쁨을\n"
	.string "이 말이 잘 드러내고 있어!\p"
	.string "확실히 {STR_VAR_3}씨와의 배틀은\n"
	.string "그야말로 “{STR_VAR_1}”인\l"
	.string "느낌의 배틀이었지!$"
	@ 「§い!」ｎ
	@ う-ん  いい ことばだねぇ!!ｐ
	@ §うさんの うれしさをｎ
	@ このことばが よく あらわしているよ!ｐ
	@ たしかに §えさんとの たたかいはｎ
	@ まさに 「§い」 というｌ
	@ かんじ だったからねぇ!

gTVBravoTrainerBattleTowerText14:: @ 81A81BC
	.string "“{STR_VAR_1}!”\n"
	.string "과연 그렇구나\p"
	.string "확실히 {STR_VAR_3}씨와의 배틀은\n"
	.string "“{STR_VAR_1}”라고밖에 할 수 없는\l"
	.string "배틀이었으니까\p"
	.string "{STR_VAR_2}씨의 분함이\n"
	.string "잘 전해져오네! 크-!$"
	@ 「§い!」ｎ
	@ なるほどねぇｐ
	@ たしかに §えさんとの たたかいはｎ
	@ 「§い」 としか いいようがないｌ
	@ たたかい でしたからねぇｐ
	@ §うさんの くやしさがｎ
	@ よく つたわってくるよ! く-!

gTVBravoTrainerBattleTowerText15:: @ 81A8267
	.string "브라보! {STR_VAR_1}!\n"
	.string "브라보!! {STR_VAR_2}!\p"
	.string "다음번 {STR_VAR_1}씨의 활약에\n"
	.string "기대가 되는걸!\p"
	.string "그럼 또 다음\n"
	.string "방송에서 만나자구-!$"
	@ ブラボ-! §いｎ
	@ ブラボ-!! §うｐ
	@ こんごの §いさんの かつやくにｎ
	@ きたい したいねぇ!ｐ
	@ それじゃあ また じかいのｎ
	@ ほうそうで あいましょ-!

SlateportCity_PokemonFanClub_Text_1A82F1:: @ 81A82F1
	.string "와아!\p"
	.string "너 그 {STR_VAR_1}{K_EULREUL} 무척\n"
	.string "소중히 여기는 모양이구나!\p"
	.string "{STR_VAR_2}{K_I}라고 하는구나...\p"
	.string "맞다!\p"
	.string "지금 나 TV 취재로\n"
	.string "포켓몬에 대한 설문을 하고 있는데\p"
	.string "잠깐 질문에\n"
	.string "답해줄 수 있을까?$"
	@ わあ!ｐ
	@ きみ その §いを とてもｎ
	@ だいじに している みたいね!ｐ
	@ §う って いうんだ……ｐ
	@ そうだ!ｐ
	@ いま わたし テレビの しゅざいでｎ
	@ ポケモンの アンケ-トを してるんだけどｐ
	@ すこしだけ しつもんにｎ
	@ こたえて くれないかな?

SlateportCity_PokemonFanClub_Text_1A83D0:: @ 81A83D0
	.string "고마워!\p"
	.string "그럼 물을게\n"
	.string "딱 한마디로 대답해줘!$"
	@ ありがとう!ｐ
	@ じゃあ きくねｎ
	@ ずばり ひとことで こたえて!

SlateportCity_PokemonFanClub_Text_1A8414:: @ 81A8414
	.string "네가 {STR_VAR_1}하고\n"
	.string "만났을 때\p"
	.string "무슨 느낌이었어?\n"
	.string "어떻게 생각했는지 알려줘!$"
	@ きみが §いとｎ
	@ であったときってｐ
	@ なにか かんじた?ｎ
	@ どう おもったか おしえて!

SlateportCity_PokemonFanClub_Text_1A8470:: @ 81A8470
	.string "네가 귀여워하는 {STR_VAR_1}!\p"
	.string "만약 무엇인가 좋아하는 것에 비유하자면\n"
	.string "뭐라고 생각해?$"
	@ きみの かわいがってる §い!ｐ
	@ もし なにか すきなものに たとえるとｎ
	@ すれば なんだと おもう?

SlateportCity_PokemonFanClub_Text_1A84D5:: @ 81A84D5
	.string "네가 귀여워하는 {STR_VAR_1}!\n"
	.string "넌 {STR_VAR_1}의 어디에\n"
	.string "이끌린 거야?$"
	@ きみの かわいがってる §い!ｐ
	@ きみは §いの どこにｎ
	@ ひかれたの?

SlateportCity_PokemonFanClub_Text_1A852D:: @ 81A852D
	.string "으-음 그렇구나\p"
	.string "그럼 다음은 살짝\n"
	.string "어려운 질문을 할게!\p"
	.string "그럼...\p"
	.string "네게 있어 포켓몬이란\n"
	.string "한마디로 뭐라고 생각해?$"
	@ う-ん なるほどねｐ
	@ じゃあ つぎは ちょっとｎ
	@ むずかしい しつもんを するね!ｐ
	@ じゃあ……ｐ
	@ きみに とって ポケモンってｎ
	@ ひとことで いうと なんだと おもう?

SlateportCity_PokemonFanClub_Text_1A85A6:: @ 81A85A6
	.string "그렇구나-!\p"
	.string "흐음흐음...\p"
	.string "아!\n"
	.string "협력해줘서 고마워!\p"
	.string "여러 얘기를 들어서\n"
	.string "재밌었어\p"
	.string "이 얘기 어쩌면 TV에\n"
	.string "나올지도 모르니까 기대해줘\p"
	.string "그럼 이만\n"
	.string "바이바이!$"
	@ なるほど-!ｐ
	@ ふむふむ……ｐ
	@ あ!ｎ
	@ きょうりょく ありがとうね!ｐ
	@ いろいろ はなしが きけて ｎ
	@ おもしろ かったよｐ
	@ このはなし もしかしたら テレビで ｎ
	@ ながすかも しれないから きたい しててねｐ
	@ じゃあねｎ
	@ バイバイ!

SlateportCity_PokemonFanClub_Text_1A8667:: @ 81A8667
	.string "그렇구나...\p"
	.string "그럼 또 포켓몬에 대해서\n"
	.string "얘기하고 싶어지면 언제든지 와줘$"
	@ そっか……ｐ
	@ じゃあ また ポケモンの ことをｎ
	@ はなしたく なったら いつでも きてね

SlateportCity_PokemonFanClub_Text_1A86B5:: @ 81A86B5
	.string "여기에 있으면 여러 포켓몬의\n"
	.string "이야기를 들을 수 있어서 재밌어$"
	@ ここに いると いろんな ポケモンのｎ
	@ はなしが きけるから おもしろいわ

SlateportCity_PokemonFanClub_Text_1A8704:: @ 81A8704
	.string "너 그 {STR_VAR_1}{K_WAGWA}\n"
	.string "무척 사이가 좋은 모양이네\p"
	.string "맞다! 지금 나\n"
	.string "TV 취재로\p"
	.string "여러 포켓몬의 이야기를\n"
	.string "들으면서 돌아다니고 있는데\p"
	.string "괜찮다면 네 {STR_VAR_1}의\n"
	.string "이야기를 들려줄 수 있을까?$"
	@ きみの その §いとｎ
	@ とても なかが よさそうねｐ
	@ そうだ! いま わたしｎ
	@ テレビの しゅざいでｐ
	@ いろんな ポケモンの はなしをｎ
	@ きいて まわってるんだけどｐ
	@ よかったら きみの §いのｎ
	@ はなしを きかせて くれないかな?

SlateportCity_PokemonFanClub_Text_1A87CA:: @ 81A87CA
	.string "와아!\n"
	.string "고마워!\p"
	.string "그럼 {STR_VAR_1}의 이야기를\n"
	.string "아무거나 좋으니까 들려줘!$"
	@ わあ!ｎ
	@ ありがとう!ｐ
	@ じゃあ §いの はなしｎ
	@ なんでも いいので きかせてよ!

SlateportCity_PokemonFanClub_Text_1A8818:: @ 81A8818
	.string "헤에-...\n"
	.string "재밌는 이야기였어!\p"
	.string "넌 정말로 {STR_VAR_1}{K_WAGWA}\n"
	.string "사이가 좋구나\p"
	.string "으-음 왠지 이 이야기로\n"
	.string "좋은 방송이 만들어질 것 같아!\p"
	.string "분명 재미있는 방송이\n"
	.string "될 테니까 기대하고 있어줘\p"
	.string "그럼 고마웠어\n"
	.string "바이바이!$"
	@ へ-……ｎ
	@ おもしろい はなし だね!ｐ
	@ きみは ほんとうに §いとｎ
	@ なかが いいんだねｐ
	@ う-ん なんか このはなしでｎ
	@ いい ばんぐみが できそうな よかん!ｐ
	@ きっと おもしろい ばんぐみにｎ
	@ するから たのしみに まっててねｐ
	@ じゃあ ありがとうねｎ
	@ バイバイ!

gTVFanClubOpinionsText1:: @ 81A8917
	.string "“우리들!\n"
	.string "포켓몬 애호가클럽!”\p"
	.string "네 시작했습니다!\p"
	.string "이 방송은 여러분의\n"
	.string "의견을 바로 제가\l"
	.string "대신 외쳐드리는!\l"
	.string "굉장한 방송이죠!!\p"
	.string "자 오늘은 포켓몬 애호가클럽에\n"
	.string "가서 여러 이야기를 들어본\l"
	.string "리포터로부터 들어온 정보입니다!\p"
	.string "자 그럼 오늘의\n"
	.string "포켓몬 애호가는?\p"
	.string "음-...\p"
	.string "{STR_VAR_1}씨다-!!\p"
	.string "그럼 자신의 포켓몬\p"
	.string "{STR_VAR_2} “{STR_VAR_3}”에\n"
	.string "대한 뜨거운 기분을\p"
	.string "바로 제가 대신 TV를\n"
	.string "통해 외쳐드리겠습니다!\p"
	.string "우-!!\p"
	.string "렛츠 샤우트!!!$"
	@ 『ぼくたち!ｎ
	@ ポケモン だいすきクラブ!』ｐ
	@ はい はじまりました!ｐ
	@ このばんぐみは みなさんのｎ
	@ いけんを このわたしがｌ
	@ かわりに さけんで しまおう!ｌ
	@ という すごい ばんぐみ!!ｐ
	@ さて きょうは ポケモンだいすきクラブ にｎ
	@ いって いろんな はなしを きいてきたｌ
	@ リポ-タ-からの じょうほうだ!ｐ
	@ さて きょうのｎ
	@ ポケモンだいすき にんげんは?ｐ
	@ ん-……ｐ
	@ §いさんだ-!!ｐ
	@ それでは ごじぶんの ポケモンｐ
	@ §うの 「§え」にｎ
	@ ついての あつい きもちをｐ
	@ かわりに この わたくしが テレビにｎ
	@ むかって さけんで あげましょう!ｐ
	@ う-!!ｐ
	@ レッツ シャウト!!!

gTVFanClubOpinionsText2:: @ 81A8AE5
	.string "자 그럼 {STR_VAR_1}씨가 처음으로\n"
	.string "{STR_VAR_2}{K_WAGWA} 만났을 때 직관적으로\l"
	.string "생각한 것은...\l"
	.string "......\p"
	.string "“{STR_VAR_3}!!”\p"
	.string "음- 좋은 외침입니다!\p"
	.string "마치 그때의 추억이\n"
	.string "되살아나는 듯하군요-!!$"
	@ さて §いさんが はじめてｎ
	@ §うと あったとき ちょっかんてきにｌ
	@ おもった ことは……ｌ
	@ ……ｐ
	@ 「§え!!」ｐ
	@ ん- いい さけびだ!ｐ
	@ まるで そのときの おもいでがｎ
	@ よみがえる ようだ-!!

gTVFanClubOpinionsText3:: @ 81A8B9D
	.string "자 그럼 {STR_VAR_1}씨가 매우 좋아하는\n"
	.string "{STR_VAR_2}{K_EULREUL} 뭔가에 비유한다면\l"
	.string "......\p"
	.string "“{STR_VAR_3}!!”\p"
	.string "음- 굉장한 발상이군요!!\p"
	.string "격렬한 {STR_VAR_2}{K_EULREUL} 향한 생각이\n"
	.string "느껴지네요-!$"
	@ さて §いさんの だいすきなｎ
	@ §うを なにかに たとえると したらｌ
	@ ……ｐ
	@ 「§え!!」ｐ
	@ ん- すごい はっそうだ!!ｐ
	@ はげしい §うへの おもいこみがｎ
	@ かんじられるね-!

gTVFanClubOpinionsText4:: @ 81A8C77
	.string "자 그럼 {STR_VAR_1}씨가 {STR_VAR_2}에게\n"
	.string "이끌린 이유는...\l"
	.string "......\p"
	.string "“{STR_VAR_3}!!”\p"
	.string "오-!! 엄청난 의견이군요-!\p"
	.string "{STR_VAR_2}{K_EULREUL} 얼마나 좋아하는지\n"
	.string "팍팍 전해져 옵니다-!$"
	@ さて §いさんが §うにｎ
	@ ひかれた りゆうは……ｌ
	@ ……ｐ
	@ 「§え!!」ｐ
	@ お-!! すんばらしい いけんだ-!ｐ
	@ §うを どんなに すきかｎ
	@ ビンビン つたわって くるね-!

gTVFanClubOpinionsText5:: @ 81A8D45
	.string "음-? 아직 더 남아있네요-\n"
	.string "불러봅시다!\p"
	.string "으-음...\p"
	.string "{STR_VAR_1}씨에게 있어 포켓몬을\n"
	.string "한마디로 비유하자면 그것은!\l"
	.string "......\p"
	.string "“{STR_VAR_3}!!”\p"
	.string "브라보!!\p"
	.string "몇 번이고 외치고 싶어지는 말이군요-!\p"
	.string "그럼 좋은 외침도 들었으니\n"
	.string "다음에 또 봅시다!\p"
	.string "마지막으로 한 번 더\n"
	.string "다 같이 외쳐보죠!\p"
	.string "“{STR_VAR_3}!!”$"
	@ ん-? まだ つづきが ありますね-ｎ
	@ よんで みましょう!ｐ
	@ え-と……ｐ
	@ §いさんに とって ポケモンをｎ
	@ ひとことで たとえると すれば それは!ｌ
	@ ……ｐ
	@ 「§え!!」ｐ
	@ ブラボ-!!ｐ
	@ いままでの なかで いちばんｎ
	@ いい さけび だった-!ｐ
	@ 「§え!!」ｐ
	@ なんども さけびたくなる ことばだね-!ｐ
	@ それでは いいさけびと であった ところでｎ
	@ また じかい おあいしましょう!ｐ
	@ さいごに もういちどｎ
	@ みんなで さけびましょう!ｐ
	@ 「§え!!」

gTVFanClubText1:: @ 81A8EC9
	.string "“우리들!\n"
	.string "포켓몬 애호가클럽!”\p"
	.string "네 시작했습니다!\p"
	.string "그럼 오늘은\n"
	.string "포켓몬 설문 코너!\p"
	.string "수많은 포켓몬과 트레이너의\n"
	.string "사연 중에서\p"
	.string "오늘은 어떤 이야기가\n"
	.string "튀어나올까요!?\l"
	.string "자 그럼 오늘의 사연은?\p"
	.string "음-...\p"
	.string "이거다!\p"
	.string "그럼 편지의 내용을 소개하겠습니다!!\n"
	.string "{STR_VAR_2}에게 보내는\n"
	.string "{STR_VAR_1}씨의 편지네요-\p"
	.string "그럼 얼마나 {STR_VAR_2}{K_EULREUL} 향한\n"
	.string "뜨거운 마음이 담겨있는지\l"
	.string "읽어보도록 합시다!\l"
	.string "음 그럼-...$"
	@ 『ぼくたち!ｎ
	@ ポケモン だいすきクラブ!』ｐ
	@ はい はじまりました!ｐ
	@ じゃあ きょうは ポケモンアンケ-トのｎ
	@ コ-ナ-から!ｐ
	@ かずある ポケモンと トレ-ナ-のｎ
	@ はなしの なかからｐ
	@ きょうは どんな はなしがｎ
	@ とびだして くるのでしょうか!?ｌ
	@ さて きょうの はなしは?ｐ
	@ ん-……ｐ
	@ これだ!ｐ
	@ では てがみの しょうかい から!!ｐ
	@ §うの ことに ついてｎ
	@ §いさん からの おてがみだ-ｐ
	@ では どれだけ §うへのｎ
	@ あつい いけんが かいてあるかｌ
	@ よませて もらいましょう!ｌ
	@ え-と……

gTVFanClubText2:: @ 81A9048
	.string "오-!!\n"
	.string "정말 굉장한 편지네요!!$"
	@ お-!!ｎ
	@ なんて すばらしい てがみなんだ!!

gTVFanClubText3:: @ 81A9067
	.string "마음에 들었으니 다시 한 번!$"
	@ きにいったから もういちど!

gTVFanClubText4:: @ 81A9088
	.string "좋은 편지는\n"
	.string "몇 번이고 읽어도 좋네요-!!$"
	@ いい てがみはｎ
	@ なんど きいても いいね-!!

gTVFanClubText5:: @ 81A90B4
	.string "“{STR_VAR_3}”{K_I}라는 말\n"
	.string "덕분에 두근 하고 마음에 전해지는\l"
	.string "좋은 편지군요-!!$"
	@ 「§え」 っていう ことばのｎ
	@ おかげで グッと こころに つたわってくるｌ
	@ いい てがみに なっているね-!!

gTVFanClubText6:: @ 81A911F
	.string "특히 “{STR_VAR_3}” 여기 이 부분!\p"
	.string "“{STR_VAR_3}”{K_I}라고 하는 부분이\n"
	.string "마음에 든다구요-!$"
	@ とくに「§え」って ところ!ｐ
	@ 「§え」っていう ところがｎ
	@ きにいったぞ-!

gTVFanClubText7:: @ 81A9152
	.string "그런데 딱히 상관은 없지만\n"
	.string "“{STR_VAR_3}”{K_EUNNEUN} 참 좋은 말이죠\p"
	.string "실은 저도 “{STR_VAR_3}”{K_I}라고\n"
	.string "자주 말하고 다니거든요$"
	@ ところで あんまり かんけい ないけどｎ
	@ 「§え」って いいことば だよねｐ
	@ じつは おれも 「§え」ってｎ
	@ ことば さいきん よく つかうんだよね

gTVFanClubText8:: @ 81A91C6
	.string "이 편지 저는\n"
	.string "{STR_VAR_3}점을 주고 싶네요-!\p"
	.string "다음은 좀 더 좋은 편지를\n"
	.string "기대하고 있을게요! {STR_VAR_1}씨!\p"
	.string "어이쿠 이제 시간이 다 됐군요!\n"
	.string "그럼 또 모두\l"
	.string "다음 방송에서 봅시다!!$"
	@ このてがみ じぶんてきにはｎ
	@ §えてん ていう かんじかな-!ｐ
	@ つぎは もっと いい てがみをｎ
	@ きたい してるよ! §いさん!!ｐ
	@ おっと もう こんなじかんだ!ｎ
	@ それでは また じかいｌ
	@ みなさま おあい しましょう!!

SlateportCity_OceanicMuseum_1F_Text_1A927F:: @ 81A927F
	.string "으음?\n"
	.string "당신도 포켓몬을 좋아하시나요?\p"
	.string "전 방송국 사람인데\n"
	.string "최근 일어난\p"
	.string "트레이너와 포켓몬의 사건을\n"
	.string "들으면서 돌아다니고 있어요\p"
	.string "만약 괜찮다면 뭔가\n"
	.string "얘기를 들려주실 수 있나요?$"
	@ おや?ｎ
	@ あなたも ポケモンのことが おすきで?ｐ
	@ わたくし テレビきょくの ものでｎ
	@ さいきん おきたｐ
	@ トレ-ナ-と ポケモンの できごとをｎ
	@ きいて まわって いるのですｐ
	@ もし よければ なにかｎ
	@ はなしを きかせて くれませんかね?

SlateportCity_OceanicMuseum_1F_Text_1A934C:: @ 81A934C
	.string "지금 최근 일어난\n"
	.string "트레이너와 포켓몬의 사건을\l"
	.string "들으면서 돌아다니고 있는데\p"
	.string "만약 괜찮다면 뭔가\n"
	.string "얘기를 들려주실 수 있을까요?$"
	@ いま さいきん おきたｎ
	@ トレ-ナ-と ポケモンの できごとをｌ
	@ きいて まわって いるのですがｐ
	@ もし よければ なにかｎ
	@ はなしを きかせて くれませんかね?

SlateportCity_OceanicMuseum_1F_Text_1A93D1:: @ 81A93D1
	.string "오오 들려주시는 거군요!\n"
	.string "정말 감사합니다\p"
	.string "그럼 최근 일어난 거라면\n"
	.string "뭐든지 좋으니까\l"
	.string "이야기를 들려주세요!$"
	@ おお きかせて くれますか!ｎ
	@ ありがとう ございますｐ
	@ では さいきん おきたこと ならｎ
	@ なんでも よいのでｌ
	@ はなしを きかせて ください!

SlateportCity_OceanicMuseum_1F_Text_1A9446:: @ 81A9446
	.string "그렇습니까...\p"
	.string "그럼 또 뭔가 재밌는 이야기가\n"
	.string "있다면 들려주세요$"
	@ そうですか……ｐ
	@ では また なにか おもしろい はなしがｎ
	@ あったら きかせて くださいね

SlateportCity_OceanicMuseum_1F_Text_1A949A:: @ 81A949A
	.string "...오오\n"
	.string "정말 좋은 이야기네요!\p"
	.string "이 이야기는 TV 방송에서\n"
	.string "쓰도록 하겠습니다!\p"
	.string "언젠가 방송할지도 모르니\n"
	.string "기대하면서 기다리고 있어주세요$"
	@ ……おおｎ
	@ なんて いいはなしだ!ｐ
	@ このはなし テレビでｎ
	@ つかわせて いただきます!ｐ
	@ いつか ほうそう するかも しれないのでｎ
	@ たのしみに まっていて くださいね

SlateportCity_OceanicMuseum_1F_Text_1A952E:: @ 81A952E
	.string "으-음\n"
	.string "좋은 TV 방송이 만들어질 것 같네요!\p"
	.string "서둘러서 정리해야겠어요!$"
	@ う-んｎ
	@ いい テレビばんぐみが できそうだ!ｐ
	@ いそいで まとめないと!

gTVRecentHappeningsText1:: @ 81A9581
	.string "“최근의 사건”\p"
	.string "포켓몬 트레이너에겐\n"
	.string "매일이 하나의 이야기입니다\l"
	.string "그 이야기를 조금이라도\l"
	.string "소개할 수 있다면 좋겠지요\p"
	.string "자 그럼 오늘은 트레이너인\n"
	.string "{STR_VAR_1}씨의 이야기입니다\p"
	.string "{STR_VAR_1}씨 최근\n"
	.string "어떤 일이 있었던 걸까요?\l"
	.string "바로 봐보도록 합시다\p"
	.string "으-음...$"
	@ 『さいきんの できごと』ｐ
	@ ポケモントレ-ナ-に とってｎ
	@ まいにちが ものがたりですｌ
	@ その ものがたりを すこしでもｌ
	@ しょうかい できたら うれしいですねｐ
	@ さて きょうは トレ-ナ-のｎ
	@ §いさんの おはなしですｐ
	@ §いさん さいきんｎ
	@ どんなことが あったんで しょうか?ｌ
	@ さっそく みてみることに しましょうｐ
	@ え-と……

gTVRecentHappeningsText2:: @ 81A9694
	.string "과연 그렇군요 {STR_VAR_1}씨의\n"
	.string "주변에서 최근 일어나고 있는 일이\l"
	.string "손에 잡히듯이 알 것 같습니다$"
	@ なるほど §いさんのｎ
	@ まわりで さいきん おきている ことがｌ
	@ てに とるように わかりますね

gTVRecentHappeningsText3:: @ 81A971B
	.string "“{STR_VAR_3}”{K_I}라는 말이\n"
	.string "이야기에 재미를 더해주네요$"
	@ 「§え」という ことばがｎ
	@ おはなしに スト-リ-を かんじさせますね

gTVRecentHappeningsText4:: @ 81A974B
	.string "“{STR_VAR_3}”{K_I}라는 말\n"
	.string "덕분에 마치 광경이\l"
	.string "떠오르는 듯합니다$"
	@ 「§え」という ことばのｎ
	@ おかげで まるで じょうけいがｌ
	@ うかんで くるようですね

gTVRecentHappeningsText5:: @ 81A979F
	.string "이 이야기는 “{STR_VAR_3}”{K_I}라고 하는\n"
	.string "부분이 무척 인상적이었네요$"
	@ このおはなしは 「§え」というｎ
	@ ぶぶんが とても いんしょうてき ですね

gTVRecentHappeningsText6:: @ 81A97D0
	.string "{STR_VAR_1}씨는 정말 좋은\n"
	.string "이야기를 들려주셨습니다\p"
	.string "이걸로 당신의 마음에도\n"
	.string "{STR_VAR_1}씨라고 하는 스토리가\l"
	.string "새겨진 것이겠지요\p"
	.string "그러면 이만\n"
	.string "다음 방송에서 만납시다$"
	@ §いさんは とても いいｎ
	@ おはなしを きかせて くれましたねｐ
	@ これで あなたの こころにもｎ
	@ §いさん という スト-リ-がｌ
	@ きざみ こまれましたよｐ
	@ それでは また じかいのｎ
	@ ほうそうで おあいしましょう

gTVPokemonOutbreakText:: @ 81A986F
	.string "안녕하세요\n"
	.string "“포켓몬 뉴스”의 시간입니다\p"
	.string "보기 힘든 중요한 뉴스가\n"
	.string "들어왔습니다\p"
	.string "{STR_VAR_1}에서\n"
	.string "{STR_VAR_2}{K_IGA} 대량발생했다는\l"
	.string "보고가 있었습니다!\p"
	.string "{STR_VAR_2}{K_I}라고 하면\n"
	.string "제법 발견하기가 힘든\l"
	.string "포켓몬으로 유명했지요\p"
	.string "당신도 이 신비한\n"
	.string "{STR_VAR_2}의 대량발생을\l"
	.string "보고 오는 게 어떻겠습니까?\p"
	.string "이상으로\n"
	.string "“포켓몬 뉴스”였습니다$"
	@ こんにちはｎ
	@ 『ポケモン ニュ-ス』の じかんですｐ
	@ たいへん めずらしい ニュ-スがｎ
	@ はいって きましたｐ
	@ §いでｎ
	@ §うが たいりょうはっせい したｌ
	@ という ほうこくが ありました!ｐ
	@ §うと いえばｎ
	@ なかなか みつけることが むずかしいｌ
	@ ポケモンとしても ゆうめい ですねｐ
	@ あなたも このしんぴてきなｎ
	@ §うの たいりょうはっせいをｌ
	@ みにいっては いかが でしょうか?ｐ
	@ いじょうｎ
	@ 『ポケモン ニュ-ス』でした

gTVNameRaterText1:: @ 81A99D9
	.string "“이름 평가”의\n"
	.string "시간이 돌아왔습니다\p"
	.string "당신이 붙인 닉네임에서\n"
	.string "포켓몬의 미래를\l"
	.string "점쳐 드립니다\p"
	.string "조금이라도 어드바이스가\n"
	.string "된다면 좋을 것 같군요\p"
	.string "오늘은 {STR_VAR_1}씨의 포켓몬\n"
	.string "{STR_VAR_2} “{STR_VAR_3}”의\l"
	.string "닉네임을 점쳐 보겠습니다\p"
	.string "흐음흐음...\p"
	.string "흐-음\n"
	.string "이 닉네임은...$"
	@ 『せいめい はんだん』のｎ
	@ じかんが やって まいりましたｐ
	@ あなたの つけた ニックネ-ムからｎ
	@ ポケモンの ことをｌ
	@ うらなって さしあげますｐ
	@ すこしでも アドバイスにｎ
	@ なれば よいと おもいますなｐ
	@ きょうは §いさんの ポケモンｎ
	@ §うの 「§え」のｌ
	@ ニックネ-ムを うらなって みますかなｐ
	@ ふむふむ……ｐ
	@ う-む ｎ
	@ この ニックネ-ムは……

gTVNameRaterText2:: @ 81A9AF0
	.string "여러 가지 분야에서 재능을\n"
	.string "발휘할 수 있는 닉네임이군요!\p"
	.string "앞으로 여러 일에\n"
	.string "도전하면 좋을 거라고 생각합니다$"
	@ いろいろな ところで さいのうをｎ
	@ はっき できる ニックネ-ム ですなぁ!ｐ
	@ こんご いろいろな ことにｎ
	@ チャレンジ すると よいと おもいますよ

gTVNameRaterText3:: @ 81A9B69
	.string "{STR_VAR_1}씨와의 궁합이\n"
	.string "무척 좋은 닉네임이군요!\p"
	.string "서로 잘 맞는\n"
	.string "좋은 콤비가 될 거라고 생각합니다$"
	@ §いさん との あいしょうがｎ
	@ とても よい ニックネ-ム ですなぁ!ｐ
	@ いきの ぴったり あったｎ
	@ よい コンビに なると おもいますよ

gTVNameRaterText4:: @ 81A9BEF
	.string "무척 개성적인 포켓몬이\n"
	.string "되는 닉네임이군요!\p"
	.string "제대로 키운다면 그 개성이\n"
	.string "커다란 꽃을 피울 거라고 생각합니다$"
	@ とても こせいてきな ポケモンにｎ
	@ なる ニックネ-ム ですなぁ!ｐ
	@ きちんと そだてて やれば その こせいがｎ
	@ おおきく はな ひらくと おもいますよ

gTVNameRaterText5:: @ 81A9C6A
	.string "무척 배려심 있는\n"
	.string "포켓몬이 되는 닉네임이군요!\p"
	.string "제대로 키운다면\n"
	.string "그에 응해줄 거라고 생각합니다$"
	@ とても おもいやりの あるｎ
	@ ポケモンに なる ニックネ-ム ですなぁ!ｐ
	@ きちんと そだてて やればｎ
	@ それに こたえて くれると おもいますよ

gTVNameRaterText6:: @ 81A9CF8
	.string "장래에 거물이 되는\n"
	.string "무척 좋은 닉네임이군요!\p"
	.string "장래가 매우\n"
	.string "기대가 되는 포켓몬입니다$"
	@ しょうらい おおものに なるｎ
	@ とても よい ニックネ-ム ですなぁ!ｐ
	@ しょうらいが とてもｎ
	@ たのしみな ポケモン ですな

gTVNameRaterText7:: @ 81A9D74
	.string "무척 건강한 포켓몬이\n"
	.string "되는 닉네임이군요!\p"
	.string "언제나 건강하게\n"
	.string "있어줄 겁니다$"
	@ とても けんこうてきな ポケモンにｎ
	@ なる よい ニックネ-ム ですなぁ!ｐ
	@ いつまでも げんきでｎ
	@ いて くれる でしょう

gTVNameRaterText8:: @ 81A9DF3
	.string "무척 활동적인 포켓몬이\n"
	.string "되는 좋은 닉네임이군요!\p"
	.string "포켓몬 승부에서\n"
	.string "큰 활약을 할 거라고 생각합니다$"
	@ とても かつどうてきな ポケモンにｎ
	@ なる よい ニックネ-ム ですなぁ!ｐ
	@ ポケモンしょうぶ ではｎ
	@ おおいに かつやく すると おもいますよ

gTVNameRaterText9:: @ 81A9E75
	.string "무척 애교가 많은\n"
	.string "포켓몬이 되는 닉네임이군요!\p"
	.string "포켓몬 콘테스트에서\n"
	.string "매우 큰 활약을 할 거라고 생각합니다$"
	@ とても あいきょうの あるｎ
	@ ポケモンになる ニックネ-ム ですなぁ!ｐ
	@ ポケモンコンテスト ではｎ
	@ とても かつやく できると おもいますよ

gTVNameRaterText10:: @ 81A9F06
	.string "이 “{STR_VAR_1}”{K_I}라는 닉네임은\n"
	.string "“{STR_VAR_3}” 문자를 중심으로\l"
	.string "여기에 “{STR_VAR_2}”{K_IGA} 붙어서\p"
	.string "묵직한 느낌을 주는\n"
	.string "좋은 닉네임이 되었군요$"
	@ この 「§い」という ニックネ-ムはｎ
	@ 「§え」の もじを ちゅうしん としてｌ
	@ これに 「§う」が つくことでｐ
	@ どっしり としたｎ
	@ よい ニックネ-ムに なっていますな

gTVNameRaterText11:: @ 81A9F9F
	.string "이 “{STR_VAR_1}”{K_I}라는 닉네임은\n"
	.string "매우 형태가 좋은\l"
	.string "닉네임이군요\p"
	.string "닉네임에 “{STR_VAR_2}”{K_WAGWA} “{STR_VAR_3}”{K_IGA}\n"
	.string "들어가 있는 게 아주 좋습니다!$"
	@ この 「§い」という ニックネ-ムはｎ
	@ とても かたちの よいｌ
	@ ニックネ-ム ですなぁｐ
	@ ニックネ-ムに 「§う」と 「§え」がｎ
	@ はいって いるのが とても よい!

gTVNameRaterText12:: @ 81AA01E
	.string "이 “{STR_VAR_1}”{K_I}라는 닉네임은\n"
	.string "무척 울림이 좋은\l"
	.string "닉네임이군요\p"
	.string "“{STR_VAR_2}”{K_I}라는 문자 뒤에\n"
	.string "“{STR_VAR_3}”{K_IGA} 오는 게 아주 좋습니다!$"
	@ この 「§い」という ニックネ-ムはｎ
	@ とても ながれの よいｌ
	@ ニックネ-ム ですなぁｐ
	@ 「§う」の もじの あとにｎ
	@ 「§え」がくる ながれが とても よい!

gTVNameRaterText13:: @ 81AA09D
	.string "...자 그럼 그 밖에\n"
	.string "좋은 닉네임의 예시로서$"
	@ ……さて そのほかにｎ
	@ よい ニックネ-ムの れい として

gTVNameRaterText14:: @ 81AA0D7
	.string "트레이너 {STR_VAR_1}씨의\n"
	.string "이름을 따서\p"
	.string "“{STR_VAR_2}{STR_VAR_3}”{K_I}라고 하는 것도\l"
	.string "무척 좋은 닉네임이 되겠군요$"
	@ トレ-ナ-の §いさんのｎ
	@ なまえを もってきてｐ
	@ 「§う§え」と いうのもｎ
	@ とても よい ニックネ-ム ですなぁ

gTVNameRaterText15:: @ 81AA138
	.string "아니면 “{STR_VAR_2}{STR_VAR_3}”도\n"
	.string "좋은 닉네임이 될 테고요$"
	@ もしくは 「§う§え」とｎ
	@ いうのも よい ニックネ-ム ですな

gTVNameRaterText16:: @ 81AA166
	.string "원래 포켓몬의 이름인\n"
	.string "{STR_VAR_2}에서 살짝 따와서\l"
	.string "{STR_VAR_1}{STR_VAR_3}{K_I}나$"
	@ もとの ポケモンの なまえｎ
	@ §うから すこし もらってｐ
	@ 「§い§え」や

gTVNameRaterText17:: @ 81AA1C0
	.string "“{STR_VAR_1}{STR_VAR_3}”도\n"
	.string "좋은 닉네임이 되겠군요$"
	@ 「§い§え」と いうのもｎ
	@ よい ニックネ-ム ですなぁ

gTVNameRaterText18:: @ 81AA1EA
	.string "무슨 일이 있어도 다른 포켓몬의 이름\n"
	.string "예를 들어 {STR_VAR_2}의 이름을 붙여\p"
	.string "“{STR_VAR_1}{STR_VAR_3}” 같은\n"
	.string "닉네임으로 지으면 안 됩니다$"
	@ まちがっても ほかの ポケモンの なまえｎ
	@ たとえば §うの なまえを つけてｐ
	@ 「§い§え」の ようなｎ
	@ ニックネ-ムに しては いけませんな

gTVNameRaterText19:: @ 81AA28A
	.string "으음 그건 그렇고 {STR_VAR_1}{K_EUNNEUN}\n"
	.string "제법 좋은 닉네임이군요\p"
	.string "앞으로도 “{STR_VAR_1}”{K_EULREUL}\n"
	.string "소중하게 여겨주십시오\p"
	.string "그럼 인연이 있으면\n"
	.string "또 보지요$"
	@ うむ それにしても 「§い」はｎ
	@ なかなか よい ニックネ-ム ですなｐ
	@ これからも 「§い」の ことをｎ
	@ たいせつに して ほしい ものですなぁｐ
	@ それでは またｎ
	@ ごえんが あれば

gTVFishingGuruAdviceText1:: @ 81AA344
	.string "“{STR_VAR_2}{K_EULREUL} 낚다”\p"
	.string "아나운서: 안녕하세요! 오늘은\n"
	.string "{STR_VAR_2} 낚시를 배우러 왔습니다\p"
	.string "그럼 선생님 {STR_VAR_2}{K_EULREUL} 낚는 데\n"
	.string "필요한 요령이 있나요?\p"
	.string "선생님: 음?\n"
	.string "{STR_VAR_2}{K_EULREUL} 낚는 요령 말인가\l"
	.string "그건 차분히 기다리는 것이라네\p"
	.string "저기 있는 {STR_VAR_1}씨를 보게나\n"
	.string "이 얼마나 훌륭한 모습인가?\p"
	.string "이미 이것도 저것도...\n"
	.string "{STR_VAR_3}번은 놓쳤지만\p"
	.string "포기하지 않고 계속 기다리고 있네\n"
	.string "저 모습이 {STR_VAR_2} 낚기의 극의인 게야\p"
	.string "아나운서: 그렇군요...\p"
	.string "아! {STR_VAR_1}씨\n"
	.string "드디어 {STR_VAR_2}{K_EULREUL} 낚았습니다!\l"
	.string "울 거 같은 표정으로 기뻐하고 있어요!\p"
	.string "...저도 저런 기뻐하는 듯한\n"
	.string "표정을 봤더니 낚시하고 싶어졌습니다!\p"
	.string "여러분들도 이 방송을 계기로\n"
	.string "{STR_VAR_2} 낚기를 해보면 어떨까요?\p"
	.string "그럼 또 다음\n"
	.string "방송에서 만납시다$"
	@ 『§うを つる』ｐ
	@ アナウンサ-「こんにちは! きょうはｎ
	@ §うつりを おそわりに きましたｐ
	@ さて せんせい §うを つるにはｎ
	@ どんな コツが いるのですか?ｐ
	@ せんせい「ん?ｎ
	@ §うを つる コツかいｌ
	@ それはね じ-っと まつことだねｐ
	@ ほら あそこにいる §いさんｎ
	@ なんて いい みほん じゃないか?ｐ
	@ もう かれこれ……ｎ
	@ §えかいは にげられて いるけどｐ
	@ あきらめず じ-っと まちつづけて いるよｎ
	@ あれが §うつりの ごくいだねｐ
	@ アナウンサ-「なるほど……ｐ
	@ あ! §いさんｎ
	@ やっと §うを つりました!ｌ
	@ なきそうな かおして よろこんで ますよ!ｐ
	@ …わたしも あんな うれしそうなｎ
	@ かおを みたら つりをしたく なりました!ｐ
	@ みなさんも これを きに §うつりをｎ
	@ してみては いかがですか?ｐ
	@ それでは また じかいのｎ
	@ ほうそうで あいましょう

gTVFishingGuruAdviceText2:: @ 81AA5F3
	.string "“{STR_VAR_2}{K_EULREUL} 낚다”\p"
	.string "인터뷰어: 안녕하세요! 오늘은\n"
	.string "{STR_VAR_2} 낚시를 배우러 왔습니다\p"
	.string "그럼 선생님 {STR_VAR_2}{K_EULREUL} 낚는 데\n"
	.string "필요한 요령이 있나요?\p"
	.string "선생님: 음?\n"
	.string "{STR_VAR_2}{K_EULREUL} 낚는 요령 말인가\l"
	.string "그건 낚싯대를 폭풍같이\l"
	.string "다루는 것이라네!\p"
	.string "자 저기 있는 {STR_VAR_1}씨의\n"
	.string "낚싯대 다루는 실력을 보게나!\p"
	.string "벌써 {STR_VAR_3}마리를 연속으로\n"
	.string "낚고 있다네!\p"
	.string "인터뷰어: 괴 굉장해요!\n"
	.string "그야말로 폭풍처럼...\p"
	.string "...저렇게 굉장한 기술을 봤더니\n"
	.string "저도 낚시하고 싶어졌습니다!\p"
	.string "여러분들도 이 방송을 계기로\n"
	.string "{STR_VAR_2} 낚기를 해보면 어떨까요?\p"
	.string "그럼 또 다음\n"
	.string "방송에서 만납시다$"
	@ 『§うを つる』ｐ
	@ インタビュア-『こんにちは! きょうはｎ
	@ §うつりを おそわりに きましたｐ
	@ さて せんせい §うを つるにはｎ
	@ どんな コツが いるのですか?ｐ
	@ せんせい『ん?ｎ
	@ §うを つる コツかいｌ
	@ それはね つりざおを あらしの ごとくｎ
	@ あつかう ことだね!ｐ
	@ ほら あそこにいる §いさんのｎ
	@ つりざお さばきを みてみなさい!ｐ
	@ もう §えひきは れんぞくでｎ
	@ つって いるぞ!ｐ
	@ インタビュア-『すっ すごい!ｎ
	@ まさに あらしの ようね……ｐ
	@ ……あんなに すごい わざを みたらｎ
	@ わたしも つりを したくなって きました!ｐ
	@ みなさんも これを きに §うつりをｎ
	@ してみては いかがですか?ｐ
	@ それでは また じかいのｎ
	@ ほうそうで あいましょう

gTVPokemonTodayFailedCaptureText1:: @ 81AA814
	.string "안녕-!\p"
	.string "“오늘의 포켓몬”의\n"
	.string "시간이야-!!\p"
	.string "누님: 안녕 다들 잘 지내지?\n"
	.string "오늘은 {STR_VAR_1}씨의 포켓몬\l"
	.string "{STR_VAR_2}{K_EULREUL} 소개할게!\p"
	.string "형님: 소개할게-!$"
	@ こんにちは-!ｐ
	@ 『きょうの ポケモン』のｎ
	@ じかんだよ-!!ｐ
	@ おねえさん『こんにちは みんな げんき!ｎ
	@ きょうは §いさんの ポケモンｌ
	@ §うの しょうかいを するよ!ｐ
	@ おにいさん『するぞ-!

gTVPokemonTodayFailedCaptureText2:: @ 81AA8C6
	.string "아!\n"
	.string "{STR_VAR_1}씨라면...\p"
	.string "누님 지난번에\n"
	.string "나 봐버렸다고!!\p"
	.string "누님: 봐버렸다니\n"
	.string "뭘 봐버렸는데?\p"
	.string "형님: 지난번에\n"
	.string "{STR_VAR_2}에 갔을 때\l"
	.string "{STR_VAR_1}씨를 봤거든\p"
	.string "마침 {STR_VAR_3}{K_EULREUL}\n"
	.string "잡는 중인 것 같았는데...$"
	@ あ!ｎ
	@ §いさん といえば……ｐ
	@ おねえさん このまえｎ
	@ ぼく みちゃった!!ｐ
	@ おねえさん『みちゃった って ｎ
	@ なにを みちゃったの?ｐ
	@ おにいさん『このまえｎ
	@ §うに でかけたときｌ
	@ §いさんを みかけたんだｐ
	@ ちょうど §えを つかまえてるｎ
	@ ところ だったん だけど……

gTVPokemonTodayFailedCaptureText3:: @ 81AA9B2
	.string "도중에 포켓몬이\n"
	.string "도망쳐버렸어!!\p"
	.string "몬스터볼을 {STR_VAR_2}개나 던졌는데도\n"
	.string "소용없었지...\p"
	.string "포켓몬이 도망쳤을 때\n"
	.string "{STR_VAR_1}씨가 지은 분한 표정은\l"
	.string "정말 엄청났어...$"
	@ とちゅうで ポケモンに ｎ
	@ にげられ ちゃったんだよ!!ｐ
	@ ボ-ルを §うこも なげたのにｎ
	@ ぜんぶ むだ……ｐ
	@ ポケモンに にげられた ときのｎ
	@ §いさんの くやしがった かおｌ
	@ すごかったなぁ……

gTVPokemonTodayFailedCaptureText4:: @ 81AAA5C
	.string "도중에 실수로 포켓몬을\n"
	.string "쓰러뜨리고 말았어!!\p"
	.string "몬스터볼을 {STR_VAR_2}개나 던졌는데도\n"
	.string "소용없었지...\p"
	.string "포켓몬을 쓰러뜨렸을 때의\n"
	.string "{STR_VAR_1}씨가 아연실색한 표정은\l"
	.string "정말 말할 수 없을 정도였지...$"
	@ とちゅうで まちがって ポケモンをｎ
	@ たおし ちゃったんだよ!!ｐ
	@ ボ-ルを §うこも なげたのにｎ
	@ ぜんぶ むだ……ｐ
	@ ポケモンを たおしちゃった ときのｎ
	@ §いさんの あぜんと した かおｌ
	@ なんとも いえなかったなぁ……

gTVPokemonTodayFailedCaptureText5:: @ 81AAB11
	.string "누님: 야야!\n"
	.string "남의 불행에 웃으면 안 되지\p"
	.string "아아 {STR_VAR_1}씨\n"
	.string "엄청 불쌍하다...\p"
	.string "형님: 그러게!\n"
	.string "웃어서 죄-송합니다$"
	@ おねえさん『こらこらっ!ｎ
	@ たにんの ふこうを わらっちゃ だめだよｐ
	@ あぁ §いさんｎ
	@ とっても かわいそう……ｐ
	@ おにいさん『は-い!ｎ
	@ わらって すいませ-ん

gTVPokemonTodayFailedCaptureText6:: @ 81AABB4
	.string "누님: 풉!\p"
	.string "형님: 아! 지금\n"
	.string "웃은 거지!?\p"
	.string "누님: 뭐!?\p"
	.string "안 웃었거든\n"
	.string "안 웃었어!\p"
	.string "아아 {STR_VAR_1}씨\n"
	.string "정말 불쌍하다...\p"
	.string "형님: ...$"
	@ おねえさん『プッ!ｐ
	@ おにいさん『あ! いまｎ
	@ わらったでしょ!?ｐ
	@ おねえさん『え!?ｐ
	@ わらってないｎ
	@ わらってないよ!ｐ
	@ あぁ §いさんｎ
	@ とっても かわいそう……ｐ
	@ おにいさん『……

gTVPokemonTodayFailedCaptureText7:: @ 81AAC47
	.string "누님: 그럼 분위기를 전환해서\n"
	.string "포켓몬을 소개...\p"
	.string "어?\n"
	.string "벌써 시간 다 됐어?\p"
	.string "나 참! 포켓몬을\n"
	.string "소개하지도 못했잖아!\p"
	.string "형님: 다음 시간에 또 보자고!\p"
	.string "누님: 멋대로 끝내지 마-!!$"
	@ おねえさん『じゃあ きを とりなおしてｎ
	@ ポケモンの しょうかいを……ｐ
	@ え?ｎ
	@ もう じかんが ない?ｐ
	@ もう! ポケモンの しょうかいがｎ
	@ できなかった じゃない!ｐ
	@ おにいさん『また じかい あおうぜ!ｐ
	@ おねえさん『かってに しめるな-!!

gTVPokemonTodayText1:: @ 81AAD23
	.string "안녕-!\p"
	.string "“오늘의 포켓몬”의\n"
	.string "시간이야-!!\p"
	.string "누님: 안녕 다들 잘 지내지?\n"
	.string "오늘은 {STR_VAR_1}씨의 포켓몬\l"
	.string "{STR_VAR_2}{K_EULREUL} 소개할게!\p"
	.string "형님: 소개할게-!$"
	@ こんにちは-!ｐ
	@ 『きょうの ポケモン』のｎ
	@ じかんだよ-!!ｐ
	@ おねえさん『こんにちは みんな げんき!ｎ
	@ きょうは §いさんの ポケモンｌ
	@ §うの しょうかいを するよ!ｐ
	@ おにいさん『するぞ-!

gTVPokemonTodayText2:: @ 81AADD5
	.string "누님: {STR_VAR_1}씨는\n"
	.string "{STR_VAR_2}에게 “{STR_VAR_3}”{K_I}라고\p"
	.string "닉네임을 붙여서 소중하게\n"
	.string "키우고 있대!$"
	@ おねえさん『§いさんはｎ
	@ §うに 「§え」ってｐ
	@ ニックネ-ムを つけて たいせつに ｎ
	@ そだてて るんだって!

gTVPokemonTodayText3:: @ 81AAE31
	.string "형님: 참고로\n"
	.string "몬스터볼을 총 {STR_VAR_3}개 던져서\p"
	.string "마지막에는 {STR_VAR_2}{K_EU}로\n"
	.string "잡았다는 소문도 있어!$"
	@ おにいさん『ちなみにｎ
	@ ボ-ルを ぜんぶで §えこ なげてｐ
	@ さいごは §うでｎ
	@ つかまえたって うわさだよ!

gTVPokemonTodayText4:: @ 81AAE9D
	.string "누님: 그렇게 간단하게\n"
	.string "포획하다니\p"
	.string "{STR_VAR_1}씨와 {STR_VAR_2}의\l"
	.string "만남은 분명 운명적이었을 거야!$"
	@ おねえさん『そんなに かんたんにｎ
	@ つかまえる なんてｐ
	@ §いさんと §うのｎ
	@ であいは きっと うんめい だったのよ!

gTVPokemonTodayText5:: @ 81AAF03
	.string "누님: 고생해서 겨우\n"
	.string "잡은 포켓몬은\l"
	.string "소중히 여기게 된다고도 하고!$"
	@ おねえさん『くろうして やっとｎ
	@ つかまえた ポケモンはｌ
	@ だいじに されるって いうしね!

gTVPokemonTodayText6:: @ 81AAF8A
	.string "누님: {STR_VAR_1}씨의\n"
	.string "{STR_VAR_2}{K_EUNNEUN} 소중한 마스터볼을\p"
	.string "써서 겨우 잡은\n"
	.string "추억의 포켓몬이래!\p"
	.string "형님: 오-! 굉장한걸-!\p"
	.string "누님: {STR_VAR_1}씨 정말로\n"
	.string "{STR_VAR_2}{K_EULREUL} 잡고 싶었구나!$"
	@ おねえさん『§いさんのｎ
	@ §うは だいじな マスタ-ボ-ルをｐ
	@ つかって やっと つかまえたｎ
	@ おもいでの ポケモン なんだって!ｐ
	@ おにいさん『え-! すごいね-!ｐ
	@ おねえさん『§いさん ほんとうにｎ
	@ §うを つかまえ たかったんだね!

gTVPokemonTodayText7:: @ 81AB040
	.string "형님: 그럼 그\n"
	.string "{STR_VAR_2}에게 “{STR_VAR_3}”{K_I}라는\p"
	.string "닉네임을 붙여준\n"
	.string "{STR_VAR_1}씨의 센스가 이해가 되네!\p"
	.string "누님: 그렇네-$"
	@ おにいさん『でも そのｎ
	@ §うに 「§え」ってｐ
	@ ニックネ-ムを つけるあたりｎ
	@ §いさんの センスが わかるね!ｐ
	@ おねえさん『そうだね-

gTVPokemonTodayText8:: @ 81AB0C8
	.string "나라면 {STR_VAR_3} 같은 거에\n"
	.string "그 닉네임을 짓겠지만!\p"
	.string "형님: 오-!\n"
	.string "그건 또 새로운걸!$"
	@ わたしなら §え とかにｎ
	@ そのニックネ-ムを つけちゃう けどね!ｐ
	@ おにいさん『お-!ｎ
	@ それ なかなか あたらしいかも!

gTVPokemonTodayText9:: @ 81AB13D
	.string "“{STR_VAR_2}”{K_I}라-\n"
	.string "정말 {STR_VAR_1}{K_I}라는 느낌이네!\p"
	.string "봐봐! 문자의 분위기가 왠지 모르게\n"
	.string "{STR_VAR_1} 같은 느낌이 나잖아!\p"
	.string "형님: ...그렇네$"
	@ 「§う」か-ｎ
	@ まさに §いって かんじよね!ｐ
	@ ほら! もじの ふんいきとか なんとなくｎ
	@ §いって かんじが するもの!ｐ
	@ おにいさん『……そうだね

gTVPokemonTodayText10:: @ 81AB1C6
	.string "내가 아는 한 {STR_VAR_1}에게\n"
	.string "“{STR_VAR_2}”{K_I}라는 닉네임을\l"
	.string "지은 트레이너는 없어!\p"
	.string "형님: 그만큼 닉네임을 짓는\n"
	.string "센스가 좋다는 거겠지!$"
	@ わたしの しってるかぎり §いにｎ
	@ 「§う」って ニックネ-ムをｌ
	@ つけている トレ-ナ-なんて いないよ!ｐ
	@ おにいさん『それだけ ニックネ-ムをつけるｎ
	@ センスが いいって ことだよ!

gTVPokemonTodayText11:: @ 81AB266
	.string "나도 다음에 포켓몬을 잡으면\n"
	.string "“{STR_VAR_2}”{K_I}라고 지어볼까?\p"
	.string "형님: 뭐? 그럼 나도\n"
	.string "“{STR_VAR_2}”{K_I}라고 지어야지-!$"
	@ わたしも こんど ポケモンを つかまえたらｎ
	@ 「§う」って つけて みようかな?ｐ
	@ おにいさん『え? じゃあ ぼくもｎ
	@ 「§う」って つけよ-!

gTVPokemonTodayText12:: @ 81AB2DB
	.string "누님: 아! 벌써 시간 다 됐네!\p"
	.string "그럼 또 다음\n"
	.string "방송에서 만나자\p"
	.string "형님: 다음엔 당신의 포켓몬을\n"
	.string "소개할지도 모른다고!$"
	@ おねえさん『あ! もう こんなじかん!ｐ
	@ それでは また じかいのｎ
	@ ほうそうで おあいしましょうｐ
	@ おにいさん『つぎは あなたの ポケモンをｎ
	@ しょうかい するかもよ!

gTVSmartShopperText1:: @ 81AB381
	.string "안녕하세요\p"
	.string "“오늘의 쇼핑 전문가”의\n"
	.string "시간입니다\p"
	.string "인터뷰어: 여러분 잘 지내셨나요?\p"
	.string "오늘은 {STR_VAR_2}의\n"
	.string "가게에 와 있습니다\p"
	.string "최근 무엇이 팔리고 있는지\n"
	.string "체크해 봅시다!$"
	@ こんにちはｐ
	@ 『きょうの かいもの じょうず』のｎ
	@ じかん ですｐ
	@ インタビュア-『みなさん おげんきですか?ｐ
	@ きょうは §うのｎ
	@ おみせに きていますｐ
	@ さいきん なにが うれているのかｎ
	@ チェック してみましょう!

gTVSmartShopperText2:: @ 81AB435
	.string "그럼 점원씨를\n"
	.string "인터뷰해 봅시다\l"
	.string "어떻습니까 장사는 잘 되시나요?\p"
	.string "점원: 네 덕분에요\p"
	.string "특히 {STR_VAR_2}{K_IGA}\n"
	.string "지금 잘 팔리고 있습니다\p"
	.string "지난번에도 {STR_VAR_1}씨라는 분이\n"
	.string "{STR_VAR_3}개나 사가셨지요$"
	@ それでは てんいんさんにｎ
	@ インタビュ- してみましょうｌ
	@ どうですか うれて いますか?ｐ
	@ てんいん『はい おかげさまでｐ
	@ とくに §うがｎ
	@ いま うれて いるんですよｐ
	@ このまえも §いさん というｎ
	@ かたが §えこも かって いかれました

gTVSmartShopperText3:: @ 81AB507
	.string "인터뷰어: {STR_VAR_2}{K_EULREUL}\n"
	.string "{STR_VAR_3}개나 사다니 굉장하군요!\p"
	.string "어쩌면 {STR_VAR_1}씨는\n"
	.string "앞으로 먼 곳까지 가기 위해서\l"
	.string "여행 준비를 했던 걸지도 모르겠네요\p"
	.string "역시 여행에는 {STR_VAR_2}{K_IGA} 최고죠!$"
	@ インタビュア-『§うをｎ
	@ §えこも かうなんて すごいですね!ｐ
	@ もしかしたら §いさんはｎ
	@ これから とおくまで いくためのｌ
	@ たびじたくを していたのかも しれませんねｐ
	@ やっぱり たびには §うですね!

gTVSmartShopperText4:: @ 81AB5B8
	.string "인터뷰어: {STR_VAR_2}{K_I}라고 하니\n"
	.string "저 어째선지 지난번에\l"
	.string "{STR_VAR_3}개나 사버렸어요!\p"
	.string "{STR_VAR_2}{K_EUNNEUN} 좋으니까요-!$"
	@ インタビュア-『§う といえばｎ
	@ わたし なんか このまえｌ
	@ §えこも かいましたよ!ｐ
	@ §うって いいですからね-!

gTVSmartShopperText5:: @ 81AB61F
	.string "인터뷰어: {STR_VAR_2}{K_EULREUL}!!\n"
	.string "{STR_VAR_3}개나요!?\p"
	.string "...그렇게 사는 사람이\n"
	.string "있다니 몰랐어요\p"
	.string "저는 한두 개 정도\n"
	.string "사는 게 다인데...$"
	@ インタビュア-『§うを!!ｎ
	@ §えこも!?ｐ
	@ ……そんなに かうひとがｎ
	@ いるなんて しらなかったわｐ
	@ わたし なんか せいぜい 1こか 2こしかｎ
	@ かわないから……

gTVSmartShopperText6:: @ 81AB6B0
	.string "인터뷰어: 저도 옛날에\n"
	.string "{STR_VAR_2}{K_EULREUL} 잔뜩 샀던 적이\l"
	.string "있었지만\p"
	.string "나중에 너무 남아서\n"
	.string "후회했던 적이 있어요...\p"
	.string "그 이후로는 딱\n"
	.string "필요한 양만큼만 사고 있죠...\p"
	.string "아차!\p"
	.string "제 얘기를 할 때가\n"
	.string "아닌데 말이죠!$"
	@ インタビュア-『わたしも むかしｎ
	@ §うを たくさん かったことがｌ
	@ あったん ですけどｐ
	@ あまって しまってｎ
	@ こうかい したわ……ｐ
	@ それからと いうもの ひつようなｎ
	@ ぶんだけ かうように してるの……ｐ
	@ おっと!ｐ
	@ わたしの ことを はなしてもｎ
	@ しょうがない ですね!

gTVSmartShopperText7:: @ 81AB78D
	.string "점원: {STR_VAR_1}씨는 그 외에도\n"
	.string "{STR_VAR_2} {STR_VAR_3}개를\l"
	.string "한꺼번에 사가셨습니다\p"
	.string "인터뷰어: 오- {STR_VAR_2}도\n"
	.string "제법 좋은 물건이죠!$"
	@ てんいん『§いさんは そのほかにもｎ
	@ §うを §えこｌ
	@ まとめて かわれましたよｐ
	@ インタビュア-『お- §うもｎ
	@ なかなか よい ですもんね!

gTVSmartShopperText8:: @ 81AB7FE
	.string "점원: 참고로 {STR_VAR_2}도\n"
	.string "{STR_VAR_3}개 사갔어요$"
	@ てんいん『ついでに §うもｎ
	@ §えこ かわれて いきました

gTVSmartShopperText9:: @ 81AB835
	.string "점원: 심지어 할인하고 있을 때였으니까\n"
	.string "역시 굉장하죠!$"
	@ てんいん『しかも おおやすうりの ときｎ
	@ ですから さすが ですよね!

gTVSmartShopperText10:: @ 81AB873
	.string "인터뷰어: 으-음...\n"
	.string "{STR_VAR_1}씨는 꽤나\l"
	.string "알뜰하게 사는 타입일지도 모르겠네요!\p"
	.string "이걸로 합계는...\p"
	.string "{STR_VAR_2}원!?\n"
	.string "정말 엄청나네요!\p"
	.string "어이쿠 그럼 또 다음\n"
	.string "방송에서 만나요!$"
	@ インタビュア-『う-ん……ｎ
	@ §いさんって かなりのｌ
	@ かいものじょうず なのかも しれませんね!ｐ
	@ これで ごうけいは……ｐ
	@ §うえん!?ｎ
	@ さすが ですね!ｐ
	@ おっと それでは またじかいのｎ
	@ ほうそうで おあい しましょう!

gTVSmartShopperText11:: @ 81AB92E
	.string "점원: {STR_VAR_1}씨는 정말로\n"
	.string "소중한 고객님이라구요$"
	@ てんいん『§いさんは ほんとうにｎ
	@ だいじな おきゃくさま ですよ

gTVSmartShopperText12:: @ 81AB95E
	.string "그럼 점원씨를\n"
	.string "인터뷰해 봅시다\l"
	.string "어떻습니까 장사는 잘 되시나요?\p"
	.string "점원: 네 덕분에요\n"
	.string "너무 잘돼서 곤란할 정도라구요!\p"
	.string "지난번에 {STR_VAR_1}씨라는 분이\n"
	.string "{STR_VAR_2}{K_EULREUL} 잔뜩 사가셔서\p"
	.string "가게 안에 {STR_VAR_2}{K_IGA}\n"
	.string "없어질 뻔했다니까요!\p"
	.string "저도 {STR_VAR_2}{K_EULREUL} 그렇게\n"
	.string "많이 사는 고객님이 계실 줄은\l"
	.string "꿈에도 상상 못 했습니다!\p"
	.string "인터뷰어: 그러면...\n"
	.string "100개나 200개 정도를 사가신 건가요?\p"
	.string "점원: 아뇨 더 많았습니다!\p"
	.string "인터뷰어: 우와-!\n"
	.string "{STR_VAR_1}씨는 굉장하네요!\p"
	.string "점원: {STR_VAR_1}씨는 정말로\n"
	.string "소중한 고객님이라구요$"
	@ それでは てんいんさんにｎ
	@ インタビュ- して みましょうｌ
	@ どうですか うれて ますか?ｐ
	@ てんいん『はい おかげさまでｎ
	@ うれてうれて こまって ますよ!ｐ
	@ このまえ §いさん というかたがｎ
	@ §うを たくさん かわれましてｐ
	@ みせのなかに §うがｎ
	@ なくなって しまいそう だったんですよ!ｐ
	@ わたくしも §うを そんなにｎ
	@ かう おきゃくさまが いるなんてｌ
	@ ゆめにも おもいません でした からね!ｐ
	@ インタビュア-『と いうことは……ｎ
	@ 100こ とか 200こ とか ですか?ｐ
	@ てんいん『いや もっと でしたよ!ｐ
	@ インタビュア-『うひゃ-!ｎ
	@ §いさんって すごい ですね!ｐ
	@ てんいん『§いさんは ほんとうにｎ
	@ だいじな おきゃくさま ですよ

gTVSmartShopperText13:: @ 81ABB75
	.string "인터뷰어: 으-음 굉장하네요\p"
	.string "근데 왜 그렇게\n"
	.string "많이 사간 걸까요?\p"
	.string "...\p"
	.string "수수께끼는 깊어져만 가지만\n"
	.string "시간이 다 된 듯하니\l"
	.string "또 다음 방송에서 만나요!\p"
	.string "그건 그렇고\n"
	.string "{STR_VAR_1}씨는 정말 신기하군요...$"
	@ インタビュア-『う-ん すごい ですねｐ
	@ でも なんで そんなにｎ
	@ いっぱい かったので しょう?ｐ
	@ ……ｐ
	@ なぞは ふかまる ばかりですがｎ
	@ じかんの ようなのでｌ
	@ またじかい おあい しましょう!ｐ
	@ それに してもｎ
	@ §いさんって なぞだわ……

gTVWorldOfMastersText1:: @ 81ABC51
	.string "“명인의 세계”\p"
	.string "여러분 안녕하십니까\p"
	.string "여러분은 {STR_VAR_1}씨라는\n"
	.string "트레이너를 알고 계신가요?\p"
	.string "{STR_VAR_1}씨는 포켓몬 잡기의\n"
	.string "명인으로 유명하답니다\p"
	.string "{STR_VAR_1}씨의 포켓몬 찾기는\n"
	.string "돌아다니는 것에서부터 시작됩니다\p"
	.string "저번에는 포켓몬을 찾기 위해서\n"
	.string "하루에 {STR_VAR_2}걸음 이상을 걸었고\p"
	.string "잡은 포켓몬의 수는\n"
	.string "무려 {STR_VAR_3}마리라고 하더군요!$"
	@ 『めいじんの せかい』ｐ
	@ みなさん こんにちはｐ
	@ みなさんは §いさん というｎ
	@ トレ-ナ-を しってますか?ｐ
	@ §いさんは ポケモンを つかまえるｎ
	@ めいじん として ゆうめい なんですｐ
	@ §いさんの ポケモンさがしはｎ
	@ あるきまわる ところから はじまりますｐ
	@ このまえは ポケモンを さがすためにｎ
	@ 1にちで §うほ いじょうも あるきｐ
	@ つかまえた ポケモンの かずはｎ
	@ なんと §え ひきにも なったとか!

gTVWorldOfMastersText2:: @ 81ABD94
	.string "분명 파트너인 {STR_VAR_1}{K_WAGWA}\n"
	.string "서로 신뢰하고 있기에\l"
	.string "이런 대단한 일이 가능한 거겠죠$"
	@ きっと あいぼうの §いとｎ
	@ しんらい しあっている からこそｌ
	@ こんな すごいことが できるんですね

gTVWorldOfMastersText3:: @ 81ABDF2
	.string "명인은 마지막에\n"
	.string "{STR_VAR_2}{K_EU}로 {STR_VAR_3}{K_EULREUL} 잡아서\p"
	.string "기념비적인 포켓몬으로 소중히\n"
	.string "키우고 있는 모양입니다\p"
	.string "자신 있는 트레이너는 이 기록에\n"
	.string "도전해 보는 게 어떨까요?\p"
	.string "그럼 또\n"
	.string "다음에 만납시다$"
	@ めいじんは さいごにｎ
	@ §うで §えを つかまえｐ
	@ きねんの ポケモンとして だいじにｎ
	@ している らしいですよｐ
	@ じしんのある トレ-ナ-は このきろくにｎ
	@ ちょうせんして みては いかがですか?ｐ
	@ それでは またｎ
	@ じかい おあいしましょう

	.include "data/text/gabby_and_ty.inc"
	.include "data/text/pokemon_news.inc"
