AbandonedShip_CaptainsOffice_Text_198C85:: @ 8198C85
	.string "해양관장님에게 부탁받아서\n"
	.string "이 배를 조사하고 있었어\p"
	.string "하는 김에 탐지기를 찾아 달라고\n"
	.string "하시긴 했는데\l"
	.string "찾을 수가 없었어...$"
	@ クスノキ かんちょうに たのまれてねｎ
	@ このふねの ちょうさを しているんだｐ
	@ ついでに たんちきを さがしてきて ｎ
	@ ほしいって いわれたんだけどｌ
	@ みあたらないなあ……

AbandonedShip_CaptainsOffice_Text_198D00:: @ 8198D00
	.string "앗! 탐지기잖아!\p"
	.string "...괜찮으면 그거\n"
	.string "해양관장님에게\l"
	.string "전해 주지 않을래?\p"
	.string "난 좀 더 여기를 조사하려고$"
	@ あ! たんちき じゃないか!ｐ
	@ ……よかったら それｎ
	@ クスノキ かんちょうにｌ
	@ わたしてきて くれないかなあｐ
	@ もうすこし このふね しらべたいんだ

AbandonedShip_CaptainsOffice_Text_198D7B:: @ 8198D7B
	.string "이 배는 캑터스호라고 불리고 있어\n"
	.string "조금 오래된 배인 것 같아$"
	@ この ふねは カクタスごうと いってねｎ
	@ ちょいと むかしの ふね らしいんだ
