Route110_TrickHousePuzzle8_Text_19E178:: @ 819E178
	.string "여기까지 올 수 있는 트레이너는\n"
	.string "그렇게 많지 않지!$"
	// ここまで こられる トレ-ナ-はｎ
	// そうは いないよな!

Route110_TrickHousePuzzle8_Text_19E1A1:: @ 819E1A1
	.string "즉 너도\n"
	.string "대단하다는 거겠지...$"
	// つまり キミもｎ
	// すごいって ことだよな…

Route110_TrickHousePuzzle8_Text_19E1C5:: @ 819E1C5
	.string "뭣 포켓몬리그의 챔피언을\n"
	.string "이겼다고? 대 대단해...!$"
	// えっ ポケモンリ-グの チャンピオンにｎ
	// かったって? す すごい……!

Route110_TrickHousePuzzle8_Text_19E201:: @ 819E201
	.string "나와 승부하다니\n"
	.string "당신 행복하겠구나!$"
	// わたしと しょうぶ できるなんてｎ
	// あなた しあわせよ!

Route110_TrickHousePuzzle8_Text_19E22C:: @ 819E22C
	.string "이럴 수가 내가\n"
	.string "져버리다니...!$"
	// そんな わたしがｎ
	// まけるなんて……!

Route110_TrickHousePuzzle8_Text_19E24C:: @ 819E24C
	.string "나를 이긴 건 기적이야!\n"
	.string "자랑스러워할 일이라고!$"
	// わたしに かつなんて きせきよ!ｎ
	// じまん できる ことだわ!

Route110_TrickHousePuzzle8_Text_19E284:: @ 819E284
	.string "당신도 미궁의 대저택에\n"
	.string "계속해서 도전하고 있군요!$"
	// あなたも カラクリやしきにｎ
	// ちょうせん しつづけて いるんですね!

Route110_TrickHousePuzzle8_Text_19E2C1:: @ 819E2C1
	.string "과연...\n"
	.string "놀라운 센스로군요!$"
	// なるほど……ｎ
	// すばらしい センスですね!

Route110_TrickHousePuzzle8_Text_19E2EE:: @ 819E2EE
	.string "당신 같은 사람이 와 줘서\n"
	.string "미궁대왕도 만족하겠죠!$"
	// あなた みたいな ひとが きてくれてｎ
	// カラクリだいおうも まんぞく でしょうね!
