MossdeepCity_House3_Text_18D909:: @ 818D909
	.string "이봐-! 거기 트레이너!\n"
	.string "대단한낚싯대는 정말로 대단하다고\p"
	.string "왜냐면 해저에 있는\n"
	.string "포켓몬도 낚아 올릴 수 있거든!\p"
	.string "어때? 갖고 싶어졌어?$"
	// お-い! トレ-ナ-よお!ｎ
	// すごいつりざおは ほんとうに すごいぞおｐ
	// なんたって かいていに いるｎ
	// ポケモンも つりあげられる からのお!ｐ
	// どお? ほしく なった?

MossdeepCity_House3_Text_18D9A9:: @ 818D9A9
	.string "그치 그치! 대단한낚싯대는\n"
	.string "정말로 대단하니까 말이다!$"
	// そうだろ そうだろ! すごいつりざおはｎ
	// ほんとうに すごい からのお!

MossdeepCity_House3_Text_18D9E3:: @ 818D9E3
	.string "물이 있는 곳이라면\n"
	.string "어디든 낚싯대를 써보도록 해!$"
	// みずの ある ところならｎ
	// どこでも つりざお つかうと いいぞお!

MossdeepCity_House3_Text_18DA26:: @ 818DA26
	.string "어라?\n"
	.string "낚시는 싫은 거야?$"
	// あら?ｎ
	// つりは きらい なのかね?

MossdeepCity_House3_Text_18DA44:: @ 818DA44
	.string "대단한낚싯대로\n"
	.string "해저의 포켓몬도 낚아 올려봐!$"
	// すごいつりざおでｎ
	// かいていの ポケモンも つりあげろお!
