SootopolisCity_PokemonCenter_1F_Text_18F6A2:: @ 818F6A2
	.string "이 마을의 체육관 관장 윤진은\n"
	.string "호연지방에서도 제일 강하다고\l"
	.string "여겨지는 실력자랍니다\p"
	.string "하지만 그런 윤진보다 강하다고\n"
	.string "전해지는 사천왕의 강함은\l"
	.string "대체 어느 정도인 걸까요?$"
	// この まちの ジムリ-ダ- ミクリはｎ
	// ホウエンちほう でも いちばんとｌ
	// うわさ される じつりょくしゃ だよｐ
	// しかし ミクリよりも つよいと いわれるｎ
	// してんのうの つよさｌ
	// どれほどの ものだろう?

SootopolisCity_PokemonCenter_1F_Text_18F770:: @ 818F770
	.string "이 마을에 사는 사람들이 모두\n"
	.string "집에 틀어박혀서 나오질 않아요!\p"
	.string "이 날씨...\n"
	.string "무언가의 전조일까요?$"
	// この まちの みんなが みんなｎ
	// いえに とじこもって でてこないんです!ｐ
	// この てんき……ｎ
	// なにかの まえぶれ なのでしょうか?

SootopolisCity_PokemonCenter_1F_Text_18F7EA:: @ 818F7EA
	.string "어떤 때라도\n"
	.string "무슨 일이 있더라도\l"
	.string "난 계속 포켓몬과 친구로 있을 거야\p"
	.string "왜냐면 포켓몬이랑 같이 있으면\n"
	.string "엄청 즐거우니까!$"
	// どんな ときでもｎ
	// どんな ことが あってもｌ
	// あたし ポケモンと ともだちで いるわｐ
	// だって ポケモンと いっしょだとｎ
	// すごく たのしいもの!

SootopolisCity_PokemonCenter_1F_Text_18F860:: @ 818F860
	.string "이유는 모르겠지만...\n"
	.string "엄청... 불안해...$"
	// りゆうは わからないけれど……ｎ
	// とっても…… ふあん なの……
