SootopolisCity_House8_Text_1900F7:: @ 81900F7
	.string "너 버섯꼬라는 포켓몬 알아?\n"
	.string "루네시티에선 좀처럼 보기 힘들지만\p"
	.string "나 커다란 버섯꼬가\n"
	.string "무지무지 좋아!\p"
	.string "동생은 미꾸리가 더\n"
	.string "크다고 하는데 말야\p"
	.string "당연히 버섯꼬가 더\n"
	.string "크지 않아!?\p"
	.string "응? 너 버섯꼬 가지고 있어?\n"
	.string "자 자 잠깐...\l"
	.string "아저씨한테 좀 보여 줘!$"
	@ きみ キノココって ポケモン しってる?ｎ
	@ ルネでは めったに みられないん だけどねｐ
	@ わし おおきな キノココがｎ
	@ めちゃめちゃ だいすき なのよ!ｐ
	@ おとうとは ドジョッチの ほうがｎ
	@ おおきいって いうんだけどｐ
	@ キノココの ほうがｎ
	@ おおきいに きまってる よね!ｐ
	@ ん? きみ キノココ もってるの?ｎ
	@ ちょ ちょ ちょっと……ｌ
	@ おじさんに みせて おくれ!

SootopolisCity_House8_Text_19021D:: @ 819021D
	.string "{STR_VAR_2}cm!\n"
	.string "오오! 이 녀석 커!\p"
	.string "동생이 본 커다란 미꾸리에\n"
	.string "지지 않는 크기일지도 몰라!\p"
	.string "보여 줘서 고마워\n"
	.string "답례로 이걸 줄게!$"
	@ §うcm!!ｎ
	@ おお! こいつは でかい!ｐ
	@ おとうとが みた でかい ドジョッチにｎ
	@ まけない おおきさ かも!ｐ
	@ みせて くれて ありがとうｎ
	@ おれいに これを あげるよ!

UnknownString_81902AE: @ 81902AE
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "상처약을 받았다!$"
	@ §あはｎ
	@ きずぐすりを もらった!

SootopolisCity_House8_Text_1902C4:: @ 81902C4
	.string "어라?\n"
	.string "너 지닌물건이 가득 찼네$"
	@ ありゃ?ｎ
	@ きみ もちもの いっぱいだね

SootopolisCity_House8_Text_1902E4:: @ 81902E4
	.string "{STR_VAR_2}cm인가...\p"
	.string "으음 난 이것보다 큰\n"
	.string "버섯꼬를 본 적이 있어...$"
	@ §うcmか……ｐ
	@ ううむ わしは これより おおきいｎ
	@ キノココを みたこと あるな……

SootopolisCity_House8_Text_190329:: @ 8190329
	.string "오오 이 녀석 꽤... 아니\n"
	.string "이거 버섯꼬가 아니잖아!$"
	@ おお こいつは なかなか…… ってｎ
	@ これ キノココじゃ ないよ!

SootopolisCity_House8_Text_190366:: @ 8190366
	.string "커다란 버섯꼬 없어?\n"
	.string "그거 안타깝네...\p"
	.string "다음에 커다란 버섯꼬 보여 줘$"
	@ おおきい キノココ もってないの?ｎ
	@ それは ざんねん……ｐ
	@ こんど おおきい キノココ みせてね

SootopolisCity_House8_Text_1903C9:: @ 81903C9
	.string "사상 최대의 버섯꼬!\n"
	.string "{STR_VAR_2}의 {STR_VAR_3}cm인 녀석!\p"
	.string "미꾸리보다 커다란 버섯꼬\n"
	.string "언제나 모집 중!$"
	@ しじょう さいだいの キノココ!ｎ
	@ §うの §えcmのやつ!ｐ
	@ ドジョッチより おおきい キノココｎ
	@ いつでも ぼしゅうちゅう!

SootopolisCity_House8_Text_190431:: @ 8190431
	.string "너 혹시 미꾸리라는 포켓몬 알아?\n"
	.string "루네시티에서는 좀처럼 보기 힘들지만\p"
	.string "나 커다란 미꾸리가\n"
	.string "무지무지 좋아!\p"
	.string "형은 버섯꼬가 더\n"
	.string "크다고 하는데 말야\p"
	.string "당연히 미꾸리가 더\n"
	.string "크지 않아!?\p"
	.string "응? 너 미꾸리 가지고 있어?\n"
	.string "자 자 잠깐...\l"
	.string "아저씨한테 좀 보여 줘!$"
	@ きみ ドジョッチって ポケモン しってる?ｎ
	@ ルネでは めったに みられないん だけどねｐ
	@ わし おおきな ドジョッチがｎ
	@ めちゃめちゃ だいすき なのよ!ｐ
	@ アニキは キノココの ほうがｎ
	@ おおきいって いうんだけどｐ
	@ ドジョッチの ほうがｎ
	@ おおきいに きまってる よね!ｐ
	@ ん? きみ ドジョッチ もってるの?ｎ
	@ ちょ ちょ ちょっと……ｌ
	@ おじさんに みせて おくれ!

SootopolisCity_House8_Text_190536:: @ 8190536
	.string "{STR_VAR_2}cm!\n"
	.string "오오! 이 녀석 커!\p"
	.string "형이 본 커다란 버섯꼬에\n"
	.string "지지 않는 크기일지도 몰라!\p"
	.string "보여 줘서 고마워\n"
	.string "보답으로 이걸 줄게!$"
	@ §うcm!!ｎ
	@ おお! こいつは でかい!ｐ
	@ あにきが みた でかい キノココにｎ
	@ まけない おおきさ かも!ｐ
	@ みせて くれて ありがとうｎ
	@ おれいに これを あげるよ!

SootopolisCity_House8_Text_1905C1:: @ 81905C1
	.string "어라?\n"
	.string "너 지닌물건이 가득 찼네$"
	@ ありゃ?ｎ
	@ きみ もちもの いっぱいだね

SootopolisCity_House8_Text_1905E6:: @ 81905E6
	.string "{STR_VAR_2}cm인가...\p"
	.string "으음 난 이것보다 큰\n"
	.string "미꾸리를 본 적이 있어...$"
	@ §うcmか……ｐ
	@ ううむ わしは これより おおきいｎ
	@ ドジョッチを みたこと あるな……

SootopolisCity_House8_Text_190628:: @ 8190628
	.string "오오 이 녀석 꽤... 아니\n"
	.string "이거 미꾸리가 아니잖아!$"
	@ おお こいつは なかなか…… ってｎ
	@ これ ドジョッチじゃ ないよ!

SootopolisCity_House8_Text_19065A:: @ 819065A
	.string "커다란 미꾸리 없어?\n"
	.string "그거 안타깝네...\p"
	.string "다음에 커다란 미꾸리 보여 줘$"
	@ おおきい ドジョッチ もってないの?ｎ
	@ それは ざんねん……ｐ
	@ こんど おおきい ドジョッチ みせてね

SootopolisCity_House8_Text_1906BE:: @ 81906BE
	.string "사상 최대의 미꾸리!\n"
	.string "{STR_VAR_2}의 {STR_VAR_3}cm인 녀석!\p"
	.string "버섯꼬보다 커다란 미꾸리\n"
	.string "언제나 모집 중!$"
	@ しじょう さいだいの ドジョッチ!ｎ
	@ §うの §えcmのやつ!ｐ
	@ キノココより おおきい ドジョッチｎ
	@ いつでも ぼしゅうちゅう!
