BattleTower_Outside_Text_199C6F:: @ 8199C6F
	.string "여기는 배틀타워!\n"
	.string "이겨나가라! 최강 트레이너$"
	@ ここは バトルタワ-!ｎ
	@ かちぬけ! さいきょう トレ-ナ-

BattleTower_Outside_Text_199CA4:: @ 8199CA4
	.string "여기는 배틀타워야!\p"
	.string "트레이너는 단련된 포켓몬으로\n"
	.string "계속해서 이겨 나가는 거지!$"
	@ ここは バトルタワ- さ!ｐ
	@ トレ-ナ-は きたえあげた ポケモンでｎ
	@ ひたすら かちぬいて いくのさ!

BattleTower_Outside_Text_199D06:: @ 8199D06
	.string "연락선을 이용하시려는 거군요!\n"
	.string "티켓은 가지고 계신가요?$"
	@ れんらくせんを ごりよう ですね!ｎ
	@ チケットは おもち でしょうか?

BattleTower_Outside_Text_199D40:: @ 8199D40
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "티켓이 없다!\p"
	.string "...죄송합니다!\p"
	.string "배에는 티켓을 가진 분들만\n"
	.string "탑승하실 수 있습니다$"
	@ §あはｎチケットを もっていない!ｐ
	@ ……もうしわけ ありません!ｐ
	@ ふねに のれるのはｎ
	@ チケットの ある かた だけです

BattleTower_Outside_Text_199D9D:: @ 8199D9D
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "승선티켓을 보여줬다!\p"
	.string "네! 확인했습니다!\p"
	.string "어디로 가시겠어요?$"
	@ §あはｎ
	@ ふねのチケットを みせた!ｐ
	@ はい! けっこう です!ｐ
	@ いきさきは どちら でしょう?

BattleTower_Outside_Text_199DF2:: @ 8199DF2
	.string "잿빛도시 말이죠!$"
	@ カイナ ですね!

BattleTower_Outside_Text_199E0E:: @ 8199E0E
	.string "해안시티 말이죠!$"
	@ ミナモ ですね!

BattleTower_Outside_Text_199E29:: @ 8199E29
	.string "또 이용해 주십시오!$"
	@ また ごりよう ください!

BattleTower_Outside_Text_199E4B:: @ 8199E4B
	.string "연락선에서 잠시 기다려 주십시오$"
	@ れんらくせんに のって おまちください

BattleTower_Outside_Text_199E7A:: @ 8199E7A
	.string "어디로 가시겠어요?$"
	@ いきさきは どちら でしょう?

BattleTower_Outside_Text_199E9C:: @ 8199E9C
	.string "오늘은 35연승을 하기 전까지\n"
	.string "돌아가지 않을 거야!$"
	@ きょうは 35にんぬき できるまではｎ
	@ かえりませんわ!

BattleTower_Outside_Text_199ED4:: @ 8199ED4
	.string "엄청 강해 보이는 트레이너가\n"
	.string "잔뜩 있네!\l"
	.string "난 아직 들어갈 자신이 없어...$"
	@ すごく つよそうな トレ-ナ-がｎ
	@ いっぱい だね!ｌ
	@ ぼくは まだ でられそうに ないや……
