SootopolisCity_House1_Text_18F991:: @ 818F991
	.string "으음...\n"
	.string "루네시티에 틀어박혀 산 지 30년...\p"
	.string "내가 만든 필살 기술머신을!\n"
	.string "너에게 주마!$"
	// うむう……ｎ
	// ルネシティに こもること 30ねん……ｐ
	// わしが あみだした ひっさつの わざマシン!ｎ
	// おまえに ゆずろう!

SootopolisCity_House1_Text_18FA03:: @ 818FA03
	.string "기술머신31은 깨트리다!\n"
	.string "설명하기조차 무서운 기술이지...$"
	// わざマシン31は かわらわり!ｎ
	// せつめい するのも おそろしい わざよ……

SootopolisCity_House1_Text_18FA50:: @ 818FA50
	.string "켈리몬: 푸- 푸햐아-$"
	// カクレオン『ぷ- ぷひゃあ-
