SootopolisCity_Gym_1F_Text_18E8A5:: @ 818E8A5
	.string "잘 있었나!!\n"
	.string "챔피언을 노리는 {PLAYER}!!\p"
	.string "루네시티 체육관 관장 윤진은\n"
	.string "물타입 포켓몬을 사용한다!!\p"
	.string "그리고 윤진이 있는 장소는\n"
	.string "얼음 바닥에 의해 가로막혀 있지...\p"
	.string "미안해! 너에게\n"
	.string "알려 줄 수 있는 건 여기까지야...!\p"
	.string "나머지는 스스로 힘내서 이겨내봐!$"
	@ げんき しとぉや!!ｎ
	@ チャンピオンを めざす §あ!!ｐ
	@ ルネシティの ジムリ-ダ- ミクリはｎ
	@ みずタイプ ポケモンを つかいこなす!ｐ
	@ そして ミクリが いる ばしょ まではｎ
	@ こおりの ゆかが ゆくてを さえぎる……ｐ
	@ ごめんな! きみに おしえてｎ
	@ あげられるのは ここまで なんだ……!ｐ
	@ あとは じぶんで きばってくれッ!

SootopolisCity_Gym_1F_Text_18E9C9:: @ 818E9C9
	.string "호연에서 가장 강하다고 알려져 있는\n"
	.string "윤진까지 이겨버렸군!!\p"
	.string "좋아! 너의\n"
	.string "트레이너카드를 보도록!\p"
	.string "모든 배지가 모였다면\n"
	.string "드디어 포켓몬리그에 도전할 수 있다!$"
	@ ホウエンで いちばん つよいと いわれるｎ
	@ ミクリに かったのかあ!!ｐ
	@ よし! きみのｎ
	@ トレ-ナ-カ-ドを みたまえ!ｐ
	@ すべての バッジが そろっているならｎ
	@ いよいよ ポケモンリ-グ ちょうせんだ!

SootopolisCity_Gym_B1F_Text_18EA87:: @ 818EA87
	.string "체육관 관장 윤진님께 배운\n"
	.string "화려한 테크닉을 보여줄게!$"
	@ ジムリ-ダ- ミクリさまに おしえてもらったｎ
	@ かれいな テクニックを みせたげる!

SootopolisCity_Gym_B1F_Text_18EACF:: @ 818EACF
	.string "윤진님 죄송해요...$"
	@ ミクリさま ごめんね……

SootopolisCity_Gym_B1F_Text_18EAED:: @ 818EAED
	.string "모든 바닥에 금이 가게 하면\n"
	.string "무슨 일이 생길 거야$"
	@ すべての ゆかに ヒビを いれるとｎ
	@ なにかが おこるわよ

SootopolisCity_Gym_B1F_Text_18EB22:: @ 818EB22
	.string "모처럼 여기까지 왔는데\n"
	.string "나한테 질 거니까\l"
	.string "윤진님과 만나지도 못하겠네!$"
	@ せっかく ここまで これたのにｎ
	@ あたしに まけるからｌ
	@ ミクリさまに あえないわね!

SootopolisCity_Gym_B1F_Text_18EB81:: @ 818EB81
	.string "강하잖아!!\n"
	.string "귀여워 보여서 속았어$"
	@ つよい じゃない!!ｎ
	@ かわいい みために だまされたわ

SootopolisCity_Gym_B1F_Text_18EBB1:: @ 818EBB1
	.string "너라면 윤진님과 싸워도\n"
	.string "한 방에 나가떨어지진 않을 거야$"
	@ あなたなら ミクリさまと たたかってもｎ
	@ いちげきで やられなくて すむかもね

SootopolisCity_Gym_B1F_Text_18EBFA:: @ 818EBFA
	.string "윤진님의 싸우는 모습...\p"
	.string "그 아름다움에 마음을 빼앗겨\n"
	.string "나도 포켓몬 승부를 시작하게 됐어$"
	@ ミクリさまの たたかう すがた……ｐ
	@ その うつくしさに こころ うばわれｎ
	@ わたくしも ポケモンを はじめましてよ

SootopolisCity_Gym_B1F_Text_18EC5E:: @ 818EC5E
	.string "싸우는 모습의\n"
	.string "아름다움마저 져버렸어...$"
	@ たたかう すがたのｎ
	@ うつくしさで まけましたわ……

SootopolisCity_Gym_B1F_Text_18EC92:: @ 818EC92
	.string "네 싸우는 방식도\n"
	.string "대단했어\p"
	.string "아아...!\n"
	.string "포켓몬과 만나서 다행이야$"
	@ あなたさまの たたかう すがたもｎ
	@ すばらしくってよｐ
	@ ああっ……!ｎ
	@ ポケモンに であえて よかったですわ

SootopolisCity_Gym_B1F_Text_18ECEB:: @ 818ECEB
	.string "내가 승부의 가혹함을\n"
	.string "잔뜩 알려 줄게$"
	@ おねえさんが しょうぶの きびしさｎ
	@ いろいろと おしえて あげちゃおっかな

SootopolisCity_Gym_B1F_Text_18ED18:: @ 818ED18
	.string "뭐야\n"
	.string "강하네$"
	@ なんだｎ
	@ つよいんだ

SootopolisCity_Gym_B1F_Text_18ED2B:: @ 818ED2B
	.string "좋은 걸 알려 줄게\p"
	.string "윤진님을 만나고 싶다면\n"
	.string "모든 바닥을 한 번씩만\l"
	.string "밟으면서 가면 돼$"
	@ いいこと おしえて あげるねｐ
	@ ミクリさまに あいたいのならｎ
	@ すべての ゆかを 1かいずつｌ
	@ あるいて いけば いいの

SootopolisCity_Gym_B1F_Text_18ED91:: @ 818ED91
	.string "호연지방에서 가장\n"
	.string "레벨이 높은 포켓몬체육관...\p"
	.string "그게 바로 여기 루네체육관이야!$"
	@ ホウエンちほうで いちばんｎ
	@ レベルの たかい ポケモンジム……ｐ
	@ それが ここ ルネジムよ!

SootopolisCity_Gym_B1F_Text_18EDE8:: @ 818EDE8
	.string "얼마나 레벨이 높은 거야...$"
	@ なんて レベルの たかい……

SootopolisCity_Gym_B1F_Text_18EE03:: @ 818EE03
	.string "레벨이 높은 체육관에 있다는 것에\n"
	.string "만족하지 않고\l"
	.string "다른 수행을 하러 가는 편이\l"
	.string "강해질 수 있기도 하고 즐거워$"
	@ レベルの たかい ジムに いることにｎ
	@ まんぞく しないでｌ
	@ ほかにも しゅぎょうに いくほうがｌ
	@ つよくなれそうだし なにより たのしそうね

SootopolisCity_Gym_B1F_Text_18EE96:: @ 818EE96
	.string "윤진님과 함께\n"
	.string "포켓몬을 단련시키고 있어\p"
	.string "간단히 이기진 못할 거야$"
	@ ミクリさまと いっしょにｎ
	@ ポケモンを きたえて いるのｐ
	@ かんたんに たおせると おもわないでね

SootopolisCity_Gym_B1F_Text_18EEDC:: @ 818EEDC
	.string "졌다...$"
	@ たおされちゃった……

SootopolisCity_Gym_B1F_Text_18EEF7:: @ 818EEF7
	.string "너 장래성이 있는 것 같은데\n"
	.string "같이 여기서 포켓몬 단련시킬래?$"
	@ あなた みどころ あると おもうのｎ
	@ いっしょに ここで ポケモン きたえない?

SootopolisCity_Gym_B1F_Text_18EF39:: @ 818EF39
	.string "얼음 위에서의 한붓그리기\p"
	.string "그게 가능한 트레이너는\n"
	.string "엘레강트하고 아름답지!$"
	@ こおりの うえでの ひとふでがきｐ
	@ それが できる トレ-ナ-はｎ
	@ エレガントに うつくしいのよ!

SootopolisCity_Gym_B1F_Text_18EFB8:: @ 818EFB8
	.string "잠깐-!?$"
	@ ちょっと-!?

SootopolisCity_Gym_B1F_Text_18EFCA:: @ 818EFCA
	.string "당연한 거지만\n"
	.string "포켓몬의 강함은\l"
	.string "나이와 관계가 없어$"
	@ あたりまえ だけどｎ
	@ ポケモンの つよさにｌ
	@ おとなも こどもも かんけい ないよ

SootopolisCity_Gym_B1F_Text_18F037:: @ 818F037
	.string "포켓몬과 함께 있으면\n"
	.string "시간이 눈 깜짝할 사이에 지나가!$"
	@ ポケモンと いっしょに いるとｎ
	@ じかんが あっ というまに すぎるのよ!

SootopolisCity_Gym_B1F_Text_18F07F:: @ 818F07F
	.string "깜짝!$"
	@ あっ!

SootopolisCity_Gym_B1F_Text_18F085:: @ 818F085
	.string "져버린 승부도\n"
	.string "눈 깜짝할 사이에 잊고 싶어...$"
	@ まけた しょうぶもｎ
	@ あっ というまに わすれたい……

SootopolisCity_Gym_1F_Text_18F0CA:: @ 818F0CA
	.string "다시 한 번 자기 소개를 하지\p"
	.string "나는 윤진\n"
	.string "이 루네시티의 체육관 관장\p"
	.string "뭐지?\n"
	.string "너 분위기가 조금\l"
	.string "변한 듯한 느낌이 드는걸\p"
	.string "각성의 사당에서 무슨 일이 있었는지\n"
	.string "네가 무엇을 해왔는지\l"
	.string "지금부터 펼쳐질 승부로 알게 되겠지\p"
	.string "자 그럼 한번 확인해볼까\n"
	.string "너와 포켓몬의 힘을\p"
	.string "그리고 확실하게 보여주지\n"
	.string "나와 포켓몬에 의한\l"
	.string "물의 일루전을!$"
	@ あらためて なのろうｐ
	@ わたしは ミクリｎ
	@ この ルネの ジムリ-ダ-ｐ
	@ なんだろうｎ
	@ きみの ふんいきが すこし かわったｐ
	@ そんな きが するｐ
	@ めざめのほこらで なにが あったかｎ
	@ きみが なにを してきたかｌ
	@ これからの たたかいで わかるだろうｐ
	@ さあ みせてもらおうｎ
	@ きみと ポケモンの ちからをｐ
	@ そして ぞんぶんに おみせしようｎ
	@ わたしと ポケモンに よるｌ
	@ みずの イリュ-ジョンを!

SootopolisCity_Gym_1F_Text_18F282:: @ 818F282
	.string "굉장해\p"
	.string "넌 정말 굉장한\n"
	.string "포켓몬 트레이너라는 걸 알았어\p"
	.string "그런 너와 너의 포켓몬을\n"
	.string "만나게 돼서 기쁘군\p"
	.string "이 레인배지는\n"
	.string "네가 받기에 적합한 것 같다\l"
	.string "자 받아$"
	@ すばらしいｐ
	@ きみが ほんとうに すばらしいｎ
	@ ポケモン トレ-ナ-だと わかったｐ
	@ そんな きみと きみの ポケモンにｎ
	@ であえたことを よろこびたいｐ
	@ この レインバッジはｎ
	@ そんな きみに ふさわしいｌ
	@ さあ うけとるが いい

SootopolisCity_Gym_1F_Text_18F342:: @ 818F342
	.string "{PLAYER}{K_EUNNEUN} 윤진에게서\n"
	.string "레인배지를 받았다!$"
	@ §あは ミクリからｎ
	@ レインバッジを もらった!

SootopolisCity_Gym_1F_Text_18F36B:: @ 818F36B
	.string "레인배지를 가지고 있으면\n"
	.string "모든 포켓몬이\l"
	.string "순순히 네 말에 따르게 되지\p"
	.string "세차게 흐르는 폭포조차도\n"
	.string "비전기술 폭포오르기를 써서\l"
	.string "올라갈 수 있게 될 거야\p"
	.string "그리고 나와의 승부를\n"
	.string "잊지 않도록 이걸...$"
	@ レインバッジを もっているとｎ
	@ すべての ポケモンがｌ
	@ きみの いうことを すなおに きいてくれるｐ
	@ はげしく ながれる たきもｎ
	@ ひでんわざ たきのぼりを つかってｌ
	@ のぼれる ように してくれるｐ
	@ それから わたしとの しょうぶをｎ
	@ わすれないように これを……

SootopolisCity_Gym_1F_Text_18F466:: @ 818F466
	.string "네게 넘겨준 그 기술머신의\n"
	.string "내용물은 물의파동\p"
	.string "쓰면 가끔씩 초음파로\n"
	.string "상대를 혼란시키지$"
	@ きみに わたした その わざマシンｎ
	@ なかみは みずのはどうｐ
	@ つかうと ときおり ちょうおんぱでｎ
	@ あいてを こんらん させる

SootopolisCity_Gym_1F_Text_18F4D7:: @ 818F4D7
	.string "호연에서 모을 수 있는\n"
	.string "모든 체육관 배지를 손에 넣은\l"
	.string "트레이너가 가야 할 장소\p"
	.string "그것이 바로 포켓몬리그\p"
	.string "포켓몬리그에 가려면\n"
	.string "호연지방 끝에 있는\l"
	.string "그랜드시티라는 섬으로 가면 돼$"
	@ ホウエンで あつめられるｎ
	@ すべての ジムバッジを てにいれたｌ
	@ トレ-ナ-が いくべき ばしょｐ
	@ それが ポケモンリ-グｐ
	@ ポケモンリ-グに いくならばｎ
	@ ホウエンちほうの さいはてｌ
	@ サイユウという しまに むかうと いい

SootopolisCity_Gym_1F_Text_18F5B4:: @ 818F5B4
	.string "호연에서 모을 수 있는\n"
	.string "체육관 배지는 앞으로 하나\p"
	.string "네가 포켓몬리그에 도전할 생각이라면\n"
	.string "검방울시티의 포켓몬체육관에서\l"
	.string "남은 배지를 손에 넣어야 할 거야$"
	@ ホウエンで あつめられるｎ
	@ ジムバッジは あと ひとつｐ
	@ きみが ポケモンリ-グに いどむ つもりならｎ
	@ ヒワマキの ポケモンジムでｌ
	@ のこりの バッジを てにいれると いい

SootopolisCity_Gym_1F_Text_18F649:: @ 818F649
	.string "루네시티 포켓몬체육관$"
	@ ルネシティ ポケモンジム

SootopolisCity_Gym_1F_Text_18F665:: @ 818F665
	.string "루네시티 포켓몬체육관\p"
	.string "윤진 인정 트레이너!\n"
	.string "{PLAYER}$"
	@ ルネシティ ポケモンジムｐ
	@ ミクリ にんてい トレ-ナ-!ｎ
	@ §あ
