AbandonedShip_HiddenFloorCorridors_Text_198DC0:: @ 8198DC0
	.string "문이 잠겨 있다\p"
	.string "문에는 1호실이라고 쓰여 있다$"
	// カギが かかっているｐ
	// とびらには 1ごうしつと かかれている

AbandonedShip_HiddenFloorCorridors_Text_198DF4:: @ 8198DF4
	.string "문이 잠겨 있다\p"
	.string "문에는 2호실이라고 쓰여 있다$"
	// カギが かかっているｐ
	// とびらには 2ごうしつと かかれている

AbandonedShip_HiddenFloorCorridors_Text_198E28:: @ 8198E28
	.string "문이 잠겨 있다\p"
	.string "문에는 4호실이라고 쓰여 있다$"
	// カギが かかっているｐ
	// とびらには 4ごうしつと かかれている

AbandonedShip_HiddenFloorCorridors_Text_198E5C:: @ 8198E5C
	.string "문이 잠겨 있다\p"
	.string "문에는 6호실이라고 쓰여 있다$"
	// カギが かかっているｐ
	// とびらには 6ごうしつと かかれている

AbandonedShip_HiddenFloorCorridors_Text_198E90:: @ 8198E90
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "열쇠를 썼다!\p"
	.string "꽂은 열쇠는 빠지지 않게 되었지만\n"
	.string "문은 열렸다!$"
	// §あはｎ
	// カギを つかった!ｐ
	// さしこんだ カギは ぬけなくなったがｎ
	// とびらは ひらいた!

AbandonedShip_HiddenFloorRooms_Text_198EE2:: @ 8198EE2
	.string "반짝거렸을 뿐인\n"
	.string "평범한 쓰레기였다...$"
	// ひかっているだけのｎ
	// ただの ゴミ だった……

UnknownString_8198F10: @ 8198F10
	.string "벽에 작은 홈이 있다$"

UnknownString_8198F34: @ 8198F34
	.string "벽에 작은 홈이 있다\p"
	.string "비밀의힘을 사용하겠습니까?$"

UnknownString_8198F6E: @ 8198F6E
	.string "작은 동굴을 발견했다!$"
