Route119_WeatherInstitute_2F_Text_19EEAF:: @ 819EEAF
	.string "이 연구소에서 만들어진\n"
	.string "포켓몬은 날씨와 관계가 있다고\l"
	.string "들어서 받아 가려고 왔어!$"
	// この けんきゅうじょで うみだされたｎ
	// ポケモンは てんきと かんけいある ってｌ
	// きいたから いただきに きたのさ!

Route119_WeatherInstitute_2F_Text_19EF1B:: @ 819EF1B
	.string "이런 꼬맹이에게 방해당한다고!?$"
	// こんな こどもに じゃま されるのか!?

Route119_WeatherInstitute_2F_Text_19EF3E:: @ 819EF3E
	.string "여기서 만들어진 포켓몬이\n"
	.string "만약 날씨를 자유롭게 조종할 수 있다면\l"
	.string "{EVIL_TEAM}단에게는 반드시 필요하다고!$"
	// ここで うみだされた ポケモンがｎ
	// もし てんきを じゆうに あやつれるならｌ
	// ぜったい §くだんに ひつよう だぜ!

Route119_WeatherInstitute_2F_Text_19EFA3:: @ 819EFA3
	.string "우리들은 {EVIL_TEAM}단!\n"
	.string "희귀한 게 있는 곳이라면\l"
	.string "어디든 나타난다!$"
	// おれたち §くだん!ｎ
	// めずらしい ものが ある ところならｌ
	// どこにでも あらわれる!

Route119_WeatherInstitute_2F_Text_19EFDD:: @ 819EFDD
	.string "이거 큰일이군!$"
	// こいつは まいった!

Route119_WeatherInstitute_2F_Text_19EFE9:: @ 819EFE9
	.string "{EVIL_TEAM}단의 이상도 모르는 주제에\n"
	.string "방해하지 마!$"
	// §くだんの りそうを しらないくせにｎ
	// じゃま するんじゃ ないよ!

Route119_WeatherInstitute_2F_Text_19F042:: @ 819F042
	.string "오-호호!\p"
	.string "우리 {EVIL_TEAM}단을\n"
	.string "방해할 셈이야!?\p"
	.string "나 참 무서운 걸 모르는 건지\n"
	.string "그냥 멍청한 건지...\p"
	.string "너무 귀여워서 얄미운걸!\n"
	.string "해치워 줄게!$"
	// オ-ッホッホ!ｐ
	// われわれ §くだんのｎ
	// じゃまを しようと いうの!?ｐ
	// もう こわいものしらず といおうかｎ
	// ただの おろかものと いおうか……ｐ
	// かわいすぎて にくらしく なっちゃう!ｎ
	// やっつけて あげるわね!

Route119_WeatherInstitute_2F_Text_19F0F4:: @ 819F0F4
	.string "오-호호!\n"
	.string "너무 강해서 얄미운걸!$"
	// オ-ッホッホ!ｎ
	// つよくて にくらしく なっちゃうわ!

Route119_WeatherInstitute_2F_Text_19F11B:: @ 819F11B
	.string "오-호호!\n"
	.string "생각지도 못하게 방해당했네!\p"
	.string "어쩔 수 없지!\n"
	.string "여기선 일단 물러나야겠어!\p"
	.string "하지만 {EVIL_TEAM}단의 활동은\n"
	.string "앞으로도 계속될 테니까\l"
	.string "기억해 두도록 해-!$"
	// オ-ッホッホ!ｎ
	// おもわぬ じゃまが はいっちゃったわ!ｐ
	// しかたないわね!ｎ
	// ここは いちど ひきあげちゃう!ｐ
	// でもね §くだんの かつどうはｎ
	// まだまだ つづくんだからｌ
	// おぼえて おきなさ-い!

Route119_WeatherInstitute_2F_Text_19F1CF:: @ 819F1CF
	.string "고맙다\n"
	.string "자네 덕분에 살았어\p"
	.string "감사의 표시라고 하기엔 좀 그렇다만\n"
	.string "이 포켓몬을 받아주게나$"
	// ありがとうよｎ
	// きみの おかげで たすかったよｐ
	// おれいと いっては なんだがｎ
	// この ポケモンを もらって おくれ

Route119_WeatherInstitute_2F_Text_19F231:: @ 819F231
	.string "어라? 그 이상\n"
	.string "포켓몬을 지닐 수 없나 보구나$"
	// あら? それいじょうｎ
	// ポケモンを もてないようだよ

Route119_WeatherInstitute_2F_Text_19F267:: @ 819F267
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "캐스퐁을 받았다!$"
	// §あはｎ
	// ポワルンを もらった!

Route119_WeatherInstitute_2F_Text_19F27D:: @ 819F27D
	.string "그 녀석은 그 당시의 날씨에 따라\n"
	.string "모습을 바꾸는 포켓몬이란다\p"
	.string "연구소에는 많이 있으니까\n"
	.string "사양 말고 받아주렴$"
	// そいつは そのときの てんきに よってｎ
	// すがたを かえる ポケモン なんだよｐ
	// けんきゅうじょ には たくさん いるからｎ
	// えんりょせずに もらって おくれよ

Route119_WeatherInstitute_2F_Text_19F2FE:: @ 819F2FE
	.string "나도 오랫동안\n"
	.string "비를 연구하고 있지만\l"
	.string "날씨를 자유자재로 바꾼다니\l"
	.string "인간에게는 불가능한 이야기야$"
	// わたしも ながい あいだｎ
	// あめの けんきゅうを してるがｌ
	// てんきを じゆうじざいに かえるだなんてｌ
	// にんげんには むりな はなし だよ
