SootopolisCity_Mart_Text_18F890:: @ 818F890
	.string "포인트업은 굉장해!\p"
	.string "왜냐면 포켓몬의\n"
	.string "파워포인트를 늘려주거든!$"
	// ポイントアップは すごいぞ!ｐ
	// なんたって ポケモンのｎ
	// パワ-ポイントを ふやせるからな!

SootopolisCity_Mart_Text_18F8D7:: @ 818F8D7
	.string "대체 무슨 일이 일어나는 거지!?$"
	// いったい なにが おこってるんだ!?

SootopolisCity_Mart_Text_18F8F2:: @ 818F8F2
	.string "회복약이라고 알고 있나요?\p"
	.string "포켓몬의 체력이 완쾌!\n"
	.string "상태 이상도 모두 회복!\l"
	.string "정말 꿈만 같은 도구랍니다$"
	// かいふくのくすり ごぞんじ ですか?ｐ
	// ポケモンの たいりょく ぜんかい!ｎ
	// じょうたい いじょうも すべて かいふく!ｌ
	// まさに ゆめのような どうぐ なのです

SootopolisCity_Mart_Text_18F96B:: @ 818F96B
	.string "이 날씨...\n"
	.string "무언가가 눈을 뜬 건가...?$"
	// この てんき……ｎ
	// なにかが めざめたのか……?
