PacifidlogTown_House4_Text_17959B:: @ 817959B
	.string "호연의 하늘 높은 곳을 날아가는\n"
	.string "포켓몬을 봤어! 라고 하는 사람이 있는데\p"
	.string "계속 날아다니고 있는 걸까?\n"
	.string "어딘가에서 쉬기도 할 것 같은데$"
	@ ホウエンの そらたかくを とんでいくｎ
	@ ポケモンを みた! って ひとが いるけどｐ
	@ ずっと とびまわって いるのかしら?ｎ
	@ どこかで やすんだり しそうだけど

PacifidlogTown_House4_Text_17961F:: @ 817961F
	.string "하늘의 포켓몬!\n"
	.string "하늘의 포켓몬!$"
	@ おそらの ポケモン!ｎ
	@ おそらの ポケモン!

PacifidlogTown_House4_Text_17963D:: @ 817963D
	.string "넌 어디서 왔니?$"
	@ きみ どこから きたの?

PacifidlogTown_House4_Text_179656:: @ 8179656
	.string "예...?\n"
	.string "예... 마을...?\p"
	.string "몰라 그런 마을은$"
	@ はい……?ｎ
	@ ハイ… タウン……?ｐ
	@ しらないなぁ そんな まち

PacifidlogTown_House4_Text_17968C:: @ 817968C
	.string "아니요라니...\n"
	.string "어디서든 왔을 거 아니야\p"
	.string "서 설마 너...\n"
	.string "바닷속에서 태어나기라도 한 거야...?$"
	@ いいえ って そんな……ｎ
	@ どこからも きてない はずが ないでしょｐ
	@ ま まさか きみ……ｎ
	@ うみの そこで うまれた とか……?
