LittlerootTown_BrendansHouse_1F_Text_172429:: @ 8172429
	.string "엄마: 봐봐 {PLAYER}{K_AYA}!\n"
	.string "집 안도 멋지지!$"
	// ママ『ほら §あ!ｎ
	// おうちの なかも すてき でしょ!

LittlerootTown_BrendansHouse_1F_Text_172453:: @ 8172453
	.string "집 정리를\n"
	.string "이삿짐센터 포켓몬이\l"
	.string "도와주니까 정말 편해!\p"
	.string "{PLAYER}도 2층에 있는\n"
	.string "네 방에 한번 가보렴!\p"
	.string "아빠가 이사 기념으로\n"
	.string "사 주신 시계가 있을 테니까\l"
	.string "시간 좀 맞춰 둬$"
	// おうちの かたづけはｎ
	// ひっこしやさんの ポケモンがｌ
	// てつだって くれるから らくちんね!ｐ
	// §あも 2かいに あるｎ
	// じぶんの おへやに いってごらん!ｐ
	// パパが ひっこしの おいわいにｎ
	// かってくれた とけいが あるからｌ
	// じかんを あわせて おきなさいよ

LittlerootTown_BrendansHouse_1F_Text_172531:: @ 8172531
	.string "엄마: {PLAYER}{K_AYA}\p"
	.string "네 방은 안 봐도 되니?$"
	// ママ『§あｐ
	// じぶんの へやを みてこないの?

LittlerootTown_BrendansHouse_1F_Text_172574:: @ 8172574
LittlerootTown_MaysHouse_1F_Text_172574:: @ 8172574
	.string "엄마: {PLAYER}{K_AYA}\n"
	.string "방 안에 있는 시계 맞춰 두렴$"
	// ママ『§あｐ
	// おへやの とけい あわせてきて

LittlerootTown_BrendansHouse_1F_Text_1725A3:: @ 81725A3
	.string "엄마: ...아! {PLAYER}{K_AYA}! {PLAYER}{K_AYA}!\n"
	.string "빨리 여기로 와보렴!$"
	// ママ『……あ! §あ! §あ!ｎ
	// はやく こっちに いらっしゃい!

LittlerootTown_BrendansHouse_1F_Text_1725C9:: @ 81725C9
LittlerootTown_MaysHouse_1F_Text_1725C9:: @ 81725C9
	.string "엄마: 등화도시 체육관이 나오고 있어\n"
	.string "아빠가 나올지도 몰라!!$"
	// ママ『トウカの ジムが うつってるわｎ
	// パパが でるかもよ!!

LittlerootTown_BrendansHouse_1F_Text_1725FE:: @ 81725FE
LittlerootTown_MaysHouse_1F_Text_1725FE:: @ 81725FE
	.string "엄마: 어머머... 끝나버렸네\p"
	.string "아빠가 나왔던 거 같은데 아쉽다$"
	// ママ『あらら…… おわっちゃったｐ
	// パパが でてたみたい だったのに ざんねんね

LittlerootTown_BrendansHouse_1F_Text_172644:: @ 8172644
LittlerootTown_MaysHouse_1F_Text_172644:: @ 8172644
	.string "...아 맞다 맞다! 이 마을에\n"
	.string "털보박사님이라고 하시는\l"
	.string "아빠 친구분이 계시거든\p"
	.string "박사님 집은 옆집이니까\n"
	.string "얼른 인사 드리고 오렴!$"
	// ……あ そうそう! このまち にはｎ
	// オダマキはかせ っていうｌ
	// パパの おともだちが いるのｐ
	// はかせの いえは おとなり だからｎ
	// きちんと あいさつ してくると いいわ!

LittlerootTown_BrendansHouse_1F_Text_1726D2:: @ 81726D2
	.string "엄마: 그럼 다녀오렴!$"
	// ママ『いってらっしゃい!

LittlerootTown_BrendansHouse_1F_Text_1726E7:: @ 81726E7
	.string "엄마: 털보박사님은 만나고 왔니?$"
	// ママ『オダマキはかせ には あえたの?

LittlerootTown_BrendansHouse_1F_Text_172717:: @ 8172717
	.string "엄마: {PLAYER}{K_AYA} 잘 있었니?\n"
	.string "조금 지쳐 보이네?\p"
	.string "집에서 좀 쉬다 가렴$"
	// ママ『どう? §あｎ
	// すこし つかれたんじゃ ないかしら?ｐ
	// おうちで やすんでいくと いいわ

LittlerootTown_BrendansHouse_1F_Text_17276B:: @ 817276B
	.string "엄마: 그럼 조심하고!$"
	// ママ『じゃあ きをつけてね!

LittlerootTown_BrendansHouse_1F_Text_172782:: @ 8172782
	.string "엄마: 어머\n"
	.string "그 배지 아빠한테 받은 거니!?\p"
	.string "그럼 엄마도 이거 줘야겠다$"
	// ママ『あらｎ
	// その バッジ パパから もらったの!?ｐ
	// じゃあ ママも これ あげようかな

LittlerootTown_BrendansHouse_1F_Text_1727CD:: @ 81727CD
	.string "너무 무리하지는 마렴\n"
	.string "언제든지 집에 와도 돼\p"
	.string "그럼 힘내!$"
	// あんまり むりは しないでねｎ
	// なにか あれば かえって くればいいからｐ
	// じゃあ がんばってね!

LittlerootTown_BrendansHouse_1F_Text_17281D:: @ 817281D
	.string "가오오 가오 가오...$"
	// ぎゃお ぎゃお ぎゃお……

LittlerootTown_BrendansHouse_1F_Text_172831:: @ 8172831
	.string "구와 구와 구와...$"
	// ぐわっ ぐわっ ぐわっ……

LittlerootTown_BrendansHouse_1F_Text_172841:: @ 8172841
	.string "인터뷰어: ... 이상으로\n"
	.string "등화체육관 앞에서 전해드렸습니다!$"
	// インタビュア-『…… いじょうｎ
	// トウカジムの まえ からでした!

UnknownString_817288C: @ 817288C
	.string "TV에서 영화를 하고 있다!\p"
	.string "어른과 아이가 둘이서 나란히\n"
	.string "커다란 피아노 위에서 춤추고 있다!\p"
	.string "빨리 가자!$"
	// テレビで えいがを やってる!ｐ
	// おとなと こどもが ふたり ならんでｎ
	// おおきな ピアノの うえで おどってる!ｐ
	// もう いかなきゃ!

UnknownString_81728E3: @ 81728E3
	.string "러닝슈즈의\n"
	.string "사용설명서가 있다!\p"
	.string "“러닝슈즈는\n"
	.string "  B 버튼을 누르면 지금보다\l"
	.string "  빨리 달릴 수 있게 해줍니다!\p"
	.string "  러닝슈즈를 신고\n"
	.string "  마음껏 달립시다!”$"
	// ランニングシュ-ズのｎ
	// せつめいしょが ある!ｐ
	// 「ランニングシュ-ズはｎ
	//  ビ-ボタンを おすことで いままでよりもｌ
	//  はやく はしれるように なります!ｐ
	//  ランニングシュ-ズを はいてｎ
	//  おもいっきり そとを はしろう!」

LittlerootTown_BrendansHouse_1F_Text_17298B:: @ 817298B
	.string "아빠: 응?\p"
	.string "{PLAYER}{K_I} 아니냐!\n"
	.string "오랜만에 보는데\l"
	.string "어딘가 늠름해진 거 같은...\p"
	.string "그런 느낌이 드는구나\n"
	.string "하지만 나도 질 수는 없지\p"
	.string "아 그래 맞다\n"
	.string "하기라는 사람한테서\l"
	.string "네 앞으로 뭔가가 왔단다!$"
	// パパ『ん?ｐ
	// §あじゃ ないか!ｎ
	// ひさしぶりに かおを みたがｌ
	// どこか たくましくなった……ｐ
	// そんな かんじ だなｎ
	// だが わたしも まけていないぞｐ
	// おっと そうだったｎ
	// ハギという ひとから おまえあてにｌ
	// これが とどいていたぞ!

LittlerootTown_BrendansHouse_1F_Text_172A7D:: @ 8172A7D
	.string "아빠: 승선티켓이구나...\p"
	.string "분명 배를 타는 선착장은\n"
	.string "잿빛도시와 해안시티에 있었지\p"
	.string "{PLAYER}! 지금보다 더 강해지고 싶다면\n"
	.string "배틀타워에 가보는 게 좋을 거다\p"
	.string "트레이너의 수행에는\n"
	.string "끝이 없다는 걸 배우게 되겠지$"
	// パパ『ふねのチケットか……ｐ
	// たしか ふねに のるならｎ
	// カイナか ミナモに ふねのりばが あったなｐ
	// §あ! もっと つよくなりたいならｎ
	// バトルタワ-に いってみると いいｐ
	// トレ-ナ-の しゅぎょうにｎ
	// おわりが ないことを しるだろう

LittlerootTown_BrendansHouse_1F_Text_172B5E:: @ 8172B5E
	.string "그럼 난\n"
	.string "등화도시 체육관으로 돌아가마\p"
	.string "여보\n"
	.string "그럼 다녀올게$"
	// では わたしはｎ
	// トウカの ジムに もどるよｐ
	// ママｎ
	// いえのこと たのんだよ

LittlerootTown_BrendansHouse_1F_Text_172BBC:: @ 8172BBC
	.string "엄마: 네 아빠도 참\n"
	.string "오랜만에 집에 왔는데\l"
	.string "포켓몬 얘기만 하고!\p"
	.string "좀 더 천천히 쉬었다 가지!$"
	// ママ『パパったらｎ
	// ひさしぶりに かえって きたのにｌ
	// ポケモンの はなし ばっかり!ｐ
	// もっと ゆっくり すれば いいのにね!

UnknownString_8172C50: @ 8172C50
	.string "임시 뉴스입니다\p"
	.string "호연지방 각지에서\n"
	.string "파란 포켓몬이 날아다니는 걸\l"
	.string "봤다는 정보가 들어왔습니다\p"
	.string "아직까지 정체는\n"
	.string "확인하지 못했다고 합니다\p"
	.string "그럼 계속 이어지는\n"
	.string "영화를 즐겨주십시오...$"
	// りんじ ニュ-ス ですｐ
	// ホウエンちほうの かくちでｎ
	// あおい ポケモンが とんでいくのを みたｌ
	// という じょうほうが よせられていますｐ
	// いまのところ しょうたいはｎ
	// わかって いないようですｐ
	// では ひきつづきｎ
	// えいがを おたのしみ ください……

UnknownString_8172D30: @ 8172D30
	.string "임시 뉴스입니다\p"
	.string "호연지방 각지에서\n"
	.string "빨간 포켓몬이 날아다니는 걸\l"
	.string "봤다는 정보가 들어왔습니다\p"
	.string "아직까지 정체는\n"
	.string "확인하지 못했다고 합니다\p"
	.string "그럼 계속 이어지는\n"
	.string "영화를 즐겨주십시오...$"
	// りんじ ニュ-ス ですｐ
	// ホウエンちほうの かくちでｎ
	// あかい ポケモンが とんでいくのを みたｌ
	// という じょうほうが よせられていますｐ
	// いまのところ しょうたいはｎ
	// わかって いないようですｐ
	// では ひきつづきｎ
	// えいがを おたのしみ ください……

UnknownString_8172E0F: @ 8172E0F
	.string "가우! 가우!$"
