Route109_SeashoreHouse_Text_19B4D9:: @ 819B4D9
	.string "난 바다의 집 아저씨!\n"
	.string "사람들은 바다아저씨라고 부르지!\p"
	.string "어쨌든 뜨거운 포켓몬 승부를\n"
	.string "보는 걸 정말 좋아한다고-!\p"
	.string "자네도 말이야- 뜨-거운 하트로\n"
	.string "여기에 있는 트레이너를 상대로\l"
	.string "이기면 내가 좋은 걸 줄게-$"
	@ わし うみのいえ の オヤジ!ｎ
	@ ひとよんで うみサン!ｐ
	@ とにかく あつい ポケモンしょうぶをｎ
	@ みることが だいすき なんだよね-!ｐ
	@ キミもね- あつ-い ハ-トでｎ
	@ ここに いる トレ-ナ-ぜんいんにｌ
	@ かてたら いいものを あげるよ-

Route109_SeashoreHouse_Text_19B5B9:: @ 819B5B9
	.string "뜨-거운 승부를 보여줘!\p"
	.string "난 그거 하나만 보고\n"
	.string "이 바다의 집을 열고 있는 거라고-!$"
	@ あつ-い しょうぶ みせてくれ-!ｐ
	@ そのためだけに わしｎ
	@ この うみのいえを やってるんだね-!

Route109_SeashoreHouse_Text_19B609:: @ 819B609
	.string "자네 대단한데-!\n"
	.string "뜨거운 포켓몬 승부였어-\l"
	.string "나 정말 대만족했다고-!\p"
	.string "이건 뜨거운 승부를 보여 준\n"
	.string "자네에게 주는 감사의 표시야\p"
	.string "미네랄사이다 반 세트 가져가-$"
	@ きみ すごいね-!ｎ
	@ あつい ポケモンしょうぶ だった-ｌ
	@ わし だいまんぞく だよ-!ｐ
	@ これは あつい しょうぶを みせてくれたｎ
	@ きみへの おれい だよ-ｐ
	@ サイコソ-ダ はんダ-ス もっていきなよ-

Route109_SeashoreHouse_Text_19B6BE:: @ 819B6BE
	.string "주려고 했는데 가방이 가득 찼네-\n"
	.string "그럼 맡아 둘게$"
	@ と おもったけど バッグ いっぱいか-ｎ
	@ じゃあ あずかっておくよ-

Route109_SeashoreHouse_Text_19B702:: @ 819B702
	.string "포켓몬도 정말 좋아하는 미네랄사이다\n"
	.string "한 병에 300원이야-\l"
	.string "사 가라구-!$"
	@ ポケモンも だいすき サイコソ-ダｎ
	@ いっぽん 300えん だよ-ｌ
	@ かって いきなよ-!

Route109_SeashoreHouse_Text_19B74C:: @ 819B74C
	.string "자 여기-$"
	@ はいよ-

Route109_SeashoreHouse_Text_19B759:: @ 819B759
	.string "돈이 부족해-$"
	@ おかねが ないよ-

Route109_SeashoreHouse_Text_19B773:: @ 819B773
	.string "그거 아쉽네-$"
	@ それは ざんねん だね-

UnknownString_819B787: @ 819B787
	.string "포켓몬도 정말 좋아하는 미네랄사이다가\n"
	.string "한 병에 300원이야 어때!?$"
	@ ポケモンも だいすき サイコソ-ダｎ
	@ いっぽん 300えんよ いかが!?

UnknownString_819B7C5: @ 819B7C5
	.string "자 받아!$"
	@ はい どうぞ!

UnknownString_819B7D2: @ 819B7D2
	.string "어라 안 돼!\n"
	.string "돈이 부족하잖아$"
	@ あらやだ!ｎ
	@ おかねが たりないわよ

UnknownString_819B7F9: @ 819B7F9
	.string "그거 아쉽다!$"
	@ それは ざんねん!

Route109_SeashoreHouse_Text_19B809:: @ 819B809
	.string "이 바다의 집에서 가장\n"
	.string "뜨거운 포켓몬 승부를 할 수 있는 건\l"
	.string "바로 이 몸이시라고!!$"
	@ この うみのいえで いちばんｎ
	@ あつい ポケモンしょうぶが できるのはｌ
	@ この オレさま だぜ!!

Route109_SeashoreHouse_Text_19B869:: @ 819B869
	.string "확실히 뜨거운 승부였다\n"
	.string "패배를 납득할 수밖에 없는 느낌이군!$"
	@ たしかに あつい しょうぶ だったｎ
	@ まけて なっとく って かんじ だぜ!

Route109_SeashoreHouse_Text_19B89F:: @ 819B89F
	.string "나는 잿빛도시에 올 때마다\n"
	.string "이곳의 뜨거운 승부와\l"
	.string "시원한 미네랄사이다를 즐기지!$"
	@ オレは カイナに くるたびにｎ
	@ ここで あつい しょうぶとｌ
	@ つめたい サイコソ-ダを たのしむんだ!

Route109_SeashoreHouse_Text_19B8E5:: @ 819B8E5
	.string "따분한 승부는 필요 없어!\p"
	.string "타오르는 듯한 승부야말로\n"
	.string "트레이너와 포켓몬을 강하게 만들지!$"
	@ たいくつな しょうぶ なんて ムダ!ｐ
	@ もえあがるような しょうぶ こそｎ
	@ トレ-ナ-と ポケモンを きたえるのよ!

Route109_SeashoreHouse_Text_19B949:: @ 819B949
	.string "너무 뜨겁잖아!$"
	@ あつい じゃない!

Route109_SeashoreHouse_Text_19B955:: @ 819B955
	.string "아-아 목마르다\n"
	.string "미네랄사이다나 마실까?$"
	@ あ-あ のどが かわいちゃったｎ
	@ サイコソ-ダ のもうかな?

Route109_SeashoreHouse_Text_19B988:: @ 819B988
	.string "내 포켓몬의 굉장함을\n"
	.string "똑똑히 보여줄 테니까 울지 말라고!$"
	@ ぼくの ポケモンの すごいところｎ
	@ みせちゃうけど なかないでよ!

Route109_SeashoreHouse_Text_19B9C7:: @ 819B9C7
	.string "... 졌지만 울지 않겠어$"
	@ …… まけたけど なかないぞ

Route109_SeashoreHouse_Text_19B9E5:: @ 819B9E5
	.string "포켓몬이 날 태우고\n"
	.string "물 위를 나아가는 기술을 쓸 수 있다면\l"
	.string "튜브도 필요 없을 텐데$"
	@ ポケモンが ぼくを のせてｎ
	@ みずの うえを すすむ わざを つかえたらｌ
	@ うきわも いらなくなるのに
