Route119_WeatherInstitute_1F_Text_19EB8A:: @ 819EB8A
	.string "리더가 이곳의 연구에\n"
	.string "흥미가 있으셔서\l"
	.string "우리들을 보낸 거다! 방해하지 마!$"
	// リ-ダ-が ここでの けんきゅうにｎ
	// きょうみを もったらしくてｌ
	// おれらを よこしたんだ! ジャマするな!

Route119_WeatherInstitute_1F_Text_19EBEE:: @ 819EBEE
	.string "젠장-\n"
	.string "어린애한테 졌다...$"
	// くそ-ｎ
	// こどもに まけた……

Route119_WeatherInstitute_1F_Text_19EC0E:: @ 819EC0E
	.string "리더는 뭐든지 알고 있어...\p"
	.string "하지만 뭘 생각하고 있는 건지\n"
	.string "조무래기인 우리한텐 상상도 안 가$"
	// リ-ダ-は なんでも しっている……ｐ
	// しかし なにを かんがえて いるのかｎ
	// したっぱの おれらには さっぱりだ

Route119_WeatherInstitute_1F_Text_19EC6B:: @ 819EC6B
	.string "어라?\n"
	.string "왜 여기에 어린애가 있는 거지?$"
	// あら?ｎ
	// どうして ここに こどもが いるのかしら?

Route119_WeatherInstitute_1F_Text_19EC89:: @ 819EC89
	.string "어라-\n"
	.string "져버린 건가-!?$"
	// あら-ｎ
	// まけちゃった-!?

Route119_WeatherInstitute_1F_Text_19EC97:: @ 819EC97
	.string "어라라...\n"
	.string "어린애한테 진 걸 들키면 혼날 거야...\p"
	.string "침대에서 자는 척이라도 할까?$"
	// あらら……ｎ
	// こどもに まけたら おこられちゃう……ｐ
	// ベッドで ねてようかしら?

Route119_WeatherInstitute_1F_Text_19ECF4:: @ 819ECF4
	.string "내가 침대에서 자는 동안\n"
	.string "모두 2층으로 가버렸어$"
	// ぼくが ベッドで ねてる あいだにｎ
	// みんな 2かいに いっちゃったよ

Route119_WeatherInstitute_1F_Text_19ED22:: @ 819ED22
	.string "{K_BOY_CALL} 강하네!\p"
	.string "나도 {K_BOY_CALL} 같은\n"
	.string "포켓몬 트레이너가 되고 싶어!$"
	// §い つよいんだね!ｐ
	// ぼくも §い みたいなｎ
	// ポケモントレ-ナ-に なりたいや!

Route119_WeatherInstitute_1F_Text_19ED6B:: @ 819ED6B
	.string "박사님은 비를 정말 좋아해요\p"
	.string "그렇지만 계속 비가 내리면\n"
	.string "곤란해지는 사람도 있죠\p"
	.string "그래서 박사님은\n"
	.string "이 비를 무언가로\l"
	.string "바꿔 쓸 수 없을까 하고\l"
	.string "연구하고 있어요$"
	// はかせは あめが だいすき なのですｐ
	// ですが あめが ふりつづくとｎ
	// こまってしまう ひとも いるわけですｐ
	// そこで はかせはｎ
	// この あめを なにかに つかえないかｌ
	// けんきゅう なさっているのです

Route119_WeatherInstitute_1F_Text_19EE25:: @ 819EE25
	.string "안녕하세요!\n"
	.string "당신 덕분에 살았습니다!\l"
	.string "그건 그렇고...\p"
	.string "{EVIL_TEAM}단 녀석들은\n"
	.string "무슨 짓을 하려고 했던 걸까요?$"
	// やあ!ｎ
	// あなたの おかげで たすかりましたよ!ｌ
	// それにしても……ｐ
	// §くの れんちゅうはｎ
	// なにを するつもり だったのでしょう?

Route119_WeatherInstitute_1F_Text_19EE8B:: @ 819EE8B
	.string "침대가 있다...\n"
	.string "조금 쉬었다 가자$"
	// ベッドが ある……ｎ
	// やすんでいこう
