PetalburgCity_PokemonCenter_1F_Text_17BD30:: @ 817BD30
	.string "PC를 이용한\n"
	.string "포켓몬 보관 시스템이라니...\p"
	.string "만든 녀석은\n"
	.string "엄청나게 과학에 빠삭할 거야!$"
	@ パソコンで つかえるｎ
	@ ポケモン あずかり システム……ｐ
	@ つくった やつはｎ
	@ すげ- かがくに くわしいんだろうな!

PetalburgCity_PokemonCenter_1F_Text_17BD92:: @ 817BD92
	.string "포켓몬한테 오랭열매를 먹였더니\n"
	.string "체력을 회복했어!$"
	@ ポケモンに オレンのみ を たべさせたらｎ
	@ たいりょくが かいふく したんだぜ!

PetalburgCity_PokemonCenter_1F_Text_17BDC5:: @ 817BDC5
	.string "포켓몬에겐\n"
	.string "다양한 타입이 있어!\p"
	.string "그리고 타입에는 상성이 있어서\n"
	.string "포켓몬 승부를 할 때\l"
	.string "유리할 때도 있고 불리할 때도 있지$"
	@ ポケモンにはｎ
	@ いろいろ タイプが あるの!ｐ
	@ で タイプには あいしょうが あるからｎ
	@ ポケモンしょうぶの ときｌ
	@ ゆうり だったり ふり だったりするの

PetalburgCity_PokemonCenter_1F_Text_17BE6C:: @ 817BE6C
	.string "예를 들면 너의 나무지기는\n"
	.string "풀타입이니까\p"
	.string "물타입이나 땅타입에 강하고\n"
	.string "불꽃타입에는 약해!$"
	@ たとえば あなたの キモリはｎ
	@ くさタイプ でしょｐ
	@ みずタイプや じめんタイプに つよくてｎ
	@ ほのおタイプが にがて なのよね!

PetalburgCity_PokemonCenter_1F_Text_17BEF1:: @ 817BEF1
	.string "예를 들면 너의 아차모는\n"
	.string "불꽃타입이니까\p"
	.string "풀타입이나 벌레타입에 강하고\n"
	.string "물타입에는 약해!$"
	@ たとえば あなたのｎ
	@ アチャモは ほのおタイプ でしょｐ
	@ くさタイプや むしタイプに つよくてｎ
	@ みずタイプが にがて なんだ!

PetalburgCity_PokemonCenter_1F_Text_17BF73:: @ 817BF73
	.string "예를 들면 너의 물짱이는\n"
	.string "물타입이니까\p"
	.string "불꽃타입에 강하고\n"
	.string "풀타입이나 전기타입에는 약해!$"
	@ たとえば あなたのｎ
	@ ミズゴロウは みずタイプ だよねｐ
	@ ほのおタイプに つよくてｎ
	@ くさタイプや でんきタイプが にがて ね!
