MossdeepCity_PokemonCenter_1F_Text_18D62F:: @ 818D62F
	.string "이 마을의 체육관 관장\n"
	.string "다른 걸 떠나서 그 콤비네이션은\l"
	.string "역시 최고야! 라는 느낌이야$"
	// この まちの ジムリ-ダ-ｎ
	// なんといっても あの コンビネ-ションはｌ
	// さいこう! さすが! って かんじよ

MossdeepCity_PokemonCenter_1F_Text_18D69A:: @ 818D69A
	.string "포켓몬의 특성에 의해서\n"
	.string "기술의 위력이 바뀌거나\l"
	.string "효과가 없기도 해!$"
	// ポケモンの とくせいに よってはｎ
	// わざの いりょくが かわったりｌ
	// まったく きかなかったり するよ!
