SootopolisCity_House3_Text_18FB36:: @ 818FB36
	.string "너 포켓몬 트레이너야?\p"
	.string "루네시티의 체육관 관장\n"
	.string "윤진님은 팬이 많던데\l"
	.string "너한테는 팬이 있니?$"
	// あなた ポケモン トレ-ナ-ね?ｐ
	// ルネの ジムリ-ダ-ｎ
	// ミクリさまには ファンが いっぱいだけどｌ
	// あなたに ファンは いるのかしら?

SootopolisCity_House3_Text_18FB9C:: @ 818FB9C
	.string "헤에-\n"
	.string "그럼 꽤 강한가 보네!$"
	// へえ-ｎ
	// じゃあ けっこう つよいのね!

SootopolisCity_House3_Text_18FBC0:: @ 818FBC0
	.string "어머머...\n"
	.string "그건 좀 슬프다\p"
	.string "팬이 생기도록 열심히 해봐!$"
	// あららん……ｎ
	// それは ちょっと さみしいわねｐ
	// ファンが できるよう がんばりなさいよ!

SootopolisCity_House3_Text_18FC1A:: @ 818FC1A
	.string "열성적인 팬들은\n"
	.string "관동이나 성도에서도 찾아와!\p"
	.string "내가 해안시티의\n"
	.string "트레이너 팬클럽에 갔을 때도\l"
	.string "엄청 굉장했어!$"
	// ねっしんな ファンだとｎ
	// カント-や ジョウトからも やってくるの!ｐ
	// あたしが ミナモのｎ
	// トレ-ナ- ファンクラブに いったときもｌ
	// とっても すごかったもの!
