Route110_TrickHousePuzzle2_Text_19CD46:: @ 819CD46
	.string "어느 스위치로\n"
	.string "어느 구멍이 닫히는 거지?$"
	// どの スイッチでｎ
	// どの あなが ふさがるんだ?

Route110_TrickHousePuzzle2_Text_19CD66:: @ 819CD66
	.string "승부했더니\n"
	.string "더 알 수 없게 됐어!$"
	// しょうぶ してたらｎ
	// よけい わかんなくなった!

Route110_TrickHousePuzzle2_Text_19CD91:: @ 819CD91
	.string "너 나 대신에\n"
	.string "스위치 전부 눌러주라!$"
	// きみ ぼくの かわりにｎ
	// スイッチ ぜんぶ おしてきてよ!

Route110_TrickHousePuzzle2_Text_19CDBF:: @ 819CDBF
	.string "오옷! 미궁의 대저택에서의\n"
	.string "2번째 챌린지구나!$"
	// おっ! カラクリやしきｎ
	// 2どめの チャレンジだね!

Route110_TrickHousePuzzle2_Text_19CDF0:: @ 819CDF0
	.string "포켓몬 승부도\n"
	.string "잘하는 거야?$"
	// ポケモンしょうぶもｎ
	// そんなに つよいの?

Route110_TrickHousePuzzle2_Text_19CE0D:: @ 819CE0D
	.string "미궁대왕이 혼자서\n"
	.string "이 장치들을 만들었대!$"
	// カラクリだいおうが ひとりでｎ
	// この しかけを つくってるんだって!

Route110_TrickHousePuzzle2_Text_19CE52:: @ 819CE52
	.string "언젠가 내 체육관을 만들고 싶어서\n"
	.string "이곳의 장치들을 연구하고 있어!$"
	// いつか わたしの ジムを つくりたくてｎ
	// しかけを けんきゅうしてるの!

Route110_TrickHousePuzzle2_Text_19CE98:: @ 819CE98
	.string "포켓몬 승부는\n"
	.string "연구가 부족했어-!$"
	// ポケモンしょうぶはｎ
	// けんきゅう ぶそく だったわ-っ!

Route110_TrickHousePuzzle2_Text_19CEB8:: @ 819CEB8
	.string "너 강하구나...\n"
	.string "체육관 관장이 될 수 있을 거 같은데?$"
	// あなた つよいのね…ｎ
	// ジムリ-ダ-に なれるんじゃない?

UnknownString_819CEF9: @ 819CEF9
	.string "{PLAYER}{K_EUNNEUN} 암호를\n"
	.string "문에 적었다!\p"
	.string "“미궁대왕님 존경해”\p"
	.string "...... ...... ......\p"
	.string "문의 자물쇠가 풀렸다!$"
