MossdeepCity_GameCorner_1F_Text_18E59A:: @ 818E59A
	.string "나도 젊었을 때는\n"
	.string "포켓몬 트레이너로서\l"
	.string "전 세계를 여행했었지\p"
	.string "할아버지가 되어버린 지금은\n"
	.string "젊은 트레이너의 승부를 보는 게\l"
	.string "유일한 낙이라네$"
	// わしも わかいころは ｎ
	// ポケモン トレ-ナ-としてｌ
	// せかいじゅうを たび していたのじゃｐ
	// ジジイとなった いまではｎ
	// わかい トレ-ナ-の しょうぶを みるのがｌ
	// ゆいいつの たのしみ じゃ

MossdeepCity_GameCorner_1F_Text_18E631:: @ 818E631
	.string "문이 잠겨 있는 것 같다!$"
	// とびらには かぎが かかって いるようだ!

MossdeepCity_GameCorner_1F_Text_18E650:: @ 818E650
	.string "지금 {STR_VAR_1}{K_I}라는 트레이너가\n"
	.string "내 집에 와 있네!\p"
	.string "{STR_VAR_1}{K_WAGWA} 승부하려는 게지?$"
	// いまは §い という トレ-ナ-がｎ
	// わしの いえに きておる!ｐ
	// §いと しょうぶ してみたいのじゃな?

MossdeepCity_GameCorner_1F_Text_18E698:: @ 818E698
	.string "승부하지 않는 겐가...\n"
	.string "승부를 볼 수 없어서 안타깝구먼...$"
	// しょうぶ せんのか……ｎ
	// しょうぶを みられなくて ガッカリ……

MossdeepCity_GameCorner_1F_Text_18E6DA:: @ 818E6DA
	.string "오오 그래그래!\p"
	.string "헌데 이 집은\n"
	.string "그다지 튼튼하지 않으니까\p"
	.string "많아도 3대3\n"
	.string "승부로 해 주지 않겠나?$"
	// おお そうか そうか!ｐ
	// じゃが この いえはｎ
	// あんまり がんじょう じゃないからｐ
	// せめて 3たい3のｎ
	// しょうぶに して くれんかのう?

MossdeepCity_GameCorner_1F_Text_18E741:: @ 818E741
	.string "그럼 승부 전에\n"
	.string "리포트를 써 두는 편이 좋겠구먼$"
	// じゃあ しょうぶの まえにｎ
	// レポ-トを かいて おいたほうが よいぞ

MossdeepCity_GameCorner_1F_Text_18E777:: @ 818E777
	.string "좋은 승부를 기대하고 있겠네!$"
	// よい しょうぶを きたい しておるぞ!

UnknownString_818E793: @ 818E793
	.string "{STR_VAR_1}$"
	// §い

MossdeepCity_GameCorner_B1F_Text_18E796:: @ 818E796
	.string "승부는 무승부로 끝났다!$"
	// しょうぶは ひきわけに おわった!

MossdeepCity_GameCorner_1F_Text_18E7B1:: @ 818E7B1
	.string "무승부였나!\p"
	.string "서로 한 치도 용납하지 않는\n"
	.string "굉장한 승부였다네!$"
	// ひきわけ じゃったか!ｐ
	// おたがい いっぽも ゆずらぬｎ
	// すばらしい しょうぶ じゃったぞ!

UnknownString_818E80B: @ 818E80B
	.string "{STR_VAR_1}$"
	// §い

MossdeepCity_GameCorner_1F_Text_18E80E:: @ 818E80E
	.string "훌륭했네!\p"
	.string "마치 내 젊은 시절을\n"
	.string "보는 것 같구먼!$"
	// みごと じゃったぞ!ｐ
	// まるで わしの わかい ころをｎ
	// みている ようじゃわい!

UnknownString_818E856: @ 818E856
	.string "{STR_VAR_1}$"
	// §い

MossdeepCity_GameCorner_1F_Text_18E859:: @ 818E859
	.string "유감이구먼\n"
	.string "하지만 좋은 승부였네!\l"
	.string "다음번엔 이기면 좋겠구먼!$"
	// ざんねん じゃったのうｎ
	// じゃが よい しょうぶ じゃったぞ!ｌ
	// つぎこそは かてると よいのう
