RustboroCity_DevonCorp_1F_Text_1828EE:: @ 81828EE
	.string "어서 오세요!\n"
	.string "데봉 코포레이션입니다!\p"
	.string "여러분의 생활에 도움이 되는\n"
	.string "도구나 약을 만들고 있습니다!$"
	// いらっしゃいませ!ｎ
	// デボン コ-ポレ-ション です!ｐ
	// みなさまの せいかつに やくだつｎ
	// どうぐや くすりを おつくりしてます!

RustboroCity_DevonCorp_1F_Text_18295E:: @ 818295E
	.string "얼빠진 연구원이\n"
	.string "화물을 빼앗겨서...$"
	// ドジな けんきゅういんがｎ
	// にもつを とられちゃって……

RustboroCity_DevonCorp_1F_Text_1829A4:: @ 81829A4
	.string "오! 러닝슈즈!\p"
	.string "우리 회사의 상품을\n"
	.string "실제로 쓰고 있는 사람을 보면\l"
	.string "굉장히 기뻐지지!$"
	// おっ! ランニングシュ-ズ!ｐ
	// じぶんたちの かいしゃの しょうひんをｎ
	// じっさいに つかっている ひとを みるとｌ
	// すごく うれしくなるよね!

RustboroCity_DevonCorp_1F_Text_182A19:: @ 8182A19
	.string "확실히 그 화물은\n"
	.string "소중한 물건이지만\l"
	.string "다른 사람이 훔쳐가도\l"
	.string "사용할 수 없을 거라 생각해\p"
	.string "내 추리로는 그 도둑...\n"
	.string "그냥 멍청이 아니었을까?$"
	// たしかに あの にもつはｎ
	// だいじな もの だけどｌ
	// ほかの ひとが ぬすんでいってもｌ
	// つかえないと おもうんだよねｐ
	// ぼくの すいりでは あの どろぼう……ｎ
	// たんなる マヌケ なんじゃないかな?

RustboroCity_DevonCorp_1F_Text_182AB3:: @ 8182AB3
	.string "아무래도 데봉화물은\n"
	.string "다시 돌아온 모양이야$"
	// どうやら デボンのにもつはｎ
	// もどってきた らしいね

RustboroCity_DevonCorp_1F_Text_182AF0:: @ 8182AF0
	.string "어이쿠 관계자가 아니신 분은\n"
	.string "여기서부터 앞으로 가실 수 없습니다!$"
	// おっと かんけいしゃ いがいの かたはｎ
	// ここから さきには はいれませんよ!

RustboroCity_DevonCorp_1F_Text_182B2D:: @ 8182B2D
	.string "도둑에게 화물을 빼앗기다니\n"
	.string "왜 이렇게 얼빠진 거야...$"
	// どろぼうに にもつを うばわれるなんてｎ
	// なんて ドジなんだろう……

RustboroCity_DevonCorp_1F_Text_182B5A:: @ 8182B5A
	.string "오!\n"
	.string "너라면 언제나 환영이지!$"
	// やあ!ｎ
	// きみなら いつでも だいかんげい だよ!
