VerdanturfTown_FriendshipRatersHouse_Text_178A9C:: @ 8178A9C
	.string "당신의 포켓몬이\n"
	.string "얼마나 따르고 있는지 봐줄게\p"
	.string "어머...\n"
	.string "당신의 포켓몬$"
	@ あなたの ポケモンがｎ
	@ どれくらい なついているか みてあげるｐ
	@ あら……ｎ
	@ あなたの ポケモン

VerdanturfTown_FriendshipRatersHouse_Text_178AF2:: @ 8178AF2
	.string "더 이상은 없을 정도로\n"
	.string "당신을 따르고 있네\l"
	.string "보고 있는 이쪽도 행복해지는걸!$"
	@ これいじょうは ない ってぐらいｎ
	@ あなたに なついているわねｌ
	@ みている こっちも しあわせに なるわ!

VerdanturfTown_FriendshipRatersHouse_Text_178B43:: @ 8178B43
	.string "왠지 행복해 보여\n"
	.string "굉장히 당신을 따르고 있네$"
	@ なんだか しあわせそうｎ
	@ すごく あなたに なついているわね

VerdanturfTown_FriendshipRatersHouse_Text_178B82:: @ 8178B82
	.string "꽤 따르고 있네\n"
	.string "당신에게 어리광 부리고 싶은가 봐$"
	@ かなり なついているわねｎ
	@ あなたに あまえたそうに しているわよ

VerdanturfTown_FriendshipRatersHouse_Text_178BC4:: @ 8178BC4
	.string "조금 따르기 시작한 느낌이야\n"
	.string "당신을 믿고 있는 것 같아$"
	@ ちょっと なついてきた って かんじ かなｎ
	@ あなたのこと しんじている みたい

VerdanturfTown_FriendshipRatersHouse_Text_178BFA:: @ 8178BFA
	.string "아직 당신을 따르지는 않는 것 같아\n"
	.string "평범한 관계라는 느낌이 들어$"
	@ まだ あなたに なれていない ようねｎ
	@ ふつうの かんけい って かんじが するわ

VerdanturfTown_FriendshipRatersHouse_Text_178C39:: @ 8178C39
	.string "...왠지 경계하고 있는 듯해\n"
	.string "눈초리도 조금 무섭고\l"
	.string "전혀 당신을 따르지 않고 있어$"
	@ …… なんだか けいかい しているみたいｎ
	@ めつきも ちょっと こわいしｌ
	@ ぜんぜん あなたに なついていないわ

VerdanturfTown_FriendshipRatersHouse_Text_178C90:: @ 8178C90
	.string "...좀 말하기 그렇지만\p"
	.string "당신 자기 포켓몬에게\n"
	.string "그렇게 미움받아도 괜찮아?$"
	@ …… ちょっと いいづらいんだけどｐ
	@ あなた じぶんの ポケモンにｎ
	@ そんなに きらわれていて だいじょうぶ?

VerdanturfTown_FriendshipRatersHouse_Text_178CFD:: @ 8178CFD
	.string "피카츄: 피카 피카!$"
	@ ピカチュウ『ピカピカッ!
