Route110_TrickHousePuzzle4_Text_19D1DE:: @ 819D1DE
	.string "이런 걸 생각해야 한다니 귀찮아!\n"
	.string "난 승부만 하고 싶은데-!$"
	@ こういうの かんがえるのって めんどう!ｎ
	@ わたしは しょうぶだけ したいのに-!

Route110_TrickHousePuzzle4_Text_19D21F:: @ 819D21F
	.string "져버렸지만 역시\n"
	.string "승부가 제일 즐거워!$"
	@ まけちゃった けど やっぱりｎ
	@ しょうぶが いちばん たのしい!

Route110_TrickHousePuzzle4_Text_19D253:: @ 819D253
	.string "트레이너가 있을 것 같은 곳이라면\n"
	.string "어디든 가고 싶어져!$"
	@ トレ-ナ-が いそうな ところはｎ
	@ どこにでも いきたく なるわよね!

Route110_TrickHousePuzzle4_Text_19D295:: @ 819D295
	.string "이 정도 바위는\n"
	.string "손가락 하나로도 껌이라고!$"
	@ このくらいの いわはｎ
	@ ゆび いっぽんで らくしょう だぜ!

Route110_TrickHousePuzzle4_Text_19D2D1:: @ 819D2D1
	.string "바위를 밀어도\n"
	.string "퍼즐이 풀리지 않아...$"
	@ いわが おせてもｎ
	@ パズルが とけない……

Route110_TrickHousePuzzle4_Text_19D306:: @ 819D306
	.string "힘만 세다고 되는 게 아니군...\n"
	.string "머리를 써야 하는 건가$"
	@ ちからが つよいだけじゃ ダメだね……ｎ
	@ アタマ つかわないと

Route110_TrickHousePuzzle4_Text_19D351:: @ 819D351
	.string "미궁의 대저택도 점점\n"
	.string "어려워지기 시작했네!$"
	@ カラクリやしきも だんだんｎ
	@ むずかしく なってきたわね!

Route110_TrickHousePuzzle4_Text_19D380:: @ 819D380
	.string "아앗!$"
	@ ああっ!

Route110_TrickHousePuzzle4_Text_19D386:: @ 819D386
	.string "마지막까지 남을\n"
	.string "사람이 있을지 모르겠네?$"
	@ さいごまで いったｎ
	@ ひとって いるのかしらね?

UnknownString_819D3A5: @ 819D3A5
	.string "{PLAYER}{K_EUNNEUN} 암호를\n"
	.string "문에 적었다!\p"
	.string "“미궁대왕님 천재”\p"
	.string "...... ...... ......\p"
	.string "문의 자물쇠가 풀렸다!$"
	@ §あは あいことばをｎ
	@ とびらに かきつけた!ｐ
	@ 「カラクリだいおう さま てんさい」ｐ
	@ …… …… ……ｐ
	@ かぎの はずれる おとがした!
