SlateportCity_OceanicMuseum_2F_Text_17ECFD:: @ 817ECFD
	.string "응? 해양관장은 나인데...?\p"
	.string "오오! 그건 데봉의 나발명씨에게\n"
	.string "부탁해둔 파츠구나!\p"
	.string "이야- 정말 수고했다!\n"
	.string "덕분에 출발할 수 있을 것 같군...$"
	// はい? クスノキは わたし だが……?ｐ
	// おお! それは デボンの ツワブキさんにｎ
	// たのんで おいた パ-ツだね!ｐ
	// いや- どうも ごくろうさま!ｎ
	// おかげで しゅっぱつ できそうだ……

SlateportCity_OceanicMuseum_2F_Text_17EDAE:: @ 817EDAE
	.string "헤헤헤 그 파츠는\n"
	.string "우리가 접수하도록 하지!$"
	// へへへ その パ-ツｎ
	// おれたちが いただくぜ!

SlateportCity_OceanicMuseum_2F_Text_17EDD7:: @ 817EDD7
	.string "해양: 누... 누구냐 너희는!$"
	// クスノキ『だ だれだ きみたちは!

SlateportCity_OceanicMuseum_2F_Text_17EE01:: @ 817EE01
	.string "우리는 {EVIL_TEAM}단!\p"
	.string "리더가 그 파츠를 원하고 있다!\n"
	.string "아무 말 말고 내놔!$"
	// おれたち §くだん!ｐ
	// リ-ダ-が そのパ-ツを ほしがってるんだ!ｎ
	// なにも いわずに よこせ!

SlateportCity_OceanicMuseum_2F_Text_17EE4E:: @ 817EE4E
	.string "으악-!\n"
	.string "어린애한테 당했다!$"
	// うわ-!ｎ
	// こどもに やられちまった!

SlateportCity_OceanicMuseum_2F_Text_17EE66:: @ 817EE66
	.string "위험한데...\n"
	.string "리더에게 혼나고 말 거야...$"
	// やばい……ｎ
	// リ-ダ-に おこられちまうぞ……

SlateportCity_OceanicMuseum_2F_Text_17EEA5:: @ 817EEA5
	.string "흥! 칠칠치 못한 녀석 같으니!\n"
	.string "여기선 나한테 맡기라고!$"
	// ふん! だらしない やつめ!ｎ
	// ここは おれに まかせてもらうぜ!

SlateportCity_OceanicMuseum_2F_Text_17EED6:: @ 817EED6
	.string "말도 안 돼!\n"
	.string "나도 져버렸어!$"
	// なんだと!ｎ
	// おれも まけてしまった!

SlateportCity_OceanicMuseum_2F_Text_17EEEA:: @ 817EEEA
	.string "어 어떡하지...\n"
	.string "파츠를 뺏지 못하면 곤란하지 않나?\p"
	.string "으음...\n"
	.string "설마 어린애에게 방해받다니\l"
	.string "눈곱만큼도 생각 못 했어$"
	// ど どうしよう……ｎ
	// パ-ツを うばえないと まずくないか?ｐ
	// うむ……ｎ
	// まさか こどもに じゃま されるなんてｌ
	// これっぽっちも おもってなかったぜ

SlateportCity_OceanicMuseum_2F_Text_17EF62:: @ 817EF62
	.string "파츠를 빼앗는데\n"
	.string "언제까지 걸리나 했더니\l"
	.string "이런 꼬마에게 방해받고 있었나?$"
	// パ-ツを うばうのにｎ
	// いつまで かかっているのかと おもえばｌ
	// こんな こどもに じゃま されていたのか?

SlateportCity_OceanicMuseum_2F_Text_17EFC9:: @ 817EFC9
	.string "나는 아쿠아단의 아강\p"
	.string "너는 왜 우리\n"
	.string "아쿠아단을 방해하는 거지?\p"
	.string "포켓몬도 사람도 모든 생명은\n"
	.string "바다에서 태어났다...\p"
	.string "그래서 아쿠아단은\n"
	.string "바다를 넓히려 하는 것이지\p"
	.string "어때?\n"
	.string "엄청 대단한 일이지?\p"
	.string "뭐 됐다...\n"
	.string "넌 아직 어리니까\p"
	.string "우리의 이상을\n"
	.string "이해하지 못해도 어쩔 수 없지...\p"
	.string "하지만 앞으로도 우리들의\n"
	.string "활동을 방해할 생각이라면\l"
	.string "그냥은 두지 않을 거다!\p"
	.string "그것만은 기억해 둬라!\n"
	.string "그럼 작별이다!$"
	// わたしは アクアだんの アオギリｐ
	// きみは なぜ われわれｎ
	// アクアだんの じゃまを するのかね?ｐ
	// ポケモンも ひとも すべての いのちはｎ
	// うみから うまれた……ｐ
	// だから アクアだんはｎ
	// うみを ふやそうと しているのだよｐ
	// どうだい?ｎ
	// とても すばらしいこと だろう?ｐ
	// まあ いい……ｎ
	// きみは まだ わかい からなｐ
	// われわれの りそうをｎ
	// りかい できなくても しかたが ない……ｐ
	// だが このさきも われわれのｎ
	// かつどうを じゃまする ようであればｌ
	// ただでは すまさない からな!ｐ
	// それだけは おぼえて おきたまえ!ｎ
	// では さらばだ!

SlateportCity_OceanicMuseum_2F_Text_17F17E:: @ 817F17E
	.string "나는 마그마단의 마적\p"
	.string "너는 왜 우리\n"
	.string "마그마단을 방해하는 거지?\p"
	.string "포켓몬도 사람도 모든 생명이\n"
	.string "대지에서 살아간다...\p"
	.string "그래서 마그마단은\n"
	.string "대지를 넓히려 하는 것이지\p"
	.string "어떤가?\n"
	.string "참으로 대단한 일 아닌가?\p"
	.string "뭐 됐다...\n"
	.string "넌 아직 어리니까\p"
	.string "우리의 이상을\n"
	.string "이해하지 못해도 어쩔 수 없지...\p"
	.string "하지만 앞으로도 우리들의\n"
	.string "활동을 방해할 생각이라면\l"
	.string "그냥은 넘어가지 않겠다!\p"
	.string "그것만은 절대로 잊지 말도록!\n"
	.string "그럼 작별이다!$"
	// わたしは マグマだんの マツブサｐ
	// きみは なぜ われわれｎ
	// マグマだんの じゃまを するのかね?ｐ
	// ポケモンも ひとも すべての いのちはｎ
	// だいちで すごす……ｐ
	// だから マグマだんはｎ
	// だいちを ふやそうと しているのだよｐ
	// どうだい?ｎ
	// とても すばらしいこと だろう?ｐ
	// まあ いい……ｎ
	// きみは まだ わかい からなｐ
	// われわれの りそうをｎ
	// りかい できなくても しかたが ない……ｐ
	// だが このさきも われわれのｎ
	// かつどうを じゃまする ようであればｌ
	// ただでは すまさない からな!ｐ
	// それだけは おぼえて おきたまえ!ｎ
	// では さらばだ!

SlateportCity_OceanicMuseum_2F_Text_17F352:: @ 817F352
	.string "해양: 넌...\n"
	.string "그렇군 {PLAYER}{K_I}라고 하는구나...\p"
	.string "이거 큰일 날 뻔했어!\n"
	.string "도와줘서 고마워!\p"
	.string "참 그렇지!\n"
	.string "네가 데봉에 부탁해뒀던 파츠를\l"
	.string "가져온 걸 깜빡했구나!$"
	// クスノキ『きみは……ｎ
	// そうか §あ§お というのか……ｐ
	// いやあ あぶない ところ だった!ｎ
	// たすけてくれて ありがとうよ!ｐ
	// おっと そうだった!ｎ
	// デボンに たのんでおいた パ-ツをｌ
	// もってきて くれたの わすれていたよ!

UnknownString_817F404: @ 817F404
	.string "{PLAYER}{K_EUNNEUN} 해양관장에게\n"
	.string "데봉화물을 건넸다!$"
	// §あは クスノキかんちょうにｎ
	// デボンのにもつを わたした!

SlateportCity_OceanicMuseum_2F_Text_17F433:: @ 817F433
	.string "해양: 어이쿠!\n"
	.string "이러고 있을 때가 아니지!\p"
	.string "슬슬 해저 조사하러\n"
	.string "출발할 시간이군!\p"
	.string "나는 이만 실례할게!$"
	// クスノキ『おっと!ｎ
	// こうしちゃ いられない!ｐ
	// そろそろ かいてい ちょうさにｎ
	// しゅっぱつ する じかんだ!ｐ
	// じゃあ これで しつれい するよ!

SlateportCity_OceanicMuseum_2F_Text_17F4B6:: @ 817F4B6
	.string "배 모형을 보고 있자니\n"
	.string "무로마을 근처의\l"
	.string "버려진 배가 생각나는구먼...$"
	// ふねの もけいを みておるとｎ
	// ムロの ちかくに あるｌ
	// すてられぶねを おもいだすのう……

SlateportCity_OceanicMuseum_2F_Text_17F50E:: @ 817F50E
	.string "박물관 안에서\n"
	.string "뛰어다니면 못써!$"
	// はくぶつかんの なかをｎ
	// はしり まわるんじゃ ありませんよッ!

SlateportCity_OceanicMuseum_2F_Text_17F53B:: @ 817F53B
	.string "잠수정 멋있다-!\n"
	.string "나도 타고 싶어-!$"
	// せんすいてい かっこい-!ｎ
	// おれも のりて-よ!

SlateportCity_OceanicMuseum_2F_Text_17F572:: @ 817F572
	.string "“관동의 수질 샘플”\n"
	.string "이라고 적힌 라벨이 붙어 있다!\p"
	.string "바다는 모두 연결되어 있는데도\n"
	.string "지역에 따라 조금씩 차이가 있는 듯하다$"
	// 「カント-の すいしつ サンプル」ｎ
	// と かかれた ラベルが はってある!ｐ
	// うみは みんな つながって いるのにｎ
	// ちいきに よって すこし ちがうらしい

SlateportCity_OceanicMuseum_2F_Text_17F5E3:: @ 817F5E3
	.string "“성도의 수질 샘플”\n"
	.string "이라고 적힌 라벨이 붙어 있다!\p"
	.string "지역이 다르면 바닷물의\n"
	.string "짠맛도 달라지는 걸까?$"
	// 「ジョウトの すいしつ サンプル」ｎ
	// と かかれた ラベルが はってある!ｐ
	// ちいきが ちがえば うみの みずのｎ
	// しょっぱさも ちがったり するのかな?

SlateportCity_OceanicMuseum_2F_Text_17F653:: @ 817F653
	.string "고무로 만들어진 볼이\n"
	.string "팽창과 수축을 반복하고 있다!\p"
	.string "“바닷속에서는 수압이라는\n"
	.string "  물 자체의 무게가 가해집니다”\p"
	.string "“얕은 곳에서는 수압이 약하고\n"
	.string "  깊은 곳에서는 몇만 톤에 달하는\l"
	.string "  수압의 영향을 받게 됩니다”$"
	// ゴムで できた ボ-ルがｎ
	// ふくらんだり しぼんだり している!ｐ
	// 「うみの そこには すいあつ といってｎ
	//  みずじたいの おもさが かかります」ｐ
	//  あさい ところでは すいあつも かるくｎ
	//  ふかい ところでは なんまんトン ものｌ
	//  すいあつが かかるのです」

SlateportCity_OceanicMuseum_2F_Text_17F754:: @ 817F754
	.string "“호연지방의 모형”\p"
	.string "호연지방 전체를 축소한 모형이다!\n"
	.string "미로마을은 어디쯤일까?$"
	// 「ホウエン ちほうの もけい」ｐ
	// ホウエンちほう ぜんたいの ミニチュアだ!ｎ
	// ミシロタウンは どのへん だろう?

SlateportCity_OceanicMuseum_2F_Text_17F7BC:: @ 817F7BC
	.string "해수의 흐름에 대한 전시물이다!\p"
	.string "“바다의 바닥 가까운 곳에서는\n"
	.string "  물 온도나 염분의 차이로\l"
	.string "  바닷물이 흘러갑니다”$"
	// かいすいの ながれに ついての てんじだ!ｐ
	// 「うみの そこに ちかい ところ ではｎ
	//  みずの おんどや えんぶんの ちがいでｌ
	//  うみの みずが ながれて いきます」

SlateportCity_OceanicMuseum_2F_Text_17F84E:: @ 817F84E
	.string "해수의 흐름에 대한 전시물이다!\p"
	.string "“바다 표면 근처에서는\n"
	.string "  바람의 힘에 의해\l"
	.string "  바닷물이 흘러갑니다”$"
	// かいすいの ながれに ついての てんじだ!ｐ
	// 「うみの ひょうめん あたり ではｎ
	//  かぜの ちからに よってｌ
	//  うみの みずが ながれて いきます」

SlateportCity_OceanicMuseum_2F_Text_17F8BC:: @ 817F8BC
	.string "“연락선 타이드립호”\p"
	.string "이것은 현재 해양조선소에서\n"
	.string "만들어지고 있는 배의 모형입니다!$"
	// 「れんらくせん タイドリップごう」ｐ
	// これは げんざい クスノキ ぞうせんじょでｎ
	// つくられている ふねの もけい です!

SlateportCity_OceanicMuseum_2F_Text_17F918:: @ 817F918
	.string "“잠수정 해연 1호”\p"
	.string "바다 밑을 조사하기 위한\n"
	.string "고성능 잠수정의 모형입니다!$"
	// 「せんすいてい かいえん 1ごう」ｐ
	// うみの そこを ちょうさ するためのｎ
	// こうせいのう せんすいていの もけい です!

SlateportCity_OceanicMuseum_2F_Text_17F975:: @ 817F975
	.string "“잠수파드”\p"
	.string "해저에서 작업하기 위한\n"
	.string "무인 소형 파드의 모형입니다!$"
	// 「せんすい ポッド」ｐ
	// かいていで さぎょうを するためのｎ
	// むじん こがたポッドの もけい です!

SlateportCity_OceanicMuseum_2F_Text_17F9C7:: @ 817F9C7
	.string "“상트앙느호”\p"
	.string "세계를 일주하고 있는\n"
	.string "호화 여객선의 모형입니다!$"
	// 「サント®アンヌ ごう」ｐ
	// せかいを いっしゅう しているｎ
	// ごうか きゃくせんの もけい です!
