PacifidlogTown_House2_Text_1790C1:: @ 81790C1
	.string "엣헴!!\p"
	.string "제가 포켓몬애호가클럽에서\n"
	.string "제-일 높은 회장의...\p"
	.string "남동생입니다!\p"
	.string "뭐 여기에서 포켓몬과 같이\n"
	.string "바캉스를 즐기고 있지요!$"
	@ ウォッホン!!ｐ
	@ わしが ポケモン だいすきクラブでｎ
	@ いちば-ん えらい かいちょうの……ｐ
	@ おとうと ですぞ!ｐ
	@ まあ ここで ポケモンと いっしょにｎ
	@ バカンスを たのしんで おるのですな!

PacifidlogTown_House2_Text_179155:: @ 8179155
	.string "호오!\n"
	.string "당신의 포켓몬...$"
	@ ほう!ｎ
	@ きみの ポケモン……

PacifidlogTown_House2_Text_179169:: @ 8179169
	.string "굉장히 잘 따르고 있군요\p"
	.string "이런 귀여운 포켓몬에게는\n"
	.string "이 기술머신이 어떨까요?$"
	@ とっても なついて いますなあｐ
	@ そんな かわいらしい ポケモンにはｎ
	@ この わざマシン どうですかな?

PacifidlogTown_House2_Text_1791CA:: @ 81791CA
	.string "흐음...\n"
	.string "나쁘지는 않지만 좋지도 않군요...\p"
	.string "어버이 트레이너인 당신의\n"
	.string "노력이 필요하겠습니다!$"
	@ ふむう……ｎ
	@ わるくは ないんだが よくもない……ｐ
	@ おやの トレ-ナ-である きみのｎ
	@ どりょくが ひつよう ですな!

PacifidlogTown_House2_Text_17922D:: @ 817922D
	.string "왠지 눈매가 사나운데요\p"
	.string "이런 무서운 포켓몬에게는\n"
	.string "이 기술머신이 어떨까요?$"
	@ なんだか めつきが わるいですのうｐ
	@ そんな こわそうな ポケモンにはｎ
	@ この わざマシン どうですかな?

PacifidlogTown_House2_Text_179283:: @ 8179283
	.string "포켓몬이 많이 따를수록\n"
	.string "은혜갚기의 위력도 높아집니다\p"
	.string "별로 따르지 않으면\n"
	.string "화풀이의 위력이 높아지지요!$"
	@ ポケモンの なつきどが たかいとｎ
	@ おんがえしの いりょくも たかくなるｐ
	@ なつきどが ひくいとｎ
	@ やつあたりの いりょくが つよまるんだよ!

PacifidlogTown_House2_Text_1792F2:: @ 81792F2
	.string "그래요 그래요 앞으로 {STR_VAR_1}일 지나면\n"
	.string "좋은 기술머신이 손에 들어온답니다!\p"
	.string "그때 다시 놀러오시지요!\n"
	.string "당신의 포켓몬에게 맞는\l"
	.string "근사한 기술머신을 드릴 테니까요$"
	@ そうそう あと§いにち たてばｎ
	@ いい わざマシンが てに はいるんだよ!ｐ
	@ そのとき また あそびに きたまえ!ｎ
	@ きみの ポケモンに あったｌ
	@ すてきな わざマシンを あげるから

PacifidlogTown_House2_Text_17938B:: @ 817938B
	.string "루리리: 루리-$"
	@ ルリリ『るり-

PacifidlogTown_House2_Text_17939B:: @ 817939B
	.string "굉장히 따르고 있는 듯하다$"
	@ とっても なついて いるようだ

PacifidlogTown_House2_Text_1793CC:: @ 81793CC
	.string "루리리: 루리릿!!$"
	@ ルリリ『ルルリッ!!

PacifidlogTown_House2_Text_1793DD:: @ 81793DD
	.string "별로 안 따르는 듯하다...$"
	@ あんまり なついて いないようだ……
