SlateportCity_Harbor_Text_17FA0A:: @ 817FA0A
	.string "에? 배 말입니까?\p"
	.string "죄송합니다만 현재\n"
	.string "연락선은 없습니다...$"
	// えっ? ふね ですか?ｐ
	// もうしわけ ございません げんざいｎ
	// れんらくせんは ないんです……

SlateportCity_Harbor_Text_17FA73:: @ 817FA73
	.string "연락선을 이용하시려는 거군요!\n"
	.string "티켓은 가지고 계신가요?$"
	// れんらくせんを ごりよう ですね!ｎ
	// チケットは おもち でしょうか?

SlateportCity_Harbor_Text_17FAAD:: @ 817FAAD
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "티켓이 없다!\p"
	.string "...죄송합니다!\p"
	.string "배에는 티켓을 가진 분들만\n"
	.string "탑승하실 수 있습니다$"
	// §あはｎ
	// チケットを もっていない!ｐ
	// ……もうしわけ ありません!ｐ
	// ふねに のれるのはｎ
	// チケットの ある かた だけです

SlateportCity_Harbor_Text_17FB0A:: @ 817FB0A
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "승선티켓을 보여줬다!\p"
	.string "네! 확인했습니다!\p"
	.string "어디로 가시겠어요?$"
	// §あはｎ
	// ふねのチケットを みせた!ｐ
	// はい! けっこう です!ｐ
	// いきさきは どちら でしょう?

SlateportCity_Harbor_Text_17FB5F:: @ 817FB5F
	.string "또 이용해 주십시오!$"
	// また ごりよう ください!

SlateportCity_Harbor_Text_17FB81:: @ 817FB81
	.string "해안시티 말씀이시군요!$"
	// ミナモ ですね!

SlateportCity_Harbor_Text_17FB9C:: @ 817FB9C
	.string "배틀타워 말씀이시군요!$"
	// バトルタワ- ですね!

SlateportCity_Harbor_Text_17FBB6:: @ 817FBB6
	.string "연락선에서 잠시 기다려 주십시오$"
	// れんらくせんに のって おまちください

SlateportCity_Harbor_Text_17FBE5:: @ 817FBE5
	.string "어디로 가시겠어요?$"
	// いきさきは どちら でしょう?

SlateportCity_Harbor_Text_17FC07:: @ 817FC07
	.string "바닷속 깊은 곳이라...\n"
	.string "과연 어떤 모습일까?\p"
	.string "나도 언젠가 들어가 보고 싶어!$"
	// うみの そこ かあ……ｎ
	// いったい どんなふう なのかな?ｐ
	// おれも いつか もぐってみたいぜ!

SlateportCity_Harbor_Text_17FC7C:: @ 817FC7C
	.string "나도 해양관장과 같이\n"
	.string "해저 조사하러 가고 싶었어!\p"
	.string "그렇지만 잠수정 안은 좁으니까\n"
	.string "내가 타 버리면 관장이\l"
	.string "못 타게 될 거야...$"
	// ぼくも クスノキ かんちょうと いっしょにｎ
	// かいてい ちょうさに いきたかった!ｐ
	// でも せんすいていの なかは せまいからｎ
	// ぼくが のったら かんちょうがｌ
	// のれなく なっちゃうんだよね……

SlateportCity_Harbor_Text_17FD1C:: @ 817FD1C
	.string "해양: 저 녀석들은...\p"
	.string "예전에 박물관에서\n"
	.string "데봉화물을 빼앗아 가려고 했던...$"
	// クスノキ『あいつらは……ｐ
	// いぜん はくぶつかんでｎ
	// デボンのにもつを うばおうと していた……

SlateportCity_Harbor_Text_17FD7D:: @ 817FD7D
	.string "{EVIL_LEADER}: 후후후...\p"
	.string "너도 고생했겠군\n"
	.string "몸소 송화산에서\l"
	.string "여기까지 쫓아온 건가?\p"
	.string "하지만 이제 누구도\n"
	.string "우리를 막을 수는 없다\p"
	.string "막고 싶다면\n"
	.string "해안시티의 아지트까지 와보지 그래?\l"
	.string "후후후...$"
	// §こ『フフフ……ｐ
	// きみも たいへん だなｎ
	// わざわざ おくりびやま からｌ
	// ここまで おいかけて きたのかｐ
	// だが もう だれにもｎ
	// われわれを とめられないｐ
	// とめられると おもうならｎ
	// ミナモの アジトまで くるかね?ｌ
	// フフフ……

SlateportCity_Harbor_Text_17FE60:: @ 817FE60
	.string "해양: 어째서...\p"
	.string "{EVIL_TEAM}단 녀석들이\n"
	.string "내 잠수정\l"
	.string "“해연 1호”를 빼앗은 거지?\p"
	.string "설마 그들도\n"
	.string "해저에 잠들어 있는 포켓몬을...\p"
	.string "하지만 나는 쫓아가도\n"
	.string "그 녀석들을 상대할 수 없을 텐데...$"
	// クスノキ『なぜ……ｐ
	// §くだんの れんちゅうがｎ
	// わたしの せんすいていｌ
	// 「かいえん 1ごう」を うばうのだろう?ｐ
	// まさか かれらもｎ
	// かいていに ねむる ポケモンを……ｐ
	// だが わたしが おいかけてもｎ
	// あんな れんちゅうに かてる わけない……

SlateportCity_Harbor_Text_17FF35:: @ 817FF35
	.string "해양: 아아 {PLAYER}{K_AYA}...\p"
	.string "그래... {EVIL_TEAM}단은\n"
	.string "출발해 버렸구나...\p"
	.string "아니야 신경 쓰지 마\n"
	.string "네 책임이 아니니까\p"
	.string "잠수정을 따라간다는 거 자체가\n"
	.string "보통 인간에게는 말도 안 되는 일이지\p"
	.string "포켓몬에게 다이빙이라고 하는\n"
	.string "바닷속으로 파고드는 기술을 가르쳐야...\p"
	.string "이끼시티에 가면\n"
	.string "다이빙을 하는 사람이 많으니까\l"
	.string "가르쳐줄 사람이 있을지도 모르겠다$"
	// クスノキ『ああ §あ§お……ｐ
	// そうか…… §くだんはｎ
	// しゅっぱつ して しまったか……ｐ
	// いや きにしなくて いいよｎ
	// きみの せきにん では ないからねｐ
	// せんすいていを おいかけるのはｎ
	// ふつうの ひとには むりな はなし だよｐ
	// ポケモンに ダイビング といってｎ
	// うみに もぐれる わざを おしえないと……ｐ
	// トクサネに いけばｎ
	// ダイビングを する ひとが おおいからｌ
	// おしえて もらえるかも しれないけどね

SlateportCity_Harbor_Text_1800A0:: @ 81800A0
	.string "해양: 잠수정을 따라간다는 거 자체가\n"
	.string "보통 인간에게는 말도 안 되는 일이지\p"
	.string "포켓몬에게 다이빙이라고 하는\n"
	.string "바닷속으로 파고드는 기술을 가르쳐야...\p"
	.string "이끼시티에 가면\n"
	.string "다이빙을 하는 사람이 많으니까\l"
	.string "가르쳐줄 사람이 있을지도 모르겠다$"
	// クスノキ『せんすいていを おいかけるのはｎ
	// ふつうの ひとには むりな はなし だよｐ
	// ポケモンに ダイビング といってｎ
	// うみに もぐれる わざを おしえないと……ｐ
	// トクサネに いけばｎ
	// ダイビングを する ひとが おおいからｌ
	// おしえて もらえるかも しれないけどね

SlateportCity_Harbor_Text_18017B:: @ 818017B
	.string "해양: 맞다! 하기노인이\n"
	.string "조선소에 와 주었어!\p"
	.string "좋-아! 이걸로 연락선이\n"
	.string "완성되는 것도 얼마 안 남았어!$"
	// クスノキ『そうだ! ハギろうじんがｎ
	// ぞうせんじょに きてくれたんだ!ｐ
	// よ-し! これで れんらくせんがｎ
	// かんせい するのも もうすぐ だぞ!

SlateportCity_Harbor_Text_1801EA:: @ 81801EA
	.string "해양: {PLAYER}!\p"
	.string "연락선 타이드립호가\n"
	.string "드디어 완성됐어!\p"
	.string "네 지인인 하기노인이\n"
	.string "도와준 덕분이야\p"
	.string "꼭 타보도록 해!$"
	// クスノキ『§あ§お!ｐ
	// れんらくせん タイドリップごうがｎ
	// ついに かんせい したんだ!ｐ
	// きみの しりあいの ハギろうじんがｎ
	// てつだって くれたからだよｐ
	// ぜひ のってみてよ!

SlateportCity_Harbor_Text_18028B:: @ 818028B
	.string "해양: 으음?\n"
	.string "{PLAYER}{K_I} 가지고 있는 그건...\p"
	.string "탐지기잖아!\n"
	.string "그게 있으면 조사가 더 진전될 거야\p"
	.string "{PLAYER}! 내가 가지고 있는\n"
	.string "심해의이빨과 심해의비늘 중 하나랑\l"
	.string "탐지기를 교환하지 않을래?$"
	// クスノキ『おや?ｎ
	// §あ§おが もってる それは……ｐ
	// たんちき だね!ｎ
	// それがあると ちょうさが はかどりそうだｐ
	// §あ§お! ぼくの もってるｎ
	// しんかいのキバか しんかいのウロコとｌ
	// たんちきを こうかん してくれないかな?

SlateportCity_Harbor_Text_180360:: @ 8180360
	.string "해양: 그래?\n"
	.string "{PLAYER}{K_IGA} 가지고 있어도\l"
	.string "쓸데는 없을 거라고 생각하지만...\p"
	.string "뭐 괜찮아\n"
	.string "탐지기를 교환하고 싶어지면\l"
	.string "다시 또 말 걸어줘!$"
	// クスノキ『そうかい?ｎ
	// §あ§おが もっていてもｌ
	// つかいみちが ないと おもうけどな……ｐ
	// まあ いいやｎ
	// たんちきを こうかん したくなったらｌ
	// また はなしかけてよ!

SlateportCity_Harbor_Text_1803DD:: @ 81803DD
	.string "해양: 심해의이빨과 교환할 거야?$"
	// クスノキ『しんかいのキバが いいんだね?

SlateportCity_Harbor_Text_180412:: @ 8180412
	.string "해양: 심해의비늘과 교환할 거야?$"
	// クスノキ『しんかいのウロコに するんだね?

SlateportCity_Harbor_Text_180447:: @ 8180447
	.string "해양: 어느 쪽이랑 교환할래?$"
	// クスノキ『どっちに するんだい?

SlateportCity_Harbor_Text_18046B:: @ 818046B
	.string "{PLAYER}{K_EUNNEUN} 해양관장에게\n"
	.string "탐지기를 건넸다!$"
	// §あは クスノキかんちょうにｎ
	// たんちきを わたした!

SlateportCity_Harbor_Text_180491:: @ 8180491
	.string "해양: 고마워 {PLAYER}!\n"
	.string "이걸로 연구가 더 진전되겠어$"
	// クスノキ『§あ§お ありがとう!ｎ
	// これで けんきゅうが はかどるよ
