BattleTower_BattleRoom_Text_19ACDC:: @ 819ACDC
	.string "포켓몬의 체력을\n"
	.string "회복시켜 드리겠습니다$"
	// ポケモンの たいりょくをｎ
	// かいふくして さしあげます

BattleTower_BattleRoom_Text_19AD09:: @ 819AD09
	.string "다음은 {STR_VAR_1}명째 상대입니다\n"
	.string "준비되셨습니까?$"
	// つぎは §いにんめの あいてですｎ
	// じゅんびは いいですか?

BattleTower_BattleRoom_Text_19AD3C:: @ 819AD3C
	.string "리포트를 작성하고 종료할까요?$"
	// レポ-トを かいて しゅうりょう しますか?

BattleTower_BattleRoom_Text_19AD66:: @ 819AD66
	.string "배틀룸 도전을\n"
	.string "중지할까요?$"
	// バトルル-ムの ちょうせんをｎ
	// ちゅうし しますか?
