OldaleTown_PokemonCenter_1F_Text_1748D1:: @ 81748D1
	.string "구석에 있는 PC는\n"
	.string "포켓몬 트레이너를 위해 놔둔 거란다\p"
	.string "자네도 자유롭게 써도 된다고!$"
	// すみっこに おいてある パソコンはｎ
	// ポケモントレ-ナ-の ための ものなんだｐ
	// きみも じゆうに つかって いいんだよ!

OldaleTown_PokemonCenter_1F_Text_174945:: @ 8174945
	.string "포켓몬센터는 정말 굉장해!\p"
	.string "포켓몬을 몇 마리 맡겨도\n"
	.string "돈이 들지 않으니까\l"
	.string "언제 어디서라도 안심할 수 있어!$"
	// ポケモンセンタ-って すごいよな!ｐ
	// ポケモン なんびき あずけてもｎ
	// おかねが かからないからｌ
	// どんな ときでも あんしん だよね!

OldaleTown_PokemonCenter_1F_Text_1749C0:: @ 81749C0
	.string "2층의 포켓몬 통신 클럽은\n"
	.string "얼마 전에 생겼어\p"
	.string "하지만 아직\n"
	.string "조정 중인가 봐$"
	// 2かいの ポケモン つうしん クラブはｎ
	// つい さいきん できたのｐ
	// でも まだｎ
	// ちょうせいちゅう ですって

OldaleTown_PokemonCenter_1F_Text_174A2E:: @ 8174A2E
	.string "2층의 포켓몬 통신 클럽은\n"
	.string "얼마 전에 생겼어\p"
	.string "그래서 바로\n"
	.string "포켓몬 교환을 했지!$"
	// 2かいの ポケモン つうしん クラブはｎ
	// つい さいきん できたのｐ
	// あたし さっそくｎ
	// ポケモンこうかん しちゃった!
